multiline_comment|/*&n; * PCI HotPlug Utility functions&n; *&n; * Copyright (c) 1995,2001 Compaq Computer Corporation&n; * Copyright (c) 2001 Greg Kroah-Hartman (greg@kroah.com)&n; * Copyright (c) 2001 IBM Corp.&n; *&n; * All rights reserved.&n; *&n; * This program is free software; you can redistribute it and/or modify&n; * it under the terms of the GNU General Public License as published by&n; * the Free Software Foundation; either version 2 of the License, or (at&n; * your option) any later version.&n; *&n; * This program is distributed in the hope that it will be useful, but&n; * WITHOUT ANY WARRANTY; without even the implied warranty of&n; * MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, GOOD TITLE or&n; * NON INFRINGEMENT.  See the GNU General Public License for more&n; * details.&n; *&n; * You should have received a copy of the GNU General Public License&n; * along with this program; if not, write to the Free Software&n; * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.&n; *&n; * Send feedback to &lt;greg@kroah.com&gt;&n; *&n; */
macro_line|#include &lt;linux/config.h&gt;
macro_line|#include &lt;linux/module.h&gt;
macro_line|#include &lt;linux/kernel.h&gt;
macro_line|#include &lt;linux/types.h&gt;
macro_line|#include &lt;linux/slab.h&gt;
macro_line|#include &lt;linux/pci.h&gt;
macro_line|#include &quot;pci_hotplug.h&quot;
macro_line|#if !defined(CONFIG_HOTPLUG_PCI_MODULE)
DECL|macro|MY_NAME
mdefine_line|#define MY_NAME&t;&quot;pci_hotplug&quot;
macro_line|#else
DECL|macro|MY_NAME
mdefine_line|#define MY_NAME&t;THIS_MODULE-&gt;name
macro_line|#endif
DECL|macro|dbg
mdefine_line|#define dbg(fmt, arg...) do { if (debug) printk(KERN_DEBUG &quot;%s: &quot;__FUNCTION__&quot;: &quot; fmt , MY_NAME , ## arg); } while (0)
DECL|macro|err
mdefine_line|#define err(format, arg...) printk(KERN_ERR &quot;%s: &quot; format , MY_NAME , ## arg)
DECL|macro|info
mdefine_line|#define info(format, arg...) printk(KERN_INFO &quot;%s: &quot; format , MY_NAME , ## arg)
DECL|macro|warn
mdefine_line|#define warn(format, arg...) printk(KERN_WARNING &quot;%s: &quot; format , MY_NAME , ## arg)
multiline_comment|/* local variables */
DECL|variable|debug
r_static
r_int
id|debug
suffix:semicolon
DECL|function|build_dev
r_static
r_int
id|build_dev
(paren
r_struct
id|pci_ops
op_star
id|ops
comma
id|u8
id|bus
comma
id|u8
id|slot
comma
id|u8
id|function
comma
r_struct
id|pci_dev
op_star
op_star
id|pci_dev
)paren
(brace
r_struct
id|pci_dev
op_star
id|my_dev
suffix:semicolon
r_struct
id|pci_bus
op_star
id|my_bus
suffix:semicolon
multiline_comment|/* Some validity checks. */
r_if
c_cond
(paren
(paren
id|function
OG
l_int|7
)paren
op_logical_or
(paren
id|slot
OG
l_int|31
)paren
op_logical_or
(paren
id|pci_dev
op_eq
l_int|NULL
)paren
op_logical_or
(paren
id|ops
op_eq
l_int|NULL
)paren
)paren
r_return
op_minus
id|ENODEV
suffix:semicolon
id|my_dev
op_assign
id|kmalloc
(paren
r_sizeof
(paren
r_struct
id|pci_dev
)paren
comma
id|GFP_KERNEL
)paren
suffix:semicolon
r_if
c_cond
(paren
op_logical_neg
id|my_dev
)paren
r_return
op_minus
id|ENOMEM
suffix:semicolon
id|my_bus
op_assign
id|kmalloc
(paren
r_sizeof
(paren
r_struct
id|pci_bus
)paren
comma
id|GFP_KERNEL
)paren
suffix:semicolon
r_if
c_cond
(paren
op_logical_neg
id|my_bus
)paren
(brace
id|kfree
(paren
id|my_dev
)paren
suffix:semicolon
r_return
op_minus
id|ENOMEM
suffix:semicolon
)brace
id|memset
c_func
(paren
id|my_dev
comma
l_int|0
comma
r_sizeof
(paren
r_struct
id|pci_dev
)paren
)paren
suffix:semicolon
id|memset
c_func
(paren
id|my_bus
comma
l_int|0
comma
r_sizeof
(paren
r_struct
id|pci_bus
)paren
)paren
suffix:semicolon
id|my_bus-&gt;number
op_assign
id|bus
suffix:semicolon
id|my_bus-&gt;ops
op_assign
id|ops
suffix:semicolon
id|my_dev-&gt;devfn
op_assign
id|PCI_DEVFN
c_func
(paren
id|slot
comma
id|function
)paren
suffix:semicolon
id|my_dev-&gt;bus
op_assign
id|my_bus
suffix:semicolon
op_star
id|pci_dev
op_assign
id|my_dev
suffix:semicolon
r_return
l_int|0
suffix:semicolon
)brace
multiline_comment|/**&n; * pci_read_config_byte_nodev - read a byte from a pci device&n; * @ops: pointer to a &amp;struct pci_ops that will be used to read from the pci device&n; * @bus: the bus of the pci device to read from&n; * @slot: the pci slot number of the pci device to read from&n; * @function: the function of the pci device to read from&n; * @where: the location on the pci address space to read from&n; * @value: pointer to where to place the data read&n; *&n; * Like pci_read_config_byte() but works for pci devices that do not have a&n; * pci_dev structure set up yet.&n; * Returns 0 on success.&n; */
DECL|function|pci_read_config_byte_nodev
r_int
id|pci_read_config_byte_nodev
(paren
r_struct
id|pci_ops
op_star
id|ops
comma
id|u8
id|bus
comma
id|u8
id|slot
comma
id|u8
id|function
comma
r_int
id|where
comma
id|u8
op_star
id|value
)paren
(brace
r_struct
id|pci_dev
op_star
id|dev
op_assign
l_int|NULL
suffix:semicolon
r_int
id|result
suffix:semicolon
id|dbg
c_func
(paren
l_string|&quot;%p, %d, %d, %d, %d, %p&bslash;n&quot;
comma
id|ops
comma
id|bus
comma
id|slot
comma
id|function
comma
id|where
comma
id|value
)paren
suffix:semicolon
id|dev
op_assign
id|pci_find_slot
c_func
(paren
id|bus
comma
id|PCI_DEVFN
c_func
(paren
id|slot
comma
id|function
)paren
)paren
suffix:semicolon
r_if
c_cond
(paren
id|dev
)paren
(brace
id|dbg
c_func
(paren
l_string|&quot;using native pci_dev&bslash;n&quot;
)paren
suffix:semicolon
r_return
id|pci_read_config_byte
(paren
id|dev
comma
id|where
comma
id|value
)paren
suffix:semicolon
)brace
id|result
op_assign
id|build_dev
(paren
id|ops
comma
id|bus
comma
id|slot
comma
id|function
comma
op_amp
id|dev
)paren
suffix:semicolon
r_if
c_cond
(paren
id|result
)paren
r_return
id|result
suffix:semicolon
id|result
op_assign
id|pci_read_config_byte
c_func
(paren
id|dev
comma
id|where
comma
id|value
)paren
suffix:semicolon
id|kfree
(paren
id|dev-&gt;bus
)paren
suffix:semicolon
id|kfree
(paren
id|dev
)paren
suffix:semicolon
r_return
id|result
suffix:semicolon
)brace
multiline_comment|/**&n; * pci_read_config_word_nodev - read a word from a pci device&n; * @ops: pointer to a &amp;struct pci_ops that will be used to read from the pci device&n; * @bus: the bus of the pci device to read from&n; * @slot: the pci slot number of the pci device to read from&n; * @function: the function of the pci device to read from&n; * @where: the location on the pci address space to read from&n; * @value: pointer to where to place the data read&n; *&n; * Like pci_read_config_word() but works for pci devices that do not have a&n; * pci_dev structure set up yet. &n; * Returns 0 on success.&n; */
DECL|function|pci_read_config_word_nodev
r_int
id|pci_read_config_word_nodev
(paren
r_struct
id|pci_ops
op_star
id|ops
comma
id|u8
id|bus
comma
id|u8
id|slot
comma
id|u8
id|function
comma
r_int
id|where
comma
id|u16
op_star
id|value
)paren
(brace
r_struct
id|pci_dev
op_star
id|dev
op_assign
l_int|NULL
suffix:semicolon
r_int
id|result
suffix:semicolon
id|dbg
c_func
(paren
l_string|&quot;%p, %d, %d, %d, %d, %p&bslash;n&quot;
comma
id|ops
comma
id|bus
comma
id|slot
comma
id|function
comma
id|where
comma
id|value
)paren
suffix:semicolon
id|dev
op_assign
id|pci_find_slot
c_func
(paren
id|bus
comma
id|PCI_DEVFN
c_func
(paren
id|slot
comma
id|function
)paren
)paren
suffix:semicolon
r_if
c_cond
(paren
id|dev
)paren
(brace
id|dbg
c_func
(paren
l_string|&quot;using native pci_dev&bslash;n&quot;
)paren
suffix:semicolon
r_return
id|pci_read_config_word
(paren
id|dev
comma
id|where
comma
id|value
)paren
suffix:semicolon
)brace
id|result
op_assign
id|build_dev
(paren
id|ops
comma
id|bus
comma
id|slot
comma
id|function
comma
op_amp
id|dev
)paren
suffix:semicolon
r_if
c_cond
(paren
id|result
)paren
r_return
id|result
suffix:semicolon
id|result
op_assign
id|pci_read_config_word
c_func
(paren
id|dev
comma
id|where
comma
id|value
)paren
suffix:semicolon
id|kfree
(paren
id|dev-&gt;bus
)paren
suffix:semicolon
id|kfree
(paren
id|dev
)paren
suffix:semicolon
r_return
id|result
suffix:semicolon
)brace
multiline_comment|/**&n; * pci_read_config_dword_nodev - read a dword from a pci device&n; * @ops: pointer to a &amp;struct pci_ops that will be used to read from the pci&n; * device&n; * @bus: the bus of the pci device to read from&n; * @slot: the pci slot number of the pci device to read from&n; * @function: the function of the pci device to read from&n; * @where: the location on the pci address space to read from&n; * @value: pointer to where to place the data read&n; *&n; * Like pci_read_config_dword() but works for pci devices that do not have a&n; * pci_dev structure set up yet. &n; * Returns 0 on success.&n; */
DECL|function|pci_read_config_dword_nodev
r_int
id|pci_read_config_dword_nodev
(paren
r_struct
id|pci_ops
op_star
id|ops
comma
id|u8
id|bus
comma
id|u8
id|slot
comma
id|u8
id|function
comma
r_int
id|where
comma
id|u32
op_star
id|value
)paren
(brace
r_struct
id|pci_dev
op_star
id|dev
op_assign
l_int|NULL
suffix:semicolon
r_int
id|result
suffix:semicolon
id|dbg
c_func
(paren
l_string|&quot;%p, %d, %d, %d, %d, %p&bslash;n&quot;
comma
id|ops
comma
id|bus
comma
id|slot
comma
id|function
comma
id|where
comma
id|value
)paren
suffix:semicolon
id|dev
op_assign
id|pci_find_slot
c_func
(paren
id|bus
comma
id|PCI_DEVFN
c_func
(paren
id|slot
comma
id|function
)paren
)paren
suffix:semicolon
r_if
c_cond
(paren
id|dev
)paren
(brace
id|dbg
c_func
(paren
l_string|&quot;using native pci_dev&bslash;n&quot;
)paren
suffix:semicolon
r_return
id|pci_read_config_dword
(paren
id|dev
comma
id|where
comma
id|value
)paren
suffix:semicolon
)brace
id|result
op_assign
id|build_dev
(paren
id|ops
comma
id|bus
comma
id|slot
comma
id|function
comma
op_amp
id|dev
)paren
suffix:semicolon
r_if
c_cond
(paren
id|result
)paren
r_return
id|result
suffix:semicolon
id|result
op_assign
id|pci_read_config_dword
c_func
(paren
id|dev
comma
id|where
comma
id|value
)paren
suffix:semicolon
id|kfree
(paren
id|dev-&gt;bus
)paren
suffix:semicolon
id|kfree
(paren
id|dev
)paren
suffix:semicolon
r_return
id|result
suffix:semicolon
)brace
multiline_comment|/**&n; * pci_write_config_byte_nodev - write a byte to a pci device&n; * @ops: pointer to a &amp;struct pci_ops that will be used to write to the pci&n; * device&n; * @bus: the bus of the pci device to write to&n; * @slot: the pci slot number of the pci device to write to&n; * @function: the function of the pci device to write to&n; * @where: the location on the pci address space to write to&n; * @value: the value to write to the pci device&n; *&n; * Like pci_write_config_byte() but works for pci devices that do not have a&n; * pci_dev structure set up yet. &n; * Returns 0 on success.&n; */
DECL|function|pci_write_config_byte_nodev
r_int
id|pci_write_config_byte_nodev
(paren
r_struct
id|pci_ops
op_star
id|ops
comma
id|u8
id|bus
comma
id|u8
id|slot
comma
id|u8
id|function
comma
r_int
id|where
comma
id|u8
id|value
)paren
(brace
r_struct
id|pci_dev
op_star
id|dev
op_assign
l_int|NULL
suffix:semicolon
r_int
id|result
suffix:semicolon
id|dbg
c_func
(paren
l_string|&quot;%p, %d, %d, %d, %d, %d&bslash;n&quot;
comma
id|ops
comma
id|bus
comma
id|slot
comma
id|function
comma
id|where
comma
id|value
)paren
suffix:semicolon
id|dev
op_assign
id|pci_find_slot
c_func
(paren
id|bus
comma
id|PCI_DEVFN
c_func
(paren
id|slot
comma
id|function
)paren
)paren
suffix:semicolon
r_if
c_cond
(paren
id|dev
)paren
(brace
id|dbg
c_func
(paren
l_string|&quot;using native pci_dev&bslash;n&quot;
)paren
suffix:semicolon
r_return
id|pci_write_config_byte
(paren
id|dev
comma
id|where
comma
id|value
)paren
suffix:semicolon
)brace
id|result
op_assign
id|build_dev
(paren
id|ops
comma
id|bus
comma
id|slot
comma
id|function
comma
op_amp
id|dev
)paren
suffix:semicolon
r_if
c_cond
(paren
id|result
)paren
r_return
id|result
suffix:semicolon
id|result
op_assign
id|pci_write_config_byte
c_func
(paren
id|dev
comma
id|where
comma
id|value
)paren
suffix:semicolon
id|kfree
(paren
id|dev-&gt;bus
)paren
suffix:semicolon
id|kfree
(paren
id|dev
)paren
suffix:semicolon
r_return
id|result
suffix:semicolon
)brace
multiline_comment|/**&n; * pci_write_config_word_nodev - write a word to a pci device&n; * @ops: pointer to a &amp;struct pci_ops that will be used to write to the pci&n; * device&n; * @bus: the bus of the pci device to write to&n; * @slot: the pci slot number of the pci device to write to&n; * @function: the function of the pci device to write to&n; * @where: the location on the pci address space to write to&n; * @value: the value to write to the pci device&n; *&n; * Like pci_write_config_word() but works for pci devices that do not have a&n; * pci_dev structure set up yet. &n; * Returns 0 on success.&n; */
DECL|function|pci_write_config_word_nodev
r_int
id|pci_write_config_word_nodev
(paren
r_struct
id|pci_ops
op_star
id|ops
comma
id|u8
id|bus
comma
id|u8
id|slot
comma
id|u8
id|function
comma
r_int
id|where
comma
id|u16
id|value
)paren
(brace
r_struct
id|pci_dev
op_star
id|dev
op_assign
l_int|NULL
suffix:semicolon
r_int
id|result
suffix:semicolon
id|dbg
c_func
(paren
l_string|&quot;%p, %d, %d, %d, %d, %d&bslash;n&quot;
comma
id|ops
comma
id|bus
comma
id|slot
comma
id|function
comma
id|where
comma
id|value
)paren
suffix:semicolon
id|dev
op_assign
id|pci_find_slot
c_func
(paren
id|bus
comma
id|PCI_DEVFN
c_func
(paren
id|slot
comma
id|function
)paren
)paren
suffix:semicolon
r_if
c_cond
(paren
id|dev
)paren
(brace
id|dbg
c_func
(paren
l_string|&quot;using native pci_dev&bslash;n&quot;
)paren
suffix:semicolon
r_return
id|pci_write_config_word
(paren
id|dev
comma
id|where
comma
id|value
)paren
suffix:semicolon
)brace
id|result
op_assign
id|build_dev
(paren
id|ops
comma
id|bus
comma
id|slot
comma
id|function
comma
op_amp
id|dev
)paren
suffix:semicolon
r_if
c_cond
(paren
id|result
)paren
r_return
id|result
suffix:semicolon
id|result
op_assign
id|pci_write_config_word
c_func
(paren
id|dev
comma
id|where
comma
id|value
)paren
suffix:semicolon
id|kfree
(paren
id|dev-&gt;bus
)paren
suffix:semicolon
id|kfree
(paren
id|dev
)paren
suffix:semicolon
r_return
id|result
suffix:semicolon
)brace
multiline_comment|/**&n; * pci_write_config_dword_nodev - write a dword to a pci device&n; * @ops: pointer to a &amp;struct pci_ops that will be used to write to the pci&n; * device&n; * @bus: the bus of the pci device to write to&n; * @slot: the pci slot number of the pci device to write to&n; * @function: the function of the pci device to write to&n; * @where: the location on the pci address space to write to&n; * @value: the value to write to the pci device&n; *&n; * Like pci_write_config_dword() but works for pci devices that do not have a&n; * pci_dev structure set up yet. &n; * Returns 0 on success.&n; */
DECL|function|pci_write_config_dword_nodev
r_int
id|pci_write_config_dword_nodev
(paren
r_struct
id|pci_ops
op_star
id|ops
comma
id|u8
id|bus
comma
id|u8
id|slot
comma
id|u8
id|function
comma
r_int
id|where
comma
id|u32
id|value
)paren
(brace
r_struct
id|pci_dev
op_star
id|dev
op_assign
l_int|NULL
suffix:semicolon
r_int
id|result
suffix:semicolon
id|dbg
c_func
(paren
l_string|&quot;%p, %d, %d, %d, %d, %d&bslash;n&quot;
comma
id|ops
comma
id|bus
comma
id|slot
comma
id|function
comma
id|where
comma
id|value
)paren
suffix:semicolon
id|dev
op_assign
id|pci_find_slot
c_func
(paren
id|bus
comma
id|PCI_DEVFN
c_func
(paren
id|slot
comma
id|function
)paren
)paren
suffix:semicolon
r_if
c_cond
(paren
id|dev
)paren
(brace
id|dbg
c_func
(paren
l_string|&quot;using native pci_dev&bslash;n&quot;
)paren
suffix:semicolon
r_return
id|pci_write_config_dword
(paren
id|dev
comma
id|where
comma
id|value
)paren
suffix:semicolon
)brace
id|result
op_assign
id|build_dev
(paren
id|ops
comma
id|bus
comma
id|slot
comma
id|function
comma
op_amp
id|dev
)paren
suffix:semicolon
r_if
c_cond
(paren
id|result
)paren
r_return
id|result
suffix:semicolon
id|result
op_assign
id|pci_write_config_dword
c_func
(paren
id|dev
comma
id|where
comma
id|value
)paren
suffix:semicolon
id|kfree
(paren
id|dev-&gt;bus
)paren
suffix:semicolon
id|kfree
(paren
id|dev
)paren
suffix:semicolon
r_return
id|result
suffix:semicolon
)brace
multiline_comment|/*&n; * This is code that scans the pci buses.&n; * Every bus and every function is presented to a custom&n; * function that can act upon it.&n; */
DECL|function|pci_visit_bus
r_static
r_int
id|pci_visit_bus
(paren
r_struct
id|pci_visit
op_star
id|fn
comma
r_struct
id|pci_bus_wrapped
op_star
id|wrapped_bus
comma
r_struct
id|pci_dev_wrapped
op_star
id|wrapped_parent
)paren
(brace
r_struct
id|list_head
op_star
id|ln
suffix:semicolon
r_struct
id|pci_dev
op_star
id|dev
suffix:semicolon
r_struct
id|pci_dev_wrapped
id|wrapped_dev
suffix:semicolon
r_int
id|result
op_assign
l_int|0
suffix:semicolon
id|dbg
c_func
(paren
l_string|&quot;scanning bus %02x&bslash;n&quot;
comma
id|wrapped_bus-&gt;bus-&gt;number
)paren
suffix:semicolon
r_if
c_cond
(paren
id|fn-&gt;pre_visit_pci_bus
)paren
(brace
id|result
op_assign
id|fn
op_member_access_from_pointer
id|pre_visit_pci_bus
c_func
(paren
id|wrapped_bus
comma
id|wrapped_parent
)paren
suffix:semicolon
r_if
c_cond
(paren
id|result
)paren
r_return
id|result
suffix:semicolon
)brace
id|ln
op_assign
id|wrapped_bus-&gt;bus-&gt;devices.next
suffix:semicolon
r_while
c_loop
(paren
id|ln
op_ne
op_amp
id|wrapped_bus-&gt;bus-&gt;devices
)paren
(brace
id|dev
op_assign
id|pci_dev_b
c_func
(paren
id|ln
)paren
suffix:semicolon
id|ln
op_assign
id|ln-&gt;next
suffix:semicolon
id|memset
c_func
(paren
op_amp
id|wrapped_dev
comma
l_int|0
comma
r_sizeof
(paren
r_struct
id|pci_dev_wrapped
)paren
)paren
suffix:semicolon
id|wrapped_dev.dev
op_assign
id|dev
suffix:semicolon
id|result
op_assign
id|pci_visit_dev
c_func
(paren
id|fn
comma
op_amp
id|wrapped_dev
comma
id|wrapped_bus
)paren
suffix:semicolon
r_if
c_cond
(paren
id|result
)paren
r_return
id|result
suffix:semicolon
)brace
r_if
c_cond
(paren
id|fn-&gt;post_visit_pci_bus
)paren
id|result
op_assign
id|fn
op_member_access_from_pointer
id|post_visit_pci_bus
c_func
(paren
id|wrapped_bus
comma
id|wrapped_parent
)paren
suffix:semicolon
r_return
id|result
suffix:semicolon
)brace
DECL|function|pci_visit_bridge
r_static
r_int
id|pci_visit_bridge
(paren
r_struct
id|pci_visit
op_star
id|fn
comma
r_struct
id|pci_dev_wrapped
op_star
id|wrapped_dev
comma
r_struct
id|pci_bus_wrapped
op_star
id|wrapped_parent
)paren
(brace
r_struct
id|pci_bus
op_star
id|bus
op_assign
id|wrapped_dev-&gt;dev-&gt;subordinate
suffix:semicolon
r_struct
id|pci_bus_wrapped
id|wrapped_bus
suffix:semicolon
r_int
id|result
suffix:semicolon
id|memset
c_func
(paren
op_amp
id|wrapped_bus
comma
l_int|0
comma
r_sizeof
(paren
r_struct
id|pci_bus_wrapped
)paren
)paren
suffix:semicolon
id|wrapped_bus.bus
op_assign
id|bus
suffix:semicolon
id|dbg
c_func
(paren
l_string|&quot;scanning bridge %02x, %02x&bslash;n&quot;
comma
id|wrapped_dev-&gt;dev-&gt;devfn
op_rshift
l_int|3
comma
id|wrapped_dev-&gt;dev-&gt;devfn
op_amp
l_int|0x7
)paren
suffix:semicolon
r_if
c_cond
(paren
id|fn-&gt;visit_pci_dev
)paren
(brace
id|result
op_assign
id|fn
op_member_access_from_pointer
id|visit_pci_dev
c_func
(paren
id|wrapped_dev
comma
id|wrapped_parent
)paren
suffix:semicolon
r_if
c_cond
(paren
id|result
)paren
r_return
id|result
suffix:semicolon
)brace
id|result
op_assign
id|pci_visit_bus
c_func
(paren
id|fn
comma
op_amp
id|wrapped_bus
comma
id|wrapped_dev
)paren
suffix:semicolon
r_return
id|result
suffix:semicolon
)brace
DECL|function|pci_visit_dev
r_int
id|pci_visit_dev
(paren
r_struct
id|pci_visit
op_star
id|fn
comma
r_struct
id|pci_dev_wrapped
op_star
id|wrapped_dev
comma
r_struct
id|pci_bus_wrapped
op_star
id|wrapped_parent
)paren
(brace
r_struct
id|pci_dev
op_star
id|dev
op_assign
id|wrapped_dev
ques
c_cond
id|wrapped_dev-&gt;dev
suffix:colon
l_int|NULL
suffix:semicolon
r_int
id|result
op_assign
l_int|0
suffix:semicolon
r_if
c_cond
(paren
op_logical_neg
id|dev
)paren
r_return
l_int|0
suffix:semicolon
r_if
c_cond
(paren
id|fn-&gt;pre_visit_pci_dev
)paren
(brace
id|result
op_assign
id|fn
op_member_access_from_pointer
id|pre_visit_pci_dev
c_func
(paren
id|wrapped_dev
comma
id|wrapped_parent
)paren
suffix:semicolon
r_if
c_cond
(paren
id|result
)paren
r_return
id|result
suffix:semicolon
)brace
r_switch
c_cond
(paren
id|dev
op_member_access_from_pointer
r_class
op_rshift
l_int|8
)paren
(brace
r_case
id|PCI_CLASS_BRIDGE_PCI
suffix:colon
id|result
op_assign
id|pci_visit_bridge
c_func
(paren
id|fn
comma
id|wrapped_dev
comma
id|wrapped_parent
)paren
suffix:semicolon
r_if
c_cond
(paren
id|result
)paren
r_return
id|result
suffix:semicolon
r_break
suffix:semicolon
r_default
suffix:colon
id|dbg
c_func
(paren
l_string|&quot;scanning device %02x, %02x&bslash;n&quot;
comma
id|PCI_SLOT
c_func
(paren
id|dev-&gt;devfn
)paren
comma
id|PCI_FUNC
c_func
(paren
id|dev-&gt;devfn
)paren
)paren
suffix:semicolon
r_if
c_cond
(paren
id|fn-&gt;visit_pci_dev
)paren
(brace
id|result
op_assign
id|fn-&gt;visit_pci_dev
(paren
id|wrapped_dev
comma
id|wrapped_parent
)paren
suffix:semicolon
r_if
c_cond
(paren
id|result
)paren
r_return
id|result
suffix:semicolon
)brace
)brace
r_if
c_cond
(paren
id|fn-&gt;post_visit_pci_dev
)paren
id|result
op_assign
id|fn
op_member_access_from_pointer
id|post_visit_pci_dev
c_func
(paren
id|wrapped_dev
comma
id|wrapped_parent
)paren
suffix:semicolon
r_return
id|result
suffix:semicolon
)brace
DECL|variable|pci_visit_dev
id|EXPORT_SYMBOL
c_func
(paren
id|pci_visit_dev
)paren
suffix:semicolon
DECL|variable|pci_read_config_byte_nodev
id|EXPORT_SYMBOL
c_func
(paren
id|pci_read_config_byte_nodev
)paren
suffix:semicolon
DECL|variable|pci_read_config_word_nodev
id|EXPORT_SYMBOL
c_func
(paren
id|pci_read_config_word_nodev
)paren
suffix:semicolon
DECL|variable|pci_read_config_dword_nodev
id|EXPORT_SYMBOL
c_func
(paren
id|pci_read_config_dword_nodev
)paren
suffix:semicolon
DECL|variable|pci_write_config_byte_nodev
id|EXPORT_SYMBOL
c_func
(paren
id|pci_write_config_byte_nodev
)paren
suffix:semicolon
DECL|variable|pci_write_config_word_nodev
id|EXPORT_SYMBOL
c_func
(paren
id|pci_write_config_word_nodev
)paren
suffix:semicolon
DECL|variable|pci_write_config_dword_nodev
id|EXPORT_SYMBOL
c_func
(paren
id|pci_write_config_dword_nodev
)paren
suffix:semicolon
eof
