multiline_comment|/*&n; *  Fast C2P (Chunky-to-Planar) Conversion&n; *&n; *  Copyright (C) 2003 Geert Uytterhoeven&n; *&n; *  This file is subject to the terms and conditions of the GNU General Public&n; *  License. See the file COPYING in the main directory of this archive&n; *  for more details.&n; */
macro_line|#include &lt;linux/types.h&gt;
r_extern
r_void
id|c2p
c_func
(paren
id|u8
op_star
id|dst
comma
r_const
id|u8
op_star
id|src
comma
id|u32
id|dx
comma
id|u32
id|dy
comma
id|u32
id|width
comma
id|u32
id|height
comma
id|u32
id|dst_nextline
comma
id|u32
id|dst_nextplane
comma
id|u32
id|src_nextline
comma
id|u32
id|bpp
)paren
suffix:semicolon
eof
