multiline_comment|/*&n; * Copyright (C) 2001 MontaVista Software, ppopov@mvista.com&n; * Copied and modified Carsten Langgaard&squot;s time.c&n; *&n; * Carsten Langgaard, carstenl@mips.com&n; * Copyright (C) 1999,2000 MIPS Technologies, Inc.  All rights reserved.&n; *&n; * ########################################################################&n; *&n; *  This program is free software; you can distribute it and/or modify it&n; *  under the terms of the GNU General Public License (Version 2) as&n; *  published by the Free Software Foundation.&n; *&n; *  This program is distributed in the hope it will be useful, but WITHOUT&n; *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or&n; *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License&n; *  for more details.&n; *&n; *  You should have received a copy of the GNU General Public License along&n; *  with this program; if not, write to the Free Software Foundation, Inc.,&n; *  59 Temple Place - Suite 330, Boston MA 02111-1307, USA.&n; *&n; * ########################################################################&n; *&n; * Setting up the clock on the MIPS boards.&n; */
macro_line|#include &lt;linux/config.h&gt;
macro_line|#include &lt;linux/init.h&gt;
macro_line|#include &lt;linux/kernel_stat.h&gt;
macro_line|#include &lt;linux/sched.h&gt;
macro_line|#include &lt;linux/spinlock.h&gt;
macro_line|#include &lt;asm/mipsregs.h&gt;
macro_line|#include &lt;asm/ptrace.h&gt;
macro_line|#include &lt;asm/div64.h&gt;
macro_line|#include &lt;asm/au1000.h&gt;
macro_line|#include &lt;linux/mc146818rtc.h&gt;
macro_line|#include &lt;linux/timex.h&gt;
r_extern
r_volatile
r_int
r_int
id|wall_jiffies
suffix:semicolon
DECL|variable|missed_heart_beats
r_int
r_int
id|missed_heart_beats
op_assign
l_int|0
suffix:semicolon
DECL|variable|uart_baud_base
r_int
r_int
id|uart_baud_base
suffix:semicolon
DECL|variable|r4k_offset
r_static
r_int
r_int
id|r4k_offset
suffix:semicolon
multiline_comment|/* Amount to increment compare reg each time */
DECL|variable|r4k_cur
r_static
r_int
r_int
id|r4k_cur
suffix:semicolon
multiline_comment|/* What counter should be at next timer irq */
r_extern
id|rwlock_t
id|xtime_lock
suffix:semicolon
DECL|macro|ALLINTS
mdefine_line|#define ALLINTS (IE_IRQ0 | IE_IRQ1 | IE_IRQ2 | IE_IRQ3 | IE_IRQ4 | IE_IRQ5)
DECL|function|ack_r4ktimer
r_static
r_inline
r_void
id|ack_r4ktimer
c_func
(paren
r_int
r_int
id|newval
)paren
(brace
id|write_32bit_cp0_register
c_func
(paren
id|CP0_COMPARE
comma
id|newval
)paren
suffix:semicolon
)brace
multiline_comment|/*&n; * There are a lot of conceptually broken versions of the MIPS timer interrupt&n; * handler floating around.  This one is rather different, but the algorithm&n; * is provably more robust.&n; */
DECL|variable|wtimer
r_int
r_int
id|wtimer
suffix:semicolon
DECL|function|mips_timer_interrupt
r_void
id|mips_timer_interrupt
c_func
(paren
r_struct
id|pt_regs
op_star
id|regs
)paren
(brace
r_int
id|irq
op_assign
l_int|7
suffix:semicolon
r_if
c_cond
(paren
id|r4k_offset
op_eq
l_int|0
)paren
r_goto
id|null
suffix:semicolon
r_do
(brace
id|kstat.irqs
(braket
l_int|0
)braket
(braket
id|irq
)braket
op_increment
suffix:semicolon
id|do_timer
c_func
(paren
id|regs
)paren
suffix:semicolon
id|r4k_cur
op_add_assign
id|r4k_offset
suffix:semicolon
id|ack_r4ktimer
c_func
(paren
id|r4k_cur
)paren
suffix:semicolon
)brace
r_while
c_loop
(paren
(paren
(paren
r_int
r_int
)paren
id|read_32bit_cp0_register
c_func
(paren
id|CP0_COUNT
)paren
op_minus
id|r4k_cur
)paren
OL
l_int|0x7fffffff
)paren
suffix:semicolon
r_return
suffix:semicolon
id|null
suffix:colon
id|ack_r4ktimer
c_func
(paren
l_int|0
)paren
suffix:semicolon
)brace
multiline_comment|/* &n; * Figure out the r4k offset, the amount to increment the compare&n; * register for each time tick. &n; * Use the Programmable Counter 1 to do this.&n; */
DECL|function|cal_r4koff
r_int
r_int
id|cal_r4koff
c_func
(paren
r_void
)paren
(brace
r_int
r_int
id|count
suffix:semicolon
r_int
r_int
id|cpu_pll
suffix:semicolon
r_int
r_int
id|cpu_speed
suffix:semicolon
r_int
r_int
id|start
comma
id|end
suffix:semicolon
r_int
r_int
id|counter
suffix:semicolon
r_int
id|i
suffix:semicolon
r_int
id|trim_divide
op_assign
l_int|16
suffix:semicolon
id|counter
op_assign
id|inl
c_func
(paren
id|PC_COUNTER_CNTRL
)paren
suffix:semicolon
id|outl
c_func
(paren
id|counter
op_or
id|PC_CNTRL_EN1
comma
id|PC_COUNTER_CNTRL
)paren
suffix:semicolon
r_while
c_loop
(paren
id|inl
c_func
(paren
id|PC_COUNTER_CNTRL
)paren
op_amp
id|PC_CNTRL_T1S
)paren
suffix:semicolon
id|outl
c_func
(paren
id|trim_divide
op_minus
l_int|1
comma
id|PC1_TRIM
)paren
suffix:semicolon
multiline_comment|/* RTC now ticks at 32.768/16 kHz */
r_while
c_loop
(paren
id|inl
c_func
(paren
id|PC_COUNTER_CNTRL
)paren
op_amp
id|PC_CNTRL_T1S
)paren
suffix:semicolon
r_while
c_loop
(paren
id|inl
c_func
(paren
id|PC_COUNTER_CNTRL
)paren
op_amp
id|PC_CNTRL_C1S
)paren
suffix:semicolon
id|outl
(paren
l_int|0
comma
id|PC1_COUNTER_WRITE
)paren
suffix:semicolon
r_while
c_loop
(paren
id|inl
c_func
(paren
id|PC_COUNTER_CNTRL
)paren
op_amp
id|PC_CNTRL_C1S
)paren
suffix:semicolon
id|start
op_assign
id|inl
c_func
(paren
id|PC1_COUNTER_READ
)paren
suffix:semicolon
id|start
op_add_assign
l_int|2
suffix:semicolon
multiline_comment|/* wait for the beginning of a new tick */
r_while
c_loop
(paren
id|inl
c_func
(paren
id|PC1_COUNTER_READ
)paren
OL
id|start
)paren
suffix:semicolon
multiline_comment|/* Start r4k counter. */
id|write_32bit_cp0_register
c_func
(paren
id|CP0_COUNT
comma
l_int|0
)paren
suffix:semicolon
id|end
op_assign
id|start
op_plus
(paren
l_int|32768
op_div
id|trim_divide
)paren
op_div
l_int|2
suffix:semicolon
multiline_comment|/* wait 0.5 seconds */
r_while
c_loop
(paren
id|end
OG
id|inl
c_func
(paren
id|PC1_COUNTER_READ
)paren
)paren
suffix:semicolon
id|count
op_assign
id|read_32bit_cp0_register
c_func
(paren
id|CP0_COUNT
)paren
suffix:semicolon
id|cpu_speed
op_assign
id|count
op_star
l_int|2
suffix:semicolon
id|uart_baud_base
op_assign
(paren
(paren
(paren
id|cpu_speed
)paren
op_div
l_int|4
)paren
op_div
l_int|16
)paren
suffix:semicolon
r_return
(paren
id|cpu_speed
op_div
id|HZ
)paren
suffix:semicolon
)brace
DECL|function|get_mips_time
r_static
r_int
r_int
id|__init
id|get_mips_time
c_func
(paren
r_void
)paren
(brace
r_return
id|inl
c_func
(paren
id|PC0_COUNTER_READ
)paren
suffix:semicolon
)brace
DECL|function|time_init
r_void
id|__init
id|time_init
c_func
(paren
r_void
)paren
(brace
r_int
r_int
id|est_freq
comma
id|flags
suffix:semicolon
id|printk
c_func
(paren
l_string|&quot;calculating r4koff... &quot;
)paren
suffix:semicolon
id|r4k_offset
op_assign
id|cal_r4koff
c_func
(paren
)paren
suffix:semicolon
id|printk
c_func
(paren
l_string|&quot;%08lx(%d)&bslash;n&quot;
comma
id|r4k_offset
comma
(paren
r_int
)paren
id|r4k_offset
)paren
suffix:semicolon
singleline_comment|//est_freq = 2*r4k_offset*HZ;&t;
id|est_freq
op_assign
id|r4k_offset
op_star
id|HZ
suffix:semicolon
id|est_freq
op_add_assign
l_int|5000
suffix:semicolon
multiline_comment|/* round */
id|est_freq
op_sub_assign
id|est_freq
op_mod
l_int|10000
suffix:semicolon
id|printk
c_func
(paren
l_string|&quot;CPU frequency %d.%02d MHz&bslash;n&quot;
comma
id|est_freq
op_div
l_int|1000000
comma
(paren
id|est_freq
op_mod
l_int|1000000
)paren
op_star
l_int|100
op_div
l_int|1000000
)paren
suffix:semicolon
id|r4k_cur
op_assign
(paren
id|read_32bit_cp0_register
c_func
(paren
id|CP0_COUNT
)paren
op_plus
id|r4k_offset
)paren
suffix:semicolon
id|write_32bit_cp0_register
c_func
(paren
id|CP0_COMPARE
comma
id|r4k_cur
)paren
suffix:semicolon
id|set_cp0_status
c_func
(paren
id|ALLINTS
)paren
suffix:semicolon
multiline_comment|/* Read time from the RTC chipset. */
id|write_lock_irqsave
(paren
op_amp
id|xtime_lock
comma
id|flags
)paren
suffix:semicolon
id|xtime.tv_sec
op_assign
id|get_mips_time
c_func
(paren
)paren
suffix:semicolon
id|xtime.tv_usec
op_assign
l_int|0
suffix:semicolon
id|write_unlock_irqrestore
c_func
(paren
op_amp
id|xtime_lock
comma
id|flags
)paren
suffix:semicolon
)brace
multiline_comment|/* This is for machines which generate the exact clock. */
DECL|macro|USECS_PER_JIFFY
mdefine_line|#define USECS_PER_JIFFY (1000000/HZ)
DECL|macro|USECS_PER_JIFFY_FRAC
mdefine_line|#define USECS_PER_JIFFY_FRAC ((1000000ULL &lt;&lt; 32) / HZ &amp; 0xffffffff)
multiline_comment|/* Cycle counter value at the previous timer interrupt.. */
DECL|variable|timerhi
DECL|variable|timerlo
r_static
r_int
r_int
id|timerhi
op_assign
l_int|0
comma
id|timerlo
op_assign
l_int|0
suffix:semicolon
r_static
r_int
r_int
DECL|function|div64_32
id|div64_32
c_func
(paren
r_int
r_int
id|v1
comma
r_int
r_int
id|v2
comma
r_int
r_int
id|v3
)paren
(brace
r_int
r_int
id|r0
suffix:semicolon
id|do_div64_32
c_func
(paren
id|r0
comma
id|v1
comma
id|v2
comma
id|v3
)paren
suffix:semicolon
r_return
id|r0
suffix:semicolon
)brace
multiline_comment|/*&n; * FIXME: Does playing with the RP bit in c0_status interfere with this code?&n; */
DECL|function|do_fast_gettimeoffset
r_static
r_int
r_int
id|do_fast_gettimeoffset
c_func
(paren
r_void
)paren
(brace
id|u32
id|count
suffix:semicolon
r_int
r_int
id|res
comma
id|tmp
suffix:semicolon
r_int
r_int
id|r0
suffix:semicolon
multiline_comment|/* Last jiffy when do_fast_gettimeoffset() was called. */
r_static
r_int
r_int
id|last_jiffies
op_assign
l_int|0
suffix:semicolon
r_int
r_int
id|quotient
suffix:semicolon
multiline_comment|/*&n;&t; * Cached &quot;1/(clocks per usec)*2^32&quot; value.&n;&t; * It has to be recalculated once each jiffy.&n;&t; */
r_static
r_int
r_int
id|cached_quotient
op_assign
l_int|0
suffix:semicolon
id|tmp
op_assign
id|jiffies
suffix:semicolon
id|quotient
op_assign
id|cached_quotient
suffix:semicolon
r_if
c_cond
(paren
id|tmp
op_logical_and
id|last_jiffies
op_ne
id|tmp
)paren
(brace
id|last_jiffies
op_assign
id|tmp
suffix:semicolon
r_if
c_cond
(paren
id|last_jiffies
op_ne
l_int|0
)paren
(brace
id|r0
op_assign
id|div64_32
c_func
(paren
id|timerhi
comma
id|timerlo
comma
id|tmp
)paren
suffix:semicolon
id|quotient
op_assign
id|div64_32
c_func
(paren
id|USECS_PER_JIFFY
comma
id|USECS_PER_JIFFY_FRAC
comma
id|r0
)paren
suffix:semicolon
id|cached_quotient
op_assign
id|quotient
suffix:semicolon
)brace
)brace
multiline_comment|/* Get last timer tick in absolute kernel time */
id|count
op_assign
id|read_32bit_cp0_register
c_func
(paren
id|CP0_COUNT
)paren
suffix:semicolon
multiline_comment|/* .. relative to previous jiffy (32 bits is enough) */
id|count
op_sub_assign
id|timerlo
suffix:semicolon
id|__asm__
c_func
(paren
l_string|&quot;multu&bslash;t%1,%2&bslash;n&bslash;t&quot;
l_string|&quot;mfhi&bslash;t%0&quot;
suffix:colon
l_string|&quot;=r&quot;
(paren
id|res
)paren
suffix:colon
l_string|&quot;r&quot;
(paren
id|count
)paren
comma
l_string|&quot;r&quot;
(paren
id|quotient
)paren
)paren
suffix:semicolon
multiline_comment|/*&n; &t; * Due to possible jiffies inconsistencies, we need to check &n;&t; * the result so that we&squot;ll get a timer that is monotonic.&n;&t; */
r_if
c_cond
(paren
id|res
op_ge
id|USECS_PER_JIFFY
)paren
id|res
op_assign
id|USECS_PER_JIFFY
op_minus
l_int|1
suffix:semicolon
r_return
id|res
suffix:semicolon
)brace
DECL|function|do_gettimeofday
r_void
id|do_gettimeofday
c_func
(paren
r_struct
id|timeval
op_star
id|tv
)paren
(brace
r_int
r_int
id|flags
suffix:semicolon
id|read_lock_irqsave
(paren
op_amp
id|xtime_lock
comma
id|flags
)paren
suffix:semicolon
op_star
id|tv
op_assign
id|xtime
suffix:semicolon
id|tv-&gt;tv_usec
op_add_assign
id|do_fast_gettimeoffset
c_func
(paren
)paren
suffix:semicolon
multiline_comment|/*&n;&t; * xtime is atomically updated in timer_bh. jiffies - wall_jiffies&n;&t; * is nonzero if the timer bottom half hasnt executed yet.&n;&t; */
r_if
c_cond
(paren
id|jiffies
op_minus
id|wall_jiffies
)paren
id|tv-&gt;tv_usec
op_add_assign
id|USECS_PER_JIFFY
suffix:semicolon
id|read_unlock_irqrestore
(paren
op_amp
id|xtime_lock
comma
id|flags
)paren
suffix:semicolon
r_if
c_cond
(paren
id|tv-&gt;tv_usec
op_ge
l_int|1000000
)paren
(brace
id|tv-&gt;tv_usec
op_sub_assign
l_int|1000000
suffix:semicolon
id|tv-&gt;tv_sec
op_increment
suffix:semicolon
)brace
)brace
DECL|function|do_settimeofday
r_void
id|do_settimeofday
c_func
(paren
r_struct
id|timeval
op_star
id|tv
)paren
(brace
id|write_lock_irq
(paren
op_amp
id|xtime_lock
)paren
suffix:semicolon
multiline_comment|/* This is revolting. We need to set the xtime.tv_usec correctly.&n;&t; * However, the value in this location is is value at the last tick.&n;&t; * Discover what correction gettimeofday would have done, and then&n;&t; * undo it!&n;&t; */
id|tv-&gt;tv_usec
op_sub_assign
id|do_fast_gettimeoffset
c_func
(paren
)paren
suffix:semicolon
r_if
c_cond
(paren
id|tv-&gt;tv_usec
OL
l_int|0
)paren
(brace
id|tv-&gt;tv_usec
op_add_assign
l_int|1000000
suffix:semicolon
id|tv-&gt;tv_sec
op_decrement
suffix:semicolon
)brace
id|xtime
op_assign
op_star
id|tv
suffix:semicolon
id|time_adjust
op_assign
l_int|0
suffix:semicolon
multiline_comment|/* stop active adjtime() */
id|time_status
op_or_assign
id|STA_UNSYNC
suffix:semicolon
id|time_maxerror
op_assign
id|NTP_PHASE_LIMIT
suffix:semicolon
id|time_esterror
op_assign
id|NTP_PHASE_LIMIT
suffix:semicolon
id|write_unlock_irq
(paren
op_amp
id|xtime_lock
)paren
suffix:semicolon
)brace
multiline_comment|/*&n; * The UART baud base is not known at compile time ... if&n; * we want to be able to use the same code on different&n; * speed CPUs.&n; */
DECL|function|get_au1000_uart_baud
r_int
r_int
id|get_au1000_uart_baud
c_func
(paren
)paren
(brace
r_return
id|uart_baud_base
suffix:semicolon
)brace
eof
