multiline_comment|/*&n; *  linux/arch/arm/mach-sa1100/leds-graphicsmaster.c&n; *&n; * GraphicsClient Plus LEDs support&n; * Woojung Huh, Feb 13, 2001&n; */
macro_line|#include &lt;linux/config.h&gt;
macro_line|#include &lt;linux/init.h&gt;
macro_line|#include &lt;asm/hardware.h&gt;
macro_line|#include &lt;asm/leds.h&gt;
macro_line|#include &lt;asm/system.h&gt;
macro_line|#include &quot;leds.h&quot;
DECL|macro|LED_STATE_ENABLED
mdefine_line|#define LED_STATE_ENABLED&t;1
DECL|macro|LED_STATE_CLAIMED
mdefine_line|#define LED_STATE_CLAIMED&t;2
DECL|variable|led_state
r_static
r_int
r_int
id|led_state
suffix:semicolon
DECL|variable|hw_led_state
r_static
r_int
r_int
id|hw_led_state
suffix:semicolon
DECL|macro|LED_TIMER
mdefine_line|#define LED_TIMER       ADS_LED0  /* green heartbeat */
DECL|macro|LED_USER
mdefine_line|#define LED_USER        ADS_LED1  /* amber, boots to on */
DECL|macro|LED_IDLE
mdefine_line|#define LED_IDLE        ADS_LED2  /* red has the idle led, if any */
DECL|macro|LED_MASK
mdefine_line|#define LED_MASK&t;(ADS_LED0|ADS_LED1|ADS_LED2)
DECL|function|graphicsmaster_leds_event
r_void
id|graphicsmaster_leds_event
c_func
(paren
id|led_event_t
id|evt
)paren
(brace
r_int
r_int
id|flags
suffix:semicolon
id|save_flags_cli
c_func
(paren
id|flags
)paren
suffix:semicolon
r_switch
c_cond
(paren
id|evt
)paren
(brace
r_case
id|led_start
suffix:colon
id|hw_led_state
op_assign
l_int|0
suffix:semicolon
multiline_comment|/* gc leds are positive logic */
id|led_state
op_assign
id|LED_STATE_ENABLED
suffix:semicolon
r_break
suffix:semicolon
r_case
id|led_stop
suffix:colon
id|led_state
op_and_assign
op_complement
id|LED_STATE_ENABLED
suffix:semicolon
r_break
suffix:semicolon
r_case
id|led_claim
suffix:colon
id|led_state
op_or_assign
id|LED_STATE_CLAIMED
suffix:semicolon
id|hw_led_state
op_assign
id|LED_MASK
suffix:semicolon
r_break
suffix:semicolon
r_case
id|led_release
suffix:colon
id|led_state
op_and_assign
op_complement
id|LED_STATE_CLAIMED
suffix:semicolon
id|hw_led_state
op_assign
id|LED_MASK
suffix:semicolon
r_break
suffix:semicolon
macro_line|#ifdef CONFIG_LEDS_TIMER
r_case
id|led_timer
suffix:colon
r_if
c_cond
(paren
op_logical_neg
(paren
id|led_state
op_amp
id|LED_STATE_CLAIMED
)paren
)paren
id|hw_led_state
op_xor_assign
id|LED_TIMER
suffix:semicolon
r_break
suffix:semicolon
macro_line|#endif
macro_line|#ifdef CONFIG_LEDS_CPU
r_case
id|led_idle_start
suffix:colon
r_if
c_cond
(paren
op_logical_neg
(paren
id|led_state
op_amp
id|LED_STATE_CLAIMED
)paren
)paren
id|hw_led_state
op_and_assign
op_complement
id|LED_IDLE
suffix:semicolon
r_break
suffix:semicolon
r_case
id|led_idle_end
suffix:colon
r_if
c_cond
(paren
op_logical_neg
(paren
id|led_state
op_amp
id|LED_STATE_CLAIMED
)paren
)paren
id|hw_led_state
op_or_assign
id|LED_IDLE
suffix:semicolon
r_break
suffix:semicolon
macro_line|#endif
r_case
id|led_green_on
suffix:colon
r_break
suffix:semicolon
r_case
id|led_green_off
suffix:colon
r_break
suffix:semicolon
r_case
id|led_amber_on
suffix:colon
id|hw_led_state
op_or_assign
id|LED_USER
suffix:semicolon
r_break
suffix:semicolon
r_case
id|led_amber_off
suffix:colon
id|hw_led_state
op_and_assign
op_complement
id|LED_USER
suffix:semicolon
r_break
suffix:semicolon
r_case
id|led_red_on
suffix:colon
r_break
suffix:semicolon
r_case
id|led_red_off
suffix:colon
r_break
suffix:semicolon
r_default
suffix:colon
r_break
suffix:semicolon
)brace
r_if
c_cond
(paren
id|led_state
op_amp
id|LED_STATE_ENABLED
)paren
(brace
id|GPSR
op_assign
id|hw_led_state
suffix:semicolon
id|GPCR
op_assign
id|hw_led_state
op_xor
id|LED_MASK
suffix:semicolon
)brace
id|restore_flags
c_func
(paren
id|flags
)paren
suffix:semicolon
)brace
eof
