multiline_comment|/* megafunction wizard: %ARM-Based Excalibur%&n;   GENERATION: STANDARD&n;   VERSION: WM1.0&n;   MODULE: ARM-Based Excalibur&n;   PROJECT: excalibur&n;   ============================================================&n;   File Name: v:&bslash;embedded&bslash;linux&bslash;bootldr&bslash;excalibur.h&n;   Megafunction Name(s): ARM-Based Excalibur&n;   ============================================================&n;&n;   ************************************************************&n;   THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!&n;   ************************************************************/
macro_line|#ifndef&t;EXCALIBUR_H_INCLUDED
DECL|macro|EXCALIBUR_H_INCLUDED
mdefine_line|#define&t;EXCALIBUR_H_INCLUDED
DECL|macro|EXC_DEFINE_PROCESSOR_LITTLE_ENDIAN
mdefine_line|#define EXC_DEFINE_PROCESSOR_LITTLE_ENDIAN
DECL|macro|EXC_DEFINE_BOOT_FROM_FLASH
mdefine_line|#define EXC_DEFINE_BOOT_FROM_FLASH
DECL|macro|EXC_INPUT_CLK_FREQUENCY
mdefine_line|#define&t;EXC_INPUT_CLK_FREQUENCY (50000000)
DECL|macro|EXC_AHB1_CLK_FREQUENCY
mdefine_line|#define&t;EXC_AHB1_CLK_FREQUENCY (150000000)
DECL|macro|EXC_AHB2_CLK_FREQUENCY
mdefine_line|#define&t;EXC_AHB2_CLK_FREQUENCY (75000000)
DECL|macro|EXC_SDRAM_CLK_FREQUENCY
mdefine_line|#define&t;EXC_SDRAM_CLK_FREQUENCY (75000000)
multiline_comment|/* Registers Block */
DECL|macro|EXC_REGISTERS_BASE
mdefine_line|#define&t;EXC_REGISTERS_BASE (0x7fffc000)
DECL|macro|EXC_MODE_CTRL00_BASE
mdefine_line|#define&t;EXC_MODE_CTRL00_BASE (EXC_REGISTERS_BASE + 0x000)
DECL|macro|EXC_IO_CTRL00_BASE
mdefine_line|#define&t;EXC_IO_CTRL00_BASE (EXC_REGISTERS_BASE + 0x040)
DECL|macro|EXC_MMAP00_BASE
mdefine_line|#define&t;EXC_MMAP00_BASE (EXC_REGISTERS_BASE + 0x080)
DECL|macro|EXC_PLD_CONFIG00_BASE
mdefine_line|#define&t;EXC_PLD_CONFIG00_BASE (EXC_REGISTERS_BASE + 0x140)
DECL|macro|EXC_TIMER00_BASE
mdefine_line|#define&t;EXC_TIMER00_BASE (EXC_REGISTERS_BASE + 0x200)
DECL|macro|EXC_INT_CTRL00_BASE
mdefine_line|#define&t;EXC_INT_CTRL00_BASE (EXC_REGISTERS_BASE + 0xc00)
DECL|macro|EXC_CLOCK_CTRL00_BASE
mdefine_line|#define&t;EXC_CLOCK_CTRL00_BASE (EXC_REGISTERS_BASE + 0x300)
DECL|macro|EXC_WATCHDOG00_BASE
mdefine_line|#define&t;EXC_WATCHDOG00_BASE (EXC_REGISTERS_BASE + 0xa00)
DECL|macro|EXC_UART00_BASE
mdefine_line|#define&t;EXC_UART00_BASE (EXC_REGISTERS_BASE + 0x280)
DECL|macro|EXC_EBI00_BASE
mdefine_line|#define&t;EXC_EBI00_BASE (EXC_REGISTERS_BASE + 0x380)
DECL|macro|EXC_SDRAM00_BASE
mdefine_line|#define&t;EXC_SDRAM00_BASE (EXC_REGISTERS_BASE + 0x400)
DECL|macro|EXC_AHB12_BRIDGE_CTRL00_BASE
mdefine_line|#define&t;EXC_AHB12_BRIDGE_CTRL00_BASE (EXC_REGISTERS_BASE + 0x800)
DECL|macro|EXC_PLD_STRIPE_BRIDGE_CTRL00_BASE
mdefine_line|#define&t;EXC_PLD_STRIPE_BRIDGE_CTRL00_BASE (EXC_REGISTERS_BASE + 0x100)
DECL|macro|EXC_STRIPE_PLD_BRIDGE_CTRL00_BASE
mdefine_line|#define&t;EXC_STRIPE_PLD_BRIDGE_CTRL00_BASE (EXC_REGISTERS_BASE + 0x100)
DECL|macro|EXC_REGISTERS_SIZE
mdefine_line|#define&t;EXC_REGISTERS_SIZE (0x00004000)
multiline_comment|/* EBI Block(s) */
DECL|macro|EXC_EBI_BLOCK0_BASE
mdefine_line|#define&t;EXC_EBI_BLOCK0_BASE (0x40000000)
DECL|macro|EXC_EBI_BLOCK0_SIZE
mdefine_line|#define&t;EXC_EBI_BLOCK0_SIZE (0x00400000)
DECL|macro|EXC_EBI_BLOCK0_WIDTH
mdefine_line|#define&t;EXC_EBI_BLOCK0_WIDTH (8)
DECL|macro|EXC_EBI_BLOCK0_NON_CACHEABLE
mdefine_line|#define&t;EXC_EBI_BLOCK0_NON_CACHEABLE
DECL|macro|EXC_EBI_BLOCK1_BASE
mdefine_line|#define&t;EXC_EBI_BLOCK1_BASE (0x40400000)
DECL|macro|EXC_EBI_BLOCK1_SIZE
mdefine_line|#define&t;EXC_EBI_BLOCK1_SIZE (0x00400000)
DECL|macro|EXC_EBI_BLOCK1_WIDTH
mdefine_line|#define&t;EXC_EBI_BLOCK1_WIDTH (16)
DECL|macro|EXC_EBI_BLOCK1_NON_CACHEABLE
mdefine_line|#define&t;EXC_EBI_BLOCK1_NON_CACHEABLE
DECL|macro|EXC_EBI_BLOCK2_BASE
mdefine_line|#define&t;EXC_EBI_BLOCK2_BASE (0x40800000)
DECL|macro|EXC_EBI_BLOCK2_SIZE
mdefine_line|#define&t;EXC_EBI_BLOCK2_SIZE (0x00400000)
DECL|macro|EXC_EBI_BLOCK2_WIDTH
mdefine_line|#define&t;EXC_EBI_BLOCK2_WIDTH (16)
DECL|macro|EXC_EBI_BLOCK2_NON_CACHEABLE
mdefine_line|#define&t;EXC_EBI_BLOCK2_NON_CACHEABLE
DECL|macro|EXC_EBI_BLOCK3_BASE
mdefine_line|#define&t;EXC_EBI_BLOCK3_BASE (0x40c00000)
DECL|macro|EXC_EBI_BLOCK3_SIZE
mdefine_line|#define&t;EXC_EBI_BLOCK3_SIZE (0x00400000)
DECL|macro|EXC_EBI_BLOCK3_WIDTH
mdefine_line|#define&t;EXC_EBI_BLOCK3_WIDTH (16)
DECL|macro|EXC_EBI_BLOCK3_NON_CACHEABLE
mdefine_line|#define&t;EXC_EBI_BLOCK3_NON_CACHEABLE
multiline_comment|/* SDRAM Block(s) */
DECL|macro|EXC_SDRAM_BLOCK0_BASE
mdefine_line|#define&t;EXC_SDRAM_BLOCK0_BASE (0x00000000)
DECL|macro|EXC_SDRAM_BLOCK0_SIZE
mdefine_line|#define&t;EXC_SDRAM_BLOCK0_SIZE (0x04000000)
DECL|macro|EXC_SDRAM_BLOCK0_WIDTH
mdefine_line|#define&t;EXC_SDRAM_BLOCK0_WIDTH (32)
DECL|macro|EXC_SDRAM_BLOCK1_BASE
mdefine_line|#define&t;EXC_SDRAM_BLOCK1_BASE (0x04000000)
DECL|macro|EXC_SDRAM_BLOCK1_SIZE
mdefine_line|#define&t;EXC_SDRAM_BLOCK1_SIZE (0x04000000)
DECL|macro|EXC_SDRAM_BLOCK1_WIDTH
mdefine_line|#define&t;EXC_SDRAM_BLOCK1_WIDTH (32)
multiline_comment|/* Single Port SRAM Block(s) */
DECL|macro|EXC_SPSRAM_BLOCK0_BASE
mdefine_line|#define&t;EXC_SPSRAM_BLOCK0_BASE (0x08000000)
DECL|macro|EXC_SPSRAM_BLOCK0_SIZE
mdefine_line|#define&t;EXC_SPSRAM_BLOCK0_SIZE (0x00020000)
DECL|macro|EXC_SPSRAM_BLOCK1_BASE
mdefine_line|#define&t;EXC_SPSRAM_BLOCK1_BASE (0x08020000)
DECL|macro|EXC_SPSRAM_BLOCK1_SIZE
mdefine_line|#define&t;EXC_SPSRAM_BLOCK1_SIZE (0x00020000)
multiline_comment|/* PLD Block(s) */
DECL|macro|EXC_PLD_BLOCK0_BASE
mdefine_line|#define&t;EXC_PLD_BLOCK0_BASE (0x80000000)
DECL|macro|EXC_PLD_BLOCK0_SIZE
mdefine_line|#define&t;EXC_PLD_BLOCK0_SIZE (0x00004000)
DECL|macro|EXC_PLD_BLOCK0_NON_CACHEABLE
mdefine_line|#define&t;EXC_PLD_BLOCK0_NON_CACHEABLE
DECL|macro|EXC_PLD_BLOCK1_BASE
mdefine_line|#define&t;EXC_PLD_BLOCK1_BASE (0xf000000)
DECL|macro|EXC_PLD_BLOCK1_SIZE
mdefine_line|#define&t;EXC_PLD_BLOCK1_SIZE (0x00004000)
DECL|macro|EXC_PLD_BLOCK1_NON_CACHEABLE
mdefine_line|#define&t;EXC_PLD_BLOCK1_NON_CACHEABLE
DECL|macro|EXC_PLD_BLOCK2_BASE
mdefine_line|#define&t;EXC_PLD_BLOCK2_BASE (0x80008000)
DECL|macro|EXC_PLD_BLOCK2_SIZE
mdefine_line|#define&t;EXC_PLD_BLOCK2_SIZE (0x00004000)
DECL|macro|EXC_PLD_BLOCK2_NON_CACHEABLE
mdefine_line|#define&t;EXC_PLD_BLOCK2_NON_CACHEABLE
DECL|macro|EXC_PLD_BLOCK3_BASE
mdefine_line|#define&t;EXC_PLD_BLOCK3_BASE (0x8000c000)
DECL|macro|EXC_PLD_BLOCK3_SIZE
mdefine_line|#define&t;EXC_PLD_BLOCK3_SIZE (0x00004000)
DECL|macro|EXC_PLD_BLOCK3_NON_CACHEABLE
mdefine_line|#define&t;EXC_PLD_BLOCK3_NON_CACHEABLE
macro_line|#endif
eof
