multiline_comment|/*&n; * IoHriMainStore.h&n; * Copyright (C) 2001  Mike Corrigan IBM Corporation&n; * &n; * This program is free software; you can redistribute it and/or modify&n; * it under the terms of the GNU General Public License as published by&n; * the Free Software Foundation; either version 2 of the License, or&n; * (at your option) any later version.&n; * &n; * This program is distributed in the hope that it will be useful,&n; * but WITHOUT ANY WARRANTY; without even the implied warranty of&n; * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the&n; * GNU General Public License for more details.&n; * &n; * You should have received a copy of the GNU General Public License&n; * along with this program; if not, write to the Free Software&n; * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA&n; */
macro_line|#ifndef _IOHRIMAINSTORE_H
DECL|macro|_IOHRIMAINSTORE_H
mdefine_line|#define _IOHRIMAINSTORE_H
DECL|struct|IoHriMainStoreSegment4
r_struct
id|IoHriMainStoreSegment4
(brace
DECL|member|msArea0Exists
id|u8
id|msArea0Exists
suffix:colon
l_int|1
suffix:semicolon
DECL|member|msArea1Exists
id|u8
id|msArea1Exists
suffix:colon
l_int|1
suffix:semicolon
DECL|member|msArea2Exists
id|u8
id|msArea2Exists
suffix:colon
l_int|1
suffix:semicolon
DECL|member|msArea3Exists
id|u8
id|msArea3Exists
suffix:colon
l_int|1
suffix:semicolon
DECL|member|reserved1
id|u8
id|reserved1
suffix:colon
l_int|4
suffix:semicolon
DECL|member|reserved2
id|u8
id|reserved2
suffix:semicolon
DECL|member|msArea0Functional
id|u8
id|msArea0Functional
suffix:colon
l_int|1
suffix:semicolon
DECL|member|msArea1Functional
id|u8
id|msArea1Functional
suffix:colon
l_int|1
suffix:semicolon
DECL|member|msArea2Functional
id|u8
id|msArea2Functional
suffix:colon
l_int|1
suffix:semicolon
DECL|member|msArea3Functional
id|u8
id|msArea3Functional
suffix:colon
l_int|1
suffix:semicolon
DECL|member|reserved3
id|u8
id|reserved3
suffix:colon
l_int|4
suffix:semicolon
DECL|member|reserved4
id|u8
id|reserved4
suffix:semicolon
DECL|member|totalMainStore
id|u32
id|totalMainStore
suffix:semicolon
DECL|member|msArea0Ptr
id|u64
id|msArea0Ptr
suffix:semicolon
DECL|member|msArea1Ptr
id|u64
id|msArea1Ptr
suffix:semicolon
DECL|member|msArea2Ptr
id|u64
id|msArea2Ptr
suffix:semicolon
DECL|member|msArea3Ptr
id|u64
id|msArea3Ptr
suffix:semicolon
DECL|member|cardProductionLevel
id|u32
id|cardProductionLevel
suffix:semicolon
DECL|member|msAdrHole
id|u32
id|msAdrHole
suffix:semicolon
DECL|member|msArea0HasRiserVpd
id|u8
id|msArea0HasRiserVpd
suffix:colon
l_int|1
suffix:semicolon
DECL|member|msArea1HasRiserVpd
id|u8
id|msArea1HasRiserVpd
suffix:colon
l_int|1
suffix:semicolon
DECL|member|msArea2HasRiserVpd
id|u8
id|msArea2HasRiserVpd
suffix:colon
l_int|1
suffix:semicolon
DECL|member|msArea3HasRiserVpd
id|u8
id|msArea3HasRiserVpd
suffix:colon
l_int|1
suffix:semicolon
DECL|member|reserved5
id|u8
id|reserved5
suffix:colon
l_int|4
suffix:semicolon
DECL|member|reserved6
id|u8
id|reserved6
suffix:semicolon
DECL|member|reserved7
id|u16
id|reserved7
suffix:semicolon
DECL|member|reserved8
id|u8
id|reserved8
(braket
l_int|28
)braket
suffix:semicolon
DECL|member|nonInterleavedBlocksStartAdr
id|u64
id|nonInterleavedBlocksStartAdr
suffix:semicolon
DECL|member|nonInterleavedBlocksEndAdr
id|u64
id|nonInterleavedBlocksEndAdr
suffix:semicolon
)brace
suffix:semicolon
macro_line|#endif 
singleline_comment|// _IOHRIMAINSTORE_H
eof
