macro_line|#ifndef __ASM_OFFSETS_H__
DECL|macro|__ASM_OFFSETS_H__
mdefine_line|#define __ASM_OFFSETS_H__
multiline_comment|/*&n; * DO NOT MODIFY.&n; *&n; * This file was generated by arch/arm26/Makefile&n; *&n; */
DECL|macro|TSK_ACTIVE_MM
mdefine_line|#define TSK_ACTIVE_MM 96 /* offsetof(struct task_struct, active_mm) */
DECL|macro|VMA_VM_MM
mdefine_line|#define VMA_VM_MM 0 /* offsetof(struct vm_area_struct, vm_mm) */
DECL|macro|VMA_VM_FLAGS
mdefine_line|#define VMA_VM_FLAGS 20 /* offsetof(struct vm_area_struct, vm_flags) */
DECL|macro|VM_EXEC
mdefine_line|#define VM_EXEC 4 /* VM_EXEC */
DECL|macro|PAGE_PRESENT
mdefine_line|#define PAGE_PRESENT 1 /* L_PTE_PRESENT */
DECL|macro|PAGE_READONLY
mdefine_line|#define PAGE_READONLY 95 /* PAGE_READONLY */
DECL|macro|PAGE_NOT_USER
mdefine_line|#define PAGE_NOT_USER 3 /* PAGE_NONE */
DECL|macro|PAGE_OLD
mdefine_line|#define PAGE_OLD 3 /* PAGE_NONE */
DECL|macro|PAGE_CLEAN
mdefine_line|#define PAGE_CLEAN 128 /* L_PTE_DIRTY */
DECL|macro|PAGE_SZ
mdefine_line|#define PAGE_SZ 32768 /* PAGE_SIZE */
DECL|macro|SYS_ERROR0
mdefine_line|#define SYS_ERROR0 10420224 /* 0x9f0000 */
macro_line|#endif
eof
