multiline_comment|/****************************************************************&n; *&n; *     kaweth.c - driver for KL5KUSB101 based USB-&gt;Ethernet&n; *&n; *     (c) 2000 Interlan Communications&n; *     (c) 2000 Stephane Alnet&n; *     (C) 2001 Brad Hards&n; *     (C) 2002 Oliver Neukum&n; *&n; *     Original author: The Zapman &lt;zapman@interlan.net&gt;&n; *     Inspired by, and much credit goes to Michael Rothwell&n; *     &lt;rothwell@interlan.net&gt; for the test equipment, help, and patience&n; *     Based off of (and with thanks to) Petko Manolov&squot;s pegaus.c driver.&n; *     Also many thanks to Joel Silverman and Ed Surprenant at Kawasaki&n; *     for providing the firmware and driver resources.&n; *&n; *     This program is free software; you can redistribute it and/or&n; *     modify it under the terms of the GNU General Public License as&n; *     published by the Free Software Foundation; either version 2, or&n; *     (at your option) any later version.&n; *&n; *     This program is distributed in the hope that it will be useful,&n; *     but WITHOUT ANY WARRANTY; without even the implied warranty of&n; *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the&n; *     GNU General Public License for more details.&n; *&n; *     You should have received a copy of the GNU General Public License&n; *     along with this program; if not, write to the Free Software Foundation,&n; *     Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.&n; *&n; ****************************************************************/
multiline_comment|/* TODO:&n; * Fix in_interrupt() problem&n; * Develop test procedures for USB net interfaces&n; * Run test procedures&n; * Fix bugs from previous two steps&n; * Snoop other OSs for any tricks we&squot;re not doing&n; * SMP locking&n; * Reduce arbitrary timeouts&n; * Smart multicast support&n; * Temporary MAC change support&n; * Tunable SOFs parameter - ioctl()?&n; * Ethernet stats collection&n; * Code formatting improvements&n; */
macro_line|#include &lt;linux/module.h&gt;
macro_line|#include &lt;linux/sched.h&gt;
macro_line|#include &lt;linux/slab.h&gt;
macro_line|#include &lt;linux/string.h&gt;
macro_line|#include &lt;linux/init.h&gt;
macro_line|#include &lt;linux/delay.h&gt;
macro_line|#include &lt;linux/netdevice.h&gt;
macro_line|#include &lt;linux/etherdevice.h&gt;
macro_line|#include &lt;linux/usb.h&gt;
macro_line|#include &lt;linux/types.h&gt;
macro_line|#include &lt;asm/semaphore.h&gt;
macro_line|#include &lt;asm/byteorder.h&gt;
DECL|macro|DEBUG
mdefine_line|#define DEBUG
macro_line|#ifdef DEBUG
DECL|macro|kaweth_dbg
mdefine_line|#define kaweth_dbg(format, arg...) printk(KERN_DEBUG __FILE__ &quot;: &quot; format &quot;&bslash;n&quot; ,##arg)
macro_line|#else
DECL|macro|kaweth_dbg
mdefine_line|#define kaweth_dbg(format, arg...) do {} while (0)
macro_line|#endif
DECL|macro|kaweth_err
mdefine_line|#define kaweth_err(format, arg...) printk(KERN_ERR __FILE__ &quot;: &quot; format &quot;&bslash;n&quot; ,##arg)
DECL|macro|kaweth_info
mdefine_line|#define kaweth_info(format, arg...) printk(KERN_INFO __FILE__ &quot;: &quot; format &quot;&bslash;n&quot; , ##arg)
DECL|macro|kaweth_warn
mdefine_line|#define kaweth_warn(format, arg...) printk(KERN_WARNING __FILE__ &quot;: &quot; format &quot;&bslash;n&quot; , ##arg)
macro_line|#include &quot;kawethfw.h&quot;
DECL|macro|KAWETH_MTU
mdefine_line|#define KAWETH_MTU&t;&t;&t;1514
DECL|macro|KAWETH_BUF_SIZE
mdefine_line|#define KAWETH_BUF_SIZE&t;&t;&t;1664
DECL|macro|KAWETH_TX_TIMEOUT
mdefine_line|#define KAWETH_TX_TIMEOUT&t;&t;(5 * HZ)
DECL|macro|KAWETH_FIRMWARE_BUF_SIZE
mdefine_line|#define KAWETH_FIRMWARE_BUF_SIZE&t;4096
DECL|macro|KAWETH_CONTROL_TIMEOUT
mdefine_line|#define KAWETH_CONTROL_TIMEOUT&t;&t;(30 * HZ)
DECL|macro|KAWETH_STATUS_BROKEN
mdefine_line|#define KAWETH_STATUS_BROKEN&t;&t;0x0000001
DECL|macro|KAWETH_STATUS_CLOSING
mdefine_line|#define KAWETH_STATUS_CLOSING&t;&t;0x0000002
DECL|macro|KAWETH_PACKET_FILTER_PROMISCUOUS
mdefine_line|#define KAWETH_PACKET_FILTER_PROMISCUOUS&t;0x01
DECL|macro|KAWETH_PACKET_FILTER_ALL_MULTICAST
mdefine_line|#define KAWETH_PACKET_FILTER_ALL_MULTICAST&t;0x02
DECL|macro|KAWETH_PACKET_FILTER_DIRECTED
mdefine_line|#define KAWETH_PACKET_FILTER_DIRECTED&t;&t;0x04
DECL|macro|KAWETH_PACKET_FILTER_BROADCAST
mdefine_line|#define KAWETH_PACKET_FILTER_BROADCAST&t;&t;0x08
DECL|macro|KAWETH_PACKET_FILTER_MULTICAST
mdefine_line|#define KAWETH_PACKET_FILTER_MULTICAST&t;&t;0x10
multiline_comment|/* Table 7 */
DECL|macro|KAWETH_COMMAND_GET_ETHERNET_DESC
mdefine_line|#define KAWETH_COMMAND_GET_ETHERNET_DESC&t;0x00
DECL|macro|KAWETH_COMMAND_MULTICAST_FILTERS
mdefine_line|#define KAWETH_COMMAND_MULTICAST_FILTERS        0x01
DECL|macro|KAWETH_COMMAND_SET_PACKET_FILTER
mdefine_line|#define KAWETH_COMMAND_SET_PACKET_FILTER&t;0x02
DECL|macro|KAWETH_COMMAND_STATISTICS
mdefine_line|#define KAWETH_COMMAND_STATISTICS               0x03
DECL|macro|KAWETH_COMMAND_SET_TEMP_MAC
mdefine_line|#define KAWETH_COMMAND_SET_TEMP_MAC     &t;0x06
DECL|macro|KAWETH_COMMAND_GET_TEMP_MAC
mdefine_line|#define KAWETH_COMMAND_GET_TEMP_MAC             0x07
DECL|macro|KAWETH_COMMAND_SET_URB_SIZE
mdefine_line|#define KAWETH_COMMAND_SET_URB_SIZE&t;&t;0x08
DECL|macro|KAWETH_COMMAND_SET_SOFS_WAIT
mdefine_line|#define KAWETH_COMMAND_SET_SOFS_WAIT&t;&t;0x09
DECL|macro|KAWETH_COMMAND_SCAN
mdefine_line|#define KAWETH_COMMAND_SCAN&t;&t;&t;0xFF
DECL|macro|KAWETH_SOFS_TO_WAIT
mdefine_line|#define KAWETH_SOFS_TO_WAIT&t;&t;&t;0x05
id|MODULE_AUTHOR
c_func
(paren
l_string|&quot;Michael Zappe &lt;zapman@interlan.net&gt;, Stephane Alnet &lt;stephane@u-picardie.fr&gt; and Brad Hards &lt;bhards@bigpond.net.au&gt;&quot;
)paren
suffix:semicolon
id|MODULE_DESCRIPTION
c_func
(paren
l_string|&quot;KL5USB101 USB Ethernet driver&quot;
)paren
suffix:semicolon
id|MODULE_LICENSE
c_func
(paren
l_string|&quot;GPL&quot;
)paren
suffix:semicolon
r_static
r_void
op_star
id|kaweth_probe
c_func
(paren
r_struct
id|usb_device
op_star
id|dev
comma
multiline_comment|/* the device */
r_int
id|ifnum
comma
multiline_comment|/* what interface */
r_const
r_struct
id|usb_device_id
op_star
id|id
multiline_comment|/* from id_table */
)paren
suffix:semicolon
r_static
r_void
id|kaweth_disconnect
c_func
(paren
r_struct
id|usb_device
op_star
id|dev
comma
r_void
op_star
id|ptr
)paren
suffix:semicolon
r_int
id|kaweth_internal_control_msg
c_func
(paren
r_struct
id|usb_device
op_star
id|usb_dev
comma
r_int
r_int
id|pipe
comma
r_struct
id|usb_ctrlrequest
op_star
id|cmd
comma
r_void
op_star
id|data
comma
r_int
id|len
comma
r_int
id|timeout
)paren
suffix:semicolon
multiline_comment|/****************************************************************&n; *     usb_device_id&n; ****************************************************************/
DECL|variable|usb_klsi_table
r_static
r_struct
id|usb_device_id
id|usb_klsi_table
(braket
)braket
op_assign
(brace
(brace
id|USB_DEVICE
c_func
(paren
l_int|0x03e8
comma
l_int|0x0008
)paren
)brace
comma
multiline_comment|/* AOX Endpoints USB Ethernet */
(brace
id|USB_DEVICE
c_func
(paren
l_int|0x04bb
comma
l_int|0x0901
)paren
)brace
comma
multiline_comment|/* I-O DATA USB-ET/T */
(brace
id|USB_DEVICE
c_func
(paren
l_int|0x0506
comma
l_int|0x03e8
)paren
)brace
comma
multiline_comment|/* 3Com 3C19250 */
(brace
id|USB_DEVICE
c_func
(paren
l_int|0x0557
comma
l_int|0x2002
)paren
)brace
comma
multiline_comment|/* ATEN USB Ethernet */
(brace
id|USB_DEVICE
c_func
(paren
l_int|0x0557
comma
l_int|0x4000
)paren
)brace
comma
multiline_comment|/* D-Link DSB-650C */
(brace
id|USB_DEVICE
c_func
(paren
l_int|0x0565
comma
l_int|0x0002
)paren
)brace
comma
multiline_comment|/* Peracom Enet */
(brace
id|USB_DEVICE
c_func
(paren
l_int|0x0565
comma
l_int|0x0003
)paren
)brace
comma
multiline_comment|/* Optus@Home UEP1045A */
(brace
id|USB_DEVICE
c_func
(paren
l_int|0x0565
comma
l_int|0x0005
)paren
)brace
comma
multiline_comment|/* Peracom Enet2 */
(brace
id|USB_DEVICE
c_func
(paren
l_int|0x05e9
comma
l_int|0x0008
)paren
)brace
comma
multiline_comment|/* KLSI KL5KUSB101B */
(brace
id|USB_DEVICE
c_func
(paren
l_int|0x05e9
comma
l_int|0x0009
)paren
)brace
comma
multiline_comment|/* KLSI KL5KUSB101B (Board change) */
(brace
id|USB_DEVICE
c_func
(paren
l_int|0x066b
comma
l_int|0x2202
)paren
)brace
comma
multiline_comment|/* Linksys USB10T */
(brace
id|USB_DEVICE
c_func
(paren
l_int|0x06e1
comma
l_int|0x0008
)paren
)brace
comma
multiline_comment|/* ADS USB-10BT */
(brace
id|USB_DEVICE
c_func
(paren
l_int|0x06e1
comma
l_int|0x0009
)paren
)brace
comma
multiline_comment|/* ADS USB-10BT */
(brace
id|USB_DEVICE
c_func
(paren
l_int|0x0707
comma
l_int|0x0100
)paren
)brace
comma
multiline_comment|/* SMC 2202USB */
(brace
id|USB_DEVICE
c_func
(paren
l_int|0x07aa
comma
l_int|0x0001
)paren
)brace
comma
multiline_comment|/* Correga K.K. */
(brace
id|USB_DEVICE
c_func
(paren
l_int|0x07b8
comma
l_int|0x4000
)paren
)brace
comma
multiline_comment|/* D-Link DU-E10 */
(brace
id|USB_DEVICE
c_func
(paren
l_int|0x0846
comma
l_int|0x1001
)paren
)brace
comma
multiline_comment|/* NetGear EA-101 */
(brace
id|USB_DEVICE
c_func
(paren
l_int|0x0846
comma
l_int|0x1002
)paren
)brace
comma
multiline_comment|/* NetGear EA-101 */
(brace
id|USB_DEVICE
c_func
(paren
l_int|0x085a
comma
l_int|0x0008
)paren
)brace
comma
multiline_comment|/* PortGear Ethernet Adapter */
(brace
id|USB_DEVICE
c_func
(paren
l_int|0x085a
comma
l_int|0x0009
)paren
)brace
comma
multiline_comment|/* PortGear Ethernet Adapter */
(brace
id|USB_DEVICE
c_func
(paren
l_int|0x087d
comma
l_int|0x5704
)paren
)brace
comma
multiline_comment|/* Jaton USB Ethernet Device Adapter */
(brace
id|USB_DEVICE
c_func
(paren
l_int|0x0951
comma
l_int|0x0008
)paren
)brace
comma
multiline_comment|/* Kingston Technology USB Ethernet Adapter */
(brace
id|USB_DEVICE
c_func
(paren
l_int|0x095a
comma
l_int|0x3003
)paren
)brace
comma
multiline_comment|/* Portsmith Express Ethernet Adapter */
(brace
id|USB_DEVICE
c_func
(paren
l_int|0x10bd
comma
l_int|0x1427
)paren
)brace
comma
multiline_comment|/* ASANTE USB To Ethernet Adapter */
(brace
id|USB_DEVICE
c_func
(paren
l_int|0x1342
comma
l_int|0x0204
)paren
)brace
comma
multiline_comment|/* Mobility USB-Ethernet Adapter */
(brace
id|USB_DEVICE
c_func
(paren
l_int|0x13d2
comma
l_int|0x0400
)paren
)brace
comma
multiline_comment|/* Shark Pocket Adapter */
(brace
id|USB_DEVICE
c_func
(paren
l_int|0x1645
comma
l_int|0x0005
)paren
)brace
comma
multiline_comment|/* Entrega E45 */
(brace
id|USB_DEVICE
c_func
(paren
l_int|0x1645
comma
l_int|0x0008
)paren
)brace
comma
multiline_comment|/* Entrega USB Ethernet Adapter */
(brace
id|USB_DEVICE
c_func
(paren
l_int|0x1645
comma
l_int|0x8005
)paren
)brace
comma
multiline_comment|/* PortGear Ethernet Adapter */
(brace
id|USB_DEVICE
c_func
(paren
l_int|0x2001
comma
l_int|0x4000
)paren
)brace
comma
multiline_comment|/* D-link DSB-650C */
(brace
)brace
multiline_comment|/* Null terminator */
)brace
suffix:semicolon
id|MODULE_DEVICE_TABLE
(paren
id|usb
comma
id|usb_klsi_table
)paren
suffix:semicolon
multiline_comment|/****************************************************************&n; *     kaweth_driver&n; ****************************************************************/
DECL|variable|kaweth_driver
r_static
r_struct
id|usb_driver
id|kaweth_driver
op_assign
(brace
id|owner
suffix:colon
id|THIS_MODULE
comma
id|name
suffix:colon
l_string|&quot;kaweth&quot;
comma
id|probe
suffix:colon
id|kaweth_probe
comma
id|disconnect
suffix:colon
id|kaweth_disconnect
comma
id|id_table
suffix:colon
id|usb_klsi_table
comma
)brace
suffix:semicolon
DECL|typedef|eth_addr_t
r_typedef
id|__u8
id|eth_addr_t
(braket
l_int|6
)braket
suffix:semicolon
multiline_comment|/****************************************************************&n; *     usb_eth_dev&n; ****************************************************************/
DECL|struct|usb_eth_dev
r_struct
id|usb_eth_dev
(brace
DECL|member|name
r_char
op_star
id|name
suffix:semicolon
DECL|member|vendor
id|__u16
id|vendor
suffix:semicolon
DECL|member|device
id|__u16
id|device
suffix:semicolon
DECL|member|pdata
r_void
op_star
id|pdata
suffix:semicolon
)brace
suffix:semicolon
multiline_comment|/****************************************************************&n; *     kaweth_ethernet_configuration&n; *     Refer Table 8&n; ****************************************************************/
DECL|struct|kaweth_ethernet_configuration
r_struct
id|kaweth_ethernet_configuration
(brace
DECL|member|size
id|__u8
id|size
suffix:semicolon
DECL|member|reserved1
id|__u8
id|reserved1
suffix:semicolon
DECL|member|reserved2
id|__u8
id|reserved2
suffix:semicolon
DECL|member|hw_addr
id|eth_addr_t
id|hw_addr
suffix:semicolon
DECL|member|statistics_mask
id|__u32
id|statistics_mask
suffix:semicolon
DECL|member|segment_size
id|__u16
id|segment_size
suffix:semicolon
DECL|member|max_multicast_filters
id|__u16
id|max_multicast_filters
suffix:semicolon
DECL|member|reserved3
id|__u8
id|reserved3
suffix:semicolon
)brace
id|__attribute__
(paren
(paren
id|packed
)paren
)paren
suffix:semicolon
multiline_comment|/****************************************************************&n; *     kaweth_device&n; ****************************************************************/
DECL|struct|kaweth_device
r_struct
id|kaweth_device
(brace
DECL|member|device_lock
id|spinlock_t
id|device_lock
suffix:semicolon
DECL|member|status
id|__u32
id|status
suffix:semicolon
DECL|member|end
r_int
id|end
suffix:semicolon
DECL|member|removed
r_int
id|removed
suffix:semicolon
DECL|member|dev
r_struct
id|usb_device
op_star
id|dev
suffix:semicolon
DECL|member|net
r_struct
id|net_device
op_star
id|net
suffix:semicolon
DECL|member|term_wait
id|wait_queue_head_t
id|term_wait
suffix:semicolon
DECL|member|rx_urb
r_struct
id|urb
op_star
id|rx_urb
suffix:semicolon
DECL|member|tx_urb
r_struct
id|urb
op_star
id|tx_urb
suffix:semicolon
DECL|member|firmware_buf
id|__u8
id|firmware_buf
(braket
id|KAWETH_FIRMWARE_BUF_SIZE
)braket
suffix:semicolon
DECL|member|tx_buf
id|__u8
id|tx_buf
(braket
id|KAWETH_BUF_SIZE
)braket
suffix:semicolon
DECL|member|rx_buf
id|__u8
id|rx_buf
(braket
id|KAWETH_BUF_SIZE
)braket
suffix:semicolon
DECL|member|packet_filter_bitmap
id|__u16
id|packet_filter_bitmap
suffix:semicolon
DECL|member|configuration
r_struct
id|kaweth_ethernet_configuration
id|configuration
suffix:semicolon
DECL|member|stats
r_struct
id|net_device_stats
id|stats
suffix:semicolon
)brace
id|__attribute__
(paren
(paren
id|packed
)paren
)paren
suffix:semicolon
multiline_comment|/****************************************************************&n; *     kaweth_control&n; ****************************************************************/
DECL|function|kaweth_control
r_static
r_int
id|kaweth_control
c_func
(paren
r_struct
id|kaweth_device
op_star
id|kaweth
comma
r_int
r_int
id|pipe
comma
id|__u8
id|request
comma
id|__u8
id|requesttype
comma
id|__u16
id|value
comma
id|__u16
id|index
comma
r_void
op_star
id|data
comma
id|__u16
id|size
comma
r_int
id|timeout
)paren
(brace
r_struct
id|usb_ctrlrequest
op_star
id|dr
suffix:semicolon
id|kaweth_dbg
c_func
(paren
l_string|&quot;kaweth_control()&quot;
)paren
suffix:semicolon
r_if
c_cond
(paren
id|in_interrupt
c_func
(paren
)paren
)paren
(brace
id|kaweth_dbg
c_func
(paren
l_string|&quot;in_interrupt()&quot;
)paren
suffix:semicolon
r_return
op_minus
id|EBUSY
suffix:semicolon
)brace
id|dr
op_assign
id|kmalloc
c_func
(paren
r_sizeof
(paren
r_struct
id|usb_ctrlrequest
)paren
comma
id|GFP_ATOMIC
)paren
suffix:semicolon
r_if
c_cond
(paren
op_logical_neg
id|dr
)paren
(brace
id|kaweth_dbg
c_func
(paren
l_string|&quot;kmalloc() failed&quot;
)paren
suffix:semicolon
r_return
op_minus
id|ENOMEM
suffix:semicolon
)brace
id|dr-&gt;bRequestType
op_assign
id|requesttype
suffix:semicolon
id|dr-&gt;bRequest
op_assign
id|request
suffix:semicolon
id|dr-&gt;wValue
op_assign
id|cpu_to_le16p
c_func
(paren
op_amp
id|value
)paren
suffix:semicolon
id|dr-&gt;wIndex
op_assign
id|cpu_to_le16p
c_func
(paren
op_amp
id|index
)paren
suffix:semicolon
id|dr-&gt;wLength
op_assign
id|cpu_to_le16p
c_func
(paren
op_amp
id|size
)paren
suffix:semicolon
r_return
id|kaweth_internal_control_msg
c_func
(paren
id|kaweth-&gt;dev
comma
id|pipe
comma
id|dr
comma
id|data
comma
id|size
comma
id|timeout
)paren
suffix:semicolon
)brace
multiline_comment|/****************************************************************&n; *     kaweth_read_configuration&n; ****************************************************************/
DECL|function|kaweth_read_configuration
r_static
r_int
id|kaweth_read_configuration
c_func
(paren
r_struct
id|kaweth_device
op_star
id|kaweth
)paren
(brace
r_int
id|retval
suffix:semicolon
id|kaweth_dbg
c_func
(paren
l_string|&quot;Reading kaweth configuration&quot;
)paren
suffix:semicolon
id|retval
op_assign
id|kaweth_control
c_func
(paren
id|kaweth
comma
id|usb_rcvctrlpipe
c_func
(paren
id|kaweth-&gt;dev
comma
l_int|0
)paren
comma
id|KAWETH_COMMAND_GET_ETHERNET_DESC
comma
id|USB_TYPE_VENDOR
op_or
id|USB_DIR_IN
op_or
id|USB_RECIP_DEVICE
comma
l_int|0
comma
l_int|0
comma
(paren
r_void
op_star
)paren
op_amp
id|kaweth-&gt;configuration
comma
r_sizeof
(paren
id|kaweth-&gt;configuration
)paren
comma
id|KAWETH_CONTROL_TIMEOUT
)paren
suffix:semicolon
r_return
id|retval
suffix:semicolon
)brace
multiline_comment|/****************************************************************&n; *     kaweth_set_urb_size&n; ****************************************************************/
DECL|function|kaweth_set_urb_size
r_static
r_int
id|kaweth_set_urb_size
c_func
(paren
r_struct
id|kaweth_device
op_star
id|kaweth
comma
id|__u16
id|urb_size
)paren
(brace
r_int
id|retval
suffix:semicolon
id|kaweth_dbg
c_func
(paren
l_string|&quot;Setting URB size to %d&quot;
comma
(paren
r_int
)paren
id|urb_size
)paren
suffix:semicolon
id|retval
op_assign
id|kaweth_control
c_func
(paren
id|kaweth
comma
id|usb_sndctrlpipe
c_func
(paren
id|kaweth-&gt;dev
comma
l_int|0
)paren
comma
id|KAWETH_COMMAND_SET_URB_SIZE
comma
id|USB_TYPE_VENDOR
op_or
id|USB_DIR_OUT
op_or
id|USB_RECIP_DEVICE
comma
id|urb_size
comma
l_int|0
comma
(paren
r_void
op_star
)paren
op_amp
id|kaweth-&gt;firmware_buf
comma
l_int|0
comma
id|KAWETH_CONTROL_TIMEOUT
)paren
suffix:semicolon
r_return
id|retval
suffix:semicolon
)brace
multiline_comment|/****************************************************************&n; *     kaweth_set_sofs_wait&n; ****************************************************************/
DECL|function|kaweth_set_sofs_wait
r_static
r_int
id|kaweth_set_sofs_wait
c_func
(paren
r_struct
id|kaweth_device
op_star
id|kaweth
comma
id|__u16
id|sofs_wait
)paren
(brace
r_int
id|retval
suffix:semicolon
id|kaweth_dbg
c_func
(paren
l_string|&quot;Set SOFS wait to %d&quot;
comma
(paren
r_int
)paren
id|sofs_wait
)paren
suffix:semicolon
id|retval
op_assign
id|kaweth_control
c_func
(paren
id|kaweth
comma
id|usb_sndctrlpipe
c_func
(paren
id|kaweth-&gt;dev
comma
l_int|0
)paren
comma
id|KAWETH_COMMAND_SET_SOFS_WAIT
comma
id|USB_TYPE_VENDOR
op_or
id|USB_DIR_OUT
op_or
id|USB_RECIP_DEVICE
comma
id|sofs_wait
comma
l_int|0
comma
(paren
r_void
op_star
)paren
op_amp
id|kaweth-&gt;firmware_buf
comma
l_int|0
comma
id|KAWETH_CONTROL_TIMEOUT
)paren
suffix:semicolon
r_return
id|retval
suffix:semicolon
)brace
multiline_comment|/****************************************************************&n; *     kaweth_set_receive_filter&n; ****************************************************************/
DECL|function|kaweth_set_receive_filter
r_static
r_int
id|kaweth_set_receive_filter
c_func
(paren
r_struct
id|kaweth_device
op_star
id|kaweth
comma
id|__u16
id|receive_filter
)paren
(brace
r_int
id|retval
suffix:semicolon
id|kaweth_dbg
c_func
(paren
l_string|&quot;Set receive filter to %d&quot;
comma
(paren
r_int
)paren
id|receive_filter
)paren
suffix:semicolon
id|retval
op_assign
id|kaweth_control
c_func
(paren
id|kaweth
comma
id|usb_sndctrlpipe
c_func
(paren
id|kaweth-&gt;dev
comma
l_int|0
)paren
comma
id|KAWETH_COMMAND_SET_PACKET_FILTER
comma
id|USB_TYPE_VENDOR
op_or
id|USB_DIR_OUT
op_or
id|USB_RECIP_DEVICE
comma
id|receive_filter
comma
l_int|0
comma
(paren
r_void
op_star
)paren
op_amp
id|kaweth-&gt;firmware_buf
comma
l_int|0
comma
id|KAWETH_CONTROL_TIMEOUT
)paren
suffix:semicolon
r_return
id|retval
suffix:semicolon
)brace
multiline_comment|/****************************************************************&n; *     kaweth_download_firmware&n; ****************************************************************/
DECL|function|kaweth_download_firmware
r_static
r_int
id|kaweth_download_firmware
c_func
(paren
r_struct
id|kaweth_device
op_star
id|kaweth
comma
id|__u8
op_star
id|data
comma
id|__u16
id|data_len
comma
id|__u8
id|interrupt
comma
id|__u8
id|type
)paren
(brace
r_if
c_cond
(paren
id|data_len
OG
id|KAWETH_FIRMWARE_BUF_SIZE
)paren
(brace
id|kaweth_err
c_func
(paren
l_string|&quot;Firmware too big: %d&quot;
comma
id|data_len
)paren
suffix:semicolon
r_return
op_minus
id|ENOSPC
suffix:semicolon
)brace
id|memcpy
c_func
(paren
id|kaweth-&gt;firmware_buf
comma
id|data
comma
id|data_len
)paren
suffix:semicolon
id|kaweth-&gt;firmware_buf
(braket
l_int|2
)braket
op_assign
(paren
id|data_len
op_amp
l_int|0xFF
)paren
op_minus
l_int|7
suffix:semicolon
id|kaweth-&gt;firmware_buf
(braket
l_int|3
)braket
op_assign
id|data_len
op_rshift
l_int|8
suffix:semicolon
id|kaweth-&gt;firmware_buf
(braket
l_int|4
)braket
op_assign
id|type
suffix:semicolon
id|kaweth-&gt;firmware_buf
(braket
l_int|5
)braket
op_assign
id|interrupt
suffix:semicolon
id|kaweth_dbg
c_func
(paren
l_string|&quot;High: %i, Low:%i&quot;
comma
id|kaweth-&gt;firmware_buf
(braket
l_int|3
)braket
comma
id|kaweth-&gt;firmware_buf
(braket
l_int|2
)braket
)paren
suffix:semicolon
id|kaweth_dbg
c_func
(paren
l_string|&quot;Downloading firmware at %p to kaweth device at %p&quot;
comma
id|data
comma
id|kaweth
)paren
suffix:semicolon
id|kaweth_dbg
c_func
(paren
l_string|&quot;Firmware length: %d&quot;
comma
id|data_len
)paren
suffix:semicolon
r_return
id|kaweth_control
c_func
(paren
id|kaweth
comma
id|usb_sndctrlpipe
c_func
(paren
id|kaweth-&gt;dev
comma
l_int|0
)paren
comma
id|KAWETH_COMMAND_SCAN
comma
id|USB_TYPE_VENDOR
op_or
id|USB_DIR_OUT
op_or
id|USB_RECIP_DEVICE
comma
l_int|0
comma
l_int|0
comma
(paren
r_void
op_star
)paren
op_amp
id|kaweth-&gt;firmware_buf
comma
id|data_len
comma
id|KAWETH_CONTROL_TIMEOUT
)paren
suffix:semicolon
)brace
multiline_comment|/****************************************************************&n; *     kaweth_trigger_firmware&n; ****************************************************************/
DECL|function|kaweth_trigger_firmware
r_static
r_int
id|kaweth_trigger_firmware
c_func
(paren
r_struct
id|kaweth_device
op_star
id|kaweth
comma
id|__u8
id|interrupt
)paren
(brace
id|kaweth-&gt;firmware_buf
(braket
l_int|0
)braket
op_assign
l_int|0xB6
suffix:semicolon
id|kaweth-&gt;firmware_buf
(braket
l_int|1
)braket
op_assign
l_int|0xC3
suffix:semicolon
id|kaweth-&gt;firmware_buf
(braket
l_int|2
)braket
op_assign
l_int|0x01
suffix:semicolon
id|kaweth-&gt;firmware_buf
(braket
l_int|3
)braket
op_assign
l_int|0x00
suffix:semicolon
id|kaweth-&gt;firmware_buf
(braket
l_int|4
)braket
op_assign
l_int|0x06
suffix:semicolon
id|kaweth-&gt;firmware_buf
(braket
l_int|5
)braket
op_assign
id|interrupt
suffix:semicolon
id|kaweth-&gt;firmware_buf
(braket
l_int|6
)braket
op_assign
l_int|0x00
suffix:semicolon
id|kaweth-&gt;firmware_buf
(braket
l_int|7
)braket
op_assign
l_int|0x00
suffix:semicolon
id|kaweth_dbg
c_func
(paren
l_string|&quot;Triggering firmware&quot;
)paren
suffix:semicolon
r_return
id|kaweth_control
c_func
(paren
id|kaweth
comma
id|usb_sndctrlpipe
c_func
(paren
id|kaweth-&gt;dev
comma
l_int|0
)paren
comma
id|KAWETH_COMMAND_SCAN
comma
id|USB_TYPE_VENDOR
op_or
id|USB_DIR_OUT
op_or
id|USB_RECIP_DEVICE
comma
l_int|0
comma
l_int|0
comma
(paren
r_void
op_star
)paren
op_amp
id|kaweth-&gt;firmware_buf
comma
l_int|8
comma
id|KAWETH_CONTROL_TIMEOUT
)paren
suffix:semicolon
)brace
multiline_comment|/****************************************************************&n; *     kaweth_reset&n; ****************************************************************/
DECL|function|kaweth_reset
r_static
r_int
id|kaweth_reset
c_func
(paren
r_struct
id|kaweth_device
op_star
id|kaweth
)paren
(brace
r_int
id|result
suffix:semicolon
id|kaweth_dbg
c_func
(paren
l_string|&quot;kaweth_reset(%p)&quot;
comma
id|kaweth
)paren
suffix:semicolon
id|result
op_assign
id|kaweth_control
c_func
(paren
id|kaweth
comma
id|usb_sndctrlpipe
c_func
(paren
id|kaweth-&gt;dev
comma
l_int|0
)paren
comma
id|USB_REQ_SET_CONFIGURATION
comma
l_int|0
comma
id|kaweth-&gt;dev-&gt;config
(braket
l_int|0
)braket
dot
id|bConfigurationValue
comma
l_int|0
comma
l_int|NULL
comma
l_int|0
comma
id|KAWETH_CONTROL_TIMEOUT
)paren
suffix:semicolon
id|udelay
c_func
(paren
l_int|10000
)paren
suffix:semicolon
id|kaweth_dbg
c_func
(paren
l_string|&quot;kaweth_reset() returns %d.&quot;
comma
id|result
)paren
suffix:semicolon
r_return
id|result
suffix:semicolon
)brace
r_static
r_void
id|kaweth_usb_receive
c_func
(paren
r_struct
id|urb
op_star
)paren
suffix:semicolon
multiline_comment|/****************************************************************&n; *     kaweth_resubmit_rx_urb&n; ****************************************************************/
DECL|function|kaweth_resubmit_rx_urb
r_static
r_inline
r_void
id|kaweth_resubmit_rx_urb
c_func
(paren
r_struct
id|kaweth_device
op_star
id|kaweth
comma
r_int
id|mem_flags
)paren
(brace
r_int
id|result
suffix:semicolon
id|memset
c_func
(paren
id|kaweth-&gt;rx_urb
comma
l_int|0
comma
r_sizeof
(paren
op_star
id|kaweth-&gt;rx_urb
)paren
)paren
suffix:semicolon
id|FILL_BULK_URB
c_func
(paren
id|kaweth-&gt;rx_urb
comma
id|kaweth-&gt;dev
comma
id|usb_rcvbulkpipe
c_func
(paren
id|kaweth-&gt;dev
comma
l_int|1
)paren
comma
id|kaweth-&gt;rx_buf
comma
id|KAWETH_BUF_SIZE
comma
id|kaweth_usb_receive
comma
id|kaweth
)paren
suffix:semicolon
r_if
c_cond
(paren
(paren
id|result
op_assign
id|usb_submit_urb
c_func
(paren
id|kaweth-&gt;rx_urb
comma
id|mem_flags
)paren
)paren
)paren
(brace
id|kaweth_err
c_func
(paren
l_string|&quot;resubmitting rx_urb %d failed&quot;
comma
id|result
)paren
suffix:semicolon
)brace
)brace
r_static
r_void
id|kaweth_async_set_rx_mode
c_func
(paren
r_struct
id|kaweth_device
op_star
id|kaweth
)paren
suffix:semicolon
multiline_comment|/****************************************************************&n; *     kaweth_usb_receive&n; ****************************************************************/
DECL|function|kaweth_usb_receive
r_static
r_void
id|kaweth_usb_receive
c_func
(paren
r_struct
id|urb
op_star
id|urb
)paren
(brace
r_struct
id|kaweth_device
op_star
id|kaweth
op_assign
id|urb-&gt;context
suffix:semicolon
r_struct
id|net_device
op_star
id|net
op_assign
id|kaweth-&gt;net
suffix:semicolon
r_int
id|count
op_assign
id|urb-&gt;actual_length
suffix:semicolon
r_int
id|count2
op_assign
id|urb-&gt;transfer_buffer_length
suffix:semicolon
id|__u16
id|pkt_len
op_assign
id|le16_to_cpup
c_func
(paren
(paren
id|u16
op_star
)paren
id|kaweth-&gt;rx_buf
)paren
suffix:semicolon
r_struct
id|sk_buff
op_star
id|skb
suffix:semicolon
r_if
c_cond
(paren
id|kaweth-&gt;status
op_amp
id|KAWETH_STATUS_CLOSING
)paren
(brace
r_return
suffix:semicolon
)brace
r_if
c_cond
(paren
id|unlikely
c_func
(paren
id|urb-&gt;status
op_eq
op_minus
id|ECONNRESET
op_logical_or
id|urb-&gt;status
op_eq
op_minus
id|ECONNABORTED
)paren
)paren
multiline_comment|/* we are killed - set a flag and wake the disconnect handler */
(brace
id|kaweth-&gt;end
op_assign
l_int|1
suffix:semicolon
id|wake_up
c_func
(paren
op_amp
id|kaweth-&gt;term_wait
)paren
suffix:semicolon
r_return
suffix:semicolon
)brace
r_if
c_cond
(paren
id|urb-&gt;status
op_logical_and
id|urb-&gt;status
op_ne
op_minus
id|EREMOTEIO
op_logical_and
id|count
op_ne
l_int|1
)paren
(brace
id|kaweth_err
c_func
(paren
l_string|&quot;%s RX status: %d count: %d packet_len: %d&quot;
comma
id|net-&gt;name
comma
id|urb-&gt;status
comma
id|count
comma
(paren
r_int
)paren
id|pkt_len
)paren
suffix:semicolon
id|kaweth_resubmit_rx_urb
c_func
(paren
id|kaweth
comma
id|GFP_ATOMIC
)paren
suffix:semicolon
r_return
suffix:semicolon
)brace
r_if
c_cond
(paren
id|kaweth-&gt;net
op_logical_and
(paren
id|count
OG
l_int|2
)paren
)paren
(brace
r_if
c_cond
(paren
id|pkt_len
OG
(paren
id|count
op_minus
l_int|2
)paren
)paren
(brace
id|kaweth_err
c_func
(paren
l_string|&quot;Packet length too long for USB frame (pkt_len: %x, count: %x)&quot;
comma
id|pkt_len
comma
id|count
)paren
suffix:semicolon
id|kaweth_err
c_func
(paren
l_string|&quot;Packet len &amp; 2047: %x&quot;
comma
id|pkt_len
op_amp
l_int|2047
)paren
suffix:semicolon
id|kaweth_err
c_func
(paren
l_string|&quot;Count 2: %x&quot;
comma
id|count2
)paren
suffix:semicolon
id|kaweth_resubmit_rx_urb
c_func
(paren
id|kaweth
comma
id|GFP_ATOMIC
)paren
suffix:semicolon
r_return
suffix:semicolon
)brace
r_if
c_cond
(paren
op_logical_neg
(paren
id|skb
op_assign
id|dev_alloc_skb
c_func
(paren
id|pkt_len
op_plus
l_int|2
)paren
)paren
)paren
(brace
id|kaweth_resubmit_rx_urb
c_func
(paren
id|kaweth
comma
id|GFP_ATOMIC
)paren
suffix:semicolon
r_return
suffix:semicolon
)brace
id|skb-&gt;dev
op_assign
id|net
suffix:semicolon
id|eth_copy_and_sum
c_func
(paren
id|skb
comma
id|kaweth-&gt;rx_buf
op_plus
l_int|2
comma
id|pkt_len
comma
l_int|0
)paren
suffix:semicolon
id|skb_put
c_func
(paren
id|skb
comma
id|pkt_len
)paren
suffix:semicolon
id|skb-&gt;protocol
op_assign
id|eth_type_trans
c_func
(paren
id|skb
comma
id|net
)paren
suffix:semicolon
id|netif_rx
c_func
(paren
id|skb
)paren
suffix:semicolon
id|kaweth-&gt;stats.rx_packets
op_increment
suffix:semicolon
id|kaweth-&gt;stats.rx_bytes
op_add_assign
id|pkt_len
suffix:semicolon
)brace
id|kaweth_resubmit_rx_urb
c_func
(paren
id|kaweth
comma
id|GFP_ATOMIC
)paren
suffix:semicolon
)brace
multiline_comment|/****************************************************************&n; *     kaweth_open&n; ****************************************************************/
DECL|function|kaweth_open
r_static
r_int
id|kaweth_open
c_func
(paren
r_struct
id|net_device
op_star
id|net
)paren
(brace
r_struct
id|kaweth_device
op_star
id|kaweth
op_assign
(paren
r_struct
id|kaweth_device
op_star
)paren
id|net-&gt;priv
suffix:semicolon
id|kaweth_dbg
c_func
(paren
l_string|&quot;Dev usage: %d&quot;
comma
id|kaweth-&gt;dev-&gt;refcnt.counter
)paren
suffix:semicolon
id|kaweth_dbg
c_func
(paren
l_string|&quot;Opening network device.&quot;
)paren
suffix:semicolon
id|MOD_INC_USE_COUNT
suffix:semicolon
id|kaweth_resubmit_rx_urb
c_func
(paren
id|kaweth
comma
id|GFP_KERNEL
)paren
suffix:semicolon
id|netif_start_queue
c_func
(paren
id|net
)paren
suffix:semicolon
id|kaweth_async_set_rx_mode
c_func
(paren
id|kaweth
)paren
suffix:semicolon
r_return
l_int|0
suffix:semicolon
)brace
multiline_comment|/****************************************************************&n; *     kaweth_close&n; ****************************************************************/
DECL|function|kaweth_close
r_static
r_int
id|kaweth_close
c_func
(paren
r_struct
id|net_device
op_star
id|net
)paren
(brace
r_struct
id|kaweth_device
op_star
id|kaweth
op_assign
id|net-&gt;priv
suffix:semicolon
id|netif_stop_queue
c_func
(paren
id|net
)paren
suffix:semicolon
id|kaweth-&gt;status
op_or_assign
id|KAWETH_STATUS_CLOSING
suffix:semicolon
id|usb_unlink_urb
c_func
(paren
id|kaweth-&gt;rx_urb
)paren
suffix:semicolon
id|kaweth-&gt;status
op_and_assign
op_complement
id|KAWETH_STATUS_CLOSING
suffix:semicolon
id|MOD_DEC_USE_COUNT
suffix:semicolon
id|printk
c_func
(paren
l_string|&quot;Dev usage: %d&quot;
comma
id|kaweth-&gt;dev-&gt;refcnt.counter
)paren
suffix:semicolon
r_return
l_int|0
suffix:semicolon
)brace
multiline_comment|/****************************************************************&n; *     kaweth_ioctl&n; ****************************************************************/
DECL|function|kaweth_ioctl
r_static
r_int
id|kaweth_ioctl
c_func
(paren
r_struct
id|net_device
op_star
id|net
comma
r_struct
id|ifreq
op_star
id|rq
comma
r_int
id|cmd
)paren
(brace
r_return
op_minus
id|EOPNOTSUPP
suffix:semicolon
)brace
multiline_comment|/****************************************************************&n; *     kaweth_usb_transmit_complete&n; ****************************************************************/
DECL|function|kaweth_usb_transmit_complete
r_static
r_void
id|kaweth_usb_transmit_complete
c_func
(paren
r_struct
id|urb
op_star
id|urb
)paren
(brace
r_struct
id|kaweth_device
op_star
id|kaweth
op_assign
id|urb-&gt;context
suffix:semicolon
r_if
c_cond
(paren
id|unlikely
c_func
(paren
id|urb-&gt;status
op_ne
l_int|0
)paren
)paren
id|kaweth_dbg
c_func
(paren
l_string|&quot;%s: TX status %d.&quot;
comma
id|kaweth-&gt;net-&gt;name
comma
id|urb-&gt;status
)paren
suffix:semicolon
id|netif_wake_queue
c_func
(paren
id|kaweth-&gt;net
)paren
suffix:semicolon
)brace
multiline_comment|/****************************************************************&n; *     kaweth_start_xmit&n; ****************************************************************/
DECL|function|kaweth_start_xmit
r_static
r_int
id|kaweth_start_xmit
c_func
(paren
r_struct
id|sk_buff
op_star
id|skb
comma
r_struct
id|net_device
op_star
id|net
)paren
(brace
r_struct
id|kaweth_device
op_star
id|kaweth
op_assign
id|net-&gt;priv
suffix:semicolon
r_int
id|count
op_assign
id|skb-&gt;len
suffix:semicolon
r_int
id|res
suffix:semicolon
id|spin_lock
c_func
(paren
op_amp
id|kaweth-&gt;device_lock
)paren
suffix:semicolon
r_if
c_cond
(paren
id|kaweth-&gt;removed
)paren
(brace
multiline_comment|/* our device is undergoing disconnection - we bail out */
id|spin_unlock
c_func
(paren
op_amp
id|kaweth-&gt;device_lock
)paren
suffix:semicolon
id|dev_kfree_skb
c_func
(paren
id|skb
)paren
suffix:semicolon
r_return
l_int|0
suffix:semicolon
)brace
id|kaweth_async_set_rx_mode
c_func
(paren
id|kaweth
)paren
suffix:semicolon
id|netif_stop_queue
c_func
(paren
id|net
)paren
suffix:semicolon
op_star
(paren
(paren
id|__u16
op_star
)paren
id|kaweth-&gt;tx_buf
)paren
op_assign
id|cpu_to_le16
c_func
(paren
id|skb-&gt;len
)paren
suffix:semicolon
id|memcpy
c_func
(paren
id|kaweth-&gt;tx_buf
op_plus
l_int|2
comma
id|skb-&gt;data
comma
id|skb-&gt;len
)paren
suffix:semicolon
id|memset
c_func
(paren
id|kaweth-&gt;tx_urb
comma
l_int|0
comma
r_sizeof
(paren
op_star
id|kaweth-&gt;tx_urb
)paren
)paren
suffix:semicolon
id|FILL_BULK_URB
c_func
(paren
id|kaweth-&gt;tx_urb
comma
id|kaweth-&gt;dev
comma
id|usb_sndbulkpipe
c_func
(paren
id|kaweth-&gt;dev
comma
l_int|2
)paren
comma
id|kaweth-&gt;tx_buf
comma
id|count
op_plus
l_int|2
comma
id|kaweth_usb_transmit_complete
comma
id|kaweth
)paren
suffix:semicolon
id|kaweth-&gt;end
op_assign
l_int|0
suffix:semicolon
id|kaweth-&gt;tx_urb-&gt;transfer_flags
op_or_assign
id|USB_ASYNC_UNLINK
suffix:semicolon
r_if
c_cond
(paren
(paren
id|res
op_assign
id|usb_submit_urb
c_func
(paren
id|kaweth-&gt;tx_urb
comma
id|GFP_ATOMIC
)paren
)paren
)paren
(brace
id|kaweth_warn
c_func
(paren
l_string|&quot;kaweth failed tx_urb %d&quot;
comma
id|res
)paren
suffix:semicolon
id|kaweth-&gt;stats.tx_errors
op_increment
suffix:semicolon
id|netif_start_queue
c_func
(paren
id|net
)paren
suffix:semicolon
)brace
r_else
(brace
id|kaweth-&gt;stats.tx_packets
op_increment
suffix:semicolon
id|kaweth-&gt;stats.tx_bytes
op_add_assign
id|skb-&gt;len
suffix:semicolon
id|net-&gt;trans_start
op_assign
id|jiffies
suffix:semicolon
)brace
id|dev_kfree_skb
c_func
(paren
id|skb
)paren
suffix:semicolon
id|spin_unlock
c_func
(paren
op_amp
id|kaweth-&gt;device_lock
)paren
suffix:semicolon
r_return
l_int|0
suffix:semicolon
)brace
multiline_comment|/****************************************************************&n; *     kaweth_set_rx_mode&n; ****************************************************************/
DECL|function|kaweth_set_rx_mode
r_static
r_void
id|kaweth_set_rx_mode
c_func
(paren
r_struct
id|net_device
op_star
id|net
)paren
(brace
r_struct
id|kaweth_device
op_star
id|kaweth
op_assign
id|net-&gt;priv
suffix:semicolon
id|__u16
id|packet_filter_bitmap
op_assign
id|KAWETH_PACKET_FILTER_DIRECTED
op_or
id|KAWETH_PACKET_FILTER_BROADCAST
op_or
id|KAWETH_PACKET_FILTER_MULTICAST
suffix:semicolon
id|kaweth_dbg
c_func
(paren
l_string|&quot;Setting Rx mode to %d&quot;
comma
id|packet_filter_bitmap
)paren
suffix:semicolon
id|netif_stop_queue
c_func
(paren
id|net
)paren
suffix:semicolon
r_if
c_cond
(paren
id|net-&gt;flags
op_amp
id|IFF_PROMISC
)paren
(brace
id|packet_filter_bitmap
op_or_assign
id|KAWETH_PACKET_FILTER_PROMISCUOUS
suffix:semicolon
)brace
r_else
r_if
c_cond
(paren
(paren
id|net-&gt;mc_count
)paren
op_logical_or
(paren
id|net-&gt;flags
op_amp
id|IFF_ALLMULTI
)paren
)paren
(brace
id|packet_filter_bitmap
op_or_assign
id|KAWETH_PACKET_FILTER_ALL_MULTICAST
suffix:semicolon
)brace
id|kaweth-&gt;packet_filter_bitmap
op_assign
id|packet_filter_bitmap
suffix:semicolon
id|netif_wake_queue
c_func
(paren
id|net
)paren
suffix:semicolon
)brace
multiline_comment|/****************************************************************&n; *     kaweth_async_set_rx_mode&n; ****************************************************************/
DECL|function|kaweth_async_set_rx_mode
r_static
r_void
id|kaweth_async_set_rx_mode
c_func
(paren
r_struct
id|kaweth_device
op_star
id|kaweth
)paren
(brace
id|__u16
id|packet_filter_bitmap
op_assign
id|kaweth-&gt;packet_filter_bitmap
suffix:semicolon
id|kaweth-&gt;packet_filter_bitmap
op_assign
l_int|0
suffix:semicolon
r_if
c_cond
(paren
id|packet_filter_bitmap
op_eq
l_int|0
)paren
(brace
r_return
suffix:semicolon
)brace
(brace
r_int
id|result
suffix:semicolon
id|result
op_assign
id|kaweth_control
c_func
(paren
id|kaweth
comma
id|usb_sndctrlpipe
c_func
(paren
id|kaweth-&gt;dev
comma
l_int|0
)paren
comma
id|KAWETH_COMMAND_SET_PACKET_FILTER
comma
id|USB_TYPE_VENDOR
op_or
id|USB_DIR_OUT
op_or
id|USB_RECIP_DEVICE
comma
id|packet_filter_bitmap
comma
l_int|0
comma
(paren
r_void
op_star
)paren
op_amp
id|kaweth-&gt;firmware_buf
comma
l_int|0
comma
id|KAWETH_CONTROL_TIMEOUT
)paren
suffix:semicolon
r_if
c_cond
(paren
id|result
OL
l_int|0
)paren
(brace
id|kaweth_err
c_func
(paren
l_string|&quot;Failed to set Rx mode: %d&quot;
comma
id|result
)paren
suffix:semicolon
)brace
r_else
(brace
id|kaweth_dbg
c_func
(paren
l_string|&quot;Set Rx mode to %d&quot;
comma
id|packet_filter_bitmap
)paren
suffix:semicolon
)brace
)brace
)brace
multiline_comment|/****************************************************************&n; *     kaweth_netdev_stats&n; ****************************************************************/
DECL|function|kaweth_netdev_stats
r_static
r_struct
id|net_device_stats
op_star
id|kaweth_netdev_stats
c_func
(paren
r_struct
id|net_device
op_star
id|dev
)paren
(brace
r_return
op_amp
(paren
(paren
r_struct
id|kaweth_device
op_star
)paren
id|dev-&gt;priv
)paren
op_member_access_from_pointer
id|stats
suffix:semicolon
)brace
multiline_comment|/****************************************************************&n; *     kaweth_tx_timeout&n; ****************************************************************/
DECL|function|kaweth_tx_timeout
r_static
r_void
id|kaweth_tx_timeout
c_func
(paren
r_struct
id|net_device
op_star
id|net
)paren
(brace
r_struct
id|kaweth_device
op_star
id|kaweth
op_assign
id|net-&gt;priv
suffix:semicolon
id|kaweth_warn
c_func
(paren
l_string|&quot;%s: Tx timed out. Resetting.&quot;
comma
id|net-&gt;name
)paren
suffix:semicolon
id|kaweth-&gt;stats.tx_errors
op_increment
suffix:semicolon
id|net-&gt;trans_start
op_assign
id|jiffies
suffix:semicolon
id|usb_unlink_urb
c_func
(paren
id|kaweth-&gt;tx_urb
)paren
suffix:semicolon
)brace
multiline_comment|/****************************************************************&n; *     kaweth_probe&n; ****************************************************************/
DECL|function|kaweth_probe
r_static
r_void
op_star
id|kaweth_probe
c_func
(paren
r_struct
id|usb_device
op_star
id|dev
comma
multiline_comment|/* the device */
r_int
id|ifnum
comma
multiline_comment|/* what interface */
r_const
r_struct
id|usb_device_id
op_star
id|id
multiline_comment|/* from id_table */
)paren
(brace
r_struct
id|kaweth_device
op_star
id|kaweth
suffix:semicolon
r_const
id|eth_addr_t
id|bcast_addr
op_assign
(brace
l_int|0xFF
comma
l_int|0xFF
comma
l_int|0xFF
comma
l_int|0xFF
comma
l_int|0xFF
comma
l_int|0xFF
)brace
suffix:semicolon
r_int
id|result
op_assign
l_int|0
suffix:semicolon
id|kaweth_dbg
c_func
(paren
l_string|&quot;Kawasaki Device Probe (Device number:%d): 0x%4.4x:0x%4.4x:0x%4.4x&quot;
comma
id|dev-&gt;devnum
comma
(paren
r_int
)paren
id|dev-&gt;descriptor.idVendor
comma
(paren
r_int
)paren
id|dev-&gt;descriptor.idProduct
comma
(paren
r_int
)paren
id|dev-&gt;descriptor.bcdDevice
)paren
suffix:semicolon
id|kaweth_dbg
c_func
(paren
l_string|&quot;Device at %p&quot;
comma
id|dev
)paren
suffix:semicolon
id|kaweth_dbg
c_func
(paren
l_string|&quot;Descriptor length: %x type: %x&quot;
comma
(paren
r_int
)paren
id|dev-&gt;descriptor.bLength
comma
(paren
r_int
)paren
id|dev-&gt;descriptor.bDescriptorType
)paren
suffix:semicolon
r_if
c_cond
(paren
op_logical_neg
(paren
id|kaweth
op_assign
id|kmalloc
c_func
(paren
r_sizeof
(paren
r_struct
id|kaweth_device
)paren
comma
id|GFP_KERNEL
)paren
)paren
)paren
(brace
id|kaweth_dbg
c_func
(paren
l_string|&quot;out of memory allocating device structure&bslash;n&quot;
)paren
suffix:semicolon
r_return
l_int|NULL
suffix:semicolon
)brace
id|memset
c_func
(paren
id|kaweth
comma
l_int|0
comma
r_sizeof
(paren
r_struct
id|kaweth_device
)paren
)paren
suffix:semicolon
id|kaweth-&gt;dev
op_assign
id|dev
suffix:semicolon
id|spin_lock_init
c_func
(paren
op_amp
id|kaweth-&gt;device_lock
)paren
suffix:semicolon
id|init_waitqueue_head
c_func
(paren
op_amp
id|kaweth-&gt;term_wait
)paren
suffix:semicolon
id|kaweth_dbg
c_func
(paren
l_string|&quot;Resetting.&quot;
)paren
suffix:semicolon
id|kaweth_reset
c_func
(paren
id|kaweth
)paren
suffix:semicolon
multiline_comment|/*&n;&t; * If high byte of bcdDevice is nonzero, firmware is already&n;&t; * downloaded. Don&squot;t try to do it again, or we&squot;ll hang the device.&n;&t; */
r_if
c_cond
(paren
id|dev-&gt;descriptor.bcdDevice
op_rshift
l_int|8
)paren
(brace
id|kaweth_info
c_func
(paren
l_string|&quot;Firmware present in device.&quot;
)paren
suffix:semicolon
)brace
r_else
(brace
multiline_comment|/* Download the firmware */
id|kaweth_info
c_func
(paren
l_string|&quot;Downloading firmware...&quot;
)paren
suffix:semicolon
r_if
c_cond
(paren
(paren
id|result
op_assign
id|kaweth_download_firmware
c_func
(paren
id|kaweth
comma
id|kaweth_new_code
comma
id|len_kaweth_new_code
comma
l_int|100
comma
l_int|2
)paren
)paren
OL
l_int|0
)paren
(brace
id|kaweth_err
c_func
(paren
l_string|&quot;Error downloading firmware (%d)&quot;
comma
id|result
)paren
suffix:semicolon
id|kfree
c_func
(paren
id|kaweth
)paren
suffix:semicolon
r_return
l_int|NULL
suffix:semicolon
)brace
r_if
c_cond
(paren
(paren
id|result
op_assign
id|kaweth_download_firmware
c_func
(paren
id|kaweth
comma
id|kaweth_new_code_fix
comma
id|len_kaweth_new_code_fix
comma
l_int|100
comma
l_int|3
)paren
)paren
OL
l_int|0
)paren
(brace
id|kaweth_err
c_func
(paren
l_string|&quot;Error downloading firmware fix (%d)&quot;
comma
id|result
)paren
suffix:semicolon
id|kfree
c_func
(paren
id|kaweth
)paren
suffix:semicolon
r_return
l_int|NULL
suffix:semicolon
)brace
r_if
c_cond
(paren
(paren
id|result
op_assign
id|kaweth_download_firmware
c_func
(paren
id|kaweth
comma
id|kaweth_trigger_code
comma
id|len_kaweth_trigger_code
comma
l_int|126
comma
l_int|2
)paren
)paren
OL
l_int|0
)paren
(brace
id|kaweth_err
c_func
(paren
l_string|&quot;Error downloading trigger code (%d)&quot;
comma
id|result
)paren
suffix:semicolon
id|kfree
c_func
(paren
id|kaweth
)paren
suffix:semicolon
r_return
l_int|NULL
suffix:semicolon
)brace
r_if
c_cond
(paren
(paren
id|result
op_assign
id|kaweth_download_firmware
c_func
(paren
id|kaweth
comma
id|kaweth_trigger_code_fix
comma
id|len_kaweth_trigger_code_fix
comma
l_int|126
comma
l_int|3
)paren
)paren
OL
l_int|0
)paren
(brace
id|kaweth_err
c_func
(paren
l_string|&quot;Error downloading trigger code fix (%d)&quot;
comma
id|result
)paren
suffix:semicolon
id|kfree
c_func
(paren
id|kaweth
)paren
suffix:semicolon
r_return
l_int|NULL
suffix:semicolon
)brace
r_if
c_cond
(paren
(paren
id|result
op_assign
id|kaweth_trigger_firmware
c_func
(paren
id|kaweth
comma
l_int|126
)paren
)paren
OL
l_int|0
)paren
(brace
id|kaweth_err
c_func
(paren
l_string|&quot;Error triggering firmware (%d)&quot;
comma
id|result
)paren
suffix:semicolon
id|kfree
c_func
(paren
id|kaweth
)paren
suffix:semicolon
r_return
l_int|NULL
suffix:semicolon
)brace
multiline_comment|/* Device will now disappear for a moment...  */
id|kaweth_info
c_func
(paren
l_string|&quot;Firmware loaded.  I&squot;ll be back...&quot;
)paren
suffix:semicolon
id|kfree
c_func
(paren
id|kaweth
)paren
suffix:semicolon
r_return
l_int|NULL
suffix:semicolon
)brace
id|result
op_assign
id|kaweth_read_configuration
c_func
(paren
id|kaweth
)paren
suffix:semicolon
r_if
c_cond
(paren
id|result
OL
l_int|0
)paren
(brace
id|kaweth_err
c_func
(paren
l_string|&quot;Error reading configuration (%d), no net device created&quot;
comma
id|result
)paren
suffix:semicolon
id|kfree
c_func
(paren
id|kaweth
)paren
suffix:semicolon
r_return
l_int|NULL
suffix:semicolon
)brace
id|kaweth_info
c_func
(paren
l_string|&quot;Statistics collection: %x&quot;
comma
id|kaweth-&gt;configuration.statistics_mask
)paren
suffix:semicolon
id|kaweth_info
c_func
(paren
l_string|&quot;Multicast filter limit: %x&quot;
comma
id|kaweth-&gt;configuration.max_multicast_filters
op_amp
(paren
(paren
l_int|1
op_lshift
l_int|15
)paren
op_minus
l_int|1
)paren
)paren
suffix:semicolon
id|kaweth_info
c_func
(paren
l_string|&quot;MTU: %d&quot;
comma
id|le16_to_cpu
c_func
(paren
id|kaweth-&gt;configuration.segment_size
)paren
)paren
suffix:semicolon
id|kaweth_info
c_func
(paren
l_string|&quot;Read MAC address %2.2x:%2.2x:%2.2x:%2.2x:%2.2x:%2.2x&quot;
comma
(paren
r_int
)paren
id|kaweth-&gt;configuration.hw_addr
(braket
l_int|0
)braket
comma
(paren
r_int
)paren
id|kaweth-&gt;configuration.hw_addr
(braket
l_int|1
)braket
comma
(paren
r_int
)paren
id|kaweth-&gt;configuration.hw_addr
(braket
l_int|2
)braket
comma
(paren
r_int
)paren
id|kaweth-&gt;configuration.hw_addr
(braket
l_int|3
)braket
comma
(paren
r_int
)paren
id|kaweth-&gt;configuration.hw_addr
(braket
l_int|4
)braket
comma
(paren
r_int
)paren
id|kaweth-&gt;configuration.hw_addr
(braket
l_int|5
)braket
)paren
suffix:semicolon
r_if
c_cond
(paren
op_logical_neg
id|memcmp
c_func
(paren
op_amp
id|kaweth-&gt;configuration.hw_addr
comma
op_amp
id|bcast_addr
comma
r_sizeof
(paren
id|bcast_addr
)paren
)paren
)paren
(brace
id|kaweth_err
c_func
(paren
l_string|&quot;Firmware not functioning properly, no net device created&quot;
)paren
suffix:semicolon
id|kfree
c_func
(paren
id|kaweth
)paren
suffix:semicolon
r_return
l_int|NULL
suffix:semicolon
)brace
r_if
c_cond
(paren
id|kaweth_set_urb_size
c_func
(paren
id|kaweth
comma
id|KAWETH_BUF_SIZE
)paren
OL
l_int|0
)paren
(brace
id|kaweth_dbg
c_func
(paren
l_string|&quot;Error setting URB size&quot;
)paren
suffix:semicolon
r_return
id|kaweth
suffix:semicolon
)brace
r_if
c_cond
(paren
id|kaweth_set_sofs_wait
c_func
(paren
id|kaweth
comma
id|KAWETH_SOFS_TO_WAIT
)paren
OL
l_int|0
)paren
(brace
id|kaweth_err
c_func
(paren
l_string|&quot;Error setting SOFS wait&quot;
)paren
suffix:semicolon
r_return
id|kaweth
suffix:semicolon
)brace
id|result
op_assign
id|kaweth_set_receive_filter
c_func
(paren
id|kaweth
comma
id|KAWETH_PACKET_FILTER_DIRECTED
op_or
id|KAWETH_PACKET_FILTER_BROADCAST
op_or
id|KAWETH_PACKET_FILTER_MULTICAST
)paren
suffix:semicolon
r_if
c_cond
(paren
id|result
OL
l_int|0
)paren
(brace
id|kaweth_err
c_func
(paren
l_string|&quot;Error setting receive filter&quot;
)paren
suffix:semicolon
r_return
id|kaweth
suffix:semicolon
)brace
id|kaweth_dbg
c_func
(paren
l_string|&quot;Initializing net device.&quot;
)paren
suffix:semicolon
id|kaweth-&gt;tx_urb
op_assign
id|usb_alloc_urb
c_func
(paren
l_int|0
comma
id|GFP_KERNEL
)paren
suffix:semicolon
id|kaweth-&gt;rx_urb
op_assign
id|usb_alloc_urb
c_func
(paren
l_int|0
comma
id|GFP_KERNEL
)paren
suffix:semicolon
id|kaweth-&gt;net
op_assign
id|init_etherdev
c_func
(paren
l_int|0
comma
l_int|0
)paren
suffix:semicolon
r_if
c_cond
(paren
op_logical_neg
id|kaweth-&gt;net
)paren
(brace
id|kaweth_err
c_func
(paren
l_string|&quot;Error calling init_etherdev.&quot;
)paren
suffix:semicolon
r_return
id|kaweth
suffix:semicolon
)brace
id|memcpy
c_func
(paren
id|kaweth-&gt;net-&gt;broadcast
comma
op_amp
id|bcast_addr
comma
r_sizeof
(paren
id|bcast_addr
)paren
)paren
suffix:semicolon
id|memcpy
c_func
(paren
id|kaweth-&gt;net-&gt;dev_addr
comma
op_amp
id|kaweth-&gt;configuration.hw_addr
comma
r_sizeof
(paren
id|kaweth-&gt;configuration.hw_addr
)paren
)paren
suffix:semicolon
id|kaweth-&gt;net-&gt;priv
op_assign
id|kaweth
suffix:semicolon
id|kaweth-&gt;net-&gt;open
op_assign
id|kaweth_open
suffix:semicolon
id|kaweth-&gt;net-&gt;stop
op_assign
id|kaweth_close
suffix:semicolon
id|kaweth-&gt;net-&gt;watchdog_timeo
op_assign
id|KAWETH_TX_TIMEOUT
suffix:semicolon
id|kaweth-&gt;net-&gt;tx_timeout
op_assign
id|kaweth_tx_timeout
suffix:semicolon
id|kaweth-&gt;net-&gt;do_ioctl
op_assign
id|kaweth_ioctl
suffix:semicolon
id|kaweth-&gt;net-&gt;hard_start_xmit
op_assign
id|kaweth_start_xmit
suffix:semicolon
id|kaweth-&gt;net-&gt;set_multicast_list
op_assign
id|kaweth_set_rx_mode
suffix:semicolon
id|kaweth-&gt;net-&gt;get_stats
op_assign
id|kaweth_netdev_stats
suffix:semicolon
id|kaweth-&gt;net-&gt;mtu
op_assign
id|le16_to_cpu
c_func
(paren
id|kaweth-&gt;configuration.segment_size
)paren
suffix:semicolon
id|memset
c_func
(paren
op_amp
id|kaweth-&gt;stats
comma
l_int|0
comma
r_sizeof
(paren
id|kaweth-&gt;stats
)paren
)paren
suffix:semicolon
id|kaweth_info
c_func
(paren
l_string|&quot;kaweth interface created at %s&quot;
comma
id|kaweth-&gt;net-&gt;name
)paren
suffix:semicolon
id|kaweth_dbg
c_func
(paren
l_string|&quot;Kaweth probe returning.&quot;
)paren
suffix:semicolon
r_return
id|kaweth
suffix:semicolon
)brace
multiline_comment|/****************************************************************&n; *     kaweth_disconnect&n; ****************************************************************/
DECL|function|kaweth_disconnect
r_static
r_void
id|kaweth_disconnect
c_func
(paren
r_struct
id|usb_device
op_star
id|dev
comma
r_void
op_star
id|ptr
)paren
(brace
r_struct
id|kaweth_device
op_star
id|kaweth
op_assign
id|ptr
suffix:semicolon
id|kaweth_info
c_func
(paren
l_string|&quot;Unregistering&quot;
)paren
suffix:semicolon
r_if
c_cond
(paren
op_logical_neg
id|kaweth
)paren
(brace
id|kaweth_warn
c_func
(paren
l_string|&quot;unregistering non-existant device&quot;
)paren
suffix:semicolon
r_return
suffix:semicolon
)brace
id|kaweth-&gt;removed
op_assign
l_int|1
suffix:semicolon
id|usb_unlink_urb
c_func
(paren
id|kaweth-&gt;rx_urb
)paren
suffix:semicolon
multiline_comment|/* we need to wait for the urb to be cancelled, if it is active */
id|spin_lock
c_func
(paren
op_amp
id|kaweth-&gt;device_lock
)paren
suffix:semicolon
r_if
c_cond
(paren
id|usb_unlink_urb
c_func
(paren
id|kaweth-&gt;tx_urb
)paren
op_eq
op_minus
id|EINPROGRESS
)paren
(brace
id|spin_unlock
c_func
(paren
op_amp
id|kaweth-&gt;device_lock
)paren
suffix:semicolon
id|wait_event
c_func
(paren
id|kaweth-&gt;term_wait
comma
id|kaweth-&gt;end
)paren
suffix:semicolon
)brace
r_else
(brace
id|spin_unlock
c_func
(paren
op_amp
id|kaweth-&gt;device_lock
)paren
suffix:semicolon
)brace
r_if
c_cond
(paren
id|kaweth-&gt;net
)paren
(brace
r_if
c_cond
(paren
id|kaweth-&gt;net-&gt;flags
op_amp
id|IFF_UP
)paren
(brace
id|kaweth_dbg
c_func
(paren
l_string|&quot;Closing net device&quot;
)paren
suffix:semicolon
id|dev_close
c_func
(paren
id|kaweth-&gt;net
)paren
suffix:semicolon
)brace
id|kaweth_dbg
c_func
(paren
l_string|&quot;Unregistering net device&quot;
)paren
suffix:semicolon
id|unregister_netdev
c_func
(paren
id|kaweth-&gt;net
)paren
suffix:semicolon
)brace
id|usb_free_urb
c_func
(paren
id|kaweth-&gt;rx_urb
)paren
suffix:semicolon
id|usb_free_urb
c_func
(paren
id|kaweth-&gt;tx_urb
)paren
suffix:semicolon
id|kfree
c_func
(paren
id|kaweth
)paren
suffix:semicolon
)brace
singleline_comment|// FIXME this completion stuff is a modified clone of
singleline_comment|// an OLD version of some stuff in usb.c ...
DECL|struct|usb_api_data
r_struct
id|usb_api_data
(brace
DECL|member|wqh
id|wait_queue_head_t
id|wqh
suffix:semicolon
DECL|member|done
r_int
id|done
suffix:semicolon
)brace
suffix:semicolon
multiline_comment|/*-------------------------------------------------------------------*&n; * completion handler for compatibility wrappers (sync control/bulk) *&n; *-------------------------------------------------------------------*/
DECL|function|usb_api_blocking_completion
r_static
r_void
id|usb_api_blocking_completion
c_func
(paren
r_struct
id|urb
op_star
id|urb
)paren
(brace
r_struct
id|usb_api_data
op_star
id|awd
op_assign
(paren
r_struct
id|usb_api_data
op_star
)paren
id|urb-&gt;context
suffix:semicolon
id|awd-&gt;done
op_assign
l_int|1
suffix:semicolon
id|wake_up
c_func
(paren
op_amp
id|awd-&gt;wqh
)paren
suffix:semicolon
)brace
multiline_comment|/*-------------------------------------------------------------------*&n; *                         COMPATIBILITY STUFF                       *&n; *-------------------------------------------------------------------*/
singleline_comment|// Starts urb and waits for completion or timeout
DECL|function|usb_start_wait_urb
r_static
r_int
id|usb_start_wait_urb
c_func
(paren
r_struct
id|urb
op_star
id|urb
comma
r_int
id|timeout
comma
r_int
op_star
id|actual_length
)paren
(brace
id|DECLARE_WAITQUEUE
c_func
(paren
id|wait
comma
id|current
)paren
suffix:semicolon
r_struct
id|usb_api_data
id|awd
suffix:semicolon
r_int
id|status
suffix:semicolon
id|init_waitqueue_head
c_func
(paren
op_amp
id|awd.wqh
)paren
suffix:semicolon
id|awd.done
op_assign
l_int|0
suffix:semicolon
id|set_current_state
c_func
(paren
id|TASK_INTERRUPTIBLE
)paren
suffix:semicolon
id|add_wait_queue
c_func
(paren
op_amp
id|awd.wqh
comma
op_amp
id|wait
)paren
suffix:semicolon
id|urb-&gt;context
op_assign
op_amp
id|awd
suffix:semicolon
id|status
op_assign
id|usb_submit_urb
c_func
(paren
id|urb
comma
id|GFP_ATOMIC
)paren
suffix:semicolon
r_if
c_cond
(paren
id|status
)paren
(brace
singleline_comment|// something went wrong
id|usb_free_urb
c_func
(paren
id|urb
)paren
suffix:semicolon
id|set_current_state
c_func
(paren
id|TASK_RUNNING
)paren
suffix:semicolon
id|remove_wait_queue
c_func
(paren
op_amp
id|awd.wqh
comma
op_amp
id|wait
)paren
suffix:semicolon
r_return
id|status
suffix:semicolon
)brace
r_while
c_loop
(paren
id|timeout
op_logical_and
op_logical_neg
id|awd.done
)paren
id|timeout
op_assign
id|schedule_timeout
c_func
(paren
id|timeout
)paren
suffix:semicolon
id|set_current_state
c_func
(paren
id|TASK_RUNNING
)paren
suffix:semicolon
id|remove_wait_queue
c_func
(paren
op_amp
id|awd.wqh
comma
op_amp
id|wait
)paren
suffix:semicolon
r_if
c_cond
(paren
op_logical_neg
id|timeout
)paren
(brace
singleline_comment|// timeout
id|kaweth_warn
c_func
(paren
l_string|&quot;usb_control/bulk_msg: timeout&quot;
)paren
suffix:semicolon
id|usb_unlink_urb
c_func
(paren
id|urb
)paren
suffix:semicolon
singleline_comment|// remove urb safely
id|status
op_assign
op_minus
id|ETIMEDOUT
suffix:semicolon
)brace
r_else
(brace
id|status
op_assign
id|urb-&gt;status
suffix:semicolon
)brace
r_if
c_cond
(paren
id|actual_length
)paren
(brace
op_star
id|actual_length
op_assign
id|urb-&gt;actual_length
suffix:semicolon
)brace
id|usb_free_urb
c_func
(paren
id|urb
)paren
suffix:semicolon
r_return
id|status
suffix:semicolon
)brace
multiline_comment|/*-------------------------------------------------------------------*/
singleline_comment|// returns status (negative) or length (positive)
DECL|function|kaweth_internal_control_msg
r_int
id|kaweth_internal_control_msg
c_func
(paren
r_struct
id|usb_device
op_star
id|usb_dev
comma
r_int
r_int
id|pipe
comma
r_struct
id|usb_ctrlrequest
op_star
id|cmd
comma
r_void
op_star
id|data
comma
r_int
id|len
comma
r_int
id|timeout
)paren
(brace
r_struct
id|urb
op_star
id|urb
suffix:semicolon
r_int
id|retv
suffix:semicolon
r_int
id|length
suffix:semicolon
id|urb
op_assign
id|usb_alloc_urb
c_func
(paren
l_int|0
comma
id|GFP_NOIO
)paren
suffix:semicolon
r_if
c_cond
(paren
op_logical_neg
id|urb
)paren
r_return
op_minus
id|ENOMEM
suffix:semicolon
id|FILL_CONTROL_URB
c_func
(paren
id|urb
comma
id|usb_dev
comma
id|pipe
comma
(paren
r_int
r_char
op_star
)paren
id|cmd
comma
id|data
comma
id|len
comma
(paren
id|usb_complete_t
)paren
id|usb_api_blocking_completion
comma
l_int|0
)paren
suffix:semicolon
id|retv
op_assign
id|usb_start_wait_urb
c_func
(paren
id|urb
comma
id|timeout
comma
op_amp
id|length
)paren
suffix:semicolon
r_if
c_cond
(paren
id|retv
OL
l_int|0
)paren
(brace
r_return
id|retv
suffix:semicolon
)brace
r_else
(brace
r_return
id|length
suffix:semicolon
)brace
)brace
multiline_comment|/****************************************************************&n; *     kaweth_init&n; ****************************************************************/
DECL|function|kaweth_init
r_int
id|__init
id|kaweth_init
c_func
(paren
r_void
)paren
(brace
id|kaweth_dbg
c_func
(paren
l_string|&quot;Driver loading&quot;
)paren
suffix:semicolon
r_return
id|usb_register
c_func
(paren
op_amp
id|kaweth_driver
)paren
suffix:semicolon
)brace
multiline_comment|/****************************************************************&n; *     kaweth_exit&n; ****************************************************************/
DECL|function|kaweth_exit
r_void
id|__exit
id|kaweth_exit
c_func
(paren
r_void
)paren
(brace
id|usb_deregister
c_func
(paren
op_amp
id|kaweth_driver
)paren
suffix:semicolon
)brace
DECL|variable|kaweth_init
id|module_init
c_func
(paren
id|kaweth_init
)paren
suffix:semicolon
DECL|variable|kaweth_exit
id|module_exit
c_func
(paren
id|kaweth_exit
)paren
suffix:semicolon
eof
