multiline_comment|/* &n; * Copyright (C) 2002 Jeff Dike (jdike@karaya.com)&n; * Licensed under the GPL&n; */
macro_line|#include &lt;signal.h&gt;
macro_line|#include &quot;sysdep/ptrace.h&quot;
macro_line|#include &quot;sysdep/sigcontext.h&quot;
r_extern
r_int
r_int
id|search_exception_table
c_func
(paren
r_int
r_int
id|addr
)paren
suffix:semicolon
DECL|function|arch_fixup
r_int
id|arch_fixup
c_func
(paren
r_int
r_int
id|address
comma
r_void
op_star
id|sc_ptr
)paren
(brace
r_struct
id|sigcontext
op_star
id|sc
op_assign
id|sc_ptr
suffix:semicolon
r_int
r_int
id|fixup
suffix:semicolon
id|fixup
op_assign
id|search_exception_tables
c_func
(paren
id|address
)paren
suffix:semicolon
r_if
c_cond
(paren
id|fixup
op_ne
l_int|0
)paren
(brace
id|sc-&gt;eip
op_assign
id|fixup
suffix:semicolon
r_return
l_int|1
suffix:semicolon
)brace
r_return
l_int|0
suffix:semicolon
)brace
multiline_comment|/*&n; * Overrides for Emacs so that we follow Linus&squot;s tabbing style.&n; * Emacs will notice this stuff at the end of the file and automatically&n; * adjust the settings for this buffer only.  This must remain at the end&n; * of the file.&n; * ---------------------------------------------------------------------------&n; * Local variables:&n; * c-file-style: &quot;linux&quot;&n; * End:&n; */
eof
