multiline_comment|/******************************************************************************&n; *&n; * Module Name: evregion - ACPI Address_space (Op_region) handler dispatch&n; *              $Revision: 128 $&n; *&n; *****************************************************************************/
multiline_comment|/*&n; *  Copyright (C) 2000 - 2002, R. Byron Moore&n; *&n; *  This program is free software; you can redistribute it and/or modify&n; *  it under the terms of the GNU General Public License as published by&n; *  the Free Software Foundation; either version 2 of the License, or&n; *  (at your option) any later version.&n; *&n; *  This program is distributed in the hope that it will be useful,&n; *  but WITHOUT ANY WARRANTY; without even the implied warranty of&n; *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the&n; *  GNU General Public License for more details.&n; *&n; *  You should have received a copy of the GNU General Public License&n; *  along with this program; if not, write to the Free Software&n; *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA&n; */
macro_line|#include &quot;acpi.h&quot;
macro_line|#include &quot;acevents.h&quot;
macro_line|#include &quot;acnamesp.h&quot;
macro_line|#include &quot;acinterp.h&quot;
macro_line|#include &quot;amlcode.h&quot;
DECL|macro|_COMPONENT
mdefine_line|#define _COMPONENT          ACPI_EVENTS
id|ACPI_MODULE_NAME
(paren
l_string|&quot;evregion&quot;
)paren
multiline_comment|/*******************************************************************************&n; *&n; * FUNCTION:    Acpi_ev_install_default_address_space_handlers&n; *&n; * PARAMETERS:&n; *&n; * RETURN:      Status&n; *&n; * DESCRIPTION: Installs the core subsystem address space handlers.&n; *&n; ******************************************************************************/
id|acpi_status
DECL|function|acpi_ev_install_default_address_space_handlers
id|acpi_ev_install_default_address_space_handlers
(paren
r_void
)paren
(brace
id|acpi_status
id|status
suffix:semicolon
id|ACPI_FUNCTION_TRACE
(paren
l_string|&quot;Ev_install_default_address_space_handlers&quot;
)paren
suffix:semicolon
multiline_comment|/*&n;&t; * All address spaces (PCI Config, EC, SMBus) are scope dependent&n;&t; * and registration must occur for a specific device.  In the case&n;&t; * system memory and IO address spaces there is currently no device&n;&t; * associated with the address space.  For these we use the root.&n;&t; * We install the default PCI config space handler at the root so&n;&t; * that this space is immediately available even though the we have&n;&t; * not enumerated all the PCI Root Buses yet.  This is to conform&n;&t; * to the ACPI specification which states that the PCI config&n;&t; * space must be always available -- even though we are nowhere&n;&t; * near ready to find the PCI root buses at this point.&n;&t; *&n;&t; * NOTE: We ignore AE_ALREADY_EXISTS because this means that a handler&n;&t; * has already been installed (via Acpi_install_address_space_handler)&n;&t; */
id|status
op_assign
id|acpi_install_address_space_handler
(paren
(paren
id|acpi_handle
)paren
id|acpi_gbl_root_node
comma
id|ACPI_ADR_SPACE_SYSTEM_MEMORY
comma
id|ACPI_DEFAULT_HANDLER
comma
l_int|NULL
comma
l_int|NULL
)paren
suffix:semicolon
r_if
c_cond
(paren
(paren
id|ACPI_FAILURE
(paren
id|status
)paren
)paren
op_logical_and
(paren
id|status
op_ne
id|AE_ALREADY_EXISTS
)paren
)paren
(brace
id|return_ACPI_STATUS
(paren
id|status
)paren
suffix:semicolon
)brace
id|status
op_assign
id|acpi_install_address_space_handler
(paren
(paren
id|acpi_handle
)paren
id|acpi_gbl_root_node
comma
id|ACPI_ADR_SPACE_SYSTEM_IO
comma
id|ACPI_DEFAULT_HANDLER
comma
l_int|NULL
comma
l_int|NULL
)paren
suffix:semicolon
r_if
c_cond
(paren
(paren
id|ACPI_FAILURE
(paren
id|status
)paren
)paren
op_logical_and
(paren
id|status
op_ne
id|AE_ALREADY_EXISTS
)paren
)paren
(brace
id|return_ACPI_STATUS
(paren
id|status
)paren
suffix:semicolon
)brace
id|status
op_assign
id|acpi_install_address_space_handler
(paren
(paren
id|acpi_handle
)paren
id|acpi_gbl_root_node
comma
id|ACPI_ADR_SPACE_PCI_CONFIG
comma
id|ACPI_DEFAULT_HANDLER
comma
l_int|NULL
comma
l_int|NULL
)paren
suffix:semicolon
r_if
c_cond
(paren
(paren
id|ACPI_FAILURE
(paren
id|status
)paren
)paren
op_logical_and
(paren
id|status
op_ne
id|AE_ALREADY_EXISTS
)paren
)paren
(brace
id|return_ACPI_STATUS
(paren
id|status
)paren
suffix:semicolon
)brace
id|status
op_assign
id|acpi_install_address_space_handler
(paren
(paren
id|acpi_handle
)paren
id|acpi_gbl_root_node
comma
id|ACPI_ADR_SPACE_DATA_TABLE
comma
id|ACPI_DEFAULT_HANDLER
comma
l_int|NULL
comma
l_int|NULL
)paren
suffix:semicolon
r_if
c_cond
(paren
(paren
id|ACPI_FAILURE
(paren
id|status
)paren
)paren
op_logical_and
(paren
id|status
op_ne
id|AE_ALREADY_EXISTS
)paren
)paren
(brace
id|return_ACPI_STATUS
(paren
id|status
)paren
suffix:semicolon
)brace
id|return_ACPI_STATUS
(paren
id|AE_OK
)paren
suffix:semicolon
)brace
multiline_comment|/*******************************************************************************&n; *&n; * FUNCTION:    Acpi_ev_execute_reg_method&n; *&n; * PARAMETERS:  Region_obj          - Object structure&n; *              Function            - On (1) or Off (0)&n; *&n; * RETURN:      Status&n; *&n; * DESCRIPTION: Execute _REG method for a region&n; *&n; ******************************************************************************/
r_static
id|acpi_status
DECL|function|acpi_ev_execute_reg_method
id|acpi_ev_execute_reg_method
(paren
id|acpi_operand_object
op_star
id|region_obj
comma
id|u32
id|function
)paren
(brace
id|acpi_operand_object
op_star
id|params
(braket
l_int|3
)braket
suffix:semicolon
id|acpi_operand_object
op_star
id|region_obj2
suffix:semicolon
id|acpi_status
id|status
suffix:semicolon
id|ACPI_FUNCTION_TRACE
(paren
l_string|&quot;Ev_execute_reg_method&quot;
)paren
suffix:semicolon
id|region_obj2
op_assign
id|acpi_ns_get_secondary_object
(paren
id|region_obj
)paren
suffix:semicolon
r_if
c_cond
(paren
op_logical_neg
id|region_obj2
)paren
(brace
id|return_ACPI_STATUS
(paren
id|AE_NOT_EXIST
)paren
suffix:semicolon
)brace
r_if
c_cond
(paren
id|region_obj2-&gt;extra.method_REG
op_eq
l_int|NULL
)paren
(brace
id|return_ACPI_STATUS
(paren
id|AE_OK
)paren
suffix:semicolon
)brace
multiline_comment|/*&n;&t; *  _REG method has two arguments&n;&t; *  Arg0:   Integer: Operation region space ID&n;&t; *          Same value as Region_obj-&gt;Region.Space_id&n;&t; *  Arg1:   Integer: connection status&n;&t; *          1 for connecting the handler,&n;&t; *          0 for disconnecting the handler&n;&t; *          Passed as a parameter&n;&t; */
id|params
(braket
l_int|0
)braket
op_assign
id|acpi_ut_create_internal_object
(paren
id|ACPI_TYPE_INTEGER
)paren
suffix:semicolon
r_if
c_cond
(paren
op_logical_neg
id|params
(braket
l_int|0
)braket
)paren
(brace
id|return_ACPI_STATUS
(paren
id|AE_NO_MEMORY
)paren
suffix:semicolon
)brace
id|params
(braket
l_int|1
)braket
op_assign
id|acpi_ut_create_internal_object
(paren
id|ACPI_TYPE_INTEGER
)paren
suffix:semicolon
r_if
c_cond
(paren
op_logical_neg
id|params
(braket
l_int|1
)braket
)paren
(brace
id|status
op_assign
id|AE_NO_MEMORY
suffix:semicolon
r_goto
id|cleanup
suffix:semicolon
)brace
multiline_comment|/*&n;&t; *  Set up the parameter objects&n;&t; */
id|params
(braket
l_int|0
)braket
op_member_access_from_pointer
id|integer.value
op_assign
id|region_obj-&gt;region.space_id
suffix:semicolon
id|params
(braket
l_int|1
)braket
op_member_access_from_pointer
id|integer.value
op_assign
id|function
suffix:semicolon
id|params
(braket
l_int|2
)braket
op_assign
l_int|NULL
suffix:semicolon
multiline_comment|/*&n;&t; *  Execute the method, no return value&n;&t; */
id|ACPI_DEBUG_EXEC
c_func
(paren
id|acpi_ut_display_init_pathname
(paren
id|region_obj2-&gt;extra.method_REG
comma
l_string|&quot; [Method]&quot;
)paren
)paren
suffix:semicolon
id|status
op_assign
id|acpi_ns_evaluate_by_handle
(paren
id|region_obj2-&gt;extra.method_REG
comma
id|params
comma
l_int|NULL
)paren
suffix:semicolon
id|acpi_ut_remove_reference
(paren
id|params
(braket
l_int|1
)braket
)paren
suffix:semicolon
id|cleanup
suffix:colon
id|acpi_ut_remove_reference
(paren
id|params
(braket
l_int|0
)braket
)paren
suffix:semicolon
id|return_ACPI_STATUS
(paren
id|status
)paren
suffix:semicolon
)brace
multiline_comment|/*******************************************************************************&n; *&n; * FUNCTION:    Acpi_ev_address_space_dispatch&n; *&n; * PARAMETERS:  Region_obj          - internal region object&n; *              Space_id            - ID of the address space (0-255)&n; *              Function            - Read or Write operation&n; *              Address             - Where in the space to read or write&n; *              Bit_width           - Field width in bits (8, 16, 32, or 64)&n; *              Value               - Pointer to in or out value&n; *&n; * RETURN:      Status&n; *&n; * DESCRIPTION: Dispatch an address space or operation region access to&n; *              a previously installed handler.&n; *&n; ******************************************************************************/
id|acpi_status
DECL|function|acpi_ev_address_space_dispatch
id|acpi_ev_address_space_dispatch
(paren
id|acpi_operand_object
op_star
id|region_obj
comma
id|u32
id|function
comma
id|ACPI_PHYSICAL_ADDRESS
id|address
comma
id|u32
id|bit_width
comma
id|acpi_integer
op_star
id|value
)paren
(brace
id|acpi_status
id|status
suffix:semicolon
id|acpi_adr_space_handler
id|handler
suffix:semicolon
id|acpi_adr_space_setup
id|region_setup
suffix:semicolon
id|acpi_operand_object
op_star
id|handler_desc
suffix:semicolon
id|acpi_operand_object
op_star
id|region_obj2
suffix:semicolon
r_void
op_star
id|region_context
op_assign
l_int|NULL
suffix:semicolon
id|ACPI_FUNCTION_TRACE
(paren
l_string|&quot;Ev_address_space_dispatch&quot;
)paren
suffix:semicolon
id|region_obj2
op_assign
id|acpi_ns_get_secondary_object
(paren
id|region_obj
)paren
suffix:semicolon
r_if
c_cond
(paren
op_logical_neg
id|region_obj2
)paren
(brace
id|return_ACPI_STATUS
(paren
id|AE_NOT_EXIST
)paren
suffix:semicolon
)brace
multiline_comment|/*&n;&t; * Ensure that there is a handler associated with this region&n;&t; */
id|handler_desc
op_assign
id|region_obj-&gt;region.addr_handler
suffix:semicolon
r_if
c_cond
(paren
op_logical_neg
id|handler_desc
)paren
(brace
id|ACPI_DEBUG_PRINT
(paren
(paren
id|ACPI_DB_ERROR
comma
l_string|&quot;no handler for region(%p) [%s]&bslash;n&quot;
comma
id|region_obj
comma
id|acpi_ut_get_region_name
(paren
id|region_obj-&gt;region.space_id
)paren
)paren
)paren
suffix:semicolon
id|return_ACPI_STATUS
(paren
id|AE_NOT_EXIST
)paren
suffix:semicolon
)brace
multiline_comment|/*&n;&t; * It may be the case that the region has never been initialized&n;&t; * Some types of regions require special init code&n;&t; */
r_if
c_cond
(paren
op_logical_neg
(paren
id|region_obj-&gt;region.flags
op_amp
id|AOPOBJ_SETUP_COMPLETE
)paren
)paren
(brace
multiline_comment|/*&n;&t;&t; * This region has not been initialized yet, do it&n;&t;&t; */
id|region_setup
op_assign
id|handler_desc-&gt;addr_handler.setup
suffix:semicolon
r_if
c_cond
(paren
op_logical_neg
id|region_setup
)paren
(brace
multiline_comment|/*&n;&t;&t;&t; *  Bad news, no init routine and not init&squot;d&n;&t;&t;&t; */
id|ACPI_DEBUG_PRINT
(paren
(paren
id|ACPI_DB_ERROR
comma
l_string|&quot;No init routine for region(%p) [%s]&bslash;n&quot;
comma
id|region_obj
comma
id|acpi_ut_get_region_name
(paren
id|region_obj-&gt;region.space_id
)paren
)paren
)paren
suffix:semicolon
id|return_ACPI_STATUS
(paren
id|AE_UNKNOWN_STATUS
)paren
suffix:semicolon
)brace
multiline_comment|/*&n;&t;&t; * We must exit the interpreter because the region setup will potentially&n;&t;&t; * execute control methods&n;&t;&t; */
id|acpi_ex_exit_interpreter
(paren
)paren
suffix:semicolon
id|status
op_assign
id|region_setup
(paren
id|region_obj
comma
id|ACPI_REGION_ACTIVATE
comma
id|handler_desc-&gt;addr_handler.context
comma
op_amp
id|region_context
)paren
suffix:semicolon
multiline_comment|/* Re-enter the interpreter */
id|acpi_ex_enter_interpreter
(paren
)paren
suffix:semicolon
multiline_comment|/*&n;&t;&t; *  Init routine may fail&n;&t;&t; */
r_if
c_cond
(paren
id|ACPI_FAILURE
(paren
id|status
)paren
)paren
(brace
id|ACPI_DEBUG_PRINT
(paren
(paren
id|ACPI_DB_ERROR
comma
l_string|&quot;Region Init: %s [%s]&bslash;n&quot;
comma
id|acpi_format_exception
(paren
id|status
)paren
comma
id|acpi_ut_get_region_name
(paren
id|region_obj-&gt;region.space_id
)paren
)paren
)paren
suffix:semicolon
id|return_ACPI_STATUS
(paren
id|status
)paren
suffix:semicolon
)brace
id|region_obj-&gt;region.flags
op_or_assign
id|AOPOBJ_SETUP_COMPLETE
suffix:semicolon
multiline_comment|/*&n;&t;&t; *  Save the returned context for use in all accesses to&n;&t;&t; *  this particular region.&n;&t;&t; */
id|region_obj2-&gt;extra.region_context
op_assign
id|region_context
suffix:semicolon
)brace
multiline_comment|/*&n;&t; *  We have everything we need, begin the process&n;&t; */
id|handler
op_assign
id|handler_desc-&gt;addr_handler.handler
suffix:semicolon
id|ACPI_DEBUG_PRINT
(paren
(paren
id|ACPI_DB_OPREGION
comma
l_string|&quot;Addrhandler %p (%p), Address %8.8X%8.8X&bslash;n&quot;
comma
op_amp
id|region_obj-&gt;region.addr_handler-&gt;addr_handler
comma
id|handler
comma
id|ACPI_HIDWORD
(paren
id|address
)paren
comma
id|ACPI_LODWORD
(paren
id|address
)paren
)paren
)paren
suffix:semicolon
r_if
c_cond
(paren
op_logical_neg
(paren
id|handler_desc-&gt;addr_handler.flags
op_amp
id|ACPI_ADDR_HANDLER_DEFAULT_INSTALLED
)paren
)paren
(brace
multiline_comment|/*&n;&t;&t; *  For handlers other than the default (supplied) handlers, we must&n;&t;&t; *  exit the interpreter because the handler *might* block -- we don&squot;t&n;&t;&t; *  know what it will do, so we can&squot;t hold the lock on the intepreter.&n;&t;&t; */
id|acpi_ex_exit_interpreter
c_func
(paren
)paren
suffix:semicolon
)brace
multiline_comment|/*&n;&t; *  Invoke the handler.&n;&t; */
id|status
op_assign
id|handler
(paren
id|function
comma
id|address
comma
id|bit_width
comma
id|value
comma
id|handler_desc-&gt;addr_handler.context
comma
id|region_obj2-&gt;extra.region_context
)paren
suffix:semicolon
r_if
c_cond
(paren
id|ACPI_FAILURE
(paren
id|status
)paren
)paren
(brace
id|ACPI_REPORT_ERROR
(paren
(paren
l_string|&quot;Handler for [%s] returned %s&bslash;n&quot;
comma
id|acpi_ut_get_region_name
(paren
id|region_obj-&gt;region.space_id
)paren
comma
id|acpi_format_exception
(paren
id|status
)paren
)paren
)paren
suffix:semicolon
)brace
r_if
c_cond
(paren
op_logical_neg
(paren
id|handler_desc-&gt;addr_handler.flags
op_amp
id|ACPI_ADDR_HANDLER_DEFAULT_INSTALLED
)paren
)paren
(brace
multiline_comment|/*&n;&t;&t; * We just returned from a non-default handler, we must re-enter the&n;&t;&t; * interpreter&n;&t;&t; */
id|acpi_ex_enter_interpreter
(paren
)paren
suffix:semicolon
)brace
id|return_ACPI_STATUS
(paren
id|status
)paren
suffix:semicolon
)brace
multiline_comment|/*******************************************************************************&n; *&n; * FUNCTION:    Acpi_ev_disassociate_region_from_handler&n; *&n; * PARAMETERS:  Region_obj      - Region Object&n; *              Acpi_ns_is_locked - Namespace Region Already Locked?&n; *&n; * RETURN:      None&n; *&n; * DESCRIPTION: Break the association between the handler and the region&n; *              this is a two way association.&n; *&n; ******************************************************************************/
r_void
DECL|function|acpi_ev_disassociate_region_from_handler
id|acpi_ev_disassociate_region_from_handler
c_func
(paren
id|acpi_operand_object
op_star
id|region_obj
comma
id|u8
id|acpi_ns_is_locked
)paren
(brace
id|acpi_operand_object
op_star
id|handler_obj
suffix:semicolon
id|acpi_operand_object
op_star
id|obj_desc
suffix:semicolon
id|acpi_operand_object
op_star
op_star
id|last_obj_ptr
suffix:semicolon
id|acpi_adr_space_setup
id|region_setup
suffix:semicolon
r_void
op_star
id|region_context
suffix:semicolon
id|acpi_operand_object
op_star
id|region_obj2
suffix:semicolon
id|acpi_status
id|status
suffix:semicolon
id|ACPI_FUNCTION_TRACE
(paren
l_string|&quot;Ev_disassociate_region_from_handler&quot;
)paren
suffix:semicolon
id|region_obj2
op_assign
id|acpi_ns_get_secondary_object
(paren
id|region_obj
)paren
suffix:semicolon
r_if
c_cond
(paren
op_logical_neg
id|region_obj2
)paren
(brace
r_return
suffix:semicolon
)brace
id|region_context
op_assign
id|region_obj2-&gt;extra.region_context
suffix:semicolon
multiline_comment|/*&n;&t; *  Get the address handler from the region object&n;&t; */
id|handler_obj
op_assign
id|region_obj-&gt;region.addr_handler
suffix:semicolon
r_if
c_cond
(paren
op_logical_neg
id|handler_obj
)paren
(brace
multiline_comment|/*&n;&t;&t; *  This region has no handler, all done&n;&t;&t; */
id|return_VOID
suffix:semicolon
)brace
multiline_comment|/*&n;&t; *  Find this region in the handler&squot;s list&n;&t; */
id|obj_desc
op_assign
id|handler_obj-&gt;addr_handler.region_list
suffix:semicolon
id|last_obj_ptr
op_assign
op_amp
id|handler_obj-&gt;addr_handler.region_list
suffix:semicolon
r_while
c_loop
(paren
id|obj_desc
)paren
(brace
multiline_comment|/*&n;&t;&t; *  See if this is the one&n;&t;&t; */
r_if
c_cond
(paren
id|obj_desc
op_eq
id|region_obj
)paren
(brace
id|ACPI_DEBUG_PRINT
(paren
(paren
id|ACPI_DB_OPREGION
comma
l_string|&quot;Removing Region %p from address handler %p&bslash;n&quot;
comma
id|region_obj
comma
id|handler_obj
)paren
)paren
suffix:semicolon
multiline_comment|/*&n;&t;&t;&t; *  This is it, remove it from the handler&squot;s list&n;&t;&t;&t; */
op_star
id|last_obj_ptr
op_assign
id|obj_desc-&gt;region.next
suffix:semicolon
id|obj_desc-&gt;region.next
op_assign
l_int|NULL
suffix:semicolon
multiline_comment|/* Must clear field */
r_if
c_cond
(paren
id|acpi_ns_is_locked
)paren
(brace
id|status
op_assign
id|acpi_ut_release_mutex
(paren
id|ACPI_MTX_NAMESPACE
)paren
suffix:semicolon
r_if
c_cond
(paren
id|ACPI_FAILURE
(paren
id|status
)paren
)paren
(brace
id|return_VOID
suffix:semicolon
)brace
)brace
multiline_comment|/*&n;&t;&t;&t; *  Now stop region accesses by executing the _REG method&n;&t;&t;&t; */
id|acpi_ev_execute_reg_method
(paren
id|region_obj
comma
l_int|0
)paren
suffix:semicolon
r_if
c_cond
(paren
id|acpi_ns_is_locked
)paren
(brace
id|status
op_assign
id|acpi_ut_acquire_mutex
(paren
id|ACPI_MTX_NAMESPACE
)paren
suffix:semicolon
r_if
c_cond
(paren
id|ACPI_FAILURE
(paren
id|status
)paren
)paren
(brace
id|return_VOID
suffix:semicolon
)brace
)brace
multiline_comment|/*&n;&t;&t;&t; *  Call the setup handler with the deactivate notification&n;&t;&t;&t; */
id|region_setup
op_assign
id|handler_obj-&gt;addr_handler.setup
suffix:semicolon
id|status
op_assign
id|region_setup
(paren
id|region_obj
comma
id|ACPI_REGION_DEACTIVATE
comma
id|handler_obj-&gt;addr_handler.context
comma
op_amp
id|region_context
)paren
suffix:semicolon
multiline_comment|/*&n;&t;&t;&t; *  Init routine may fail, Just ignore errors&n;&t;&t;&t; */
r_if
c_cond
(paren
id|ACPI_FAILURE
(paren
id|status
)paren
)paren
(brace
id|ACPI_DEBUG_PRINT
(paren
(paren
id|ACPI_DB_ERROR
comma
l_string|&quot;%s from region init, [%s]&bslash;n&quot;
comma
id|acpi_format_exception
(paren
id|status
)paren
comma
id|acpi_ut_get_region_name
(paren
id|region_obj-&gt;region.space_id
)paren
)paren
)paren
suffix:semicolon
)brace
id|region_obj-&gt;region.flags
op_and_assign
op_complement
(paren
id|AOPOBJ_SETUP_COMPLETE
)paren
suffix:semicolon
multiline_comment|/*&n;&t;&t;&t; *  Remove handler reference in the region&n;&t;&t;&t; *&n;&t;&t;&t; *  NOTE: this doesn&squot;t mean that the region goes away&n;&t;&t;&t; *  The region is just inaccessible as indicated to&n;&t;&t;&t; *  the _REG method&n;&t;&t;&t; *&n;&t;&t;&t; *  If the region is on the handler&squot;s list&n;&t;&t;&t; *  this better be the region&squot;s handler&n;&t;&t;&t; */
id|region_obj-&gt;region.addr_handler
op_assign
l_int|NULL
suffix:semicolon
id|return_VOID
suffix:semicolon
)brace
multiline_comment|/* found the right handler */
multiline_comment|/*&n;&t;&t; *  Move through the linked list of handlers&n;&t;&t; */
id|last_obj_ptr
op_assign
op_amp
id|obj_desc-&gt;region.next
suffix:semicolon
id|obj_desc
op_assign
id|obj_desc-&gt;region.next
suffix:semicolon
)brace
multiline_comment|/*&n;&t; *  If we get here, the region was not in the handler&squot;s region list&n;&t; */
id|ACPI_DEBUG_PRINT
(paren
(paren
id|ACPI_DB_OPREGION
comma
l_string|&quot;Cannot remove region %p from address handler %p&bslash;n&quot;
comma
id|region_obj
comma
id|handler_obj
)paren
)paren
suffix:semicolon
id|return_VOID
suffix:semicolon
)brace
multiline_comment|/*******************************************************************************&n; *&n; * FUNCTION:    Acpi_ev_associate_region_and_handler&n; *&n; * PARAMETERS:  Handler_obj     - Handler Object&n; *              Region_obj      - Region Object&n; *              Acpi_ns_is_locked - Namespace Region Already Locked?&n; *&n; * RETURN:      None&n; *&n; * DESCRIPTION: Create the association between the handler and the region&n; *              this is a two way association.&n; *&n; ******************************************************************************/
id|acpi_status
DECL|function|acpi_ev_associate_region_and_handler
id|acpi_ev_associate_region_and_handler
(paren
id|acpi_operand_object
op_star
id|handler_obj
comma
id|acpi_operand_object
op_star
id|region_obj
comma
id|u8
id|acpi_ns_is_locked
)paren
(brace
id|acpi_status
id|status
suffix:semicolon
id|ACPI_FUNCTION_TRACE
(paren
l_string|&quot;Ev_associate_region_and_handler&quot;
)paren
suffix:semicolon
id|ACPI_DEBUG_PRINT
(paren
(paren
id|ACPI_DB_OPREGION
comma
l_string|&quot;Adding Region %p to address handler %p [%s]&bslash;n&quot;
comma
id|region_obj
comma
id|handler_obj
comma
id|acpi_ut_get_region_name
(paren
id|region_obj-&gt;region.space_id
)paren
)paren
)paren
suffix:semicolon
multiline_comment|/*&n;&t; * Link this region to the front of the handler&squot;s list&n;&t; */
id|region_obj-&gt;region.next
op_assign
id|handler_obj-&gt;addr_handler.region_list
suffix:semicolon
id|handler_obj-&gt;addr_handler.region_list
op_assign
id|region_obj
suffix:semicolon
multiline_comment|/*&n;&t; * Set the region&squot;s handler&n;&t; */
id|region_obj-&gt;region.addr_handler
op_assign
id|handler_obj
suffix:semicolon
multiline_comment|/*&n;&t; * Tell all users that this region is usable by running the _REG&n;&t; * method&n;&t; */
r_if
c_cond
(paren
id|acpi_ns_is_locked
)paren
(brace
id|acpi_ut_release_mutex
(paren
id|ACPI_MTX_NAMESPACE
)paren
suffix:semicolon
)brace
id|status
op_assign
id|acpi_ev_execute_reg_method
(paren
id|region_obj
comma
l_int|1
)paren
suffix:semicolon
r_if
c_cond
(paren
id|acpi_ns_is_locked
)paren
(brace
(paren
r_void
)paren
id|acpi_ut_acquire_mutex
(paren
id|ACPI_MTX_NAMESPACE
)paren
suffix:semicolon
)brace
id|return_ACPI_STATUS
(paren
id|status
)paren
suffix:semicolon
)brace
multiline_comment|/*******************************************************************************&n; *&n; * FUNCTION:    Acpi_ev_addr_handler_helper&n; *&n; * PARAMETERS:  Handle              - Node to be dumped&n; *              Level               - Nesting level of the handle&n; *              Context             - Passed into Acpi_ns_walk_namespace&n; *&n; * DESCRIPTION: This routine installs an address handler into objects that are&n; *              of type Region.&n; *&n; *              If the Object is a Device, and the device has a handler of&n; *              the same type then the search is terminated in that branch.&n; *&n; *              This is because the existing handler is closer in proximity&n; *              to any more regions than the one we are trying to install.&n; *&n; ******************************************************************************/
id|acpi_status
DECL|function|acpi_ev_addr_handler_helper
id|acpi_ev_addr_handler_helper
(paren
id|acpi_handle
id|obj_handle
comma
id|u32
id|level
comma
r_void
op_star
id|context
comma
r_void
op_star
op_star
id|return_value
)paren
(brace
id|acpi_operand_object
op_star
id|handler_obj
suffix:semicolon
id|acpi_operand_object
op_star
id|tmp_obj
suffix:semicolon
id|acpi_operand_object
op_star
id|obj_desc
suffix:semicolon
id|acpi_namespace_node
op_star
id|node
suffix:semicolon
id|acpi_status
id|status
suffix:semicolon
id|ACPI_FUNCTION_NAME
(paren
l_string|&quot;Ev_addr_handler_helper&quot;
)paren
suffix:semicolon
id|handler_obj
op_assign
(paren
id|acpi_operand_object
op_star
)paren
id|context
suffix:semicolon
multiline_comment|/* Parameter validation */
r_if
c_cond
(paren
op_logical_neg
id|handler_obj
)paren
(brace
r_return
(paren
id|AE_OK
)paren
suffix:semicolon
)brace
multiline_comment|/* Convert and validate the device handle */
id|node
op_assign
id|acpi_ns_map_handle_to_node
(paren
id|obj_handle
)paren
suffix:semicolon
r_if
c_cond
(paren
op_logical_neg
id|node
)paren
(brace
r_return
(paren
id|AE_BAD_PARAMETER
)paren
suffix:semicolon
)brace
multiline_comment|/*&n;&t; *  We only care about regions.and objects&n;&t; *  that can have address handlers&n;&t; */
r_if
c_cond
(paren
(paren
id|node-&gt;type
op_ne
id|ACPI_TYPE_DEVICE
)paren
op_logical_and
(paren
id|node-&gt;type
op_ne
id|ACPI_TYPE_REGION
)paren
op_logical_and
(paren
id|node
op_ne
id|acpi_gbl_root_node
)paren
)paren
(brace
r_return
(paren
id|AE_OK
)paren
suffix:semicolon
)brace
multiline_comment|/* Check for an existing internal object */
id|obj_desc
op_assign
id|acpi_ns_get_attached_object
(paren
id|node
)paren
suffix:semicolon
r_if
c_cond
(paren
op_logical_neg
id|obj_desc
)paren
(brace
multiline_comment|/*&n;&t;&t; *  The object DNE, we don&squot;t care about it&n;&t;&t; */
r_return
(paren
id|AE_OK
)paren
suffix:semicolon
)brace
multiline_comment|/*&n;&t; *  Devices are handled different than regions&n;&t; */
r_if
c_cond
(paren
id|obj_desc-&gt;common.type
op_eq
id|ACPI_TYPE_DEVICE
)paren
(brace
multiline_comment|/*&n;&t;&t; *  See if this guy has any handlers&n;&t;&t; */
id|tmp_obj
op_assign
id|obj_desc-&gt;device.addr_handler
suffix:semicolon
r_while
c_loop
(paren
id|tmp_obj
)paren
(brace
multiline_comment|/*&n;&t;&t;&t; *  Now let&squot;s see if it&squot;s for the same address space.&n;&t;&t;&t; */
r_if
c_cond
(paren
id|tmp_obj-&gt;addr_handler.space_id
op_eq
id|handler_obj-&gt;addr_handler.space_id
)paren
(brace
multiline_comment|/*&n;&t;&t;&t;&t; *  It&squot;s for the same address space&n;&t;&t;&t;&t; */
id|ACPI_DEBUG_PRINT
(paren
(paren
id|ACPI_DB_OPREGION
comma
l_string|&quot;Found handler for region [%s] in device %p(%p) handler %p&bslash;n&quot;
comma
id|acpi_ut_get_region_name
(paren
id|handler_obj-&gt;addr_handler.space_id
)paren
comma
id|obj_desc
comma
id|tmp_obj
comma
id|handler_obj
)paren
)paren
suffix:semicolon
multiline_comment|/*&n;&t;&t;&t;&t; *  Since the object we found it on was a device, then it&n;&t;&t;&t;&t; *  means that someone has already installed a handler for&n;&t;&t;&t;&t; *  the branch of the namespace from this device on.  Just&n;&t;&t;&t;&t; *  bail out telling the walk routine to not traverse this&n;&t;&t;&t;&t; *  branch.  This preserves the scoping rule for handlers.&n;&t;&t;&t;&t; */
r_return
(paren
id|AE_CTRL_DEPTH
)paren
suffix:semicolon
)brace
multiline_comment|/*&n;&t;&t;&t; *  Move through the linked list of handlers&n;&t;&t;&t; */
id|tmp_obj
op_assign
id|tmp_obj-&gt;addr_handler.next
suffix:semicolon
)brace
multiline_comment|/*&n;&t;&t; *  As long as the device didn&squot;t have a handler for this&n;&t;&t; *  space we don&squot;t care about it.  We just ignore it and&n;&t;&t; *  proceed.&n;&t;&t; */
r_return
(paren
id|AE_OK
)paren
suffix:semicolon
)brace
multiline_comment|/*&n;&t; *  Only here if it was a region&n;&t; */
r_if
c_cond
(paren
id|obj_desc-&gt;region.space_id
op_ne
id|handler_obj-&gt;addr_handler.space_id
)paren
(brace
multiline_comment|/*&n;&t;&t; *  This region is for a different address space&n;&t;&t; *  ignore it&n;&t;&t; */
r_return
(paren
id|AE_OK
)paren
suffix:semicolon
)brace
multiline_comment|/*&n;&t; *  Now we have a region and it is for the handler&squot;s address&n;&t; *  space type.&n;&t; *&n;&t; *  First disconnect region for any previous handler (if any)&n;&t; */
id|acpi_ev_disassociate_region_from_handler
(paren
id|obj_desc
comma
id|FALSE
)paren
suffix:semicolon
multiline_comment|/*&n;&t; *  Then connect the region to the new handler&n;&t; */
id|status
op_assign
id|acpi_ev_associate_region_and_handler
(paren
id|handler_obj
comma
id|obj_desc
comma
id|FALSE
)paren
suffix:semicolon
r_return
(paren
id|status
)paren
suffix:semicolon
)brace
eof
