macro_line|#ifndef __ASM_OFFSETS_H__
DECL|macro|__ASM_OFFSETS_H__
mdefine_line|#define __ASM_OFFSETS_H__
multiline_comment|/*&n; * DO NOT MODIFY.&n; *&n; * This file was generated by arch/cris/Makefile&n; *&n; */
DECL|macro|PT_orig_r10
mdefine_line|#define PT_orig_r10 4 /* offsetof(struct pt_regs, orig_r10) */
DECL|macro|PT_r13
mdefine_line|#define PT_r13 8 /* offsetof(struct pt_regs, r13) */
DECL|macro|PT_r12
mdefine_line|#define PT_r12 12 /* offsetof(struct pt_regs, r12) */
DECL|macro|PT_r11
mdefine_line|#define PT_r11 16 /* offsetof(struct pt_regs, r11) */
DECL|macro|PT_r10
mdefine_line|#define PT_r10 20 /* offsetof(struct pt_regs, r10) */
DECL|macro|PT_r9
mdefine_line|#define PT_r9 24 /* offsetof(struct pt_regs, r9) */
DECL|macro|PT_mof
mdefine_line|#define PT_mof 64 /* offsetof(struct pt_regs, mof) */
DECL|macro|PT_dccr
mdefine_line|#define PT_dccr 68 /* offsetof(struct pt_regs, dccr) */
DECL|macro|PT_srp
mdefine_line|#define PT_srp 72 /* offsetof(struct pt_regs, srp) */
DECL|macro|TI_task
mdefine_line|#define TI_task 0 /* offsetof(struct thread_info, task) */
DECL|macro|TI_flags
mdefine_line|#define TI_flags 8 /* offsetof(struct thread_info, flags) */
DECL|macro|TI_preempt_count
mdefine_line|#define TI_preempt_count 16 /* offsetof(struct thread_info, preempt_count) */
DECL|macro|THREAD_ksp
mdefine_line|#define THREAD_ksp 0 /* offsetof(struct thread_struct, ksp) */
DECL|macro|THREAD_usp
mdefine_line|#define THREAD_usp 4 /* offsetof(struct thread_struct, usp) */
DECL|macro|THREAD_dccr
mdefine_line|#define THREAD_dccr 8 /* offsetof(struct thread_struct, dccr) */
DECL|macro|TASK_pid
mdefine_line|#define TASK_pid 121 /* offsetof(struct task_struct, pid) */
DECL|macro|LCLONE_VM
mdefine_line|#define LCLONE_VM 256 /* CLONE_VM */
DECL|macro|LCLONE_UNTRACED
mdefine_line|#define LCLONE_UNTRACED 8388608 /* CLONE_UNTRACED */
macro_line|#endif
eof
