macro_line|#ifndef __ASM_OFFSETS_H__
DECL|macro|__ASM_OFFSETS_H__
mdefine_line|#define __ASM_OFFSETS_H__
multiline_comment|/*&n; * DO NOT MODIFY.&n; *&n; * This file was generated by arch/ppc64/Makefile&n; *&n; */
DECL|macro|THREAD_SHIFT
mdefine_line|#define THREAD_SHIFT 14 /* THREAD_SHIFT */
DECL|macro|THREAD_SIZE
mdefine_line|#define THREAD_SIZE 16384 /* THREAD_SIZE */
DECL|macro|TI_FLAGS
mdefine_line|#define TI_FLAGS 16 /* offsetof(struct thread_info, flags) */
DECL|macro|THREAD
mdefine_line|#define THREAD 1328 /* offsetof(struct task_struct, thread) */
DECL|macro|PT_REGS
mdefine_line|#define PT_REGS 8 /* offsetof(struct thread_struct, regs) */
DECL|macro|THREAD_FPEXC_MODE
mdefine_line|#define THREAD_FPEXC_MODE 288 /* offsetof(struct thread_struct, fpexc_mode) */
DECL|macro|THREAD_FPR0
mdefine_line|#define THREAD_FPR0 24 /* offsetof(struct thread_struct, fpr[0]) */
DECL|macro|THREAD_FPSCR
mdefine_line|#define THREAD_FPSCR 280 /* offsetof(struct thread_struct, fpscr) */
DECL|macro|KSP
mdefine_line|#define KSP 0 /* offsetof(struct thread_struct, ksp) */
DECL|macro|THREAD_VR0
mdefine_line|#define THREAD_VR0 320 /* offsetof(struct thread_struct, vr[0]) */
DECL|macro|THREAD_VRSAVE
mdefine_line|#define THREAD_VRSAVE 848 /* offsetof(struct thread_struct, vrsave) */
DECL|macro|THREAD_VSCR
mdefine_line|#define THREAD_VSCR 832 /* offsetof(struct thread_struct, vscr) */
DECL|macro|THREAD_USED_VR
mdefine_line|#define THREAD_USED_VR 856 /* offsetof(struct thread_struct, used_vr) */
DECL|macro|MM
mdefine_line|#define MM 184 /* offsetof(struct task_struct, mm) */
DECL|macro|PACA
mdefine_line|#define PACA 24 /* offsetof(struct naca_struct, paca) */
DECL|macro|DCACHEL1LINESIZE
mdefine_line|#define DCACHEL1LINESIZE 100 /* offsetof(struct systemcfg, dCacheL1LineSize) */
DECL|macro|DCACHEL1LOGLINESIZE
mdefine_line|#define DCACHEL1LOGLINESIZE 96 /* offsetof(struct naca_struct, dCacheL1LogLineSize) */
DECL|macro|DCACHEL1LINESPERPAGE
mdefine_line|#define DCACHEL1LINESPERPAGE 100 /* offsetof(struct naca_struct, dCacheL1LinesPerPage) */
DECL|macro|ICACHEL1LINESIZE
mdefine_line|#define ICACHEL1LINESIZE 108 /* offsetof(struct systemcfg, iCacheL1LineSize) */
DECL|macro|ICACHEL1LOGLINESIZE
mdefine_line|#define ICACHEL1LOGLINESIZE 104 /* offsetof(struct naca_struct, iCacheL1LogLineSize) */
DECL|macro|ICACHEL1LINESPERPAGE
mdefine_line|#define ICACHEL1LINESPERPAGE 108 /* offsetof(struct naca_struct, iCacheL1LinesPerPage) */
DECL|macro|SLBSIZE
mdefine_line|#define SLBSIZE 72 /* offsetof(struct naca_struct, slb_size) */
DECL|macro|PLATFORM
mdefine_line|#define PLATFORM 24 /* offsetof(struct systemcfg, platform) */
DECL|macro|PACA_SIZE
mdefine_line|#define PACA_SIZE 8192 /* sizeof(struct paca_struct) */
DECL|macro|PACAPACAINDEX
mdefine_line|#define PACAPACAINDEX 24 /* offsetof(struct paca_struct, xPacaIndex) */
DECL|macro|PACAPROCSTART
mdefine_line|#define PACAPROCSTART 256 /* offsetof(struct paca_struct, xProcStart) */
DECL|macro|PACAKSAVE
mdefine_line|#define PACAKSAVE 32 /* offsetof(struct paca_struct, xKsave) */
DECL|macro|PACACURRENT
mdefine_line|#define PACACURRENT 16 /* offsetof(struct paca_struct, xCurrent) */
DECL|macro|PACASAVEDMSR
mdefine_line|#define PACASAVEDMSR 2144 /* offsetof(struct paca_struct, xSavedMsr) */
DECL|macro|PACASTABREAL
mdefine_line|#define PACASTABREAL 56 /* offsetof(struct paca_struct, xStab_data.real) */
DECL|macro|PACASTABVIRT
mdefine_line|#define PACASTABVIRT 64 /* offsetof(struct paca_struct, xStab_data.virt) */
DECL|macro|PACASTABRR
mdefine_line|#define PACASTABRR 72 /* offsetof(struct paca_struct, xStab_data.next_round_robin) */
DECL|macro|PACAR1
mdefine_line|#define PACAR1 2136 /* offsetof(struct paca_struct, xR1) */
DECL|macro|PACALPQUEUE
mdefine_line|#define PACALPQUEUE 40 /* offsetof(struct paca_struct, lpQueuePtr) */
DECL|macro|PACATOC
mdefine_line|#define PACATOC 48 /* offsetof(struct paca_struct, xTOC) */
DECL|macro|PACAEXCSP
mdefine_line|#define PACAEXCSP 80 /* offsetof(struct paca_struct, exception_sp) */
DECL|macro|PACAPROCENABLED
mdefine_line|#define PACAPROCENABLED 88 /* offsetof(struct paca_struct, xProcEnabled) */
DECL|macro|PACADEFAULTDECR
mdefine_line|#define PACADEFAULTDECR 28 /* offsetof(struct paca_struct, default_decr) */
DECL|macro|PACAPROFENABLED
mdefine_line|#define PACAPROFENABLED 89 /* offsetof(struct paca_struct, prof_enabled) */
DECL|macro|PACAPROFLEN
mdefine_line|#define PACAPROFLEN 200 /* offsetof(struct paca_struct, prof_len) */
DECL|macro|PACAPROFSHIFT
mdefine_line|#define PACAPROFSHIFT 180 /* offsetof(struct paca_struct, prof_shift) */
DECL|macro|PACAPROFBUFFER
mdefine_line|#define PACAPROFBUFFER 184 /* offsetof(struct paca_struct, prof_buffer) */
DECL|macro|PACAPROFSTEXT
mdefine_line|#define PACAPROFSTEXT 192 /* offsetof(struct paca_struct, prof_stext) */
DECL|macro|PACALPPACA
mdefine_line|#define PACALPPACA 384 /* offsetof(struct paca_struct, xLpPaca) */
DECL|macro|LPPACA
mdefine_line|#define LPPACA 384 /* offsetof(struct paca_struct, xLpPaca) */
DECL|macro|PACAREGSAV
mdefine_line|#define PACAREGSAV 1024 /* offsetof(struct paca_struct, xRegSav) */
DECL|macro|PACAEXC
mdefine_line|#define PACAEXC 3840 /* offsetof(struct paca_struct, exception_stack) */
DECL|macro|PACAGUARD
mdefine_line|#define PACAGUARD 4096 /* offsetof(struct paca_struct, guard) */
DECL|macro|LPPACASRR0
mdefine_line|#define LPPACASRR0 144 /* offsetof(struct ItLpPaca, xSavedSrr0) */
DECL|macro|LPPACASRR1
mdefine_line|#define LPPACASRR1 152 /* offsetof(struct ItLpPaca, xSavedSrr1) */
DECL|macro|LPPACAANYINT
mdefine_line|#define LPPACAANYINT 128 /* offsetof(struct ItLpPaca, xIntDword.xAnyInt) */
DECL|macro|LPPACADECRINT
mdefine_line|#define LPPACADECRINT 132 /* offsetof(struct ItLpPaca, xIntDword.xFields.xDecrInt) */
DECL|macro|LPQCUREVENTPTR
mdefine_line|#define LPQCUREVENTPTR 16 /* offsetof(struct ItLpQueue, xSlicCurEventPtr) */
DECL|macro|LPQOVERFLOW
mdefine_line|#define LPQOVERFLOW 0 /* offsetof(struct ItLpQueue, xPlicOverflowIntPending) */
DECL|macro|LPEVENTFLAGS
mdefine_line|#define LPEVENTFLAGS 0 /* offsetof(struct HvLpEvent, xFlags) */
DECL|macro|PROMENTRY
mdefine_line|#define PROMENTRY 0 /* offsetof(struct prom_t, entry) */
DECL|macro|RTASBASE
mdefine_line|#define RTASBASE 8 /* offsetof(struct rtas_t, base) */
DECL|macro|RTASENTRY
mdefine_line|#define RTASENTRY 0 /* offsetof(struct rtas_t, entry) */
DECL|macro|RTASSIZE
mdefine_line|#define RTASSIZE 16 /* offsetof(struct rtas_t, size) */
DECL|macro|STACK_FRAME_OVERHEAD
mdefine_line|#define STACK_FRAME_OVERHEAD 112 /* STACK_FRAME_OVERHEAD */
DECL|macro|SWITCH_FRAME_SIZE
mdefine_line|#define SWITCH_FRAME_SIZE 464 /* STACK_FRAME_OVERHEAD + sizeof(struct pt_regs) */
DECL|macro|INT_FRAME_SIZE
mdefine_line|#define INT_FRAME_SIZE 752 /* STACK_FRAME_OVERHEAD + sizeof(struct pt_regs) + 288 */
DECL|macro|PROM_FRAME_SIZE
mdefine_line|#define PROM_FRAME_SIZE 480 /* STACK_FRAME_OVERHEAD + sizeof(struct pt_regs) + 16 */
DECL|macro|RTAS_FRAME_SIZE
mdefine_line|#define RTAS_FRAME_SIZE 480 /* STACK_FRAME_OVERHEAD + sizeof(struct pt_regs) + 16 */
DECL|macro|GPR0
mdefine_line|#define GPR0 112 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, gpr[0]) */
DECL|macro|GPR1
mdefine_line|#define GPR1 120 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, gpr[1]) */
DECL|macro|GPR2
mdefine_line|#define GPR2 128 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, gpr[2]) */
DECL|macro|GPR3
mdefine_line|#define GPR3 136 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, gpr[3]) */
DECL|macro|GPR4
mdefine_line|#define GPR4 144 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, gpr[4]) */
DECL|macro|GPR5
mdefine_line|#define GPR5 152 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, gpr[5]) */
DECL|macro|GPR6
mdefine_line|#define GPR6 160 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, gpr[6]) */
DECL|macro|GPR7
mdefine_line|#define GPR7 168 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, gpr[7]) */
DECL|macro|GPR8
mdefine_line|#define GPR8 176 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, gpr[8]) */
DECL|macro|GPR9
mdefine_line|#define GPR9 184 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, gpr[9]) */
DECL|macro|GPR20
mdefine_line|#define GPR20 272 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, gpr[20]) */
DECL|macro|GPR21
mdefine_line|#define GPR21 280 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, gpr[21]) */
DECL|macro|GPR22
mdefine_line|#define GPR22 288 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, gpr[22]) */
DECL|macro|GPR23
mdefine_line|#define GPR23 296 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, gpr[23]) */
DECL|macro|_NIP
mdefine_line|#define _NIP 368 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, nip) */
DECL|macro|_MSR
mdefine_line|#define _MSR 376 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, msr) */
DECL|macro|_CTR
mdefine_line|#define _CTR 392 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, ctr) */
DECL|macro|_LINK
mdefine_line|#define _LINK 400 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, link) */
DECL|macro|_CCR
mdefine_line|#define _CCR 416 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, ccr) */
DECL|macro|_XER
mdefine_line|#define _XER 408 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, xer) */
DECL|macro|_DAR
mdefine_line|#define _DAR 440 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, dar) */
DECL|macro|_DSISR
mdefine_line|#define _DSISR 448 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, dsisr) */
DECL|macro|ORIG_GPR3
mdefine_line|#define ORIG_GPR3 384 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, orig_gpr3) */
DECL|macro|RESULT
mdefine_line|#define RESULT 456 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, result) */
DECL|macro|TRAP
mdefine_line|#define TRAP 432 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, trap) */
DECL|macro|SOFTE
mdefine_line|#define SOFTE 424 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, softe) */
DECL|macro|_SRR0
mdefine_line|#define _SRR0 464 /* STACK_FRAME_OVERHEAD+sizeof(struct pt_regs) */
DECL|macro|_SRR1
mdefine_line|#define _SRR1 472 /* STACK_FRAME_OVERHEAD+sizeof(struct pt_regs)+8 */
DECL|macro|CLONE_VM
mdefine_line|#define CLONE_VM 256 /* CLONE_VM */
DECL|macro|CLONE_UNTRACED
mdefine_line|#define CLONE_UNTRACED 8388608 /* CLONE_UNTRACED */
DECL|macro|CPU_SPEC_ENTRY_SIZE
mdefine_line|#define CPU_SPEC_ENTRY_SIZE 56 /* sizeof(struct cpu_spec) */
DECL|macro|CPU_SPEC_PVR_MASK
mdefine_line|#define CPU_SPEC_PVR_MASK 0 /* offsetof(struct cpu_spec, pvr_mask) */
DECL|macro|CPU_SPEC_PVR_VALUE
mdefine_line|#define CPU_SPEC_PVR_VALUE 4 /* offsetof(struct cpu_spec, pvr_value) */
DECL|macro|CPU_SPEC_FEATURES
mdefine_line|#define CPU_SPEC_FEATURES 16 /* offsetof(struct cpu_spec, cpu_features) */
DECL|macro|CPU_SPEC_SETUP
mdefine_line|#define CPU_SPEC_SETUP 40 /* offsetof(struct cpu_spec, cpu_setup) */
macro_line|#endif
eof
