multiline_comment|/*&n; * arch/ppc/syslib/ppc4xx_pic.c&n; *&n; * Interrupt controller driver for PowerPC 4xx-based processors.&n; *&n; * Eugene Surovegin &lt;eugene.surovegin@zultys.com&gt; or &lt;ebs@ebshome.net&gt;&n; * Copyright (c) 2004 Zultys Technologies&n; *&n; * Based on original code by&n; *    Copyright (c) 1999 Grant Erickson &lt;grant@lcse.umn.edu&gt;&n; *    Armin Custer &lt;akuster@mvista.com&gt;&n; *&n; * This program is free software; you can redistribute  it and/or modify it&n; * under  the terms of  the GNU General  Public License as published by the&n; * Free Software Foundation;  either version 2 of the  License, or (at your&n; * option) any later version.&n;*/
macro_line|#include &lt;linux/config.h&gt;
macro_line|#include &lt;linux/init.h&gt;
macro_line|#include &lt;linux/sched.h&gt;
macro_line|#include &lt;linux/signal.h&gt;
macro_line|#include &lt;linux/stddef.h&gt;
macro_line|#include &lt;asm/processor.h&gt;
macro_line|#include &lt;asm/system.h&gt;
macro_line|#include &lt;asm/irq.h&gt;
macro_line|#include &lt;asm/ppc4xx_pic.h&gt;
multiline_comment|/* See comment in include/arch-ppc/ppc4xx_pic.h&n; * for more info about these two variables&n; */
r_extern
r_struct
id|ppc4xx_uic_settings
id|ppc4xx_core_uic_cfg
(braket
id|NR_UICS
)braket
id|__attribute__
(paren
(paren
id|weak
)paren
)paren
suffix:semicolon
r_extern
r_int
r_char
id|ppc4xx_uic_ext_irq_cfg
(braket
)braket
id|__attribute__
(paren
(paren
id|weak
)paren
)paren
suffix:semicolon
DECL|macro|IRQ_MASK_UIC0
mdefine_line|#define IRQ_MASK_UIC0(irq)&t;&t;(1 &lt;&lt; (31 - (irq)))
DECL|macro|IRQ_MASK_UICx
mdefine_line|#define IRQ_MASK_UICx(irq)&t;&t;(1 &lt;&lt; (31 - ((irq) &amp; 0x1f)))
DECL|macro|IRQ_MASK_UIC1
mdefine_line|#define IRQ_MASK_UIC1(irq)&t;&t;IRQ_MASK_UICx(irq)
DECL|macro|IRQ_MASK_UIC2
mdefine_line|#define IRQ_MASK_UIC2(irq)&t;&t;IRQ_MASK_UICx(irq)
DECL|macro|UIC_HANDLERS
mdefine_line|#define UIC_HANDLERS(n)&t;&t;&t;&t;&t;&t;&t;&bslash;&n;static void ppc4xx_uic##n##_enable(unsigned int irq)&t;&t;&t;&bslash;&n;{&t;&t;&t;&t;&t;&t;&t;&t;&t;&bslash;&n;&t;ppc_cached_irq_mask[n] |= IRQ_MASK_UIC##n(irq);&t;&t;&t;&bslash;&n;&t;mtdcr(DCRN_UIC_ER(UIC##n), ppc_cached_irq_mask[n]);&t;&t;&bslash;&n;}&t;&t;&t;&t;&t;&t;&t;&t;&t;&bslash;&n;&t;&t;&t;&t;&t;&t;&t;&t;&t;&bslash;&n;static void ppc4xx_uic##n##_disable(unsigned int irq)&t;&t;&t;&bslash;&n;{&t;&t;&t;&t;&t;&t;&t;&t;&t;&bslash;&n;&t;ppc_cached_irq_mask[n] &amp;= ~IRQ_MASK_UIC##n(irq);&t;&t;&bslash;&n;&t;mtdcr(DCRN_UIC_ER(UIC##n), ppc_cached_irq_mask[n]);&t;&t;&bslash;&n;}&t;&t;&t;&t;&t;&t;&t;&t;&t;&bslash;&n;&t;&t;&t;&t;&t;&t;&t;&t;&t;&bslash;&n;static void ppc4xx_uic##n##_ack(unsigned int irq)&t;&t;&t;&bslash;&n;{&t;&t;&t;&t;&t;&t;&t;&t;&t;&bslash;&n;&t;u32 mask = IRQ_MASK_UIC##n(irq);&t;&t;&t;&t;&bslash;&n;&t;ppc_cached_irq_mask[n] &amp;= ~mask;&t;&t;&t;&t;&bslash;&n;&t;mtdcr(DCRN_UIC_ER(UIC##n), ppc_cached_irq_mask[n]);&t;&t;&bslash;&n;&t;mtdcr(DCRN_UIC_SR(UIC##n), mask);&t;&t;&t;&t;&bslash;&n;&t;ACK_UIC##n##_PARENT&t;&t;&t;&t;&t;&t;&bslash;&n;}&t;&t;&t;&t;&t;&t;&t;&t;&t;&bslash;&n;&t;&t;&t;&t;&t;&t;&t;&t;&t;&bslash;&n;static void ppc4xx_uic##n##_end(unsigned int irq)&t;&t;&t;&bslash;&n;{&t;&t;&t;&t;&t;&t;&t;&t;&t;&bslash;&n;&t;unsigned int status = irq_desc[irq].status;&t;&t;&t;&bslash;&n;&t;u32 mask = IRQ_MASK_UIC##n(irq);&t;&t;&t;&t;&bslash;&n;&t;if (status &amp; IRQ_LEVEL) {&t;&t;&t;&t;&t;&bslash;&n;&t;&t;mtdcr(DCRN_UIC_SR(UIC##n), mask);&t;&t;&t;&bslash;&n;&t;&t;ACK_UIC##n##_PARENT&t;&t;&t;&t;&t;&bslash;&n;&t;}&t;&t;&t;&t;&t;&t;&t;&t;&bslash;&n;&t;if (!(status &amp; (IRQ_DISABLED | IRQ_INPROGRESS))) {&t;&t;&bslash;&n;&t;&t;ppc_cached_irq_mask[n] |= mask;&t;&t;&t;&t;&bslash;&n;&t;&t;mtdcr(DCRN_UIC_ER(UIC##n), ppc_cached_irq_mask[n]);&t;&bslash;&n;&t;}&t;&t;&t;&t;&t;&t;&t;&t;&bslash;&n;}
DECL|macro|DECLARE_UIC
mdefine_line|#define DECLARE_UIC(n)&t;&t;&t;&t;&t;&t;&t;&bslash;&n;{&t;&t;&t;&t;&t;&t;&t;&t;&t;&bslash;&n;&t;.typename &t;= &quot;UIC&quot;#n,&t;&t;&t;&t;&t;&bslash;&n;&t;.enable &t;= ppc4xx_uic##n##_enable,&t;&t;&t;&bslash;&n;&t;.disable &t;= ppc4xx_uic##n##_disable,&t;&t;&t;&bslash;&n;&t;.ack &t;&t;= ppc4xx_uic##n##_ack,&t;&t;&t;&t;&bslash;&n;&t;.end &t;&t;= ppc4xx_uic##n##_end,&t;&t;&t;&t;&bslash;&n;}&t;&t;&t;&t;&t;&t;&t;&t;&t;&bslash;&n;
macro_line|#if NR_UICS == 3
DECL|macro|ACK_UIC0_PARENT
mdefine_line|#define ACK_UIC0_PARENT&t;mtdcr(DCRN_UIC_SR(UICB), UICB_UIC0NC);
DECL|macro|ACK_UIC1_PARENT
mdefine_line|#define ACK_UIC1_PARENT&t;mtdcr(DCRN_UIC_SR(UICB), UICB_UIC1NC);
DECL|macro|ACK_UIC2_PARENT
mdefine_line|#define ACK_UIC2_PARENT&t;mtdcr(DCRN_UIC_SR(UICB), UICB_UIC2NC);
id|UIC_HANDLERS
c_func
(paren
l_int|0
)paren
suffix:semicolon
id|UIC_HANDLERS
c_func
(paren
l_int|1
)paren
suffix:semicolon
id|UIC_HANDLERS
c_func
(paren
l_int|2
)paren
suffix:semicolon
DECL|function|ppc4xx_pic_get_irq
r_static
r_int
id|ppc4xx_pic_get_irq
c_func
(paren
r_struct
id|pt_regs
op_star
id|regs
)paren
(brace
id|u32
id|uicb
op_assign
id|mfdcr
c_func
(paren
id|DCRN_UIC_MSR
c_func
(paren
id|UICB
)paren
)paren
suffix:semicolon
r_if
c_cond
(paren
id|uicb
op_amp
id|UICB_UIC0NC
)paren
r_return
l_int|32
op_minus
id|ffs
c_func
(paren
id|mfdcr
c_func
(paren
id|DCRN_UIC_MSR
c_func
(paren
id|UIC0
)paren
)paren
)paren
suffix:semicolon
r_else
r_if
c_cond
(paren
id|uicb
op_amp
id|UICB_UIC1NC
)paren
r_return
l_int|64
op_minus
id|ffs
c_func
(paren
id|mfdcr
c_func
(paren
id|DCRN_UIC_MSR
c_func
(paren
id|UIC1
)paren
)paren
)paren
suffix:semicolon
r_else
r_if
c_cond
(paren
id|uicb
op_amp
id|UICB_UIC2NC
)paren
r_return
l_int|96
op_minus
id|ffs
c_func
(paren
id|mfdcr
c_func
(paren
id|DCRN_UIC_MSR
c_func
(paren
id|UIC2
)paren
)paren
)paren
suffix:semicolon
r_else
r_return
op_minus
l_int|1
suffix:semicolon
)brace
DECL|function|ppc4xx_pic_impl_init
r_static
r_void
id|__init
id|ppc4xx_pic_impl_init
c_func
(paren
r_void
)paren
(brace
multiline_comment|/* Configure Base UIC */
id|mtdcr
c_func
(paren
id|DCRN_UIC_CR
c_func
(paren
id|UICB
)paren
comma
l_int|0
)paren
suffix:semicolon
id|mtdcr
c_func
(paren
id|DCRN_UIC_TR
c_func
(paren
id|UICB
)paren
comma
l_int|0
)paren
suffix:semicolon
id|mtdcr
c_func
(paren
id|DCRN_UIC_PR
c_func
(paren
id|UICB
)paren
comma
l_int|0xffffffff
)paren
suffix:semicolon
id|mtdcr
c_func
(paren
id|DCRN_UIC_SR
c_func
(paren
id|UICB
)paren
comma
l_int|0xffffffff
)paren
suffix:semicolon
id|mtdcr
c_func
(paren
id|DCRN_UIC_ER
c_func
(paren
id|UICB
)paren
comma
id|UICB_UIC0NC
op_or
id|UICB_UIC1NC
op_or
id|UICB_UIC2NC
)paren
suffix:semicolon
)brace
macro_line|#elif NR_UICS == 2
DECL|macro|ACK_UIC0_PARENT
mdefine_line|#define ACK_UIC0_PARENT
DECL|macro|ACK_UIC1_PARENT
mdefine_line|#define ACK_UIC1_PARENT&t;mtdcr(DCRN_UIC_SR(UIC0), UIC0_UIC1NC);
id|UIC_HANDLERS
c_func
(paren
l_int|0
)paren
suffix:semicolon
id|UIC_HANDLERS
c_func
(paren
l_int|1
)paren
suffix:semicolon
DECL|function|ppc4xx_pic_get_irq
r_static
r_int
id|ppc4xx_pic_get_irq
c_func
(paren
r_struct
id|pt_regs
op_star
id|regs
)paren
(brace
id|u32
id|uic0
op_assign
id|mfdcr
c_func
(paren
id|DCRN_UIC_MSR
c_func
(paren
id|UIC0
)paren
)paren
suffix:semicolon
r_if
c_cond
(paren
id|uic0
op_amp
id|UIC0_UIC1NC
)paren
r_return
l_int|64
op_minus
id|ffs
c_func
(paren
id|mfdcr
c_func
(paren
id|DCRN_UIC_MSR
c_func
(paren
id|UIC1
)paren
)paren
)paren
suffix:semicolon
r_else
r_return
id|uic0
ques
c_cond
l_int|32
op_minus
id|ffs
c_func
(paren
id|uic0
)paren
suffix:colon
op_minus
l_int|1
suffix:semicolon
)brace
DECL|function|ppc4xx_pic_impl_init
r_static
r_void
id|__init
id|ppc4xx_pic_impl_init
c_func
(paren
r_void
)paren
(brace
multiline_comment|/* Enable cascade interrupt in UIC0 */
id|ppc_cached_irq_mask
(braket
l_int|0
)braket
op_or_assign
id|UIC0_UIC1NC
suffix:semicolon
id|mtdcr
c_func
(paren
id|DCRN_UIC_SR
c_func
(paren
id|UIC0
)paren
comma
id|UIC0_UIC1NC
)paren
suffix:semicolon
id|mtdcr
c_func
(paren
id|DCRN_UIC_ER
c_func
(paren
id|UIC0
)paren
comma
id|ppc_cached_irq_mask
(braket
l_int|0
)braket
)paren
suffix:semicolon
)brace
macro_line|#elif NR_UICS == 1
DECL|macro|ACK_UIC0_PARENT
mdefine_line|#define ACK_UIC0_PARENT
id|UIC_HANDLERS
c_func
(paren
l_int|0
)paren
suffix:semicolon
DECL|function|ppc4xx_pic_get_irq
r_static
r_int
id|ppc4xx_pic_get_irq
c_func
(paren
r_struct
id|pt_regs
op_star
id|regs
)paren
(brace
id|u32
id|uic0
op_assign
id|mfdcr
c_func
(paren
id|DCRN_UIC_MSR
c_func
(paren
id|UIC0
)paren
)paren
suffix:semicolon
r_return
id|uic0
ques
c_cond
l_int|32
op_minus
id|ffs
c_func
(paren
id|uic0
)paren
suffix:colon
op_minus
l_int|1
suffix:semicolon
)brace
DECL|function|ppc4xx_pic_impl_init
r_static
r_inline
r_void
id|ppc4xx_pic_impl_init
c_func
(paren
r_void
)paren
(brace
)brace
macro_line|#endif
DECL|struct|ppc4xx_uic_impl
r_static
r_struct
id|ppc4xx_uic_impl
(brace
DECL|member|decl
r_struct
id|hw_interrupt_type
id|decl
suffix:semicolon
DECL|member|base
r_int
id|base
suffix:semicolon
multiline_comment|/* Base DCR number */
DECL|variable|__uic
)brace
id|__uic
(braket
)braket
op_assign
(brace
(brace
dot
id|decl
op_assign
id|DECLARE_UIC
c_func
(paren
l_int|0
)paren
comma
dot
id|base
op_assign
id|UIC0
)brace
comma
macro_line|#if NR_UICS &gt; 1
(brace
dot
id|decl
op_assign
id|DECLARE_UIC
c_func
(paren
l_int|1
)paren
comma
dot
id|base
op_assign
id|UIC1
)brace
comma
macro_line|#if NR_UICS &gt; 2
(brace
dot
id|decl
op_assign
id|DECLARE_UIC
c_func
(paren
l_int|2
)paren
comma
dot
id|base
op_assign
id|UIC2
)brace
comma
macro_line|#endif
macro_line|#endif
)brace
suffix:semicolon
DECL|function|is_level_sensitive
r_static
r_inline
r_int
id|is_level_sensitive
c_func
(paren
r_int
id|irq
)paren
(brace
id|u32
id|tr
op_assign
id|mfdcr
c_func
(paren
id|DCRN_UIC_TR
c_func
(paren
id|__uic
(braket
id|irq
op_rshift
l_int|5
)braket
dot
id|base
)paren
)paren
suffix:semicolon
r_return
(paren
id|tr
op_amp
id|IRQ_MASK_UICx
c_func
(paren
id|irq
)paren
)paren
op_eq
l_int|0
suffix:semicolon
)brace
DECL|function|ppc4xx_pic_init
r_void
id|__init
id|ppc4xx_pic_init
c_func
(paren
r_void
)paren
(brace
r_int
id|i
suffix:semicolon
r_int
r_char
op_star
id|eirqs
op_assign
id|ppc4xx_uic_ext_irq_cfg
suffix:semicolon
r_for
c_loop
(paren
id|i
op_assign
l_int|0
suffix:semicolon
id|i
OL
id|NR_UICS
suffix:semicolon
op_increment
id|i
)paren
(brace
r_int
id|base
op_assign
id|__uic
(braket
id|i
)braket
dot
id|base
suffix:semicolon
multiline_comment|/* Disable everything by default */
id|ppc_cached_irq_mask
(braket
id|i
)braket
op_assign
l_int|0
suffix:semicolon
id|mtdcr
c_func
(paren
id|DCRN_UIC_ER
c_func
(paren
id|base
)paren
comma
l_int|0
)paren
suffix:semicolon
multiline_comment|/* We don&squot;t use critical interrupts */
id|mtdcr
c_func
(paren
id|DCRN_UIC_CR
c_func
(paren
id|base
)paren
comma
l_int|0
)paren
suffix:semicolon
multiline_comment|/* Configure polarity and triggering */
r_if
c_cond
(paren
id|ppc4xx_core_uic_cfg
)paren
(brace
r_struct
id|ppc4xx_uic_settings
op_star
id|p
op_assign
id|ppc4xx_core_uic_cfg
op_plus
id|i
suffix:semicolon
id|u32
id|mask
op_assign
id|p-&gt;ext_irq_mask
suffix:semicolon
id|u32
id|pr
op_assign
id|mfdcr
c_func
(paren
id|DCRN_UIC_PR
c_func
(paren
id|base
)paren
)paren
op_amp
id|mask
suffix:semicolon
id|u32
id|tr
op_assign
id|mfdcr
c_func
(paren
id|DCRN_UIC_TR
c_func
(paren
id|base
)paren
)paren
op_amp
id|mask
suffix:semicolon
multiline_comment|/* &quot;Fixed&quot; interrupts (on-chip devices) */
id|pr
op_or_assign
id|p-&gt;polarity
op_amp
op_complement
id|mask
suffix:semicolon
id|tr
op_or_assign
id|p-&gt;triggering
op_amp
op_complement
id|mask
suffix:semicolon
multiline_comment|/* Merge external IRQs settings if board port&n;&t;&t;&t; * provided them&n;&t;&t;&t; */
r_if
c_cond
(paren
id|eirqs
op_logical_and
id|mask
)paren
(brace
id|pr
op_and_assign
op_complement
id|mask
suffix:semicolon
id|tr
op_and_assign
op_complement
id|mask
suffix:semicolon
r_while
c_loop
(paren
id|mask
)paren
(brace
multiline_comment|/* Extract current external IRQ mask */
id|u32
id|eirq_mask
op_assign
l_int|1
op_lshift
id|__ilog2
c_func
(paren
id|mask
)paren
suffix:semicolon
r_if
c_cond
(paren
op_logical_neg
(paren
op_star
id|eirqs
op_amp
id|IRQ_SENSE_LEVEL
)paren
)paren
id|tr
op_or_assign
id|eirq_mask
suffix:semicolon
r_if
c_cond
(paren
op_star
id|eirqs
op_amp
id|IRQ_POLARITY_POSITIVE
)paren
id|pr
op_or_assign
id|eirq_mask
suffix:semicolon
id|mask
op_and_assign
op_complement
id|eirq_mask
suffix:semicolon
op_increment
id|eirqs
suffix:semicolon
)brace
)brace
id|mtdcr
c_func
(paren
id|DCRN_UIC_PR
c_func
(paren
id|base
)paren
comma
id|pr
)paren
suffix:semicolon
id|mtdcr
c_func
(paren
id|DCRN_UIC_TR
c_func
(paren
id|base
)paren
comma
id|tr
)paren
suffix:semicolon
)brace
multiline_comment|/* ACK any pending interrupts to prevent false&n;&t;&t; * triggering after first enable&n;&t;&t; */
id|mtdcr
c_func
(paren
id|DCRN_UIC_SR
c_func
(paren
id|base
)paren
comma
l_int|0xffffffff
)paren
suffix:semicolon
)brace
multiline_comment|/* Perform optional implementation specific setup&n;&t; * (e.g. enable cascade interrupts for multi-UIC configurations)&n;&t; */
id|ppc4xx_pic_impl_init
c_func
(paren
)paren
suffix:semicolon
multiline_comment|/* Attach low-level handlers */
r_for
c_loop
(paren
id|i
op_assign
l_int|0
suffix:semicolon
id|i
OL
(paren
id|NR_UICS
op_lshift
l_int|5
)paren
suffix:semicolon
op_increment
id|i
)paren
(brace
id|irq_desc
(braket
id|i
)braket
dot
id|handler
op_assign
op_amp
id|__uic
(braket
id|i
op_rshift
l_int|5
)braket
dot
id|decl
suffix:semicolon
r_if
c_cond
(paren
id|is_level_sensitive
c_func
(paren
id|i
)paren
)paren
id|irq_desc
(braket
id|i
)braket
dot
id|status
op_or_assign
id|IRQ_LEVEL
suffix:semicolon
)brace
id|ppc_md.get_irq
op_assign
id|ppc4xx_pic_get_irq
suffix:semicolon
)brace
eof
