multiline_comment|/* Written 2000 by Andi Kleen */
multiline_comment|/* This program is never executed, just its assembly is examined for offsets &n;   (this trick is needed to get cross compiling right) */
multiline_comment|/* $Id: offset.c,v 1.13 2002/01/08 15:19:57 ak Exp $ */
DECL|macro|ASM_OFFSET_H
mdefine_line|#define ASM_OFFSET_H 1
macro_line|#ifndef __KERNEL__
DECL|macro|__KERNEL__
mdefine_line|#define __KERNEL__ 
macro_line|#endif
macro_line|#include &lt;linux/sched.h&gt; 
macro_line|#include &lt;linux/stddef.h&gt;
macro_line|#include &lt;linux/errno.h&gt; 
macro_line|#include &lt;asm/pda.h&gt;
macro_line|#include &lt;asm/hardirq.h&gt;
macro_line|#include &lt;asm/processor.h&gt;
macro_line|#include &lt;asm/segment.h&gt;
macro_line|#include &lt;asm/thread_info.h&gt;
DECL|macro|output
mdefine_line|#define output(x) asm volatile (&quot;--- &quot; x)
DECL|macro|outconst
mdefine_line|#define outconst(x,y) asm volatile (&quot;--- &quot; x : : &quot;i&quot; (y)) 
DECL|function|main
r_int
id|main
c_func
(paren
r_void
)paren
(brace
id|output
c_func
(paren
l_string|&quot;/* Auto generated by arch/../tools/offset.c at &quot;
id|__DATE__
l_string|&quot;. Do not edit. */&bslash;n&quot;
)paren
suffix:semicolon
id|output
c_func
(paren
l_string|&quot;#ifndef ASM_OFFSET_H&bslash;n&quot;
)paren
suffix:semicolon
id|output
c_func
(paren
l_string|&quot;#define ASM_OFFSET_H 1&bslash;n&quot;
)paren
suffix:semicolon
singleline_comment|// task struct entries needed by entry.S
DECL|macro|ENTRY
mdefine_line|#define ENTRY(entry) outconst(&quot;#define tsk_&quot; #entry &quot; %0&quot;, offsetof(struct task_struct, entry))
id|ENTRY
c_func
(paren
id|state
)paren
suffix:semicolon
id|ENTRY
c_func
(paren
id|flags
)paren
suffix:semicolon
id|ENTRY
c_func
(paren
id|thread
)paren
suffix:semicolon
DECL|macro|ENTRY
macro_line|#undef ENTRY
DECL|macro|ENTRY
mdefine_line|#define ENTRY(entry) outconst(&quot;#define threadinfo_&quot; #entry &quot; %0&quot;, offsetof(struct thread_info, entry))
id|ENTRY
c_func
(paren
id|flags
)paren
suffix:semicolon
id|ENTRY
c_func
(paren
id|addr_limit
)paren
suffix:semicolon
id|ENTRY
c_func
(paren
id|preempt_count
)paren
suffix:semicolon
DECL|macro|ENTRY
macro_line|#undef ENTRY
DECL|macro|ENTRY
mdefine_line|#define ENTRY(entry) outconst(&quot;#define pda_&quot; #entry &quot; %0&quot;, offsetof(struct x8664_pda, entry))
id|ENTRY
c_func
(paren
id|kernelstack
)paren
suffix:semicolon
id|ENTRY
c_func
(paren
id|oldrsp
)paren
suffix:semicolon
id|ENTRY
c_func
(paren
id|pcurrent
)paren
suffix:semicolon
id|ENTRY
c_func
(paren
id|irqrsp
)paren
suffix:semicolon
id|ENTRY
c_func
(paren
id|irqcount
)paren
suffix:semicolon
id|ENTRY
c_func
(paren
id|cpunumber
)paren
suffix:semicolon
id|ENTRY
c_func
(paren
id|irqstackptr
)paren
suffix:semicolon
id|ENTRY
c_func
(paren
id|__softirq_pending
)paren
suffix:semicolon
id|ENTRY
c_func
(paren
id|__local_irq_count
)paren
suffix:semicolon
id|ENTRY
c_func
(paren
id|__local_bh_count
)paren
suffix:semicolon
id|ENTRY
c_func
(paren
id|__ksoftirqd_task
)paren
suffix:semicolon
id|ENTRY
c_func
(paren
id|level4_pgt
)paren
suffix:semicolon
id|ENTRY
c_func
(paren
id|me
)paren
suffix:semicolon
DECL|macro|ENTRY
macro_line|#undef ENTRY
id|output
c_func
(paren
l_string|&quot;#ifdef __ASSEMBLY__&quot;
)paren
suffix:semicolon
DECL|macro|CONST
mdefine_line|#define CONST(t) outconst(&quot;#define &quot; #t &quot; %0&quot;, t)
id|CONST
c_func
(paren
id|TASK_SIZE
)paren
suffix:semicolon
id|CONST
c_func
(paren
id|SIGCHLD
)paren
suffix:semicolon
id|CONST
c_func
(paren
id|CLONE_VFORK
)paren
suffix:semicolon
id|CONST
c_func
(paren
id|CLONE_VM
)paren
suffix:semicolon
DECL|macro|CONST
macro_line|#undef CONST
id|output
c_func
(paren
l_string|&quot;#endif&quot;
)paren
suffix:semicolon
id|output
c_func
(paren
l_string|&quot;#endif&bslash;n&quot;
)paren
suffix:semicolon
r_return
l_int|0
suffix:semicolon
)brace
eof
