multiline_comment|/* include/version.h.  Generated by configure.  */
DECL|macro|CONFIG_SND_VERSION
mdefine_line|#define CONFIG_SND_VERSION &quot;0.9.6&quot;
DECL|macro|CONFIG_SND_DATE
mdefine_line|#define CONFIG_SND_DATE &quot; (Mon Jul 28 11:08:42 2003 UTC)&quot;
eof
