multiline_comment|/* include/version.h.  Generated by configure.  */
DECL|macro|CONFIG_SND_VERSION
mdefine_line|#define CONFIG_SND_VERSION &quot;1.0.8&quot;
DECL|macro|CONFIG_SND_DATE
mdefine_line|#define CONFIG_SND_DATE &quot; (Thu Jan 13 09:39:32 2005 UTC)&quot;
eof
