multiline_comment|/* include/version.h.  Generated by configure.  */
DECL|macro|CONFIG_SND_VERSION
mdefine_line|#define CONFIG_SND_VERSION &quot;0.9.4&quot;
DECL|macro|CONFIG_SND_DATE
mdefine_line|#define CONFIG_SND_DATE &quot; (Sat May 31 13:37:06 2003 UTC)&quot;
eof
