multiline_comment|/*&n; * Linux driver attachment glue for aic7770 based controllers.&n; *&n; * Copyright (c) 2000 Adaptec Inc.&n; * All rights reserved.&n; *&n; * Redistribution and use in source and binary forms, with or without&n; * modification, are permitted provided that the following conditions&n; * are met:&n; * 1. Redistributions of source code must retain the above copyright&n; *    notice, this list of conditions, and the following disclaimer,&n; *    without modification.&n; * 2. The name of the author may not be used to endorse or promote products&n; *    derived from this software without specific prior written permission.&n; *&n; * Alternatively, this software may be distributed under the terms of the&n; * GNU Public License (&quot;GPL&quot;).&n; *&n; * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS&squot;&squot; AND&n; * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE&n; * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE&n; * ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR&n; * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL&n; * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS&n; * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)&n; * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT&n; * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY&n; * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF&n; * SUCH DAMAGE.&n; *&n; * $Id: //depot/src/linux/drivers/scsi/aic7xxx/aic7770_linux.c#5 $&n; */
macro_line|#include &quot;aic7xxx_osm.h&quot;
DECL|macro|MINSLOT
mdefine_line|#define MINSLOT&t;&t;&t;1
DECL|macro|NUMSLOTS
mdefine_line|#define NUMSLOTS&t;&t;16
DECL|macro|IDOFFSET
mdefine_line|#define IDOFFSET&t;&t;0x80
r_int
DECL|function|aic7770_linux_probe
id|aic7770_linux_probe
c_func
(paren
id|Scsi_Host_Template
op_star
r_template
)paren
(brace
macro_line|#if defined(__i386__) || defined(__alpha__)
r_struct
id|aic7770_identity
op_star
id|entry
suffix:semicolon
r_struct
id|ahc_softc
op_star
id|ahc
suffix:semicolon
r_int
id|i
comma
id|slot
suffix:semicolon
r_int
id|eisaBase
suffix:semicolon
r_int
id|found
suffix:semicolon
r_if
c_cond
(paren
id|aic7xxx_no_probe
)paren
r_return
(paren
l_int|0
)paren
suffix:semicolon
id|eisaBase
op_assign
l_int|0x1000
op_plus
id|AHC_EISA_SLOT_OFFSET
suffix:semicolon
id|found
op_assign
l_int|0
suffix:semicolon
r_for
c_loop
(paren
id|slot
op_assign
l_int|1
suffix:semicolon
id|slot
OL
id|NUMSLOTS
suffix:semicolon
id|eisaBase
op_add_assign
l_int|0x1000
comma
id|slot
op_increment
)paren
(brace
r_uint32
id|eisa_id
suffix:semicolon
r_int
id|id_size
suffix:semicolon
r_if
c_cond
(paren
id|check_region
c_func
(paren
id|eisaBase
comma
id|AHC_EISA_IOSIZE
)paren
op_ne
l_int|0
)paren
r_continue
suffix:semicolon
id|eisa_id
op_assign
l_int|0
suffix:semicolon
id|id_size
op_assign
r_sizeof
(paren
id|eisa_id
)paren
suffix:semicolon
r_for
c_loop
(paren
id|i
op_assign
l_int|0
suffix:semicolon
id|i
OL
l_int|4
suffix:semicolon
id|i
op_increment
)paren
(brace
multiline_comment|/* VLcards require priming*/
id|outb
c_func
(paren
l_int|0x80
op_plus
id|i
comma
id|eisaBase
op_plus
id|IDOFFSET
)paren
suffix:semicolon
id|eisa_id
op_or_assign
id|inb
c_func
(paren
id|eisaBase
op_plus
id|IDOFFSET
op_plus
id|i
)paren
op_lshift
(paren
(paren
id|id_size
op_minus
id|i
op_minus
l_int|1
)paren
op_star
l_int|8
)paren
suffix:semicolon
)brace
r_if
c_cond
(paren
id|eisa_id
op_amp
l_int|0x80000000
)paren
r_continue
suffix:semicolon
multiline_comment|/* no EISA card in slot */
id|entry
op_assign
id|aic7770_find_device
c_func
(paren
id|eisa_id
)paren
suffix:semicolon
r_if
c_cond
(paren
id|entry
op_ne
l_int|NULL
)paren
(brace
r_char
id|buf
(braket
l_int|80
)braket
suffix:semicolon
r_char
op_star
id|name
suffix:semicolon
r_int
id|error
suffix:semicolon
multiline_comment|/*&n;&t;&t;&t; * Allocate a softc for this card and&n;&t;&t;&t; * set it up for attachment by our&n;&t;&t;&t; * common detect routine.&n;&t;&t;&t; */
id|sprintf
c_func
(paren
id|buf
comma
l_string|&quot;ahc_eisa:%d&quot;
comma
id|slot
)paren
suffix:semicolon
id|name
op_assign
id|malloc
c_func
(paren
id|strlen
c_func
(paren
id|buf
)paren
op_plus
l_int|1
comma
id|M_DEVBUF
comma
id|M_NOWAIT
)paren
suffix:semicolon
r_if
c_cond
(paren
id|name
op_eq
l_int|NULL
)paren
r_break
suffix:semicolon
id|strcpy
c_func
(paren
id|name
comma
id|buf
)paren
suffix:semicolon
id|ahc
op_assign
id|ahc_alloc
c_func
(paren
r_template
comma
id|name
)paren
suffix:semicolon
r_if
c_cond
(paren
id|ahc
op_eq
l_int|NULL
)paren
(brace
multiline_comment|/*&n;&t;&t;&t;&t; * If we can&squot;t allocate this one,&n;&t;&t;&t;&t; * chances are we won&squot;t be able to&n;&t;&t;&t;&t; * allocate future card structures.&n;&t;&t;&t;&t; */
r_break
suffix:semicolon
)brace
id|ahc-&gt;tag
op_assign
id|BUS_SPACE_PIO
suffix:semicolon
id|ahc-&gt;bsh.ioport
op_assign
id|eisaBase
suffix:semicolon
id|error
op_assign
id|aic7770_config
c_func
(paren
id|ahc
comma
id|entry
)paren
suffix:semicolon
r_if
c_cond
(paren
id|error
op_ne
l_int|0
)paren
(brace
id|ahc_free
c_func
(paren
id|ahc
)paren
suffix:semicolon
r_continue
suffix:semicolon
)brace
id|found
op_increment
suffix:semicolon
)brace
)brace
r_return
(paren
id|found
)paren
suffix:semicolon
macro_line|#else
r_return
(paren
l_int|0
)paren
suffix:semicolon
macro_line|#endif
)brace
r_int
DECL|function|aic7770_map_registers
id|aic7770_map_registers
c_func
(paren
r_struct
id|ahc_softc
op_star
id|ahc
)paren
(brace
multiline_comment|/*&n;&t; * Lock out other contenders for our i/o space.&n;&t; */
macro_line|#if LINUX_VERSION_CODE &lt; KERNEL_VERSION(2,4,0)
id|request_region
c_func
(paren
id|ahc-&gt;bsh.ioport
comma
id|AHC_EISA_IOSIZE
comma
l_string|&quot;aic7xxx&quot;
)paren
suffix:semicolon
macro_line|#else
r_if
c_cond
(paren
id|request_region
c_func
(paren
id|ahc-&gt;bsh.ioport
comma
id|AHC_EISA_IOSIZE
comma
l_string|&quot;aic7xxx&quot;
)paren
op_eq
l_int|0
)paren
r_return
(paren
id|ENOMEM
)paren
suffix:semicolon
macro_line|#endif
r_return
(paren
l_int|0
)paren
suffix:semicolon
)brace
r_int
DECL|function|aic7770_map_int
id|aic7770_map_int
c_func
(paren
r_struct
id|ahc_softc
op_star
id|ahc
comma
id|u_int
id|irq
comma
r_int
id|shared
)paren
(brace
r_int
id|error
suffix:semicolon
r_if
c_cond
(paren
id|shared
)paren
id|shared
op_assign
id|SA_SHIRQ
suffix:semicolon
id|ahc-&gt;platform_data-&gt;irq
op_assign
id|irq
suffix:semicolon
id|error
op_assign
id|request_irq
c_func
(paren
id|ahc-&gt;platform_data-&gt;irq
comma
id|aic7xxx_isr
comma
id|SA_INTERRUPT
op_or
id|shared
comma
l_string|&quot;aic7xxx&quot;
comma
id|ahc
)paren
suffix:semicolon
r_if
c_cond
(paren
id|error
OL
l_int|0
)paren
id|error
op_assign
id|request_irq
c_func
(paren
id|ahc-&gt;platform_data-&gt;irq
comma
id|aic7xxx_isr
comma
id|shared
comma
l_string|&quot;aic7xxx&quot;
comma
id|ahc
)paren
suffix:semicolon
r_return
(paren
op_minus
id|error
)paren
suffix:semicolon
)brace
eof
