macro_line|#ifndef __ASM_OFFSETS_H__
DECL|macro|__ASM_OFFSETS_H__
mdefine_line|#define __ASM_OFFSETS_H__
multiline_comment|/*&n; * DO NOT MODIFY.&n; *&n; * This file was generated by arch/m68knommu/Makefile&n; *&n; */
DECL|macro|TASK_STATE
mdefine_line|#define TASK_STATE 0 /* offsetof(struct task_struct, state) */
DECL|macro|TASK_FLAGS
mdefine_line|#define TASK_FLAGS 12 /* offsetof(struct task_struct, flags) */
DECL|macro|TASK_PTRACE
mdefine_line|#define TASK_PTRACE 16 /* offsetof(struct task_struct, ptrace) */
DECL|macro|TASK_BLOCKED
mdefine_line|#define TASK_BLOCKED 922 /* offsetof(struct task_struct, blocked) */
DECL|macro|TASK_THREAD
mdefine_line|#define TASK_THREAD 772 /* offsetof(struct task_struct, thread) */
DECL|macro|TASK_THREAD_INFO
mdefine_line|#define TASK_THREAD_INFO 4 /* offsetof(struct task_struct, thread_info) */
DECL|macro|TASK_MM
mdefine_line|#define TASK_MM 92 /* offsetof(struct task_struct, mm) */
DECL|macro|TASK_ACTIVE_MM
mdefine_line|#define TASK_ACTIVE_MM 96 /* offsetof(struct task_struct, active_mm) */
DECL|macro|CPUSTAT_SOFTIRQ_PENDING
mdefine_line|#define CPUSTAT_SOFTIRQ_PENDING 0 /* offsetof(irq_cpustat_t, __softirq_pending) */
DECL|macro|THREAD_KSP
mdefine_line|#define THREAD_KSP 0 /* offsetof(struct thread_struct, ksp) */
DECL|macro|THREAD_USP
mdefine_line|#define THREAD_USP 4 /* offsetof(struct thread_struct, usp) */
DECL|macro|THREAD_SR
mdefine_line|#define THREAD_SR 8 /* offsetof(struct thread_struct, sr) */
DECL|macro|THREAD_FS
mdefine_line|#define THREAD_FS 10 /* offsetof(struct thread_struct, fs) */
DECL|macro|THREAD_CRP
mdefine_line|#define THREAD_CRP 12 /* offsetof(struct thread_struct, crp) */
DECL|macro|THREAD_ESP0
mdefine_line|#define THREAD_ESP0 20 /* offsetof(struct thread_struct, esp0) */
DECL|macro|THREAD_FPREG
mdefine_line|#define THREAD_FPREG 24 /* offsetof(struct thread_struct, fp) */
DECL|macro|THREAD_FPCNTL
mdefine_line|#define THREAD_FPCNTL 120 /* offsetof(struct thread_struct, fpcntl) */
DECL|macro|THREAD_FPSTATE
mdefine_line|#define THREAD_FPSTATE 132 /* offsetof(struct thread_struct, fpstate) */
DECL|macro|PT_D0
mdefine_line|#define PT_D0 32 /* offsetof(struct pt_regs, d0) */
DECL|macro|PT_ORIG_D0
mdefine_line|#define PT_ORIG_D0 36 /* offsetof(struct pt_regs, orig_d0) */
DECL|macro|PT_D1
mdefine_line|#define PT_D1 0 /* offsetof(struct pt_regs, d1) */
DECL|macro|PT_D2
mdefine_line|#define PT_D2 4 /* offsetof(struct pt_regs, d2) */
DECL|macro|PT_D3
mdefine_line|#define PT_D3 8 /* offsetof(struct pt_regs, d3) */
DECL|macro|PT_D4
mdefine_line|#define PT_D4 12 /* offsetof(struct pt_regs, d4) */
DECL|macro|PT_D5
mdefine_line|#define PT_D5 16 /* offsetof(struct pt_regs, d5) */
DECL|macro|PT_A0
mdefine_line|#define PT_A0 20 /* offsetof(struct pt_regs, a0) */
DECL|macro|PT_A1
mdefine_line|#define PT_A1 24 /* offsetof(struct pt_regs, a1) */
DECL|macro|PT_A2
mdefine_line|#define PT_A2 28 /* offsetof(struct pt_regs, a2) */
DECL|macro|PT_PC
mdefine_line|#define PT_PC 48 /* offsetof(struct pt_regs, pc) */
DECL|macro|PT_SR
mdefine_line|#define PT_SR 46 /* offsetof(struct pt_regs, sr) */
DECL|macro|PT_VECTOR
mdefine_line|#define PT_VECTOR 52 /* offsetof(struct pt_regs, pc) + 4 */
DECL|macro|STAT_IRQ
mdefine_line|#define STAT_IRQ 5140 /* offsetof(struct kernel_stat, irqs) */
DECL|macro|SIGSEGV
mdefine_line|#define SIGSEGV 11 /* SIGSEGV */
DECL|macro|SEGV_MAPERR
mdefine_line|#define SEGV_MAPERR 196609 /* SEGV_MAPERR */
DECL|macro|SIGTRAP
mdefine_line|#define SIGTRAP 5 /* SIGTRAP */
DECL|macro|TRAP_TRACE
mdefine_line|#define TRAP_TRACE 196610 /* TRAP_TRACE */
DECL|macro|PT_PTRACED
mdefine_line|#define PT_PTRACED 1 /* PT_PTRACED */
DECL|macro|PT_DTRACE
mdefine_line|#define PT_DTRACE 2 /* PT_DTRACE */
macro_line|#endif
eof
