multiline_comment|/*&n; *&t;Generic address resultion entity&n; *&n; *&t;Authors:&n; *&t;net_random Alan Cox&n; *&t;net_ratelimit Andy Kleen&n; *&n; *&t;Created by Alexey Kuznetsov &lt;kuznet@ms2.inr.ac.ru&gt;&n; *&n; *&t;This program is free software; you can redistribute it and/or&n; *      modify it under the terms of the GNU General Public License&n; *      as published by the Free Software Foundation; either version&n; *      2 of the License, or (at your option) any later version.&n; */
macro_line|#include &lt;linux/module.h&gt;
macro_line|#include &lt;linux/jiffies.h&gt;
macro_line|#include &lt;linux/kernel.h&gt;
macro_line|#include &lt;linux/mm.h&gt;
macro_line|#include &lt;linux/string.h&gt;
macro_line|#include &lt;linux/types.h&gt;
macro_line|#include &lt;linux/random.h&gt;
macro_line|#include &lt;linux/percpu.h&gt;
macro_line|#include &lt;linux/init.h&gt;
macro_line|#include &lt;asm/system.h&gt;
macro_line|#include &lt;asm/uaccess.h&gt;
multiline_comment|/*&n;  This is a maximally equidistributed combined Tausworthe generator&n;  based on code from GNU Scientific Library 1.5 (30 Jun 2004)&n;&n;   x_n = (s1_n ^ s2_n ^ s3_n) &n;&n;   s1_{n+1} = (((s1_n &amp; 4294967294) &lt;&lt;12) ^ (((s1_n &lt;&lt;13) ^ s1_n) &gt;&gt;19))&n;   s2_{n+1} = (((s2_n &amp; 4294967288) &lt;&lt; 4) ^ (((s2_n &lt;&lt; 2) ^ s2_n) &gt;&gt;25))&n;   s3_{n+1} = (((s3_n &amp; 4294967280) &lt;&lt;17) ^ (((s3_n &lt;&lt; 3) ^ s3_n) &gt;&gt;11))&n;&n;   The period of this generator is about 2^88.&n;&n;   From: P. L&squot;Ecuyer, &quot;Maximally Equidistributed Combined Tausworthe&n;   Generators&quot;, Mathematics of Computation, 65, 213 (1996), 203--213.&n;&n;   This is available on the net from L&squot;Ecuyer&squot;s home page,&n;&n;   http://www.iro.umontreal.ca/~lecuyer/myftp/papers/tausme.ps&n;   ftp://ftp.iro.umontreal.ca/pub/simulation/lecuyer/papers/tausme.ps &n;&n;   There is an erratum in the paper &quot;Tables of Maximally&n;   Equidistributed Combined LFSR Generators&quot;, Mathematics of&n;   Computation, 68, 225 (1999), 261--269:&n;   http://www.iro.umontreal.ca/~lecuyer/myftp/papers/tausme2.ps&n;&n;        ... the k_j most significant bits of z_j must be non-&n;        zero, for each j. (Note: this restriction also applies to the &n;        computer code given in [4], but was mistakenly not mentioned in&n;        that paper.)&n;   &n;   This affects the seeding procedure by imposing the requirement&n;   s1 &gt; 1, s2 &gt; 7, s3 &gt; 15.&n;&n;*/
DECL|struct|nrnd_state
r_struct
id|nrnd_state
(brace
DECL|member|s1
DECL|member|s2
DECL|member|s3
id|u32
id|s1
comma
id|s2
comma
id|s3
suffix:semicolon
)brace
suffix:semicolon
r_static
id|DEFINE_PER_CPU
c_func
(paren
r_struct
id|nrnd_state
comma
id|net_rand_state
)paren
suffix:semicolon
DECL|function|__net_random
r_static
id|u32
id|__net_random
c_func
(paren
r_struct
id|nrnd_state
op_star
id|state
)paren
(brace
DECL|macro|TAUSWORTHE
mdefine_line|#define TAUSWORTHE(s,a,b,c,d) ((s&amp;c)&lt;&lt;d) ^ (((s &lt;&lt;a) ^ s)&gt;&gt;b)
id|state-&gt;s1
op_assign
id|TAUSWORTHE
c_func
(paren
id|state-&gt;s1
comma
l_int|13
comma
l_int|19
comma
l_int|4294967294UL
comma
l_int|12
)paren
suffix:semicolon
id|state-&gt;s2
op_assign
id|TAUSWORTHE
c_func
(paren
id|state-&gt;s2
comma
l_int|2
comma
l_int|25
comma
l_int|4294967288UL
comma
l_int|4
)paren
suffix:semicolon
id|state-&gt;s3
op_assign
id|TAUSWORTHE
c_func
(paren
id|state-&gt;s3
comma
l_int|3
comma
l_int|11
comma
l_int|4294967280UL
comma
l_int|17
)paren
suffix:semicolon
r_return
(paren
id|state-&gt;s1
op_xor
id|state-&gt;s2
op_xor
id|state-&gt;s3
)paren
suffix:semicolon
)brace
DECL|function|__net_srandom
r_static
r_void
id|__net_srandom
c_func
(paren
r_struct
id|nrnd_state
op_star
id|state
comma
r_int
r_int
id|s
)paren
(brace
r_if
c_cond
(paren
id|s
op_eq
l_int|0
)paren
id|s
op_assign
l_int|1
suffix:semicolon
multiline_comment|/* default seed is 1 */
DECL|macro|LCG
mdefine_line|#define LCG(n) (69069 * n)
id|state-&gt;s1
op_assign
id|LCG
c_func
(paren
id|s
)paren
suffix:semicolon
id|state-&gt;s2
op_assign
id|LCG
c_func
(paren
id|state-&gt;s1
)paren
suffix:semicolon
id|state-&gt;s3
op_assign
id|LCG
c_func
(paren
id|state-&gt;s2
)paren
suffix:semicolon
multiline_comment|/* &quot;warm it up&quot; */
id|__net_random
c_func
(paren
id|state
)paren
suffix:semicolon
id|__net_random
c_func
(paren
id|state
)paren
suffix:semicolon
id|__net_random
c_func
(paren
id|state
)paren
suffix:semicolon
id|__net_random
c_func
(paren
id|state
)paren
suffix:semicolon
id|__net_random
c_func
(paren
id|state
)paren
suffix:semicolon
id|__net_random
c_func
(paren
id|state
)paren
suffix:semicolon
)brace
DECL|function|net_random
r_int
r_int
id|net_random
c_func
(paren
r_void
)paren
(brace
r_int
r_int
id|r
suffix:semicolon
r_struct
id|nrnd_state
op_star
id|state
op_assign
op_amp
id|get_cpu_var
c_func
(paren
id|net_rand_state
)paren
suffix:semicolon
id|r
op_assign
id|__net_random
c_func
(paren
id|state
)paren
suffix:semicolon
id|put_cpu_var
c_func
(paren
id|state
)paren
suffix:semicolon
r_return
id|r
suffix:semicolon
)brace
DECL|function|net_srandom
r_void
id|net_srandom
c_func
(paren
r_int
r_int
id|entropy
)paren
(brace
r_struct
id|nrnd_state
op_star
id|state
op_assign
op_amp
id|get_cpu_var
c_func
(paren
id|net_rand_state
)paren
suffix:semicolon
id|__net_srandom
c_func
(paren
id|state
comma
id|state-&gt;s1
op_xor
id|entropy
)paren
suffix:semicolon
id|put_cpu_var
c_func
(paren
id|state
)paren
suffix:semicolon
)brace
DECL|function|net_random_init
r_void
id|__init
id|net_random_init
c_func
(paren
r_void
)paren
(brace
r_int
id|i
suffix:semicolon
r_for
c_loop
(paren
id|i
op_assign
l_int|0
suffix:semicolon
id|i
OL
id|NR_CPUS
suffix:semicolon
id|i
op_increment
)paren
(brace
r_struct
id|nrnd_state
op_star
id|state
op_assign
op_amp
id|per_cpu
c_func
(paren
id|net_rand_state
comma
id|i
)paren
suffix:semicolon
id|__net_srandom
c_func
(paren
id|state
comma
id|i
op_plus
id|jiffies
)paren
suffix:semicolon
)brace
)brace
DECL|function|net_random_reseed
r_static
r_int
id|net_random_reseed
c_func
(paren
r_void
)paren
(brace
r_int
id|i
suffix:semicolon
r_int
r_int
id|seed
(braket
id|NR_CPUS
)braket
suffix:semicolon
id|get_random_bytes
c_func
(paren
id|seed
comma
r_sizeof
(paren
id|seed
)paren
)paren
suffix:semicolon
r_for
c_loop
(paren
id|i
op_assign
l_int|0
suffix:semicolon
id|i
OL
id|NR_CPUS
suffix:semicolon
id|i
op_increment
)paren
(brace
r_struct
id|nrnd_state
op_star
id|state
op_assign
op_amp
id|per_cpu
c_func
(paren
id|net_rand_state
comma
id|i
)paren
suffix:semicolon
id|__net_srandom
c_func
(paren
id|state
comma
id|seed
(braket
id|i
)braket
)paren
suffix:semicolon
)brace
r_return
l_int|0
suffix:semicolon
)brace
DECL|variable|net_random_reseed
id|late_initcall
c_func
(paren
id|net_random_reseed
)paren
suffix:semicolon
DECL|variable|net_msg_cost
r_int
id|net_msg_cost
op_assign
l_int|5
op_star
id|HZ
suffix:semicolon
DECL|variable|net_msg_burst
r_int
id|net_msg_burst
op_assign
l_int|10
suffix:semicolon
multiline_comment|/* &n; * All net warning printk()s should be guarded by this function.&n; */
DECL|function|net_ratelimit
r_int
id|net_ratelimit
c_func
(paren
r_void
)paren
(brace
r_return
id|__printk_ratelimit
c_func
(paren
id|net_msg_cost
comma
id|net_msg_burst
)paren
suffix:semicolon
)brace
DECL|variable|net_random
id|EXPORT_SYMBOL
c_func
(paren
id|net_random
)paren
suffix:semicolon
DECL|variable|net_ratelimit
id|EXPORT_SYMBOL
c_func
(paren
id|net_ratelimit
)paren
suffix:semicolon
DECL|variable|net_srandom
id|EXPORT_SYMBOL
c_func
(paren
id|net_srandom
)paren
suffix:semicolon
eof
