multiline_comment|/*&n; * This file implement the Wireless Extensions APIs.&n; *&n; * Authors :&t;Jean Tourrilhes - HPL - &lt;jt@hpl.hp.com&gt;&n; * Copyright (c) 1997-2001 Jean Tourrilhes, All Rights Reserved.&n; *&n; * (As all part of the Linux kernel, this file is GPL)&n; */
multiline_comment|/************************** DOCUMENTATION **************************/
multiline_comment|/*&n; * API definition :&n; * --------------&n; * See &lt;linux/wireless.h&gt; for details of the APIs and the rest.&n; *&n; * History :&n; * -------&n; *&n; * v1 - 5.12.01 - Jean II&n; *&t;o Created this file.&n; *&n; * v2 - 13.12.01 - Jean II&n; *&t;o Move /proc/net/wireless stuff from net/core/dev.c to here&n; *&t;o Make Wireless Extension IOCTLs go through here&n; *&t;o Added iw_handler handling ;-)&n; *&t;o Added standard ioctl description&n; *&t;o Initial dumb commit strategy based on orinoco.c&n; */
multiline_comment|/***************************** INCLUDES *****************************/
macro_line|#include &lt;asm/uaccess.h&gt;&t;&t;/* copy_to_user() */
macro_line|#include &lt;linux/config.h&gt;&t;&t;/* Not needed ??? */
macro_line|#include &lt;linux/types.h&gt;&t;&t;/* off_t */
macro_line|#include &lt;linux/netdevice.h&gt;&t;&t;/* struct ifreq, dev_get_by_name() */
macro_line|#include &lt;linux/wireless.h&gt;&t;&t;/* Pretty obvious */
macro_line|#include &lt;net/iw_handler.h&gt;&t;&t;/* New driver API */
multiline_comment|/**************************** CONSTANTS ****************************/
multiline_comment|/* This will be turned on later on... */
DECL|macro|WE_STRICT_WRITE
macro_line|#undef WE_STRICT_WRITE&t;&t;/* Check write buffer size */
multiline_comment|/* Debuging stuff */
DECL|macro|WE_IOCTL_DEBUG
macro_line|#undef WE_IOCTL_DEBUG&t;&t;/* Debug IOCTL API */
multiline_comment|/************************* GLOBAL VARIABLES *************************/
multiline_comment|/*&n; * You should not use global variables, because or re-entrancy.&n; * On our case, it&squot;s only const, so it&squot;s OK...&n; */
DECL|variable|standard_ioctl
r_static
r_const
r_struct
id|iw_ioctl_description
id|standard_ioctl
(braket
)braket
op_assign
(brace
multiline_comment|/* SIOCSIWCOMMIT (internal) */
(brace
id|IW_HEADER_TYPE_NULL
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
)brace
comma
multiline_comment|/* SIOCGIWNAME */
(brace
id|IW_HEADER_TYPE_CHAR
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
id|IW_DESCR_FLAG_DUMP
)brace
comma
multiline_comment|/* SIOCSIWNWID */
(brace
id|IW_HEADER_TYPE_PARAM
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
id|IW_DESCR_FLAG_EVENT
)brace
comma
multiline_comment|/* SIOCGIWNWID */
(brace
id|IW_HEADER_TYPE_PARAM
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
id|IW_DESCR_FLAG_DUMP
)brace
comma
multiline_comment|/* SIOCSIWFREQ */
(brace
id|IW_HEADER_TYPE_FREQ
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
id|IW_DESCR_FLAG_EVENT
)brace
comma
multiline_comment|/* SIOCGIWFREQ */
(brace
id|IW_HEADER_TYPE_FREQ
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
id|IW_DESCR_FLAG_DUMP
)brace
comma
multiline_comment|/* SIOCSIWMODE */
(brace
id|IW_HEADER_TYPE_UINT
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
id|IW_DESCR_FLAG_EVENT
)brace
comma
multiline_comment|/* SIOCGIWMODE */
(brace
id|IW_HEADER_TYPE_UINT
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
id|IW_DESCR_FLAG_DUMP
)brace
comma
multiline_comment|/* SIOCSIWSENS */
(brace
id|IW_HEADER_TYPE_PARAM
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
)brace
comma
multiline_comment|/* SIOCGIWSENS */
(brace
id|IW_HEADER_TYPE_PARAM
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
)brace
comma
multiline_comment|/* SIOCSIWRANGE */
(brace
id|IW_HEADER_TYPE_NULL
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
)brace
comma
multiline_comment|/* SIOCGIWRANGE */
(brace
id|IW_HEADER_TYPE_POINT
comma
l_int|0
comma
l_int|1
comma
l_int|0
comma
r_sizeof
(paren
r_struct
id|iw_range
)paren
comma
id|IW_DESCR_FLAG_DUMP
)brace
comma
multiline_comment|/* SIOCSIWPRIV */
(brace
id|IW_HEADER_TYPE_NULL
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
)brace
comma
multiline_comment|/* SIOCGIWPRIV (handled directly by us) */
(brace
id|IW_HEADER_TYPE_NULL
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
)brace
comma
multiline_comment|/* SIOCSIWSTATS */
(brace
id|IW_HEADER_TYPE_NULL
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
)brace
comma
multiline_comment|/* SIOCGIWSTATS (handled directly by us) */
(brace
id|IW_HEADER_TYPE_NULL
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
id|IW_DESCR_FLAG_DUMP
)brace
comma
multiline_comment|/* SIOCSIWSPY */
(brace
id|IW_HEADER_TYPE_POINT
comma
l_int|0
comma
r_sizeof
(paren
r_struct
id|sockaddr
)paren
comma
l_int|0
comma
id|IW_MAX_SPY
comma
l_int|0
)brace
comma
multiline_comment|/* SIOCGIWSPY */
(brace
id|IW_HEADER_TYPE_POINT
comma
l_int|0
comma
(paren
r_sizeof
(paren
r_struct
id|sockaddr
)paren
op_plus
r_sizeof
(paren
r_struct
id|iw_quality
)paren
)paren
comma
l_int|0
comma
id|IW_MAX_SPY
comma
l_int|0
)brace
comma
multiline_comment|/* -- hole -- */
(brace
id|IW_HEADER_TYPE_NULL
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
)brace
comma
multiline_comment|/* -- hole -- */
(brace
id|IW_HEADER_TYPE_NULL
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
)brace
comma
multiline_comment|/* SIOCSIWAP */
(brace
id|IW_HEADER_TYPE_ADDR
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
)brace
comma
multiline_comment|/* SIOCGIWAP */
(brace
id|IW_HEADER_TYPE_ADDR
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
id|IW_DESCR_FLAG_DUMP
)brace
comma
multiline_comment|/* -- hole -- */
(brace
id|IW_HEADER_TYPE_NULL
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
)brace
comma
multiline_comment|/* SIOCGIWAPLIST */
(brace
id|IW_HEADER_TYPE_POINT
comma
l_int|0
comma
(paren
r_sizeof
(paren
r_struct
id|sockaddr
)paren
op_plus
r_sizeof
(paren
r_struct
id|iw_quality
)paren
)paren
comma
l_int|0
comma
id|IW_MAX_AP
comma
l_int|0
)brace
comma
multiline_comment|/* -- hole -- */
(brace
id|IW_HEADER_TYPE_NULL
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
)brace
comma
multiline_comment|/* -- hole -- */
(brace
id|IW_HEADER_TYPE_NULL
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
)brace
comma
multiline_comment|/* SIOCSIWESSID */
(brace
id|IW_HEADER_TYPE_POINT
comma
l_int|0
comma
l_int|1
comma
l_int|0
comma
id|IW_ESSID_MAX_SIZE
comma
id|IW_DESCR_FLAG_EVENT
)brace
comma
multiline_comment|/* SIOCGIWESSID */
(brace
id|IW_HEADER_TYPE_POINT
comma
l_int|0
comma
l_int|1
comma
l_int|0
comma
id|IW_ESSID_MAX_SIZE
comma
id|IW_DESCR_FLAG_DUMP
)brace
comma
multiline_comment|/* SIOCSIWNICKN */
(brace
id|IW_HEADER_TYPE_POINT
comma
l_int|0
comma
l_int|1
comma
l_int|0
comma
id|IW_ESSID_MAX_SIZE
comma
l_int|0
)brace
comma
multiline_comment|/* SIOCGIWNICKN */
(brace
id|IW_HEADER_TYPE_POINT
comma
l_int|0
comma
l_int|1
comma
l_int|0
comma
id|IW_ESSID_MAX_SIZE
comma
l_int|0
)brace
comma
multiline_comment|/* -- hole -- */
(brace
id|IW_HEADER_TYPE_NULL
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
)brace
comma
multiline_comment|/* -- hole -- */
(brace
id|IW_HEADER_TYPE_NULL
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
)brace
comma
multiline_comment|/* SIOCSIWRATE */
(brace
id|IW_HEADER_TYPE_PARAM
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
)brace
comma
multiline_comment|/* SIOCGIWRATE */
(brace
id|IW_HEADER_TYPE_PARAM
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
)brace
comma
multiline_comment|/* SIOCSIWRTS */
(brace
id|IW_HEADER_TYPE_PARAM
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
)brace
comma
multiline_comment|/* SIOCGIWRTS */
(brace
id|IW_HEADER_TYPE_PARAM
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
)brace
comma
multiline_comment|/* SIOCSIWFRAG */
(brace
id|IW_HEADER_TYPE_PARAM
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
)brace
comma
multiline_comment|/* SIOCGIWFRAG */
(brace
id|IW_HEADER_TYPE_PARAM
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
)brace
comma
multiline_comment|/* SIOCSIWTXPOW */
(brace
id|IW_HEADER_TYPE_PARAM
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
)brace
comma
multiline_comment|/* SIOCGIWTXPOW */
(brace
id|IW_HEADER_TYPE_PARAM
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
)brace
comma
multiline_comment|/* SIOCSIWRETRY */
(brace
id|IW_HEADER_TYPE_PARAM
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
)brace
comma
multiline_comment|/* SIOCGIWRETRY */
(brace
id|IW_HEADER_TYPE_PARAM
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
)brace
comma
multiline_comment|/* SIOCSIWENCODE */
(brace
id|IW_HEADER_TYPE_POINT
comma
l_int|4
comma
l_int|1
comma
l_int|0
comma
id|IW_ENCODING_TOKEN_MAX
comma
id|IW_DESCR_FLAG_EVENT
op_or
id|IW_DESCR_FLAG_RESTRICT
)brace
comma
multiline_comment|/* SIOCGIWENCODE */
(brace
id|IW_HEADER_TYPE_POINT
comma
l_int|0
comma
l_int|1
comma
l_int|0
comma
id|IW_ENCODING_TOKEN_MAX
comma
id|IW_DESCR_FLAG_DUMP
op_or
id|IW_DESCR_FLAG_RESTRICT
)brace
comma
multiline_comment|/* SIOCSIWPOWER */
(brace
id|IW_HEADER_TYPE_PARAM
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
)brace
comma
multiline_comment|/* SIOCGIWPOWER */
(brace
id|IW_HEADER_TYPE_PARAM
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
comma
l_int|0
)brace
comma
)brace
suffix:semicolon
multiline_comment|/* Size (in bytes) of the various private data types */
DECL|variable|priv_type_size
r_char
id|priv_type_size
(braket
)braket
op_assign
(brace
l_int|0
comma
l_int|1
comma
l_int|1
comma
l_int|0
comma
l_int|4
comma
l_int|4
comma
l_int|0
comma
l_int|0
)brace
suffix:semicolon
multiline_comment|/************************ COMMON SUBROUTINES ************************/
multiline_comment|/*&n; * Stuff that may be used in various place or doesn&squot;t fit in one&n; * of the section below.&n; */
multiline_comment|/* ---------------------------------------------------------------- */
multiline_comment|/*&n; * Return the driver handler associated with a specific Wireless Extension.&n; * Called from various place, so make sure it remains efficient.&n; */
DECL|function|get_handler
r_static
r_inline
id|iw_handler
id|get_handler
c_func
(paren
r_struct
id|net_device
op_star
id|dev
comma
r_int
r_int
id|cmd
)paren
(brace
r_int
r_int
id|index
suffix:semicolon
multiline_comment|/* MUST be unsigned */
multiline_comment|/* Check if we have some wireless handlers defined */
r_if
c_cond
(paren
id|dev-&gt;wireless_handlers
op_eq
l_int|NULL
)paren
(brace
r_return
l_int|NULL
suffix:semicolon
)brace
multiline_comment|/* Try as a standard command */
id|index
op_assign
id|cmd
op_minus
id|SIOCIWFIRST
suffix:semicolon
r_if
c_cond
(paren
id|index
OL
id|dev-&gt;wireless_handlers-&gt;num_standard
)paren
(brace
r_return
id|dev-&gt;wireless_handlers-&gt;standard
(braket
id|index
)braket
suffix:semicolon
)brace
multiline_comment|/* Try as a private command */
id|index
op_assign
id|cmd
op_minus
id|SIOCIWFIRSTPRIV
suffix:semicolon
r_if
c_cond
(paren
id|index
OL
id|dev-&gt;wireless_handlers-&gt;num_private
)paren
(brace
r_return
id|dev-&gt;wireless_handlers
op_member_access_from_pointer
r_private
(braket
id|index
)braket
suffix:semicolon
)brace
multiline_comment|/* Not found */
r_return
l_int|NULL
suffix:semicolon
)brace
multiline_comment|/* ---------------------------------------------------------------- */
multiline_comment|/*&n; * Get statistics out of the driver&n; */
DECL|function|get_wireless_stats
r_static
r_inline
r_struct
id|iw_statistics
op_star
id|get_wireless_stats
c_func
(paren
r_struct
id|net_device
op_star
id|dev
)paren
(brace
r_return
(paren
id|dev-&gt;get_wireless_stats
ques
c_cond
id|dev
op_member_access_from_pointer
id|get_wireless_stats
c_func
(paren
id|dev
)paren
suffix:colon
(paren
r_struct
id|iw_statistics
op_star
)paren
l_int|NULL
)paren
suffix:semicolon
multiline_comment|/* In the future, get_wireless_stats may move from &squot;struct net_device&squot;&n;&t; * to &squot;struct iw_handler_def&squot;, to de-bloat struct net_device.&n;&t; * Definitely worse a thought... */
)brace
multiline_comment|/* ---------------------------------------------------------------- */
multiline_comment|/*&n; * Call the commit handler in the driver&n; * (if exist and if conditions are right)&n; *&n; * Note : our current commit strategy is currently pretty dumb,&n; * but we will be able to improve on that...&n; * The goal is to try to agreagate as many changes as possible&n; * before doing the commit. Drivers that will define a commit handler&n; * are usually those that need a reset after changing parameters, so&n; * we want to minimise the number of reset.&n; * A cool idea is to use a timer : at each &quot;set&quot; command, we re-set the&n; * timer, when the timer eventually fires, we call the driver.&n; * Hopefully, more on that later.&n; *&n; * Also, I&squot;m waiting to see how many people will complain about the&n; * netif_running(dev) test. I&squot;m open on that one...&n; * Hopefully, the driver will remember to do a commit in &quot;open()&quot; ;-)&n; */
DECL|function|call_commit_handler
r_static
r_inline
r_int
id|call_commit_handler
c_func
(paren
r_struct
id|net_device
op_star
id|dev
)paren
(brace
r_if
c_cond
(paren
(paren
id|netif_running
c_func
(paren
id|dev
)paren
)paren
op_logical_and
(paren
id|dev-&gt;wireless_handlers-&gt;standard
(braket
l_int|0
)braket
op_ne
l_int|NULL
)paren
)paren
(brace
multiline_comment|/* Call the commit handler on the driver */
r_return
id|dev-&gt;wireless_handlers-&gt;standard
(braket
l_int|0
)braket
(paren
id|dev
comma
l_int|NULL
comma
l_int|NULL
comma
l_int|NULL
)paren
suffix:semicolon
)brace
r_else
r_return
l_int|0
suffix:semicolon
multiline_comment|/* Command completed successfully */
)brace
multiline_comment|/* ---------------------------------------------------------------- */
multiline_comment|/*&n; * Number of private arguments&n; */
DECL|function|get_priv_size
r_static
r_inline
r_int
id|get_priv_size
c_func
(paren
id|__u16
id|args
)paren
(brace
r_int
id|num
op_assign
id|args
op_amp
id|IW_PRIV_SIZE_MASK
suffix:semicolon
r_int
id|type
op_assign
(paren
id|args
op_amp
id|IW_PRIV_TYPE_MASK
)paren
op_rshift
l_int|12
suffix:semicolon
r_return
id|num
op_star
id|priv_type_size
(braket
id|type
)braket
suffix:semicolon
)brace
multiline_comment|/******************** /proc/net/wireless SUPPORT ********************/
multiline_comment|/*&n; * The /proc/net/wireless file is a human readable user-space interface&n; * exporting various wireless specific statistics from the wireless devices.&n; * This is the most popular part of the Wireless Extensions ;-)&n; *&n; * This interface is a pure clone of /proc/net/dev (in net/core/dev.c).&n; * The content of the file is basically the content of &quot;struct iw_statistics&quot;.&n; */
macro_line|#ifdef CONFIG_PROC_FS
multiline_comment|/* ---------------------------------------------------------------- */
multiline_comment|/*&n; * Print one entry (line) of /proc/net/wireless&n; */
DECL|function|sprintf_wireless_stats
r_static
r_inline
r_int
id|sprintf_wireless_stats
c_func
(paren
r_char
op_star
id|buffer
comma
r_struct
id|net_device
op_star
id|dev
)paren
(brace
multiline_comment|/* Get stats from the driver */
r_struct
id|iw_statistics
op_star
id|stats
suffix:semicolon
r_int
id|size
suffix:semicolon
id|stats
op_assign
id|get_wireless_stats
c_func
(paren
id|dev
)paren
suffix:semicolon
r_if
c_cond
(paren
id|stats
op_ne
(paren
r_struct
id|iw_statistics
op_star
)paren
l_int|NULL
)paren
(brace
id|size
op_assign
id|sprintf
c_func
(paren
id|buffer
comma
l_string|&quot;%6s: %04x  %3d%c  %3d%c  %3d%c  %6d %6d %6d %6d %6d   %6d&bslash;n&quot;
comma
id|dev-&gt;name
comma
id|stats-&gt;status
comma
id|stats-&gt;qual.qual
comma
id|stats-&gt;qual.updated
op_amp
l_int|1
ques
c_cond
l_char|&squot;.&squot;
suffix:colon
l_char|&squot; &squot;
comma
id|stats-&gt;qual.level
comma
id|stats-&gt;qual.updated
op_amp
l_int|2
ques
c_cond
l_char|&squot;.&squot;
suffix:colon
l_char|&squot; &squot;
comma
id|stats-&gt;qual.noise
comma
id|stats-&gt;qual.updated
op_amp
l_int|4
ques
c_cond
l_char|&squot;.&squot;
suffix:colon
l_char|&squot; &squot;
comma
id|stats-&gt;discard.nwid
comma
id|stats-&gt;discard.code
comma
id|stats-&gt;discard.fragment
comma
id|stats-&gt;discard.retries
comma
id|stats-&gt;discard.misc
comma
id|stats-&gt;miss.beacon
)paren
suffix:semicolon
id|stats-&gt;qual.updated
op_assign
l_int|0
suffix:semicolon
)brace
r_else
id|size
op_assign
l_int|0
suffix:semicolon
r_return
id|size
suffix:semicolon
)brace
multiline_comment|/* ---------------------------------------------------------------- */
multiline_comment|/*&n; * Print info for /proc/net/wireless (print all entries)&n; */
DECL|function|dev_get_wireless_info
r_int
id|dev_get_wireless_info
c_func
(paren
r_char
op_star
id|buffer
comma
r_char
op_star
op_star
id|start
comma
id|off_t
id|offset
comma
r_int
id|length
)paren
(brace
r_int
id|len
op_assign
l_int|0
suffix:semicolon
id|off_t
id|begin
op_assign
l_int|0
suffix:semicolon
id|off_t
id|pos
op_assign
l_int|0
suffix:semicolon
r_int
id|size
suffix:semicolon
r_struct
id|net_device
op_star
id|dev
suffix:semicolon
id|size
op_assign
id|sprintf
c_func
(paren
id|buffer
comma
l_string|&quot;Inter-| sta-|   Quality        |   Discarded packets               | Missed&bslash;n&quot;
l_string|&quot; face | tus | link level noise |  nwid  crypt   frag  retry   misc | beacon&bslash;n&quot;
)paren
suffix:semicolon
id|pos
op_add_assign
id|size
suffix:semicolon
id|len
op_add_assign
id|size
suffix:semicolon
id|read_lock
c_func
(paren
op_amp
id|dev_base_lock
)paren
suffix:semicolon
r_for
c_loop
(paren
id|dev
op_assign
id|dev_base
suffix:semicolon
id|dev
op_ne
l_int|NULL
suffix:semicolon
id|dev
op_assign
id|dev-&gt;next
)paren
(brace
id|size
op_assign
id|sprintf_wireless_stats
c_func
(paren
id|buffer
op_plus
id|len
comma
id|dev
)paren
suffix:semicolon
id|len
op_add_assign
id|size
suffix:semicolon
id|pos
op_assign
id|begin
op_plus
id|len
suffix:semicolon
r_if
c_cond
(paren
id|pos
OL
id|offset
)paren
(brace
id|len
op_assign
l_int|0
suffix:semicolon
id|begin
op_assign
id|pos
suffix:semicolon
)brace
r_if
c_cond
(paren
id|pos
OG
id|offset
op_plus
id|length
)paren
r_break
suffix:semicolon
)brace
id|read_unlock
c_func
(paren
op_amp
id|dev_base_lock
)paren
suffix:semicolon
op_star
id|start
op_assign
id|buffer
op_plus
(paren
id|offset
op_minus
id|begin
)paren
suffix:semicolon
multiline_comment|/* Start of wanted data */
id|len
op_sub_assign
(paren
id|offset
op_minus
id|begin
)paren
suffix:semicolon
multiline_comment|/* Start slop */
r_if
c_cond
(paren
id|len
OG
id|length
)paren
id|len
op_assign
id|length
suffix:semicolon
multiline_comment|/* Ending slop */
r_if
c_cond
(paren
id|len
OL
l_int|0
)paren
id|len
op_assign
l_int|0
suffix:semicolon
r_return
id|len
suffix:semicolon
)brace
macro_line|#endif&t;/* CONFIG_PROC_FS */
multiline_comment|/************************** IOCTL SUPPORT **************************/
multiline_comment|/*&n; * The original user space API to configure all those Wireless Extensions&n; * is through IOCTLs.&n; * In there, we check if we need to call the new driver API (iw_handler)&n; * or just call the driver ioctl handler.&n; */
multiline_comment|/* ---------------------------------------------------------------- */
multiline_comment|/*&n; *&t;Allow programatic access to /proc/net/wireless even if /proc&n; *&t;doesn&squot;t exist... Also more efficient...&n; */
DECL|function|dev_iwstats
r_static
r_inline
r_int
id|dev_iwstats
c_func
(paren
r_struct
id|net_device
op_star
id|dev
comma
r_struct
id|ifreq
op_star
id|ifr
)paren
(brace
multiline_comment|/* Get stats from the driver */
r_struct
id|iw_statistics
op_star
id|stats
suffix:semicolon
id|stats
op_assign
id|get_wireless_stats
c_func
(paren
id|dev
)paren
suffix:semicolon
r_if
c_cond
(paren
id|stats
op_ne
(paren
r_struct
id|iw_statistics
op_star
)paren
l_int|NULL
)paren
(brace
r_struct
id|iwreq
op_star
id|wrq
op_assign
(paren
r_struct
id|iwreq
op_star
)paren
id|ifr
suffix:semicolon
multiline_comment|/* Copy statistics to the user buffer */
r_if
c_cond
(paren
id|copy_to_user
c_func
(paren
id|wrq-&gt;u.data.pointer
comma
id|stats
comma
r_sizeof
(paren
r_struct
id|iw_statistics
)paren
)paren
)paren
(brace
r_return
op_minus
id|EFAULT
suffix:semicolon
)brace
multiline_comment|/* Check if we need to clear the update flag */
r_if
c_cond
(paren
id|wrq-&gt;u.data.flags
op_ne
l_int|0
)paren
(brace
id|stats-&gt;qual.updated
op_assign
l_int|0
suffix:semicolon
)brace
r_return
l_int|0
suffix:semicolon
)brace
r_else
r_return
op_minus
id|EOPNOTSUPP
suffix:semicolon
)brace
multiline_comment|/* ---------------------------------------------------------------- */
multiline_comment|/*&n; * Export the driver private handler definition&n; * They will be picked up by tools like iwpriv...&n; */
DECL|function|ioctl_export_private
r_static
r_inline
r_int
id|ioctl_export_private
c_func
(paren
r_struct
id|net_device
op_star
id|dev
comma
r_struct
id|ifreq
op_star
id|ifr
)paren
(brace
r_struct
id|iwreq
op_star
id|iwr
op_assign
(paren
r_struct
id|iwreq
op_star
)paren
id|ifr
suffix:semicolon
multiline_comment|/* Check if the driver has something to export */
r_if
c_cond
(paren
(paren
id|dev-&gt;wireless_handlers-&gt;num_private_args
op_eq
l_int|0
)paren
op_logical_or
(paren
id|dev-&gt;wireless_handlers-&gt;private_args
op_eq
l_int|NULL
)paren
)paren
(brace
r_return
op_minus
id|EOPNOTSUPP
suffix:semicolon
)brace
multiline_comment|/* Check NULL pointer */
r_if
c_cond
(paren
id|iwr-&gt;u.data.pointer
op_eq
l_int|NULL
)paren
(brace
r_return
op_minus
id|EFAULT
suffix:semicolon
)brace
macro_line|#ifdef WE_STRICT_WRITE
multiline_comment|/* Check if there is enough buffer up there */
r_if
c_cond
(paren
id|iwr-&gt;u.data.length
OL
(paren
id|SIOCIWLASTPRIV
op_minus
id|SIOCIWFIRSTPRIV
op_plus
l_int|1
)paren
)paren
(brace
r_return
op_minus
id|E2BIG
suffix:semicolon
)brace
macro_line|#endif&t;/* WE_STRICT_WRITE */
multiline_comment|/* Set the number of available ioctls. */
id|iwr-&gt;u.data.length
op_assign
id|dev-&gt;wireless_handlers-&gt;num_private_args
suffix:semicolon
multiline_comment|/* Copy structure to the user buffer. */
r_if
c_cond
(paren
id|copy_to_user
c_func
(paren
id|iwr-&gt;u.data.pointer
comma
id|dev-&gt;wireless_handlers-&gt;private_args
comma
r_sizeof
(paren
r_struct
id|iw_priv_args
)paren
op_star
id|iwr-&gt;u.data.length
)paren
)paren
r_return
op_minus
id|EFAULT
suffix:semicolon
r_return
l_int|0
suffix:semicolon
)brace
multiline_comment|/* ---------------------------------------------------------------- */
multiline_comment|/*&n; * Wrapper to call a standard Wireless Extension handler.&n; * We do various checks and also take care of moving data between&n; * user space and kernel space.&n; */
DECL|function|ioctl_standard_call
r_static
r_inline
r_int
id|ioctl_standard_call
c_func
(paren
r_struct
id|net_device
op_star
id|dev
comma
r_struct
id|ifreq
op_star
id|ifr
comma
r_int
r_int
id|cmd
comma
id|iw_handler
id|handler
)paren
(brace
r_struct
id|iwreq
op_star
id|iwr
op_assign
(paren
r_struct
id|iwreq
op_star
)paren
id|ifr
suffix:semicolon
r_const
r_struct
id|iw_ioctl_description
op_star
id|descr
suffix:semicolon
r_struct
id|iw_request_info
id|info
suffix:semicolon
r_int
id|ret
op_assign
op_minus
id|EINVAL
suffix:semicolon
multiline_comment|/* Get the description of the IOCTL */
id|descr
op_assign
op_amp
(paren
id|standard_ioctl
(braket
id|cmd
op_minus
id|SIOCIWFIRST
)braket
)paren
suffix:semicolon
macro_line|#ifdef WE_IOCTL_DEBUG
id|printk
c_func
(paren
id|KERN_DEBUG
l_string|&quot;%s : Found standard handler for 0x%04X&bslash;n&quot;
comma
id|ifr-&gt;ifr_name
comma
id|cmd
)paren
suffix:semicolon
id|printk
c_func
(paren
id|KERN_DEBUG
l_string|&quot;Header type : %d, token type : %d, token_size : %d, max_token : %d&bslash;n&quot;
comma
id|descr-&gt;header_type
comma
id|descr-&gt;token_type
comma
id|descr-&gt;token_size
comma
id|descr-&gt;max_tokens
)paren
suffix:semicolon
macro_line|#endif&t;/* WE_IOCTL_DEBUG */
multiline_comment|/* Prepare the call */
id|info.cmd
op_assign
id|cmd
suffix:semicolon
id|info.flags
op_assign
l_int|0
suffix:semicolon
multiline_comment|/* Check if we have a pointer to user space data or not */
r_if
c_cond
(paren
id|descr-&gt;header_type
op_ne
id|IW_HEADER_TYPE_POINT
)paren
(brace
multiline_comment|/* No extra arguments. Trivial to handle */
id|ret
op_assign
id|handler
c_func
(paren
id|dev
comma
op_amp
id|info
comma
op_amp
(paren
id|iwr-&gt;u
)paren
comma
l_int|NULL
)paren
suffix:semicolon
)brace
r_else
(brace
r_char
op_star
id|extra
suffix:semicolon
r_int
id|err
suffix:semicolon
multiline_comment|/* Check what user space is giving us */
r_if
c_cond
(paren
id|IW_IS_SET
c_func
(paren
id|cmd
)paren
)paren
(brace
multiline_comment|/* Check NULL pointer */
r_if
c_cond
(paren
(paren
id|iwr-&gt;u.data.pointer
op_eq
l_int|NULL
)paren
op_logical_and
(paren
id|iwr-&gt;u.data.length
op_ne
l_int|0
)paren
)paren
(brace
r_return
op_minus
id|EFAULT
suffix:semicolon
)brace
multiline_comment|/* Check if number of token fits within bounds */
r_if
c_cond
(paren
id|iwr-&gt;u.data.length
OG
id|descr-&gt;max_tokens
)paren
(brace
r_return
op_minus
id|E2BIG
suffix:semicolon
)brace
r_if
c_cond
(paren
id|iwr-&gt;u.data.length
OL
id|descr-&gt;min_tokens
)paren
(brace
r_return
op_minus
id|EINVAL
suffix:semicolon
)brace
)brace
r_else
(brace
multiline_comment|/* Check NULL pointer */
r_if
c_cond
(paren
id|iwr-&gt;u.data.pointer
op_eq
l_int|NULL
)paren
(brace
r_return
op_minus
id|EFAULT
suffix:semicolon
)brace
macro_line|#ifdef WE_STRICT_WRITE
multiline_comment|/* Check if there is enough buffer up there */
r_if
c_cond
(paren
id|iwr-&gt;u.data.length
OL
id|descr-&gt;max_tokens
)paren
(brace
r_return
op_minus
id|E2BIG
suffix:semicolon
)brace
macro_line|#endif&t;/* WE_STRICT_WRITE */
)brace
macro_line|#ifdef WE_IOCTL_DEBUG
id|printk
c_func
(paren
id|KERN_DEBUG
l_string|&quot;Malloc %d bytes&bslash;n&quot;
comma
id|descr-&gt;max_tokens
op_star
id|descr-&gt;token_size
)paren
suffix:semicolon
macro_line|#endif&t;/* WE_IOCTL_DEBUG */
multiline_comment|/* Always allocate for max space. Easier, and won&squot;t last&n;&t;&t; * long... */
id|extra
op_assign
id|kmalloc
c_func
(paren
id|descr-&gt;max_tokens
op_star
id|descr-&gt;token_size
comma
id|GFP_KERNEL
)paren
suffix:semicolon
r_if
c_cond
(paren
id|extra
op_eq
l_int|NULL
)paren
(brace
r_return
op_minus
id|ENOMEM
suffix:semicolon
)brace
multiline_comment|/* If it is a SET, get all the extra data in here */
r_if
c_cond
(paren
id|IW_IS_SET
c_func
(paren
id|cmd
)paren
op_logical_and
(paren
id|iwr-&gt;u.data.length
op_ne
l_int|0
)paren
)paren
(brace
id|err
op_assign
id|copy_from_user
c_func
(paren
id|extra
comma
id|iwr-&gt;u.data.pointer
comma
id|iwr-&gt;u.data.length
op_star
id|descr-&gt;token_size
)paren
suffix:semicolon
r_if
c_cond
(paren
id|err
)paren
(brace
id|kfree
c_func
(paren
id|extra
)paren
suffix:semicolon
r_return
op_minus
id|EFAULT
suffix:semicolon
)brace
macro_line|#ifdef WE_IOCTL_DEBUG
id|printk
c_func
(paren
id|KERN_DEBUG
l_string|&quot;Got %d bytes&bslash;n&quot;
comma
id|iwr-&gt;u.data.length
op_star
id|descr-&gt;token_size
)paren
suffix:semicolon
macro_line|#endif&t;/* WE_IOCTL_DEBUG */
)brace
multiline_comment|/* Call the handler */
id|ret
op_assign
id|handler
c_func
(paren
id|dev
comma
op_amp
id|info
comma
op_amp
(paren
id|iwr-&gt;u
)paren
comma
id|extra
)paren
suffix:semicolon
multiline_comment|/* If we have something to return to the user */
r_if
c_cond
(paren
op_logical_neg
id|ret
op_logical_and
id|IW_IS_GET
c_func
(paren
id|cmd
)paren
)paren
(brace
id|err
op_assign
id|copy_to_user
c_func
(paren
id|iwr-&gt;u.data.pointer
comma
id|extra
comma
id|iwr-&gt;u.data.length
op_star
id|descr-&gt;token_size
)paren
suffix:semicolon
r_if
c_cond
(paren
id|err
)paren
id|ret
op_assign
op_minus
id|EFAULT
suffix:semicolon
macro_line|#ifdef WE_IOCTL_DEBUG
id|printk
c_func
(paren
id|KERN_DEBUG
l_string|&quot;Wrote %d bytes&bslash;n&quot;
comma
id|iwr-&gt;u.data.length
op_star
id|descr-&gt;token_size
)paren
suffix:semicolon
macro_line|#endif&t;/* WE_IOCTL_DEBUG */
)brace
multiline_comment|/* Cleanup - I told you it wasn&squot;t that long ;-) */
id|kfree
c_func
(paren
id|extra
)paren
suffix:semicolon
)brace
multiline_comment|/* Call commit handler if needed and defined */
r_if
c_cond
(paren
id|ret
op_eq
op_minus
id|EIWCOMMIT
)paren
(brace
id|ret
op_assign
id|call_commit_handler
c_func
(paren
id|dev
)paren
suffix:semicolon
)brace
multiline_comment|/* Here, we will generate the appropriate event if needed */
r_return
id|ret
suffix:semicolon
)brace
multiline_comment|/* ---------------------------------------------------------------- */
multiline_comment|/*&n; * Wrapper to call a private Wireless Extension handler.&n; * We do various checks and also take care of moving data between&n; * user space and kernel space.&n; * It&squot;s not as nice and slimline as the standard wrapper. The cause&n; * is struct iw_priv_args, which was not really designed for the&n; * job we are going here.&n; *&n; * IMPORTANT : This function prevent to set and get data on the same&n; * IOCTL and enforce the SET/GET convention. Not doing it would be&n; * far too hairy...&n; * If you need to set and get data at the same time, please don&squot;t use&n; * a iw_handler but process it in your ioctl handler (i.e. use the&n; * old driver API).&n; */
DECL|function|ioctl_private_call
r_static
r_inline
r_int
id|ioctl_private_call
c_func
(paren
r_struct
id|net_device
op_star
id|dev
comma
r_struct
id|ifreq
op_star
id|ifr
comma
r_int
r_int
id|cmd
comma
id|iw_handler
id|handler
)paren
(brace
r_struct
id|iwreq
op_star
id|iwr
op_assign
(paren
r_struct
id|iwreq
op_star
)paren
id|ifr
suffix:semicolon
r_struct
id|iw_priv_args
op_star
id|descr
op_assign
l_int|NULL
suffix:semicolon
r_struct
id|iw_request_info
id|info
suffix:semicolon
r_int
id|extra_size
op_assign
l_int|0
suffix:semicolon
r_int
id|i
suffix:semicolon
r_int
id|ret
op_assign
op_minus
id|EINVAL
suffix:semicolon
multiline_comment|/* Get the description of the IOCTL */
r_for
c_loop
(paren
id|i
op_assign
l_int|0
suffix:semicolon
id|i
OL
id|dev-&gt;wireless_handlers-&gt;num_private_args
suffix:semicolon
id|i
op_increment
)paren
r_if
c_cond
(paren
id|cmd
op_eq
id|dev-&gt;wireless_handlers-&gt;private_args
(braket
id|i
)braket
dot
id|cmd
)paren
(brace
id|descr
op_assign
op_amp
(paren
id|dev-&gt;wireless_handlers-&gt;private_args
(braket
id|i
)braket
)paren
suffix:semicolon
r_break
suffix:semicolon
)brace
macro_line|#ifdef WE_IOCTL_DEBUG
id|printk
c_func
(paren
id|KERN_DEBUG
l_string|&quot;%s : Found private handler for 0x%04X&bslash;n&quot;
comma
id|ifr-&gt;ifr_name
comma
id|cmd
)paren
suffix:semicolon
r_if
c_cond
(paren
id|descr
)paren
(brace
id|printk
c_func
(paren
id|KERN_DEBUG
l_string|&quot;Name %s, set %X, get %X&bslash;n&quot;
comma
id|descr-&gt;name
comma
id|descr-&gt;set_args
comma
id|descr-&gt;get_args
)paren
suffix:semicolon
)brace
macro_line|#endif&t;/* WE_IOCTL_DEBUG */
multiline_comment|/* Compute the size of the set/get arguments */
r_if
c_cond
(paren
id|descr
op_ne
l_int|NULL
)paren
(brace
r_if
c_cond
(paren
id|IW_IS_SET
c_func
(paren
id|cmd
)paren
)paren
(brace
multiline_comment|/* Size of set arguments */
id|extra_size
op_assign
id|get_priv_size
c_func
(paren
id|descr-&gt;set_args
)paren
suffix:semicolon
multiline_comment|/* Does it fits in iwr ? */
r_if
c_cond
(paren
(paren
id|descr-&gt;set_args
op_amp
id|IW_PRIV_SIZE_FIXED
)paren
op_logical_and
(paren
id|extra_size
OL
id|IFNAMSIZ
)paren
)paren
(brace
id|extra_size
op_assign
l_int|0
suffix:semicolon
)brace
)brace
r_else
(brace
multiline_comment|/* Size of set arguments */
id|extra_size
op_assign
id|get_priv_size
c_func
(paren
id|descr-&gt;get_args
)paren
suffix:semicolon
multiline_comment|/* Does it fits in iwr ? */
r_if
c_cond
(paren
(paren
id|descr-&gt;get_args
op_amp
id|IW_PRIV_SIZE_FIXED
)paren
op_logical_and
(paren
id|extra_size
OL
id|IFNAMSIZ
)paren
)paren
(brace
id|extra_size
op_assign
l_int|0
suffix:semicolon
)brace
)brace
)brace
multiline_comment|/* Prepare the call */
id|info.cmd
op_assign
id|cmd
suffix:semicolon
id|info.flags
op_assign
l_int|0
suffix:semicolon
multiline_comment|/* Check if we have a pointer to user space data or not. */
r_if
c_cond
(paren
id|extra_size
op_eq
l_int|0
)paren
(brace
multiline_comment|/* No extra arguments. Trivial to handle */
id|ret
op_assign
id|handler
c_func
(paren
id|dev
comma
op_amp
id|info
comma
op_amp
(paren
id|iwr-&gt;u
)paren
comma
(paren
r_char
op_star
)paren
op_amp
(paren
id|iwr-&gt;u
)paren
)paren
suffix:semicolon
)brace
r_else
(brace
r_char
op_star
id|extra
suffix:semicolon
r_int
id|err
suffix:semicolon
multiline_comment|/* Check what user space is giving us */
r_if
c_cond
(paren
id|IW_IS_SET
c_func
(paren
id|cmd
)paren
)paren
(brace
multiline_comment|/* Check NULL pointer */
r_if
c_cond
(paren
(paren
id|iwr-&gt;u.data.pointer
op_eq
l_int|NULL
)paren
op_logical_and
(paren
id|iwr-&gt;u.data.length
op_ne
l_int|0
)paren
)paren
(brace
r_return
op_minus
id|EFAULT
suffix:semicolon
)brace
multiline_comment|/* Does it fits within bounds ? */
r_if
c_cond
(paren
id|iwr-&gt;u.data.length
OG
(paren
id|descr-&gt;set_args
op_amp
id|IW_PRIV_SIZE_MASK
)paren
)paren
(brace
r_return
op_minus
id|E2BIG
suffix:semicolon
)brace
)brace
r_else
(brace
multiline_comment|/* Check NULL pointer */
r_if
c_cond
(paren
id|iwr-&gt;u.data.pointer
op_eq
l_int|NULL
)paren
(brace
r_return
op_minus
id|EFAULT
suffix:semicolon
)brace
)brace
macro_line|#ifdef WE_IOCTL_DEBUG
id|printk
c_func
(paren
id|KERN_DEBUG
l_string|&quot;Malloc %d bytes&bslash;n&quot;
comma
id|extra_size
)paren
suffix:semicolon
macro_line|#endif&t;/* WE_IOCTL_DEBUG */
multiline_comment|/* Always allocate for max space. Easier, and won&squot;t last&n;&t;&t; * long... */
id|extra
op_assign
id|kmalloc
c_func
(paren
id|extra_size
comma
id|GFP_KERNEL
)paren
suffix:semicolon
r_if
c_cond
(paren
id|extra
op_eq
l_int|NULL
)paren
(brace
r_return
op_minus
id|ENOMEM
suffix:semicolon
)brace
multiline_comment|/* If it is a SET, get all the extra data in here */
r_if
c_cond
(paren
id|IW_IS_SET
c_func
(paren
id|cmd
)paren
op_logical_and
(paren
id|iwr-&gt;u.data.length
op_ne
l_int|0
)paren
)paren
(brace
id|err
op_assign
id|copy_from_user
c_func
(paren
id|extra
comma
id|iwr-&gt;u.data.pointer
comma
id|extra_size
)paren
suffix:semicolon
r_if
c_cond
(paren
id|err
)paren
(brace
id|kfree
c_func
(paren
id|extra
)paren
suffix:semicolon
r_return
op_minus
id|EFAULT
suffix:semicolon
)brace
macro_line|#ifdef WE_IOCTL_DEBUG
id|printk
c_func
(paren
id|KERN_DEBUG
l_string|&quot;Got %d elem&bslash;n&quot;
comma
id|iwr-&gt;u.data.length
)paren
suffix:semicolon
macro_line|#endif&t;/* WE_IOCTL_DEBUG */
)brace
multiline_comment|/* Call the handler */
id|ret
op_assign
id|handler
c_func
(paren
id|dev
comma
op_amp
id|info
comma
op_amp
(paren
id|iwr-&gt;u
)paren
comma
id|extra
)paren
suffix:semicolon
multiline_comment|/* If we have something to return to the user */
r_if
c_cond
(paren
op_logical_neg
id|ret
op_logical_and
id|IW_IS_GET
c_func
(paren
id|cmd
)paren
)paren
(brace
id|err
op_assign
id|copy_to_user
c_func
(paren
id|iwr-&gt;u.data.pointer
comma
id|extra
comma
id|extra_size
)paren
suffix:semicolon
r_if
c_cond
(paren
id|err
)paren
id|ret
op_assign
op_minus
id|EFAULT
suffix:semicolon
macro_line|#ifdef WE_IOCTL_DEBUG
id|printk
c_func
(paren
id|KERN_DEBUG
l_string|&quot;Wrote %d elem&bslash;n&quot;
comma
id|iwr-&gt;u.data.length
)paren
suffix:semicolon
macro_line|#endif&t;/* WE_IOCTL_DEBUG */
)brace
multiline_comment|/* Cleanup - I told you it wasn&squot;t that long ;-) */
id|kfree
c_func
(paren
id|extra
)paren
suffix:semicolon
)brace
multiline_comment|/* Call commit handler if needed and defined */
r_if
c_cond
(paren
id|ret
op_eq
op_minus
id|EIWCOMMIT
)paren
(brace
id|ret
op_assign
id|call_commit_handler
c_func
(paren
id|dev
)paren
suffix:semicolon
)brace
r_return
id|ret
suffix:semicolon
)brace
multiline_comment|/* ---------------------------------------------------------------- */
multiline_comment|/*&n; * Main IOCTl dispatcher. Called from the main networking code&n; * (dev_ioctl() in net/core/dev.c).&n; * Check the type of IOCTL and call the appropriate wrapper...&n; */
DECL|function|wireless_process_ioctl
r_int
id|wireless_process_ioctl
c_func
(paren
r_struct
id|ifreq
op_star
id|ifr
comma
r_int
r_int
id|cmd
)paren
(brace
r_struct
id|net_device
op_star
id|dev
suffix:semicolon
id|iw_handler
id|handler
suffix:semicolon
multiline_comment|/* Permissions are already checked in dev_ioctl() before calling us.&n;&t; * The copy_to/from_user() of ifr is also dealt with in there */
multiline_comment|/* Make sure the device exist */
r_if
c_cond
(paren
(paren
id|dev
op_assign
id|__dev_get_by_name
c_func
(paren
id|ifr-&gt;ifr_name
)paren
)paren
op_eq
l_int|NULL
)paren
r_return
op_minus
id|ENODEV
suffix:semicolon
multiline_comment|/* A bunch of special cases, then the generic case...&n;&t; * Note that &squot;cmd&squot; is already filtered in dev_ioctl() with&n;&t; * (cmd &gt;= SIOCIWFIRST &amp;&amp; cmd &lt;= SIOCIWLAST) */
r_switch
c_cond
(paren
id|cmd
)paren
(brace
r_case
id|SIOCGIWSTATS
suffix:colon
multiline_comment|/* Get Wireless Stats */
r_return
id|dev_iwstats
c_func
(paren
id|dev
comma
id|ifr
)paren
suffix:semicolon
r_case
id|SIOCGIWPRIV
suffix:colon
multiline_comment|/* Check if we have some wireless handlers defined */
r_if
c_cond
(paren
id|dev-&gt;wireless_handlers
op_ne
l_int|NULL
)paren
(brace
multiline_comment|/* We export to user space the definition of&n;&t;&t;&t;&t; * the private handler ourselves */
r_return
id|ioctl_export_private
c_func
(paren
id|dev
comma
id|ifr
)paren
suffix:semicolon
)brace
singleline_comment|// ## Fall-through for old API ##
r_default
suffix:colon
(brace
)brace
multiline_comment|/* Generic IOCTL */
multiline_comment|/* Basic check */
r_if
c_cond
(paren
op_logical_neg
id|netif_device_present
c_func
(paren
id|dev
)paren
)paren
r_return
op_minus
id|ENODEV
suffix:semicolon
multiline_comment|/* New driver API : try to find the handler */
id|handler
op_assign
id|get_handler
c_func
(paren
id|dev
comma
id|cmd
)paren
suffix:semicolon
r_if
c_cond
(paren
id|handler
op_ne
l_int|NULL
)paren
(brace
multiline_comment|/* Standard and private are not the same */
r_if
c_cond
(paren
id|cmd
OL
id|SIOCIWFIRSTPRIV
)paren
(brace
r_return
id|ioctl_standard_call
c_func
(paren
id|dev
comma
id|ifr
comma
id|cmd
comma
id|handler
)paren
suffix:semicolon
)brace
r_else
r_return
id|ioctl_private_call
c_func
(paren
id|dev
comma
id|ifr
comma
id|cmd
comma
id|handler
)paren
suffix:semicolon
)brace
multiline_comment|/* Old driver API : call driver ioctl handler */
r_if
c_cond
(paren
id|dev-&gt;do_ioctl
)paren
(brace
r_return
id|dev
op_member_access_from_pointer
id|do_ioctl
c_func
(paren
id|dev
comma
id|ifr
comma
id|cmd
)paren
suffix:semicolon
)brace
r_return
op_minus
id|EOPNOTSUPP
suffix:semicolon
)brace
multiline_comment|/* Not reached */
r_return
op_minus
id|EINVAL
suffix:semicolon
)brace
eof
