multiline_comment|/*&n; * isp1301_omap - ISP 1301 USB transceiver, talking to OMAP OTG controller&n; *&n; * Copyright (C) 2004 Texas Instruments&n; * Copyright (C) 2004 David Brownell&n; *&n; * This program is free software; you can redistribute it and/or modify&n; * it under the terms of the GNU General Public License as published by&n; * the Free Software Foundation; either version 2 of the License, or&n; * (at your option) any later version.&n; *&n; * This program is distributed in the hope that it will be useful,&n; * but WITHOUT ANY WARRANTY; without even the implied warranty of&n; * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the&n; * GNU General Public License for more details.&n; *&n; * You should have received a copy of the GNU General Public License&n; * along with this program; if not, write to the Free Software&n; * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.&n; */
DECL|macro|DEBUG
macro_line|#undef&t;DEBUG
DECL|macro|VERBOSE
macro_line|#undef&t;VERBOSE
macro_line|#include &lt;linux/config.h&gt;
macro_line|#include &lt;linux/kernel.h&gt;
macro_line|#include &lt;linux/module.h&gt;
macro_line|#include &lt;linux/init.h&gt;
macro_line|#include &lt;linux/slab.h&gt;
macro_line|#include &lt;linux/interrupt.h&gt;
macro_line|#include &lt;linux/device.h&gt;
macro_line|#include &lt;linux/usb_ch9.h&gt;
macro_line|#include &lt;linux/usb_gadget.h&gt;
macro_line|#include &lt;linux/usb.h&gt;
macro_line|#include &lt;linux/usb_otg.h&gt;
macro_line|#include &lt;linux/i2c.h&gt;
macro_line|#include &lt;linux/workqueue.h&gt;
macro_line|#include &lt;asm/irq.h&gt;
macro_line|#include &lt;asm/arch/usb.h&gt;
macro_line|#ifndef&t;DEBUG
DECL|macro|VERBOSE
macro_line|#undef&t;VERBOSE
macro_line|#endif
DECL|macro|DRIVER_VERSION
mdefine_line|#define&t;DRIVER_VERSION&t;&quot;24 August 2004&quot;
DECL|macro|DRIVER_NAME
mdefine_line|#define&t;DRIVER_NAME&t;(isp1301_driver.name)
id|MODULE_DESCRIPTION
c_func
(paren
l_string|&quot;ISP1301 USB OTG Transceiver Driver&quot;
)paren
suffix:semicolon
id|MODULE_LICENSE
c_func
(paren
l_string|&quot;GPL&quot;
)paren
suffix:semicolon
DECL|struct|isp1301
r_struct
id|isp1301
(brace
DECL|member|otg
r_struct
id|otg_transceiver
id|otg
suffix:semicolon
DECL|member|client
r_struct
id|i2c_client
id|client
suffix:semicolon
DECL|member|i2c_release
r_void
(paren
op_star
id|i2c_release
)paren
(paren
r_struct
id|device
op_star
id|dev
)paren
suffix:semicolon
DECL|member|irq
r_int
id|irq
suffix:semicolon
DECL|member|last_otg_ctrl
id|u32
id|last_otg_ctrl
suffix:semicolon
DECL|member|working
r_int
id|working
suffix:colon
l_int|1
suffix:semicolon
DECL|member|timer
r_struct
id|timer_list
id|timer
suffix:semicolon
multiline_comment|/* use keventd context to change the state for us */
DECL|member|work
r_struct
id|work_struct
id|work
suffix:semicolon
DECL|member|todo
r_int
r_int
id|todo
suffix:semicolon
DECL|macro|WORK_UPDATE_ISP
macro_line|#&t;&t;define WORK_UPDATE_ISP&t;0&t;/* update ISP from OTG */
DECL|macro|WORK_UPDATE_OTG
macro_line|#&t;&t;define WORK_UPDATE_OTG&t;1&t;/* update OTG from ISP */
DECL|macro|WORK_HOST_RESUME
macro_line|#&t;&t;define WORK_HOST_RESUME&t;4&t;/* resume host */
DECL|macro|WORK_TIMER
macro_line|#&t;&t;define WORK_TIMER&t;6&t;/* timer fired */
DECL|macro|WORK_STOP
macro_line|#&t;&t;define WORK_STOP&t;7&t;/* don&squot;t resubmit */
)brace
suffix:semicolon
multiline_comment|/* bits in OTG_CTRL_REG */
DECL|macro|OTG_XCEIV_OUTPUTS
mdefine_line|#define&t;OTG_XCEIV_OUTPUTS &bslash;&n;&t;(OTG_ASESSVLD|OTG_BSESSEND|OTG_BSESSVLD|OTG_VBUSVLD|OTG_ID)
DECL|macro|OTG_XCEIV_INPUTS
mdefine_line|#define&t;OTG_XCEIV_INPUTS &bslash;&n;&t;(OTG_PULLDOWN|OTG_PULLUP|OTG_DRV_VBUS|OTG_PD_VBUS|OTG_PU_VBUS|OTG_PU_ID)
DECL|macro|OTG_CTRL_BITS
mdefine_line|#define&t;OTG_CTRL_BITS &bslash;&n;&t;(OTG_A_BUSREQ|OTG_A_SETB_HNPEN|OTG_B_BUSREQ|OTG_B_HNPEN|OTG_BUSDROP)
multiline_comment|/* and OTG_PULLUP is sometimes written */
DECL|macro|OTG_CTRL_MASK
mdefine_line|#define&t;OTG_CTRL_MASK&t;(OTG_DRIVER_SEL| &bslash;&n;&t;OTG_XCEIV_OUTPUTS|OTG_XCEIV_INPUTS| &bslash;&n;&t;OTG_CTRL_BITS)
multiline_comment|/*-------------------------------------------------------------------------*/
macro_line|#ifdef&t;CONFIG_MACH_OMAP_H2
multiline_comment|/* board-specific PM hooks */
macro_line|#include &lt;asm/arch/gpio.h&gt;
macro_line|#include &lt;asm/arch/mux.h&gt;
macro_line|#include &lt;asm/mach-types.h&gt;
macro_line|#if&t;defined(CONFIG_TPS65010) || defined(CONFIG_TPS65010_MODULE)
macro_line|#include &lt;asm/arch/tps65010.h&gt;
macro_line|#else
DECL|function|tps65010_set_vbus_draw
r_static
r_inline
r_int
id|tps65010_set_vbus_draw
c_func
(paren
r_int
id|mA
)paren
(brace
id|pr_debug
c_func
(paren
l_string|&quot;tps65010: draw %d mA (STUB)&bslash;n&quot;
comma
id|mA
)paren
suffix:semicolon
r_return
l_int|0
suffix:semicolon
)brace
macro_line|#endif
DECL|function|enable_vbus_draw
r_static
r_void
id|enable_vbus_draw
c_func
(paren
r_struct
id|isp1301
op_star
id|isp
comma
r_int
id|mA
)paren
(brace
r_int
id|status
op_assign
id|tps65010_set_vbus_draw
c_func
(paren
id|mA
)paren
suffix:semicolon
r_if
c_cond
(paren
id|status
OL
l_int|0
)paren
id|pr_debug
c_func
(paren
l_string|&quot;  VBUS %d mA error %d&bslash;n&quot;
comma
id|mA
comma
id|status
)paren
suffix:semicolon
)brace
DECL|function|enable_vbus_source
r_static
r_void
id|enable_vbus_source
c_func
(paren
r_struct
id|isp1301
op_star
id|isp
)paren
(brace
multiline_comment|/* this board won&squot;t supply more than 8mA vbus power.&n;&t; * some boards can switch a 100ma &quot;unit load&quot; (or more).&n;&t; */
)brace
multiline_comment|/* products will deliver OTG messages with LEDs, GUI, etc */
DECL|function|notresponding
r_static
r_inline
r_void
id|notresponding
c_func
(paren
r_struct
id|isp1301
op_star
id|isp
)paren
(brace
id|printk
c_func
(paren
id|KERN_NOTICE
l_string|&quot;OTG device not responding.&bslash;n&quot;
)paren
suffix:semicolon
)brace
macro_line|#endif
multiline_comment|/*-------------------------------------------------------------------------*/
multiline_comment|/* only two addresses possible */
DECL|macro|ISP_BASE
mdefine_line|#define&t;ISP_BASE&t;&t;0x2c
DECL|variable|normal_i2c
r_static
r_int
r_int
id|normal_i2c
(braket
)braket
op_assign
(brace
id|ISP_BASE
comma
id|ISP_BASE
op_plus
l_int|1
comma
id|I2C_CLIENT_END
)brace
suffix:semicolon
DECL|variable|normal_i2c_range
r_static
r_int
r_int
id|normal_i2c_range
(braket
)braket
op_assign
(brace
id|I2C_CLIENT_END
)brace
suffix:semicolon
id|I2C_CLIENT_INSMOD
suffix:semicolon
DECL|variable|isp1301_driver
r_static
r_struct
id|i2c_driver
id|isp1301_driver
suffix:semicolon
multiline_comment|/* smbus apis are used for portability */
r_static
r_inline
id|u8
DECL|function|isp1301_get_u8
id|isp1301_get_u8
c_func
(paren
r_struct
id|isp1301
op_star
id|isp
comma
id|u8
id|reg
)paren
(brace
r_return
id|i2c_smbus_read_byte_data
c_func
(paren
op_amp
id|isp-&gt;client
comma
id|reg
op_plus
l_int|0
)paren
suffix:semicolon
)brace
r_static
r_inline
r_int
DECL|function|isp1301_get_u16
id|isp1301_get_u16
c_func
(paren
r_struct
id|isp1301
op_star
id|isp
comma
id|u8
id|reg
)paren
(brace
r_return
id|i2c_smbus_read_word_data
c_func
(paren
op_amp
id|isp-&gt;client
comma
id|reg
)paren
suffix:semicolon
)brace
r_static
r_inline
r_int
DECL|function|isp1301_set_bits
id|isp1301_set_bits
c_func
(paren
r_struct
id|isp1301
op_star
id|isp
comma
id|u8
id|reg
comma
id|u8
id|bits
)paren
(brace
r_return
id|i2c_smbus_write_byte_data
c_func
(paren
op_amp
id|isp-&gt;client
comma
id|reg
op_plus
l_int|0
comma
id|bits
)paren
suffix:semicolon
)brace
r_static
r_inline
r_int
DECL|function|isp1301_clear_bits
id|isp1301_clear_bits
c_func
(paren
r_struct
id|isp1301
op_star
id|isp
comma
id|u8
id|reg
comma
id|u8
id|bits
)paren
(brace
r_return
id|i2c_smbus_write_byte_data
c_func
(paren
op_amp
id|isp-&gt;client
comma
id|reg
op_plus
l_int|1
comma
id|bits
)paren
suffix:semicolon
)brace
multiline_comment|/*-------------------------------------------------------------------------*/
multiline_comment|/* identification */
DECL|macro|ISP1301_VENDOR_ID
mdefine_line|#define&t;ISP1301_VENDOR_ID&t;&t;0x00&t;/* u16 read */
DECL|macro|ISP1301_PRODUCT_ID
mdefine_line|#define&t;ISP1301_PRODUCT_ID&t;&t;0x02&t;/* u16 read */
DECL|macro|ISP1301_BCD_DEVICE
mdefine_line|#define&t;ISP1301_BCD_DEVICE&t;&t;0x14&t;/* u16 read */
DECL|macro|I2C_VENDOR_ID_PHILIPS
mdefine_line|#define&t;I2C_VENDOR_ID_PHILIPS&t;&t;0x04cc
DECL|macro|I2C_PRODUCT_ID_PHILIPS_1301
mdefine_line|#define&t;I2C_PRODUCT_ID_PHILIPS_1301&t;0x1301
multiline_comment|/* operational registers */
DECL|macro|ISP1301_MODE_CONTROL_1
mdefine_line|#define&t;ISP1301_MODE_CONTROL_1&t;&t;0x04&t;/* u8 read, set, +1 clear */
DECL|macro|MC1_SPEED_REG
macro_line|#&t;define&t;MC1_SPEED_REG&t;&t;(1 &lt;&lt; 0)
DECL|macro|MC1_SUSPEND_REG
macro_line|#&t;define&t;MC1_SUSPEND_REG&t;&t;(1 &lt;&lt; 1)
DECL|macro|MC1_DAT_SE0
macro_line|#&t;define&t;MC1_DAT_SE0&t;&t;(1 &lt;&lt; 2)
DECL|macro|MC1_TRANSPARENT
macro_line|#&t;define&t;MC1_TRANSPARENT&t;&t;(1 &lt;&lt; 3)
DECL|macro|MC1_BDIS_ACON_EN
macro_line|#&t;define&t;MC1_BDIS_ACON_EN&t;(1 &lt;&lt; 4)
DECL|macro|MC1_OE_INT_EN
macro_line|#&t;define&t;MC1_OE_INT_EN&t;&t;(1 &lt;&lt; 5)
DECL|macro|MC1_UART_EN
macro_line|#&t;define&t;MC1_UART_EN&t;&t;(1 &lt;&lt; 6)
DECL|macro|MC1_MASK
macro_line|#&t;define&t;MC1_MASK&t;&t;0x7f
DECL|macro|ISP1301_MODE_CONTROL_2
mdefine_line|#define&t;ISP1301_MODE_CONTROL_2&t;&t;0x12&t;/* u8 read, set, +1 clear */
DECL|macro|MC2_GLOBAL_PWR_DN
macro_line|#&t;define&t;MC2_GLOBAL_PWR_DN&t;(1 &lt;&lt; 0)
DECL|macro|MC2_SPD_SUSP_CTRL
macro_line|#&t;define&t;MC2_SPD_SUSP_CTRL&t;(1 &lt;&lt; 1)
DECL|macro|MC2_BI_DI
macro_line|#&t;define&t;MC2_BI_DI&t;&t;(1 &lt;&lt; 2)
DECL|macro|MC2_TRANSP_BDIR0
macro_line|#&t;define&t;MC2_TRANSP_BDIR0&t;(1 &lt;&lt; 3)
DECL|macro|MC2_TRANSP_BDIR1
macro_line|#&t;define&t;MC2_TRANSP_BDIR1&t;(1 &lt;&lt; 4)
DECL|macro|MC2_AUDIO_EN
macro_line|#&t;define&t;MC2_AUDIO_EN&t;&t;(1 &lt;&lt; 5)
DECL|macro|MC2_PSW_EN
macro_line|#&t;define&t;MC2_PSW_EN&t;&t;(1 &lt;&lt; 6)
DECL|macro|MC2_EN2V7
macro_line|#&t;define&t;MC2_EN2V7&t;&t;(1 &lt;&lt; 7)
DECL|macro|ISP1301_OTG_CONTROL_1
mdefine_line|#define&t;ISP1301_OTG_CONTROL_1&t;&t;0x06&t;/* u8 read, set, +1 clear */
DECL|macro|OTG1_DP_PULLUP
macro_line|#&t;define&t;OTG1_DP_PULLUP&t;&t;(1 &lt;&lt; 0)
DECL|macro|OTG1_DM_PULLUP
macro_line|#&t;define&t;OTG1_DM_PULLUP&t;&t;(1 &lt;&lt; 1)
DECL|macro|OTG1_DP_PULLDOWN
macro_line|#&t;define&t;OTG1_DP_PULLDOWN&t;(1 &lt;&lt; 2)
DECL|macro|OTG1_DM_PULLDOWN
macro_line|#&t;define&t;OTG1_DM_PULLDOWN&t;(1 &lt;&lt; 3)
DECL|macro|OTG1_ID_PULLDOWN
macro_line|#&t;define&t;OTG1_ID_PULLDOWN&t;(1 &lt;&lt; 4)
DECL|macro|OTG1_VBUS_DRV
macro_line|#&t;define&t;OTG1_VBUS_DRV&t;&t;(1 &lt;&lt; 5)
DECL|macro|OTG1_VBUS_DISCHRG
macro_line|#&t;define&t;OTG1_VBUS_DISCHRG&t;(1 &lt;&lt; 6)
DECL|macro|OTG1_VBUS_CHRG
macro_line|#&t;define&t;OTG1_VBUS_CHRG&t;&t;(1 &lt;&lt; 7)
DECL|macro|ISP1301_OTG_STATUS
mdefine_line|#define&t;ISP1301_OTG_STATUS&t;&t;0x10&t;/* u8 readonly */
DECL|macro|OTG_B_SESS_END
macro_line|#&t;define&t;OTG_B_SESS_END&t;&t;(1 &lt;&lt; 6)
DECL|macro|OTG_B_SESS_VLD
macro_line|#&t;define&t;OTG_B_SESS_VLD&t;&t;(1 &lt;&lt; 7)
DECL|macro|ISP1301_INTERRUPT_SOURCE
mdefine_line|#define&t;ISP1301_INTERRUPT_SOURCE&t;0x08&t;/* u8 read */
DECL|macro|ISP1301_INTERRUPT_LATCH
mdefine_line|#define&t;ISP1301_INTERRUPT_LATCH&t;&t;0x0A&t;/* u8 read, set, +1 clear */
DECL|macro|ISP1301_INTERRUPT_FALLING
mdefine_line|#define&t;ISP1301_INTERRUPT_FALLING&t;0x0C&t;/* u8 read, set, +1 clear */
DECL|macro|ISP1301_INTERRUPT_RISING
mdefine_line|#define&t;ISP1301_INTERRUPT_RISING&t;0x0E&t;/* u8 read, set, +1 clear */
multiline_comment|/* same bitfields in all interrupt registers */
DECL|macro|INTR_VBUS_VLD
macro_line|#&t;define&t;INTR_VBUS_VLD&t;&t;(1 &lt;&lt; 0)
DECL|macro|INTR_SESS_VLD
macro_line|#&t;define&t;INTR_SESS_VLD&t;&t;(1 &lt;&lt; 1)
DECL|macro|INTR_DP_HI
macro_line|#&t;define&t;INTR_DP_HI&t;&t;(1 &lt;&lt; 2)
DECL|macro|INTR_ID_GND
macro_line|#&t;define&t;INTR_ID_GND&t;&t;(1 &lt;&lt; 3)
DECL|macro|INTR_DM_HI
macro_line|#&t;define&t;INTR_DM_HI&t;&t;(1 &lt;&lt; 4)
DECL|macro|INTR_ID_FLOAT
macro_line|#&t;define&t;INTR_ID_FLOAT&t;&t;(1 &lt;&lt; 5)
DECL|macro|INTR_BDIS_ACON
macro_line|#&t;define&t;INTR_BDIS_ACON&t;&t;(1 &lt;&lt; 6)
DECL|macro|INTR_CR_INT
macro_line|#&t;define&t;INTR_CR_INT&t;&t;(1 &lt;&lt; 7)
multiline_comment|/*-------------------------------------------------------------------------*/
DECL|function|state_string
r_static
r_const
r_char
op_star
id|state_string
c_func
(paren
r_enum
id|usb_otg_state
id|state
)paren
(brace
r_switch
c_cond
(paren
id|state
)paren
(brace
r_case
id|OTG_STATE_A_IDLE
suffix:colon
r_return
l_string|&quot;a_idle&quot;
suffix:semicolon
r_case
id|OTG_STATE_A_WAIT_VRISE
suffix:colon
r_return
l_string|&quot;a_wait_vrise&quot;
suffix:semicolon
r_case
id|OTG_STATE_A_WAIT_BCON
suffix:colon
r_return
l_string|&quot;a_wait_bcon&quot;
suffix:semicolon
r_case
id|OTG_STATE_A_HOST
suffix:colon
r_return
l_string|&quot;a_host&quot;
suffix:semicolon
r_case
id|OTG_STATE_A_SUSPEND
suffix:colon
r_return
l_string|&quot;a_suspend&quot;
suffix:semicolon
r_case
id|OTG_STATE_A_PERIPHERAL
suffix:colon
r_return
l_string|&quot;a_peripheral&quot;
suffix:semicolon
r_case
id|OTG_STATE_A_WAIT_VFALL
suffix:colon
r_return
l_string|&quot;a_wait_vfall&quot;
suffix:semicolon
r_case
id|OTG_STATE_A_VBUS_ERR
suffix:colon
r_return
l_string|&quot;a_vbus_err&quot;
suffix:semicolon
r_case
id|OTG_STATE_B_IDLE
suffix:colon
r_return
l_string|&quot;b_idle&quot;
suffix:semicolon
r_case
id|OTG_STATE_B_SRP_INIT
suffix:colon
r_return
l_string|&quot;b_srp_init&quot;
suffix:semicolon
r_case
id|OTG_STATE_B_PERIPHERAL
suffix:colon
r_return
l_string|&quot;b_peripheral&quot;
suffix:semicolon
r_case
id|OTG_STATE_B_WAIT_ACON
suffix:colon
r_return
l_string|&quot;b_wait_acon&quot;
suffix:semicolon
r_case
id|OTG_STATE_B_HOST
suffix:colon
r_return
l_string|&quot;b_host&quot;
suffix:semicolon
r_default
suffix:colon
r_return
l_string|&quot;UNDEFINED&quot;
suffix:semicolon
)brace
)brace
DECL|function|state_name
r_static
r_inline
r_const
r_char
op_star
id|state_name
c_func
(paren
r_struct
id|isp1301
op_star
id|isp
)paren
(brace
r_return
id|state_string
c_func
(paren
id|isp-&gt;otg.state
)paren
suffix:semicolon
)brace
macro_line|#ifdef&t;VERBOSE
DECL|macro|dev_vdbg
mdefine_line|#define&t;dev_vdbg&t;&t;&t;dev_dbg
macro_line|#else
DECL|macro|dev_vdbg
mdefine_line|#define&t;dev_vdbg(dev, fmt, arg...)&t;do{}while(0)
macro_line|#endif
multiline_comment|/*-------------------------------------------------------------------------*/
multiline_comment|/* NOTE:  some of this ISP1301 setup is specific to H2 boards;&n; * not everything is guarded by board-specific checks, or even using&n; * omap_usb_config data to deduce MC1_DAT_SE0 and MC2_BI_DI.&n; *&n; * ALSO:  this currently doesn&squot;t use ISP1301 low-power modes&n; * while OTG is running.&n; */
DECL|function|power_down
r_static
r_void
id|power_down
c_func
(paren
r_struct
id|isp1301
op_star
id|isp
)paren
(brace
id|isp-&gt;otg.state
op_assign
id|OTG_STATE_UNDEFINED
suffix:semicolon
singleline_comment|// isp1301_set_bits(isp, ISP1301_MODE_CONTROL_2, MC2_GLOBAL_PWR_DN);
id|isp1301_set_bits
c_func
(paren
id|isp
comma
id|ISP1301_MODE_CONTROL_1
comma
id|MC1_SUSPEND_REG
)paren
suffix:semicolon
id|isp1301_clear_bits
c_func
(paren
id|isp
comma
id|ISP1301_OTG_CONTROL_1
comma
id|OTG1_ID_PULLDOWN
)paren
suffix:semicolon
id|isp1301_clear_bits
c_func
(paren
id|isp
comma
id|ISP1301_MODE_CONTROL_1
comma
id|MC1_DAT_SE0
)paren
suffix:semicolon
)brace
DECL|function|power_up
r_static
r_void
id|power_up
c_func
(paren
r_struct
id|isp1301
op_star
id|isp
)paren
(brace
singleline_comment|// isp1301_clear_bits(isp, ISP1301_MODE_CONTROL_2, MC2_GLOBAL_PWR_DN);
id|isp1301_clear_bits
c_func
(paren
id|isp
comma
id|ISP1301_MODE_CONTROL_1
comma
id|MC1_SUSPEND_REG
)paren
suffix:semicolon
multiline_comment|/* do this only when cpu is driving transceiver,&n;&t; * so host won&squot;t see a low speed device...&n;&t; */
id|isp1301_set_bits
c_func
(paren
id|isp
comma
id|ISP1301_MODE_CONTROL_1
comma
id|MC1_DAT_SE0
)paren
suffix:semicolon
)brace
DECL|macro|NO_HOST_SUSPEND
mdefine_line|#define&t;NO_HOST_SUSPEND
DECL|function|host_suspend
r_static
r_int
id|host_suspend
c_func
(paren
r_struct
id|isp1301
op_star
id|isp
)paren
(brace
macro_line|#ifdef&t;NO_HOST_SUSPEND
r_return
l_int|0
suffix:semicolon
macro_line|#else
r_struct
id|device
op_star
id|dev
suffix:semicolon
r_if
c_cond
(paren
op_logical_neg
id|isp-&gt;otg.host
)paren
r_return
op_minus
id|ENODEV
suffix:semicolon
multiline_comment|/* Currently ASSUMES only the OTG port matters;&n;&t; * other ports could be active...&n;&t; */
id|dev
op_assign
id|isp-&gt;otg.host-&gt;controller
suffix:semicolon
r_return
id|dev-&gt;driver
op_member_access_from_pointer
id|suspend
c_func
(paren
id|dev
comma
l_int|3
comma
l_int|0
)paren
suffix:semicolon
macro_line|#endif
)brace
DECL|function|host_resume
r_static
r_int
id|host_resume
c_func
(paren
r_struct
id|isp1301
op_star
id|isp
)paren
(brace
macro_line|#ifdef&t;NO_HOST_SUSPEND
r_return
l_int|0
suffix:semicolon
macro_line|#else
r_struct
id|device
op_star
id|dev
suffix:semicolon
r_if
c_cond
(paren
op_logical_neg
id|isp-&gt;otg.host
)paren
r_return
op_minus
id|ENODEV
suffix:semicolon
id|dev
op_assign
id|isp-&gt;otg.host-&gt;controller
suffix:semicolon
r_return
id|dev-&gt;driver
op_member_access_from_pointer
id|resume
c_func
(paren
id|dev
comma
l_int|0
)paren
suffix:semicolon
macro_line|#endif
)brace
DECL|function|gadget_suspend
r_static
r_int
id|gadget_suspend
c_func
(paren
r_struct
id|isp1301
op_star
id|isp
)paren
(brace
id|isp-&gt;otg.gadget-&gt;b_hnp_enable
op_assign
l_int|0
suffix:semicolon
id|isp-&gt;otg.gadget-&gt;a_hnp_support
op_assign
l_int|0
suffix:semicolon
id|isp-&gt;otg.gadget-&gt;a_alt_hnp_support
op_assign
l_int|0
suffix:semicolon
r_return
id|usb_gadget_vbus_disconnect
c_func
(paren
id|isp-&gt;otg.gadget
)paren
suffix:semicolon
)brace
multiline_comment|/*-------------------------------------------------------------------------*/
DECL|macro|TIMER_MINUTES
mdefine_line|#define&t;TIMER_MINUTES&t;10
DECL|macro|TIMER_JIFFIES
mdefine_line|#define&t;TIMER_JIFFIES&t;(TIMER_MINUTES * 60 * HZ)
multiline_comment|/* Almost all our I2C messaging comes from a work queue&squot;s task context.&n; * NOTE: guaranteeing certain response times might mean we shouldn&squot;t&n; * share keventd&squot;s work queue; a realtime task might be safest.&n; */
r_void
DECL|function|isp1301_defer_work
id|isp1301_defer_work
c_func
(paren
r_struct
id|isp1301
op_star
id|isp
comma
r_int
id|work
)paren
(brace
r_int
id|status
suffix:semicolon
r_if
c_cond
(paren
id|isp
op_logical_and
op_logical_neg
id|test_and_set_bit
c_func
(paren
id|work
comma
op_amp
id|isp-&gt;todo
)paren
)paren
(brace
(paren
r_void
)paren
id|get_device
c_func
(paren
op_amp
id|isp-&gt;client.dev
)paren
suffix:semicolon
id|status
op_assign
id|schedule_work
c_func
(paren
op_amp
id|isp-&gt;work
)paren
suffix:semicolon
r_if
c_cond
(paren
op_logical_neg
id|status
op_logical_and
op_logical_neg
id|isp-&gt;working
)paren
id|dev_vdbg
c_func
(paren
op_amp
id|isp-&gt;client.dev
comma
l_string|&quot;work item %d may be lost&bslash;n&quot;
comma
id|work
)paren
suffix:semicolon
)brace
)brace
multiline_comment|/* called from irq handlers */
DECL|function|a_idle
r_static
r_void
id|a_idle
c_func
(paren
r_struct
id|isp1301
op_star
id|isp
comma
r_const
r_char
op_star
id|tag
)paren
(brace
r_if
c_cond
(paren
id|isp-&gt;otg.state
op_eq
id|OTG_STATE_A_IDLE
)paren
r_return
suffix:semicolon
id|isp-&gt;otg.default_a
op_assign
l_int|1
suffix:semicolon
r_if
c_cond
(paren
id|isp-&gt;otg.host
)paren
(brace
id|isp-&gt;otg.host-&gt;is_b_host
op_assign
l_int|0
suffix:semicolon
id|host_suspend
c_func
(paren
id|isp
)paren
suffix:semicolon
)brace
r_if
c_cond
(paren
id|isp-&gt;otg.gadget
)paren
(brace
id|isp-&gt;otg.gadget-&gt;is_a_peripheral
op_assign
l_int|1
suffix:semicolon
id|gadget_suspend
c_func
(paren
id|isp
)paren
suffix:semicolon
)brace
id|isp-&gt;otg.state
op_assign
id|OTG_STATE_A_IDLE
suffix:semicolon
id|isp-&gt;last_otg_ctrl
op_assign
id|OTG_CTRL_REG
op_assign
id|OTG_CTRL_REG
op_amp
id|OTG_XCEIV_OUTPUTS
suffix:semicolon
id|pr_debug
c_func
(paren
l_string|&quot;  --&gt; %s/%s&bslash;n&quot;
comma
id|state_name
c_func
(paren
id|isp
)paren
comma
id|tag
)paren
suffix:semicolon
)brace
multiline_comment|/* called from irq handlers */
DECL|function|b_idle
r_static
r_void
id|b_idle
c_func
(paren
r_struct
id|isp1301
op_star
id|isp
comma
r_const
r_char
op_star
id|tag
)paren
(brace
r_if
c_cond
(paren
id|isp-&gt;otg.state
op_eq
id|OTG_STATE_B_IDLE
)paren
r_return
suffix:semicolon
id|isp-&gt;otg.default_a
op_assign
l_int|0
suffix:semicolon
r_if
c_cond
(paren
id|isp-&gt;otg.host
)paren
(brace
id|isp-&gt;otg.host-&gt;is_b_host
op_assign
l_int|1
suffix:semicolon
id|host_suspend
c_func
(paren
id|isp
)paren
suffix:semicolon
)brace
r_if
c_cond
(paren
id|isp-&gt;otg.gadget
)paren
(brace
id|isp-&gt;otg.gadget-&gt;is_a_peripheral
op_assign
l_int|0
suffix:semicolon
id|gadget_suspend
c_func
(paren
id|isp
)paren
suffix:semicolon
)brace
id|isp-&gt;otg.state
op_assign
id|OTG_STATE_B_IDLE
suffix:semicolon
id|isp-&gt;last_otg_ctrl
op_assign
id|OTG_CTRL_REG
op_assign
id|OTG_CTRL_REG
op_amp
id|OTG_XCEIV_OUTPUTS
suffix:semicolon
id|pr_debug
c_func
(paren
l_string|&quot;  --&gt; %s/%s&bslash;n&quot;
comma
id|state_name
c_func
(paren
id|isp
)paren
comma
id|tag
)paren
suffix:semicolon
)brace
r_static
r_void
DECL|function|dump_regs
id|dump_regs
c_func
(paren
r_struct
id|isp1301
op_star
id|isp
comma
r_const
r_char
op_star
id|label
)paren
(brace
macro_line|#ifdef&t;DEBUG
id|u8
id|ctrl
op_assign
id|isp1301_get_u8
c_func
(paren
id|isp
comma
id|ISP1301_OTG_CONTROL_1
)paren
suffix:semicolon
id|u8
id|status
op_assign
id|isp1301_get_u8
c_func
(paren
id|isp
comma
id|ISP1301_OTG_STATUS
)paren
suffix:semicolon
id|u8
id|src
op_assign
id|isp1301_get_u8
c_func
(paren
id|isp
comma
id|ISP1301_INTERRUPT_SOURCE
)paren
suffix:semicolon
id|pr_debug
c_func
(paren
l_string|&quot;otg: %06x, %s %s, otg/%02x stat/%02x.%02x&bslash;n&quot;
comma
id|OTG_CTRL_REG
comma
id|label
comma
id|state_name
c_func
(paren
id|isp
)paren
comma
id|ctrl
comma
id|status
comma
id|src
)paren
suffix:semicolon
multiline_comment|/* mode control and irq enables don&squot;t change much */
macro_line|#endif
)brace
multiline_comment|/*-------------------------------------------------------------------------*/
macro_line|#ifdef&t;CONFIG_USB_OTG
multiline_comment|/*&n; * The OMAP OTG controller handles most of the OTG state transitions.&n; *&n; * We translate isp1301 outputs (mostly voltage comparator status) into&n; * OTG inputs; OTG outputs (mostly pullup/pulldown controls) and HNP state&n; * flags into isp1301 inputs ... and infer state transitions.&n; */
macro_line|#ifdef&t;VERBOSE
DECL|function|check_state
r_static
r_void
id|check_state
c_func
(paren
r_struct
id|isp1301
op_star
id|isp
comma
r_const
r_char
op_star
id|tag
)paren
(brace
r_enum
id|usb_otg_state
id|state
op_assign
id|OTG_STATE_UNDEFINED
suffix:semicolon
id|u8
id|fsm
op_assign
id|OTG_TEST_REG
op_amp
l_int|0x0ff
suffix:semicolon
r_int
id|extra
op_assign
l_int|0
suffix:semicolon
r_switch
c_cond
(paren
id|fsm
)paren
(brace
multiline_comment|/* default-b */
r_case
l_int|0x0
suffix:colon
id|state
op_assign
id|OTG_STATE_B_IDLE
suffix:semicolon
r_break
suffix:semicolon
r_case
l_int|0x3
suffix:colon
r_case
l_int|0x7
suffix:colon
id|extra
op_assign
l_int|1
suffix:semicolon
r_case
l_int|0x1
suffix:colon
id|state
op_assign
id|OTG_STATE_B_PERIPHERAL
suffix:semicolon
r_break
suffix:semicolon
r_case
l_int|0x11
suffix:colon
id|state
op_assign
id|OTG_STATE_B_SRP_INIT
suffix:semicolon
r_break
suffix:semicolon
multiline_comment|/* extra dual-role default-b states */
r_case
l_int|0x12
suffix:colon
r_case
l_int|0x13
suffix:colon
r_case
l_int|0x16
suffix:colon
id|extra
op_assign
l_int|1
suffix:semicolon
r_case
l_int|0x17
suffix:colon
id|state
op_assign
id|OTG_STATE_B_WAIT_ACON
suffix:semicolon
r_break
suffix:semicolon
r_case
l_int|0x34
suffix:colon
id|state
op_assign
id|OTG_STATE_B_HOST
suffix:semicolon
r_break
suffix:semicolon
multiline_comment|/* default-a */
r_case
l_int|0x36
suffix:colon
id|state
op_assign
id|OTG_STATE_A_IDLE
suffix:semicolon
r_break
suffix:semicolon
r_case
l_int|0x3c
suffix:colon
id|state
op_assign
id|OTG_STATE_A_WAIT_VFALL
suffix:semicolon
r_break
suffix:semicolon
r_case
l_int|0x7d
suffix:colon
id|state
op_assign
id|OTG_STATE_A_VBUS_ERR
suffix:semicolon
r_break
suffix:semicolon
r_case
l_int|0x9e
suffix:colon
r_case
l_int|0x9f
suffix:colon
id|extra
op_assign
l_int|1
suffix:semicolon
r_case
l_int|0x89
suffix:colon
id|state
op_assign
id|OTG_STATE_A_PERIPHERAL
suffix:semicolon
r_break
suffix:semicolon
r_case
l_int|0xb7
suffix:colon
id|state
op_assign
id|OTG_STATE_A_WAIT_VRISE
suffix:semicolon
r_break
suffix:semicolon
r_case
l_int|0xb8
suffix:colon
id|state
op_assign
id|OTG_STATE_A_WAIT_BCON
suffix:semicolon
r_break
suffix:semicolon
r_case
l_int|0xb9
suffix:colon
id|state
op_assign
id|OTG_STATE_A_HOST
suffix:semicolon
r_break
suffix:semicolon
r_case
l_int|0xba
suffix:colon
id|state
op_assign
id|OTG_STATE_A_SUSPEND
suffix:semicolon
r_break
suffix:semicolon
r_default
suffix:colon
r_break
suffix:semicolon
)brace
r_if
c_cond
(paren
id|isp-&gt;otg.state
op_eq
id|state
op_logical_and
op_logical_neg
id|extra
)paren
r_return
suffix:semicolon
id|pr_debug
c_func
(paren
l_string|&quot;otg: %s FSM %s/%02x, %s, %06x&bslash;n&quot;
comma
id|tag
comma
id|state_string
c_func
(paren
id|state
)paren
comma
id|fsm
comma
id|state_name
c_func
(paren
id|isp
)paren
comma
id|OTG_CTRL_REG
)paren
suffix:semicolon
)brace
macro_line|#else
DECL|function|check_state
r_static
r_inline
r_void
id|check_state
c_func
(paren
r_struct
id|isp1301
op_star
id|isp
comma
r_const
r_char
op_star
id|tag
)paren
(brace
)brace
macro_line|#endif
multiline_comment|/* outputs from ISP1301_INTERRUPT_SOURCE */
DECL|function|update_otg1
r_static
r_void
id|update_otg1
c_func
(paren
r_struct
id|isp1301
op_star
id|isp
comma
id|u8
id|int_src
)paren
(brace
id|u32
id|otg_ctrl
suffix:semicolon
id|otg_ctrl
op_assign
id|OTG_CTRL_REG
op_amp
id|OTG_CTRL_MASK
op_amp
op_complement
id|OTG_XCEIV_INPUTS
op_amp
op_complement
(paren
id|OTG_ID
op_or
id|OTG_ASESSVLD
op_or
id|OTG_VBUSVLD
)paren
suffix:semicolon
r_if
c_cond
(paren
id|int_src
op_amp
id|INTR_SESS_VLD
)paren
id|otg_ctrl
op_or_assign
id|OTG_ASESSVLD
suffix:semicolon
r_else
r_if
c_cond
(paren
id|isp-&gt;otg.state
op_eq
id|OTG_STATE_A_WAIT_VFALL
)paren
(brace
id|a_idle
c_func
(paren
id|isp
comma
l_string|&quot;vfall&quot;
)paren
suffix:semicolon
id|otg_ctrl
op_and_assign
op_complement
id|OTG_CTRL_BITS
suffix:semicolon
)brace
r_if
c_cond
(paren
id|int_src
op_amp
id|INTR_VBUS_VLD
)paren
id|otg_ctrl
op_or_assign
id|OTG_VBUSVLD
suffix:semicolon
r_if
c_cond
(paren
id|int_src
op_amp
id|INTR_ID_GND
)paren
(brace
multiline_comment|/* default-A */
r_if
c_cond
(paren
id|isp-&gt;otg.state
op_eq
id|OTG_STATE_B_IDLE
op_logical_or
id|isp-&gt;otg.state
op_eq
id|OTG_STATE_UNDEFINED
)paren
(brace
id|a_idle
c_func
(paren
id|isp
comma
l_string|&quot;init&quot;
)paren
suffix:semicolon
r_return
suffix:semicolon
)brace
)brace
r_else
(brace
multiline_comment|/* default-B */
id|otg_ctrl
op_or_assign
id|OTG_ID
suffix:semicolon
r_if
c_cond
(paren
id|isp-&gt;otg.state
op_eq
id|OTG_STATE_A_IDLE
op_logical_or
id|isp-&gt;otg.state
op_eq
id|OTG_STATE_UNDEFINED
)paren
(brace
id|b_idle
c_func
(paren
id|isp
comma
l_string|&quot;init&quot;
)paren
suffix:semicolon
r_return
suffix:semicolon
)brace
)brace
id|OTG_CTRL_REG
op_assign
id|otg_ctrl
suffix:semicolon
)brace
multiline_comment|/* outputs from ISP1301_OTG_STATUS */
DECL|function|update_otg2
r_static
r_void
id|update_otg2
c_func
(paren
r_struct
id|isp1301
op_star
id|isp
comma
id|u8
id|otg_status
)paren
(brace
id|u32
id|otg_ctrl
suffix:semicolon
id|otg_ctrl
op_assign
id|OTG_CTRL_REG
op_amp
id|OTG_CTRL_MASK
op_amp
op_complement
id|OTG_XCEIV_INPUTS
op_amp
op_complement
(paren
id|OTG_BSESSVLD
op_or
id|OTG_BSESSEND
)paren
suffix:semicolon
r_if
c_cond
(paren
id|otg_status
op_amp
id|OTG_B_SESS_VLD
)paren
id|otg_ctrl
op_or_assign
id|OTG_BSESSVLD
suffix:semicolon
r_else
r_if
c_cond
(paren
id|otg_status
op_amp
id|OTG_B_SESS_END
)paren
id|otg_ctrl
op_or_assign
id|OTG_BSESSEND
suffix:semicolon
id|OTG_CTRL_REG
op_assign
id|otg_ctrl
suffix:semicolon
)brace
multiline_comment|/* inputs going to ISP1301 */
DECL|function|otg_update_isp
r_static
r_void
id|otg_update_isp
c_func
(paren
r_struct
id|isp1301
op_star
id|isp
)paren
(brace
id|u32
id|otg_ctrl
comma
id|otg_change
suffix:semicolon
id|u8
id|set
op_assign
id|OTG1_DM_PULLDOWN
comma
id|clr
op_assign
id|OTG1_DM_PULLUP
suffix:semicolon
id|otg_ctrl
op_assign
id|OTG_CTRL_REG
suffix:semicolon
id|otg_change
op_assign
id|otg_ctrl
op_xor
id|isp-&gt;last_otg_ctrl
suffix:semicolon
id|isp-&gt;last_otg_ctrl
op_assign
id|otg_ctrl
suffix:semicolon
id|otg_ctrl
op_assign
id|otg_ctrl
op_amp
id|OTG_XCEIV_INPUTS
suffix:semicolon
r_switch
c_cond
(paren
id|isp-&gt;otg.state
)paren
(brace
r_case
id|OTG_STATE_B_IDLE
suffix:colon
r_case
id|OTG_STATE_B_PERIPHERAL
suffix:colon
r_case
id|OTG_STATE_B_SRP_INIT
suffix:colon
r_if
c_cond
(paren
op_logical_neg
(paren
id|otg_ctrl
op_amp
id|OTG_PULLUP
)paren
)paren
(brace
singleline_comment|// if (otg_ctrl &amp; OTG_B_HNPEN) {
r_if
c_cond
(paren
id|isp-&gt;otg.gadget-&gt;b_hnp_enable
)paren
(brace
id|isp-&gt;otg.state
op_assign
id|OTG_STATE_B_WAIT_ACON
suffix:semicolon
id|pr_debug
c_func
(paren
l_string|&quot;  --&gt; b_wait_acon&bslash;n&quot;
)paren
suffix:semicolon
)brace
r_goto
id|pulldown
suffix:semicolon
)brace
id|pullup
suffix:colon
id|set
op_or_assign
id|OTG1_DP_PULLUP
suffix:semicolon
id|clr
op_or_assign
id|OTG1_DP_PULLDOWN
suffix:semicolon
r_break
suffix:semicolon
r_case
id|OTG_STATE_A_SUSPEND
suffix:colon
r_case
id|OTG_STATE_A_PERIPHERAL
suffix:colon
r_if
c_cond
(paren
id|otg_ctrl
op_amp
id|OTG_PULLUP
)paren
r_goto
id|pullup
suffix:semicolon
multiline_comment|/* FALLTHROUGH */
singleline_comment|// case OTG_STATE_B_WAIT_ACON:
r_default
suffix:colon
id|pulldown
suffix:colon
id|set
op_or_assign
id|OTG1_DP_PULLDOWN
suffix:semicolon
id|clr
op_or_assign
id|OTG1_DP_PULLUP
suffix:semicolon
r_break
suffix:semicolon
)brace
DECL|macro|toggle
macro_line|#&t;define toggle(OTG,ISP) do { &bslash;&n;&t;&t;if (otg_ctrl &amp; OTG) set |= ISP; &bslash;&n;&t;&t;else clr |= ISP; &bslash;&n;&t;&t;} while (0)
r_if
c_cond
(paren
op_logical_neg
(paren
id|isp-&gt;otg.host
)paren
)paren
id|otg_ctrl
op_and_assign
op_complement
id|OTG_DRV_VBUS
suffix:semicolon
r_switch
c_cond
(paren
id|isp-&gt;otg.state
)paren
(brace
r_case
id|OTG_STATE_A_SUSPEND
suffix:colon
r_if
c_cond
(paren
id|otg_ctrl
op_amp
id|OTG_DRV_VBUS
)paren
(brace
id|set
op_or_assign
id|OTG1_VBUS_DRV
suffix:semicolon
r_break
suffix:semicolon
)brace
multiline_comment|/* HNP failed for some reason (A_AIDL_BDIS timeout) */
id|notresponding
c_func
(paren
id|isp
)paren
suffix:semicolon
multiline_comment|/* FALLTHROUGH */
r_case
id|OTG_STATE_A_VBUS_ERR
suffix:colon
id|isp-&gt;otg.state
op_assign
id|OTG_STATE_A_WAIT_VFALL
suffix:semicolon
id|pr_debug
c_func
(paren
l_string|&quot;  --&gt; a_wait_vfall&bslash;n&quot;
)paren
suffix:semicolon
multiline_comment|/* FALLTHROUGH */
r_case
id|OTG_STATE_A_WAIT_VFALL
suffix:colon
multiline_comment|/* FIXME usbcore thinks port power is still on ... */
id|clr
op_or_assign
id|OTG1_VBUS_DRV
suffix:semicolon
r_break
suffix:semicolon
r_case
id|OTG_STATE_A_IDLE
suffix:colon
r_if
c_cond
(paren
id|otg_ctrl
op_amp
id|OTG_DRV_VBUS
)paren
(brace
id|isp-&gt;otg.state
op_assign
id|OTG_STATE_A_WAIT_VRISE
suffix:semicolon
id|pr_debug
c_func
(paren
l_string|&quot;  --&gt; a_wait_vrise&bslash;n&quot;
)paren
suffix:semicolon
)brace
multiline_comment|/* FALLTHROUGH */
r_default
suffix:colon
id|toggle
c_func
(paren
id|OTG_DRV_VBUS
comma
id|OTG1_VBUS_DRV
)paren
suffix:semicolon
)brace
id|toggle
c_func
(paren
id|OTG_PU_VBUS
comma
id|OTG1_VBUS_CHRG
)paren
suffix:semicolon
id|toggle
c_func
(paren
id|OTG_PD_VBUS
comma
id|OTG1_VBUS_DISCHRG
)paren
suffix:semicolon
DECL|macro|toggle
macro_line|#&t;undef toggle
id|isp1301_set_bits
c_func
(paren
id|isp
comma
id|ISP1301_OTG_CONTROL_1
comma
id|set
)paren
suffix:semicolon
id|isp1301_clear_bits
c_func
(paren
id|isp
comma
id|ISP1301_OTG_CONTROL_1
comma
id|clr
)paren
suffix:semicolon
multiline_comment|/* HNP switch to host or peripheral; and SRP */
r_if
c_cond
(paren
id|otg_change
op_amp
id|OTG_PULLUP
)paren
(brace
r_switch
c_cond
(paren
id|isp-&gt;otg.state
)paren
(brace
r_case
id|OTG_STATE_B_IDLE
suffix:colon
r_if
c_cond
(paren
id|clr
op_amp
id|OTG1_DP_PULLUP
)paren
r_break
suffix:semicolon
id|isp-&gt;otg.state
op_assign
id|OTG_STATE_B_PERIPHERAL
suffix:semicolon
id|pr_debug
c_func
(paren
l_string|&quot;  --&gt; b_peripheral&bslash;n&quot;
)paren
suffix:semicolon
r_break
suffix:semicolon
r_case
id|OTG_STATE_A_SUSPEND
suffix:colon
r_if
c_cond
(paren
id|clr
op_amp
id|OTG1_DP_PULLUP
)paren
r_break
suffix:semicolon
id|isp-&gt;otg.state
op_assign
id|OTG_STATE_A_PERIPHERAL
suffix:semicolon
id|pr_debug
c_func
(paren
l_string|&quot;  --&gt; a_peripheral&bslash;n&quot;
)paren
suffix:semicolon
r_break
suffix:semicolon
r_default
suffix:colon
r_break
suffix:semicolon
)brace
id|OTG_CTRL_REG
op_or_assign
id|OTG_PULLUP
suffix:semicolon
)brace
id|check_state
c_func
(paren
id|isp
comma
id|__FUNCTION__
)paren
suffix:semicolon
id|dump_regs
c_func
(paren
id|isp
comma
l_string|&quot;otg-&gt;isp1301&quot;
)paren
suffix:semicolon
)brace
DECL|function|omap_otg_irq
r_static
id|irqreturn_t
id|omap_otg_irq
c_func
(paren
r_int
id|irq
comma
r_void
op_star
id|_isp
comma
r_struct
id|pt_regs
op_star
id|regs
)paren
(brace
id|u16
id|otg_irq
op_assign
id|OTG_IRQ_SRC_REG
suffix:semicolon
id|u32
id|otg_ctrl
suffix:semicolon
r_int
id|ret
op_assign
id|IRQ_NONE
suffix:semicolon
r_struct
id|isp1301
op_star
id|isp
op_assign
id|_isp
suffix:semicolon
multiline_comment|/* update ISP1301 transciever from OTG controller */
r_if
c_cond
(paren
id|otg_irq
op_amp
id|OPRT_CHG
)paren
(brace
id|OTG_IRQ_SRC_REG
op_assign
id|OPRT_CHG
suffix:semicolon
id|isp1301_defer_work
c_func
(paren
id|isp
comma
id|WORK_UPDATE_ISP
)paren
suffix:semicolon
id|ret
op_assign
id|IRQ_HANDLED
suffix:semicolon
multiline_comment|/* SRP to become b_peripheral failed */
)brace
r_else
r_if
c_cond
(paren
id|otg_irq
op_amp
id|B_SRP_TMROUT
)paren
(brace
id|pr_debug
c_func
(paren
l_string|&quot;otg: B_SRP_TIMEOUT, %06x&bslash;n&quot;
comma
id|OTG_CTRL_REG
)paren
suffix:semicolon
id|notresponding
c_func
(paren
id|isp
)paren
suffix:semicolon
multiline_comment|/* gadget drivers that care should monitor all kinds of&n;&t;&t; * remote wakeup (SRP, normal) using their own timer&n;&t;&t; * to give &quot;check cable and A-device&quot; messages.&n;&t;&t; */
r_if
c_cond
(paren
id|isp-&gt;otg.state
op_eq
id|OTG_STATE_B_SRP_INIT
)paren
id|b_idle
c_func
(paren
id|isp
comma
l_string|&quot;srp_timeout&quot;
)paren
suffix:semicolon
id|OTG_IRQ_SRC_REG
op_assign
id|B_SRP_TMROUT
suffix:semicolon
id|ret
op_assign
id|IRQ_HANDLED
suffix:semicolon
multiline_comment|/* HNP to become b_host failed */
)brace
r_else
r_if
c_cond
(paren
id|otg_irq
op_amp
id|B_HNP_FAIL
)paren
(brace
id|pr_debug
c_func
(paren
l_string|&quot;otg: %s B_HNP_FAIL, %06x&bslash;n&quot;
comma
id|state_name
c_func
(paren
id|isp
)paren
comma
id|OTG_CTRL_REG
)paren
suffix:semicolon
id|notresponding
c_func
(paren
id|isp
)paren
suffix:semicolon
id|otg_ctrl
op_assign
id|OTG_CTRL_REG
suffix:semicolon
id|otg_ctrl
op_or_assign
id|OTG_BUSDROP
suffix:semicolon
id|otg_ctrl
op_and_assign
id|OTG_CTRL_MASK
op_amp
op_complement
id|OTG_XCEIV_INPUTS
suffix:semicolon
id|OTG_CTRL_REG
op_assign
id|otg_ctrl
suffix:semicolon
multiline_comment|/* subset of b_peripheral()... */
id|isp-&gt;otg.state
op_assign
id|OTG_STATE_B_PERIPHERAL
suffix:semicolon
id|pr_debug
c_func
(paren
l_string|&quot;  --&gt; b_peripheral&bslash;n&quot;
)paren
suffix:semicolon
id|OTG_IRQ_SRC_REG
op_assign
id|B_HNP_FAIL
suffix:semicolon
id|ret
op_assign
id|IRQ_HANDLED
suffix:semicolon
multiline_comment|/* detect SRP from B-device ... */
)brace
r_else
r_if
c_cond
(paren
id|otg_irq
op_amp
id|A_SRP_DETECT
)paren
(brace
id|pr_debug
c_func
(paren
l_string|&quot;otg: %s SRP_DETECT, %06x&bslash;n&quot;
comma
id|state_name
c_func
(paren
id|isp
)paren
comma
id|OTG_CTRL_REG
)paren
suffix:semicolon
id|isp1301_defer_work
c_func
(paren
id|isp
comma
id|WORK_UPDATE_OTG
)paren
suffix:semicolon
r_switch
c_cond
(paren
id|isp-&gt;otg.state
)paren
(brace
r_case
id|OTG_STATE_A_IDLE
suffix:colon
r_if
c_cond
(paren
op_logical_neg
id|isp-&gt;otg.host
)paren
r_break
suffix:semicolon
id|isp1301_defer_work
c_func
(paren
id|isp
comma
id|WORK_HOST_RESUME
)paren
suffix:semicolon
id|otg_ctrl
op_assign
id|OTG_CTRL_REG
suffix:semicolon
id|otg_ctrl
op_or_assign
id|OTG_A_BUSREQ
suffix:semicolon
id|otg_ctrl
op_and_assign
op_complement
(paren
id|OTG_BUSDROP
op_or
id|OTG_B_BUSREQ
)paren
op_amp
op_complement
id|OTG_XCEIV_INPUTS
op_amp
id|OTG_CTRL_MASK
suffix:semicolon
id|OTG_CTRL_REG
op_assign
id|otg_ctrl
suffix:semicolon
r_break
suffix:semicolon
r_default
suffix:colon
r_break
suffix:semicolon
)brace
id|OTG_IRQ_SRC_REG
op_assign
id|A_SRP_DETECT
suffix:semicolon
id|ret
op_assign
id|IRQ_HANDLED
suffix:semicolon
multiline_comment|/* timer expired:  T(a_wait_bcon) and maybe T(a_wait_vrise)&n;&t; * we don&squot;t track them separately&n;&t; */
)brace
r_else
r_if
c_cond
(paren
id|otg_irq
op_amp
id|A_REQ_TMROUT
)paren
(brace
id|otg_ctrl
op_assign
id|OTG_CTRL_REG
suffix:semicolon
id|pr_info
c_func
(paren
l_string|&quot;otg: BCON_TMOUT from %s, %06x&bslash;n&quot;
comma
id|state_name
c_func
(paren
id|isp
)paren
comma
id|otg_ctrl
)paren
suffix:semicolon
id|notresponding
c_func
(paren
id|isp
)paren
suffix:semicolon
id|otg_ctrl
op_or_assign
id|OTG_BUSDROP
suffix:semicolon
id|otg_ctrl
op_and_assign
op_complement
id|OTG_A_BUSREQ
op_amp
id|OTG_CTRL_MASK
op_amp
op_complement
id|OTG_XCEIV_INPUTS
suffix:semicolon
id|OTG_CTRL_REG
op_assign
id|otg_ctrl
suffix:semicolon
id|isp-&gt;otg.state
op_assign
id|OTG_STATE_A_WAIT_VFALL
suffix:semicolon
id|OTG_IRQ_SRC_REG
op_assign
id|A_REQ_TMROUT
suffix:semicolon
id|ret
op_assign
id|IRQ_HANDLED
suffix:semicolon
multiline_comment|/* A-supplied voltage fell too low; overcurrent */
)brace
r_else
r_if
c_cond
(paren
id|otg_irq
op_amp
id|A_VBUS_ERR
)paren
(brace
id|otg_ctrl
op_assign
id|OTG_CTRL_REG
suffix:semicolon
id|printk
c_func
(paren
id|KERN_ERR
l_string|&quot;otg: %s, VBUS_ERR %04x ctrl %06x&bslash;n&quot;
comma
id|state_name
c_func
(paren
id|isp
)paren
comma
id|otg_irq
comma
id|otg_ctrl
)paren
suffix:semicolon
id|otg_ctrl
op_or_assign
id|OTG_BUSDROP
suffix:semicolon
id|otg_ctrl
op_and_assign
op_complement
id|OTG_A_BUSREQ
op_amp
id|OTG_CTRL_MASK
op_amp
op_complement
id|OTG_XCEIV_INPUTS
suffix:semicolon
id|OTG_CTRL_REG
op_assign
id|otg_ctrl
suffix:semicolon
id|isp-&gt;otg.state
op_assign
id|OTG_STATE_A_VBUS_ERR
suffix:semicolon
id|OTG_IRQ_SRC_REG
op_assign
id|A_VBUS_ERR
suffix:semicolon
id|ret
op_assign
id|IRQ_HANDLED
suffix:semicolon
multiline_comment|/* switch driver; the transciever code activates it,&n;&t; * ungating the udc clock or resuming OHCI.&n;&t; */
)brace
r_else
r_if
c_cond
(paren
id|otg_irq
op_amp
id|DRIVER_SWITCH
)paren
(brace
r_int
id|kick
op_assign
l_int|0
suffix:semicolon
id|otg_ctrl
op_assign
id|OTG_CTRL_REG
suffix:semicolon
id|printk
c_func
(paren
id|KERN_NOTICE
l_string|&quot;otg: %s, SWITCH to %s, ctrl %06x&bslash;n&quot;
comma
id|state_name
c_func
(paren
id|isp
)paren
comma
(paren
id|otg_ctrl
op_amp
id|OTG_DRIVER_SEL
)paren
ques
c_cond
l_string|&quot;gadget&quot;
suffix:colon
l_string|&quot;host&quot;
comma
id|otg_ctrl
)paren
suffix:semicolon
id|isp1301_defer_work
c_func
(paren
id|isp
comma
id|WORK_UPDATE_ISP
)paren
suffix:semicolon
multiline_comment|/* role is peripheral */
r_if
c_cond
(paren
id|otg_ctrl
op_amp
id|OTG_DRIVER_SEL
)paren
(brace
r_switch
c_cond
(paren
id|isp-&gt;otg.state
)paren
(brace
r_case
id|OTG_STATE_A_IDLE
suffix:colon
id|b_idle
c_func
(paren
id|isp
comma
id|__FUNCTION__
)paren
suffix:semicolon
r_break
suffix:semicolon
r_default
suffix:colon
r_break
suffix:semicolon
)brace
id|isp1301_defer_work
c_func
(paren
id|isp
comma
id|WORK_UPDATE_ISP
)paren
suffix:semicolon
multiline_comment|/* role is host */
)brace
r_else
(brace
r_if
c_cond
(paren
op_logical_neg
(paren
id|otg_ctrl
op_amp
id|OTG_ID
)paren
)paren
(brace
id|otg_ctrl
op_and_assign
id|OTG_CTRL_MASK
op_amp
op_complement
id|OTG_XCEIV_INPUTS
suffix:semicolon
id|OTG_CTRL_REG
op_assign
id|otg_ctrl
op_or
id|OTG_A_BUSREQ
suffix:semicolon
)brace
r_if
c_cond
(paren
id|isp-&gt;otg.host
)paren
(brace
r_switch
c_cond
(paren
id|isp-&gt;otg.state
)paren
(brace
r_case
id|OTG_STATE_B_WAIT_ACON
suffix:colon
id|isp-&gt;otg.state
op_assign
id|OTG_STATE_B_HOST
suffix:semicolon
id|pr_debug
c_func
(paren
l_string|&quot;  --&gt; b_host&bslash;n&quot;
)paren
suffix:semicolon
id|kick
op_assign
l_int|1
suffix:semicolon
r_break
suffix:semicolon
r_case
id|OTG_STATE_A_WAIT_BCON
suffix:colon
id|isp-&gt;otg.state
op_assign
id|OTG_STATE_A_HOST
suffix:semicolon
id|pr_debug
c_func
(paren
l_string|&quot;  --&gt; a_host&bslash;n&quot;
)paren
suffix:semicolon
r_break
suffix:semicolon
r_case
id|OTG_STATE_A_PERIPHERAL
suffix:colon
id|isp-&gt;otg.state
op_assign
id|OTG_STATE_A_WAIT_BCON
suffix:semicolon
id|pr_debug
c_func
(paren
l_string|&quot;  --&gt; a_wait_bcon&bslash;n&quot;
)paren
suffix:semicolon
r_break
suffix:semicolon
r_default
suffix:colon
r_break
suffix:semicolon
)brace
id|isp1301_defer_work
c_func
(paren
id|isp
comma
id|WORK_HOST_RESUME
)paren
suffix:semicolon
)brace
)brace
id|OTG_IRQ_SRC_REG
op_assign
id|DRIVER_SWITCH
suffix:semicolon
id|ret
op_assign
id|IRQ_HANDLED
suffix:semicolon
r_if
c_cond
(paren
id|kick
)paren
id|usb_bus_start_enum
c_func
(paren
id|isp-&gt;otg.host
comma
id|isp-&gt;otg.host-&gt;otg_port
)paren
suffix:semicolon
)brace
id|check_state
c_func
(paren
id|isp
comma
id|__FUNCTION__
)paren
suffix:semicolon
r_return
id|ret
suffix:semicolon
)brace
DECL|variable|otg_dev
r_static
r_struct
id|platform_device
op_star
id|otg_dev
suffix:semicolon
DECL|function|otg_init
r_static
r_int
id|otg_init
c_func
(paren
r_struct
id|isp1301
op_star
id|isp
)paren
(brace
r_if
c_cond
(paren
op_logical_neg
id|otg_dev
)paren
r_return
op_minus
id|ENODEV
suffix:semicolon
id|dump_regs
c_func
(paren
id|isp
comma
id|__FUNCTION__
)paren
suffix:semicolon
multiline_comment|/* some of these values are board-specific... */
id|OTG_SYSCON_2_REG
op_or_assign
id|OTG_EN
multiline_comment|/* for B-device: */
op_or
id|SRP_GPDATA
multiline_comment|/* 9msec Bdev D+ pulse */
op_or
id|SRP_GPDVBUS
multiline_comment|/* discharge after VBUS pulse */
singleline_comment|// | (3 &lt;&lt; 24)&t;&t;/* 2msec VBUS pulse */
multiline_comment|/* for A-device: */
op_or
(paren
l_int|0
op_lshift
l_int|20
)paren
multiline_comment|/* 200ms nominal A_WAIT_VRISE timer */
op_or
id|SRP_DPW
multiline_comment|/* detect 167+ns SRP pulses */
op_or
id|SRP_DATA
op_or
id|SRP_VBUS
multiline_comment|/* accept both kinds of SRP pulse */
suffix:semicolon
id|update_otg1
c_func
(paren
id|isp
comma
id|isp1301_get_u8
c_func
(paren
id|isp
comma
id|ISP1301_INTERRUPT_SOURCE
)paren
)paren
suffix:semicolon
id|update_otg2
c_func
(paren
id|isp
comma
id|isp1301_get_u8
c_func
(paren
id|isp
comma
id|ISP1301_OTG_STATUS
)paren
)paren
suffix:semicolon
id|check_state
c_func
(paren
id|isp
comma
id|__FUNCTION__
)paren
suffix:semicolon
id|pr_debug
c_func
(paren
l_string|&quot;otg: %s, %s %06x&bslash;n&quot;
comma
id|state_name
c_func
(paren
id|isp
)paren
comma
id|__FUNCTION__
comma
id|OTG_CTRL_REG
)paren
suffix:semicolon
id|OTG_IRQ_EN_REG
op_assign
id|DRIVER_SWITCH
op_or
id|OPRT_CHG
op_or
id|B_SRP_TMROUT
op_or
id|B_HNP_FAIL
op_or
id|A_VBUS_ERR
op_or
id|A_SRP_DETECT
op_or
id|A_REQ_TMROUT
suffix:semicolon
id|OTG_SYSCON_2_REG
op_or_assign
id|OTG_EN
suffix:semicolon
r_return
l_int|0
suffix:semicolon
)brace
DECL|function|otg_probe
r_static
r_int
id|otg_probe
c_func
(paren
r_struct
id|device
op_star
id|dev
)paren
(brace
singleline_comment|// struct omap_usb_config *config = dev-&gt;platform_data;
id|otg_dev
op_assign
id|to_platform_device
c_func
(paren
id|dev
)paren
suffix:semicolon
r_return
l_int|0
suffix:semicolon
)brace
DECL|function|otg_remove
r_static
r_int
id|otg_remove
c_func
(paren
r_struct
id|device
op_star
id|dev
)paren
(brace
id|otg_dev
op_assign
l_int|0
suffix:semicolon
r_return
l_int|0
suffix:semicolon
)brace
DECL|variable|omap_otg_driver
r_struct
id|device_driver
id|omap_otg_driver
op_assign
(brace
dot
id|name
op_assign
l_string|&quot;omap_otg&quot;
comma
dot
id|bus
op_assign
op_amp
id|platform_bus_type
comma
dot
id|probe
op_assign
id|otg_probe
comma
dot
id|remove
op_assign
id|otg_remove
comma
)brace
suffix:semicolon
DECL|function|otg_bind
r_static
r_int
id|otg_bind
c_func
(paren
r_struct
id|isp1301
op_star
id|isp
)paren
(brace
r_int
id|status
suffix:semicolon
r_if
c_cond
(paren
id|otg_dev
)paren
r_return
op_minus
id|EBUSY
suffix:semicolon
id|status
op_assign
id|driver_register
c_func
(paren
op_amp
id|omap_otg_driver
)paren
suffix:semicolon
r_if
c_cond
(paren
id|status
OL
l_int|0
)paren
r_return
id|status
suffix:semicolon
r_if
c_cond
(paren
id|otg_dev
)paren
id|status
op_assign
id|request_irq
c_func
(paren
id|otg_dev-&gt;resource
(braket
l_int|1
)braket
dot
id|start
comma
id|omap_otg_irq
comma
id|SA_INTERRUPT
comma
id|DRIVER_NAME
comma
id|isp
)paren
suffix:semicolon
r_else
id|status
op_assign
op_minus
id|ENODEV
suffix:semicolon
r_if
c_cond
(paren
id|status
OL
l_int|0
)paren
id|driver_unregister
c_func
(paren
op_amp
id|omap_otg_driver
)paren
suffix:semicolon
r_return
id|status
suffix:semicolon
)brace
DECL|function|otg_unbind
r_static
r_void
id|otg_unbind
c_func
(paren
r_struct
id|isp1301
op_star
id|isp
)paren
(brace
r_if
c_cond
(paren
op_logical_neg
id|otg_dev
)paren
r_return
suffix:semicolon
id|free_irq
c_func
(paren
id|otg_dev-&gt;resource
(braket
l_int|1
)braket
dot
id|start
comma
id|isp
)paren
suffix:semicolon
)brace
macro_line|#else
multiline_comment|/* OTG controller isn&squot;t clocked */
macro_line|#endif&t;/* CONFIG_USB_OTG */
multiline_comment|/*-------------------------------------------------------------------------*/
DECL|function|b_peripheral
r_static
r_void
id|b_peripheral
c_func
(paren
r_struct
id|isp1301
op_star
id|isp
)paren
(brace
id|OTG_CTRL_REG
op_assign
id|OTG_CTRL_REG
op_amp
id|OTG_XCEIV_OUTPUTS
suffix:semicolon
id|usb_gadget_vbus_connect
c_func
(paren
id|isp-&gt;otg.gadget
)paren
suffix:semicolon
macro_line|#ifdef&t;CONFIG_USB_OTG
id|enable_vbus_draw
c_func
(paren
id|isp
comma
l_int|8
)paren
suffix:semicolon
id|otg_update_isp
c_func
(paren
id|isp
)paren
suffix:semicolon
macro_line|#else
id|enable_vbus_draw
c_func
(paren
id|isp
comma
l_int|100
)paren
suffix:semicolon
multiline_comment|/* UDC driver just set OTG_BSESSVLD */
id|isp1301_set_bits
c_func
(paren
id|isp
comma
id|ISP1301_OTG_CONTROL_1
comma
id|OTG1_DP_PULLUP
)paren
suffix:semicolon
id|isp1301_clear_bits
c_func
(paren
id|isp
comma
id|ISP1301_OTG_CONTROL_1
comma
id|OTG1_DP_PULLDOWN
)paren
suffix:semicolon
id|isp-&gt;otg.state
op_assign
id|OTG_STATE_B_PERIPHERAL
suffix:semicolon
id|pr_debug
c_func
(paren
l_string|&quot;  --&gt; b_peripheral&bslash;n&quot;
)paren
suffix:semicolon
id|dump_regs
c_func
(paren
id|isp
comma
l_string|&quot;2periph&quot;
)paren
suffix:semicolon
macro_line|#endif
)brace
DECL|function|isp_update_otg
r_static
r_void
id|isp_update_otg
c_func
(paren
r_struct
id|isp1301
op_star
id|isp
comma
id|u8
id|stat
)paren
(brace
id|u8
id|isp_stat
comma
id|isp_bstat
suffix:semicolon
r_enum
id|usb_otg_state
id|state
op_assign
id|isp-&gt;otg.state
suffix:semicolon
r_if
c_cond
(paren
id|stat
op_amp
id|INTR_BDIS_ACON
)paren
id|pr_debug
c_func
(paren
l_string|&quot;OTG:  BDIS_ACON, %s&bslash;n&quot;
comma
id|state_name
c_func
(paren
id|isp
)paren
)paren
suffix:semicolon
multiline_comment|/* start certain state transitions right away */
id|isp_stat
op_assign
id|isp1301_get_u8
c_func
(paren
id|isp
comma
id|ISP1301_INTERRUPT_SOURCE
)paren
suffix:semicolon
r_if
c_cond
(paren
id|isp_stat
op_amp
id|INTR_ID_GND
)paren
(brace
r_if
c_cond
(paren
id|isp-&gt;otg.default_a
)paren
(brace
r_switch
c_cond
(paren
id|state
)paren
(brace
r_case
id|OTG_STATE_B_IDLE
suffix:colon
id|a_idle
c_func
(paren
id|isp
comma
l_string|&quot;idle&quot;
)paren
suffix:semicolon
multiline_comment|/* FALLTHROUGH */
r_case
id|OTG_STATE_A_IDLE
suffix:colon
id|enable_vbus_source
c_func
(paren
id|isp
)paren
suffix:semicolon
multiline_comment|/* FALLTHROUGH */
r_case
id|OTG_STATE_A_WAIT_VRISE
suffix:colon
multiline_comment|/* we skip over OTG_STATE_A_WAIT_BCON, since&n;&t;&t;&t;&t; * the HC will transition to A_HOST (or&n;&t;&t;&t;&t; * A_SUSPEND!) without our noticing except&n;&t;&t;&t;&t; * when HNP is used.&n;&t;&t;&t;&t; */
r_if
c_cond
(paren
id|isp_stat
op_amp
id|INTR_VBUS_VLD
)paren
id|isp-&gt;otg.state
op_assign
id|OTG_STATE_A_HOST
suffix:semicolon
r_break
suffix:semicolon
r_case
id|OTG_STATE_A_WAIT_VFALL
suffix:colon
r_if
c_cond
(paren
op_logical_neg
(paren
id|isp_stat
op_amp
id|INTR_SESS_VLD
)paren
)paren
id|a_idle
c_func
(paren
id|isp
comma
l_string|&quot;vfell&quot;
)paren
suffix:semicolon
r_break
suffix:semicolon
r_default
suffix:colon
(brace
)brace
r_if
c_cond
(paren
op_logical_neg
(paren
id|isp_stat
op_amp
id|INTR_VBUS_VLD
)paren
)paren
id|isp-&gt;otg.state
op_assign
id|OTG_STATE_A_VBUS_ERR
suffix:semicolon
r_break
suffix:semicolon
)brace
id|isp_bstat
op_assign
id|isp1301_get_u8
c_func
(paren
id|isp
comma
id|ISP1301_OTG_STATUS
)paren
suffix:semicolon
)brace
r_else
(brace
r_switch
c_cond
(paren
id|state
)paren
(brace
r_case
id|OTG_STATE_B_PERIPHERAL
suffix:colon
r_case
id|OTG_STATE_B_HOST
suffix:colon
r_case
id|OTG_STATE_B_WAIT_ACON
suffix:colon
id|usb_gadget_vbus_disconnect
c_func
(paren
id|isp-&gt;otg.gadget
)paren
suffix:semicolon
r_break
suffix:semicolon
r_default
suffix:colon
r_break
suffix:semicolon
)brace
r_if
c_cond
(paren
id|state
op_ne
id|OTG_STATE_A_IDLE
)paren
id|a_idle
c_func
(paren
id|isp
comma
l_string|&quot;id&quot;
)paren
suffix:semicolon
r_if
c_cond
(paren
id|isp-&gt;otg.host
op_logical_and
id|state
op_eq
id|OTG_STATE_A_IDLE
)paren
id|isp1301_defer_work
c_func
(paren
id|isp
comma
id|WORK_HOST_RESUME
)paren
suffix:semicolon
id|isp_bstat
op_assign
l_int|0
suffix:semicolon
)brace
)brace
r_else
(brace
multiline_comment|/* if user unplugged mini-A end of cable,&n;&t;&t; * don&squot;t bypass A_WAIT_VFALL.&n;&t;&t; */
r_if
c_cond
(paren
id|isp-&gt;otg.default_a
)paren
(brace
r_switch
c_cond
(paren
id|state
)paren
(brace
r_default
suffix:colon
id|isp-&gt;otg.state
op_assign
id|OTG_STATE_A_WAIT_VFALL
suffix:semicolon
r_break
suffix:semicolon
r_case
id|OTG_STATE_A_WAIT_VFALL
suffix:colon
id|state
op_assign
id|OTG_STATE_A_IDLE
suffix:semicolon
multiline_comment|/* khubd may take a while to notice and&n;&t;&t;&t;&t; * handle this disconnect, so don&squot;t go&n;&t;&t;&t;&t; * to B_IDLE quite yet.&n;&t;&t;&t;&t; */
r_break
suffix:semicolon
r_case
id|OTG_STATE_A_IDLE
suffix:colon
id|host_suspend
c_func
(paren
id|isp
)paren
suffix:semicolon
id|isp1301_clear_bits
c_func
(paren
id|isp
comma
id|ISP1301_MODE_CONTROL_1
comma
id|MC1_BDIS_ACON_EN
)paren
suffix:semicolon
id|isp-&gt;otg.state
op_assign
id|OTG_STATE_B_IDLE
suffix:semicolon
id|OTG_CTRL_REG
op_and_assign
id|OTG_CTRL_REG
op_amp
id|OTG_CTRL_MASK
op_amp
op_complement
id|OTG_CTRL_BITS
suffix:semicolon
r_break
suffix:semicolon
r_case
id|OTG_STATE_B_IDLE
suffix:colon
r_break
suffix:semicolon
)brace
)brace
id|isp_bstat
op_assign
id|isp1301_get_u8
c_func
(paren
id|isp
comma
id|ISP1301_OTG_STATUS
)paren
suffix:semicolon
r_switch
c_cond
(paren
id|isp-&gt;otg.state
)paren
(brace
r_case
id|OTG_STATE_B_PERIPHERAL
suffix:colon
r_case
id|OTG_STATE_B_WAIT_ACON
suffix:colon
r_case
id|OTG_STATE_B_HOST
suffix:colon
r_if
c_cond
(paren
id|likely
c_func
(paren
id|isp_bstat
op_amp
id|OTG_B_SESS_VLD
)paren
)paren
r_break
suffix:semicolon
id|enable_vbus_draw
c_func
(paren
id|isp
comma
l_int|0
)paren
suffix:semicolon
macro_line|#ifndef&t;CONFIG_USB_OTG
multiline_comment|/* UDC driver will clear OTG_BSESSVLD */
id|isp1301_set_bits
c_func
(paren
id|isp
comma
id|ISP1301_OTG_CONTROL_1
comma
id|OTG1_DP_PULLDOWN
)paren
suffix:semicolon
id|isp1301_clear_bits
c_func
(paren
id|isp
comma
id|ISP1301_OTG_CONTROL_1
comma
id|OTG1_DP_PULLUP
)paren
suffix:semicolon
id|dump_regs
c_func
(paren
id|isp
comma
id|__FUNCTION__
)paren
suffix:semicolon
macro_line|#endif
multiline_comment|/* FALLTHROUGH */
r_case
id|OTG_STATE_B_SRP_INIT
suffix:colon
id|b_idle
c_func
(paren
id|isp
comma
id|__FUNCTION__
)paren
suffix:semicolon
id|OTG_CTRL_REG
op_and_assign
id|OTG_CTRL_REG
op_amp
id|OTG_XCEIV_OUTPUTS
suffix:semicolon
multiline_comment|/* FALLTHROUGH */
r_case
id|OTG_STATE_B_IDLE
suffix:colon
r_if
c_cond
(paren
id|isp-&gt;otg.gadget
op_logical_and
(paren
id|isp_bstat
op_amp
id|OTG_B_SESS_VLD
)paren
)paren
(brace
macro_line|#ifdef&t;CONFIG_USB_OTG
id|update_otg1
c_func
(paren
id|isp
comma
id|isp_stat
)paren
suffix:semicolon
id|update_otg2
c_func
(paren
id|isp
comma
id|isp_bstat
)paren
suffix:semicolon
macro_line|#endif
id|b_peripheral
c_func
(paren
id|isp
)paren
suffix:semicolon
)brace
r_else
r_if
c_cond
(paren
op_logical_neg
(paren
id|isp_stat
op_amp
(paren
id|INTR_VBUS_VLD
op_or
id|INTR_SESS_VLD
)paren
)paren
)paren
id|isp_bstat
op_or_assign
id|OTG_B_SESS_END
suffix:semicolon
r_break
suffix:semicolon
r_case
id|OTG_STATE_A_WAIT_VFALL
suffix:colon
r_break
suffix:semicolon
r_default
suffix:colon
id|pr_debug
c_func
(paren
l_string|&quot;otg: unsupported b-device %s&bslash;n&quot;
comma
id|state_name
c_func
(paren
id|isp
)paren
)paren
suffix:semicolon
r_break
suffix:semicolon
)brace
)brace
r_if
c_cond
(paren
id|state
op_ne
id|isp-&gt;otg.state
)paren
id|pr_debug
c_func
(paren
l_string|&quot;  isp, %s -&gt; %s&bslash;n&quot;
comma
id|state_string
c_func
(paren
id|state
)paren
comma
id|state_name
c_func
(paren
id|isp
)paren
)paren
suffix:semicolon
macro_line|#ifdef&t;CONFIG_USB_OTG
multiline_comment|/* update the OTG controller state to match the isp1301; may&n;&t; * trigger OPRT_CHG irqs for changes going to the isp1301.&n;&t; */
id|update_otg1
c_func
(paren
id|isp
comma
id|isp_stat
)paren
suffix:semicolon
id|update_otg2
c_func
(paren
id|isp
comma
id|isp_bstat
)paren
suffix:semicolon
id|check_state
c_func
(paren
id|isp
comma
id|__FUNCTION__
)paren
suffix:semicolon
macro_line|#endif
id|dump_regs
c_func
(paren
id|isp
comma
l_string|&quot;isp1301-&gt;otg&quot;
)paren
suffix:semicolon
)brace
multiline_comment|/*-------------------------------------------------------------------------*/
DECL|function|isp1301_clear_latch
r_static
id|u8
id|isp1301_clear_latch
c_func
(paren
r_struct
id|isp1301
op_star
id|isp
)paren
(brace
id|u8
id|latch
op_assign
id|isp1301_get_u8
c_func
(paren
id|isp
comma
id|ISP1301_INTERRUPT_LATCH
)paren
suffix:semicolon
id|isp1301_clear_bits
c_func
(paren
id|isp
comma
id|ISP1301_INTERRUPT_LATCH
comma
id|latch
)paren
suffix:semicolon
r_return
id|latch
suffix:semicolon
)brace
r_static
r_void
DECL|function|isp1301_work
id|isp1301_work
c_func
(paren
r_void
op_star
id|data
)paren
(brace
r_struct
id|isp1301
op_star
id|isp
op_assign
id|data
suffix:semicolon
r_int
id|stop
suffix:semicolon
multiline_comment|/* implicit lock:  we&squot;re the only task using this device */
id|isp-&gt;working
op_assign
l_int|1
suffix:semicolon
r_do
(brace
id|stop
op_assign
id|test_bit
c_func
(paren
id|WORK_STOP
comma
op_amp
id|isp-&gt;todo
)paren
suffix:semicolon
macro_line|#ifdef&t;CONFIG_USB_OTG
multiline_comment|/* transfer state from otg engine to isp1301 */
r_if
c_cond
(paren
id|test_and_clear_bit
c_func
(paren
id|WORK_UPDATE_ISP
comma
op_amp
id|isp-&gt;todo
)paren
)paren
(brace
id|otg_update_isp
c_func
(paren
id|isp
)paren
suffix:semicolon
id|put_device
c_func
(paren
op_amp
id|isp-&gt;client.dev
)paren
suffix:semicolon
)brace
macro_line|#endif
multiline_comment|/* transfer state from isp1301 to otg engine */
r_if
c_cond
(paren
id|test_and_clear_bit
c_func
(paren
id|WORK_UPDATE_OTG
comma
op_amp
id|isp-&gt;todo
)paren
)paren
(brace
id|u8
id|stat
op_assign
id|isp1301_clear_latch
c_func
(paren
id|isp
)paren
suffix:semicolon
id|isp_update_otg
c_func
(paren
id|isp
comma
id|stat
)paren
suffix:semicolon
id|put_device
c_func
(paren
op_amp
id|isp-&gt;client.dev
)paren
suffix:semicolon
)brace
r_if
c_cond
(paren
id|test_and_clear_bit
c_func
(paren
id|WORK_HOST_RESUME
comma
op_amp
id|isp-&gt;todo
)paren
)paren
(brace
id|u32
id|otg_ctrl
suffix:semicolon
multiline_comment|/*&n;&t;&t;&t; * skip A_WAIT_VRISE; hc transitions invisibly&n;&t;&t;&t; * skip A_WAIT_BCON; same.&n;&t;&t;&t; */
r_switch
c_cond
(paren
id|isp-&gt;otg.state
)paren
(brace
r_case
id|OTG_STATE_A_WAIT_BCON
suffix:colon
r_case
id|OTG_STATE_A_WAIT_VRISE
suffix:colon
id|isp-&gt;otg.state
op_assign
id|OTG_STATE_A_HOST
suffix:semicolon
id|pr_debug
c_func
(paren
l_string|&quot;  --&gt; a_host&bslash;n&quot;
)paren
suffix:semicolon
id|otg_ctrl
op_assign
id|OTG_CTRL_REG
suffix:semicolon
id|otg_ctrl
op_or_assign
id|OTG_A_BUSREQ
suffix:semicolon
id|otg_ctrl
op_and_assign
op_complement
(paren
id|OTG_BUSDROP
op_or
id|OTG_B_BUSREQ
)paren
op_amp
id|OTG_CTRL_MASK
suffix:semicolon
id|OTG_CTRL_REG
op_assign
id|otg_ctrl
suffix:semicolon
r_break
suffix:semicolon
r_case
id|OTG_STATE_B_WAIT_ACON
suffix:colon
id|isp-&gt;otg.state
op_assign
id|OTG_STATE_B_HOST
suffix:semicolon
id|pr_debug
c_func
(paren
l_string|&quot;  --&gt; b_host (acon)&bslash;n&quot;
)paren
suffix:semicolon
r_break
suffix:semicolon
r_case
id|OTG_STATE_B_HOST
suffix:colon
r_case
id|OTG_STATE_B_IDLE
suffix:colon
r_case
id|OTG_STATE_A_IDLE
suffix:colon
r_break
suffix:semicolon
r_default
suffix:colon
id|pr_debug
c_func
(paren
l_string|&quot;  host resume in %s&bslash;n&quot;
comma
id|state_name
c_func
(paren
id|isp
)paren
)paren
suffix:semicolon
)brace
id|host_resume
c_func
(paren
id|isp
)paren
suffix:semicolon
singleline_comment|// mdelay(10);
id|put_device
c_func
(paren
op_amp
id|isp-&gt;client.dev
)paren
suffix:semicolon
)brace
r_if
c_cond
(paren
id|test_and_clear_bit
c_func
(paren
id|WORK_TIMER
comma
op_amp
id|isp-&gt;todo
)paren
)paren
(brace
macro_line|#ifdef&t;VERBOSE
id|dump_regs
c_func
(paren
id|isp
comma
l_string|&quot;timer&quot;
)paren
suffix:semicolon
r_if
c_cond
(paren
op_logical_neg
id|stop
)paren
id|mod_timer
c_func
(paren
op_amp
id|isp-&gt;timer
comma
id|jiffies
op_plus
id|TIMER_JIFFIES
)paren
suffix:semicolon
macro_line|#endif
id|put_device
c_func
(paren
op_amp
id|isp-&gt;client.dev
)paren
suffix:semicolon
)brace
r_if
c_cond
(paren
id|isp-&gt;todo
)paren
id|dev_vdbg
c_func
(paren
op_amp
id|isp-&gt;client.dev
comma
l_string|&quot;work done, todo = 0x%lx&bslash;n&quot;
comma
id|isp-&gt;todo
)paren
suffix:semicolon
r_if
c_cond
(paren
id|stop
)paren
(brace
id|dev_dbg
c_func
(paren
op_amp
id|isp-&gt;client.dev
comma
l_string|&quot;stop&bslash;n&quot;
)paren
suffix:semicolon
r_break
suffix:semicolon
)brace
)brace
r_while
c_loop
(paren
id|isp-&gt;todo
)paren
suffix:semicolon
id|isp-&gt;working
op_assign
l_int|0
suffix:semicolon
)brace
DECL|function|isp1301_irq
r_static
id|irqreturn_t
id|isp1301_irq
c_func
(paren
r_int
id|irq
comma
r_void
op_star
id|isp
comma
r_struct
id|pt_regs
op_star
id|regs
)paren
(brace
id|isp1301_defer_work
c_func
(paren
id|isp
comma
id|WORK_UPDATE_OTG
)paren
suffix:semicolon
r_return
id|IRQ_HANDLED
suffix:semicolon
)brace
DECL|function|isp1301_timer
r_static
r_void
id|isp1301_timer
c_func
(paren
r_int
r_int
id|_isp
)paren
(brace
id|isp1301_defer_work
c_func
(paren
(paren
r_void
op_star
)paren
id|_isp
comma
id|WORK_TIMER
)paren
suffix:semicolon
)brace
multiline_comment|/*-------------------------------------------------------------------------*/
DECL|function|isp1301_release
r_static
r_void
id|isp1301_release
c_func
(paren
r_struct
id|device
op_star
id|dev
)paren
(brace
r_struct
id|isp1301
op_star
id|isp
suffix:semicolon
id|isp
op_assign
id|container_of
c_func
(paren
id|dev
comma
r_struct
id|isp1301
comma
id|client.dev
)paren
suffix:semicolon
multiline_comment|/* ugly -- i2c hijacks our memory hook to wait_for_completion() */
r_if
c_cond
(paren
id|isp-&gt;i2c_release
)paren
id|isp
op_member_access_from_pointer
id|i2c_release
c_func
(paren
id|dev
)paren
suffix:semicolon
id|kfree
(paren
id|isp
)paren
suffix:semicolon
)brace
DECL|variable|the_transceiver
r_static
r_struct
id|isp1301
op_star
id|the_transceiver
suffix:semicolon
DECL|function|isp1301_detach_client
r_static
r_int
id|isp1301_detach_client
c_func
(paren
r_struct
id|i2c_client
op_star
id|i2c
)paren
(brace
r_struct
id|isp1301
op_star
id|isp
suffix:semicolon
id|isp
op_assign
id|container_of
c_func
(paren
id|i2c
comma
r_struct
id|isp1301
comma
id|client
)paren
suffix:semicolon
id|isp1301_clear_bits
c_func
(paren
id|isp
comma
id|ISP1301_INTERRUPT_FALLING
comma
op_complement
l_int|0
)paren
suffix:semicolon
id|isp1301_clear_bits
c_func
(paren
id|isp
comma
id|ISP1301_INTERRUPT_RISING
comma
op_complement
l_int|0
)paren
suffix:semicolon
id|free_irq
c_func
(paren
id|isp-&gt;irq
comma
id|isp
)paren
suffix:semicolon
macro_line|#ifdef&t;CONFIG_USB_OTG
id|otg_unbind
c_func
(paren
id|isp
)paren
suffix:semicolon
macro_line|#endif
r_if
c_cond
(paren
id|machine_is_omap_h2
c_func
(paren
)paren
)paren
id|omap_free_gpio
c_func
(paren
l_int|2
)paren
suffix:semicolon
id|isp-&gt;timer.data
op_assign
l_int|0
suffix:semicolon
id|set_bit
c_func
(paren
id|WORK_STOP
comma
op_amp
id|isp-&gt;todo
)paren
suffix:semicolon
id|del_timer_sync
c_func
(paren
op_amp
id|isp-&gt;timer
)paren
suffix:semicolon
id|flush_scheduled_work
c_func
(paren
)paren
suffix:semicolon
id|put_device
c_func
(paren
op_amp
id|i2c-&gt;dev
)paren
suffix:semicolon
id|the_transceiver
op_assign
l_int|0
suffix:semicolon
r_return
id|i2c_detach_client
c_func
(paren
id|i2c
)paren
suffix:semicolon
)brace
multiline_comment|/*-------------------------------------------------------------------------*/
multiline_comment|/* NOTE:  three modes are possible here, only one of which&n; * will be standards-conformant on any given system:&n; *&n; *  - OTG mode (dual-role), required if there&squot;s a Mini-AB connector&n; *  - HOST mode, for when there&squot;s one or more A (host) connectors&n; *  - DEVICE mode, for when there&squot;s a B/Mini-B (device) connector&n; *&n; * As a rule, you won&squot;t have an isp1301 chip unless it&squot;s there to&n; * support the OTG mode.  Other modes help testing USB controllers &n; * in isolation from (full) OTG support, or maybe so later board&n; * revisions can help to support those feature.&n; */
macro_line|#ifdef&t;CONFIG_USB_OTG
DECL|function|isp1301_otg_enable
r_static
r_int
id|isp1301_otg_enable
c_func
(paren
r_struct
id|isp1301
op_star
id|isp
)paren
(brace
id|power_up
c_func
(paren
id|isp
)paren
suffix:semicolon
id|otg_init
c_func
(paren
id|isp
)paren
suffix:semicolon
multiline_comment|/* NOTE:  since we don&squot;t change this, this provides&n;&t; * a few more interrupts than are strictly needed.&n;&t; */
id|isp1301_set_bits
c_func
(paren
id|isp
comma
id|ISP1301_INTERRUPT_RISING
comma
id|INTR_VBUS_VLD
op_or
id|INTR_SESS_VLD
op_or
id|INTR_ID_GND
)paren
suffix:semicolon
id|isp1301_set_bits
c_func
(paren
id|isp
comma
id|ISP1301_INTERRUPT_FALLING
comma
id|INTR_VBUS_VLD
op_or
id|INTR_SESS_VLD
op_or
id|INTR_ID_GND
)paren
suffix:semicolon
id|dev_info
c_func
(paren
op_amp
id|isp-&gt;client.dev
comma
l_string|&quot;ready for dual-role USB ...&bslash;n&quot;
)paren
suffix:semicolon
r_return
l_int|0
suffix:semicolon
)brace
macro_line|#endif
multiline_comment|/* add or disable the host device+driver */
r_static
r_int
DECL|function|isp1301_set_host
id|isp1301_set_host
c_func
(paren
r_struct
id|otg_transceiver
op_star
id|otg
comma
r_struct
id|usb_bus
op_star
id|host
)paren
(brace
r_struct
id|isp1301
op_star
id|isp
op_assign
id|container_of
c_func
(paren
id|otg
comma
r_struct
id|isp1301
comma
id|otg
)paren
suffix:semicolon
r_if
c_cond
(paren
op_logical_neg
id|otg
op_logical_or
id|isp
op_ne
id|the_transceiver
)paren
r_return
op_minus
id|ENODEV
suffix:semicolon
r_if
c_cond
(paren
op_logical_neg
id|host
)paren
(brace
id|OTG_IRQ_EN_REG
op_assign
l_int|0
suffix:semicolon
id|power_down
c_func
(paren
id|isp
)paren
suffix:semicolon
id|isp-&gt;otg.host
op_assign
l_int|0
suffix:semicolon
r_return
l_int|0
suffix:semicolon
)brace
macro_line|#ifdef&t;CONFIG_USB_OTG
id|isp-&gt;otg.host
op_assign
id|host
suffix:semicolon
id|dev_dbg
c_func
(paren
op_amp
id|isp-&gt;client.dev
comma
l_string|&quot;registered host&bslash;n&quot;
)paren
suffix:semicolon
id|host_suspend
c_func
(paren
id|isp
)paren
suffix:semicolon
r_if
c_cond
(paren
id|isp-&gt;otg.gadget
)paren
r_return
id|isp1301_otg_enable
c_func
(paren
id|isp
)paren
suffix:semicolon
r_return
l_int|0
suffix:semicolon
macro_line|#elif&t;!defined(CONFIG_USB_GADGET_OMAP)
singleline_comment|// FIXME update its refcount
id|isp-&gt;otg.host
op_assign
id|host
suffix:semicolon
id|power_up
c_func
(paren
id|isp
)paren
suffix:semicolon
r_if
c_cond
(paren
id|machine_is_omap_h2
c_func
(paren
)paren
)paren
id|isp1301_set_bits
c_func
(paren
id|isp
comma
id|ISP1301_MODE_CONTROL_1
comma
id|MC1_DAT_SE0
)paren
suffix:semicolon
id|dev_info
c_func
(paren
op_amp
id|isp-&gt;client.dev
comma
l_string|&quot;A-Host sessions ok&bslash;n&quot;
)paren
suffix:semicolon
id|isp1301_set_bits
c_func
(paren
id|isp
comma
id|ISP1301_INTERRUPT_RISING
comma
id|INTR_ID_GND
)paren
suffix:semicolon
id|isp1301_set_bits
c_func
(paren
id|isp
comma
id|ISP1301_INTERRUPT_FALLING
comma
id|INTR_ID_GND
)paren
suffix:semicolon
multiline_comment|/* If this has a Mini-AB connector, this mode is highly&n;&t; * nonstandard ... but can be handy for testing, especially with&n;&t; * the Mini-A end of an OTG cable.  (Or something nonstandard&n;&t; * like MiniB-to-StandardB, maybe built with a gender mender.)&n;&t; */
id|isp1301_set_bits
c_func
(paren
id|isp
comma
id|ISP1301_OTG_CONTROL_1
comma
id|OTG1_VBUS_DRV
)paren
suffix:semicolon
id|dump_regs
c_func
(paren
id|isp
comma
id|__FUNCTION__
)paren
suffix:semicolon
r_return
l_int|0
suffix:semicolon
macro_line|#else
id|dev_dbg
c_func
(paren
op_amp
id|isp-&gt;client.dev
comma
l_string|&quot;host sessions not allowed&bslash;n&quot;
)paren
suffix:semicolon
r_return
op_minus
id|EINVAL
suffix:semicolon
macro_line|#endif
)brace
r_static
r_int
DECL|function|isp1301_set_peripheral
id|isp1301_set_peripheral
c_func
(paren
r_struct
id|otg_transceiver
op_star
id|otg
comma
r_struct
id|usb_gadget
op_star
id|gadget
)paren
(brace
r_struct
id|isp1301
op_star
id|isp
op_assign
id|container_of
c_func
(paren
id|otg
comma
r_struct
id|isp1301
comma
id|otg
)paren
suffix:semicolon
r_if
c_cond
(paren
op_logical_neg
id|otg
op_logical_or
id|isp
op_ne
id|the_transceiver
)paren
r_return
op_minus
id|ENODEV
suffix:semicolon
r_if
c_cond
(paren
op_logical_neg
id|gadget
)paren
(brace
id|OTG_IRQ_EN_REG
op_assign
l_int|0
suffix:semicolon
r_if
c_cond
(paren
op_logical_neg
id|isp-&gt;otg.default_a
)paren
id|enable_vbus_draw
c_func
(paren
id|isp
comma
l_int|0
)paren
suffix:semicolon
id|usb_gadget_vbus_disconnect
c_func
(paren
id|isp-&gt;otg.gadget
)paren
suffix:semicolon
id|isp-&gt;otg.gadget
op_assign
l_int|0
suffix:semicolon
id|power_down
c_func
(paren
id|isp
)paren
suffix:semicolon
r_return
l_int|0
suffix:semicolon
)brace
macro_line|#ifdef&t;CONFIG_USB_OTG
id|isp-&gt;otg.gadget
op_assign
id|gadget
suffix:semicolon
id|dev_dbg
c_func
(paren
op_amp
id|isp-&gt;client.dev
comma
l_string|&quot;registered gadget&bslash;n&quot;
)paren
suffix:semicolon
multiline_comment|/* gadget driver may be suspended until vbus_connect () */
r_if
c_cond
(paren
id|isp-&gt;otg.host
)paren
r_return
id|isp1301_otg_enable
c_func
(paren
id|isp
)paren
suffix:semicolon
r_return
l_int|0
suffix:semicolon
macro_line|#elif&t;!defined(CONFIG_USB_OHCI_HCD) &amp;&amp; !defined(CONFIG_USB_OHCI_HCD_MODULE)
id|isp-&gt;otg.gadget
op_assign
id|gadget
suffix:semicolon
singleline_comment|// FIXME update its refcount
id|OTG_CTRL_REG
op_assign
(paren
id|OTG_CTRL_REG
op_amp
id|OTG_CTRL_MASK
op_amp
op_complement
(paren
id|OTG_XCEIV_OUTPUTS
op_or
id|OTG_CTRL_BITS
)paren
)paren
op_or
id|OTG_ID
suffix:semicolon
id|power_up
c_func
(paren
id|isp
)paren
suffix:semicolon
id|isp-&gt;otg.state
op_assign
id|OTG_STATE_B_IDLE
suffix:semicolon
r_if
c_cond
(paren
id|machine_is_omap_h2
c_func
(paren
)paren
)paren
id|isp1301_set_bits
c_func
(paren
id|isp
comma
id|ISP1301_MODE_CONTROL_1
comma
id|MC1_DAT_SE0
)paren
suffix:semicolon
id|isp1301_set_bits
c_func
(paren
id|isp
comma
id|ISP1301_INTERRUPT_RISING
comma
id|INTR_SESS_VLD
)paren
suffix:semicolon
id|isp1301_set_bits
c_func
(paren
id|isp
comma
id|ISP1301_INTERRUPT_FALLING
comma
id|INTR_VBUS_VLD
)paren
suffix:semicolon
id|dev_info
c_func
(paren
op_amp
id|isp-&gt;client.dev
comma
l_string|&quot;B-Peripheral sessions ok&bslash;n&quot;
)paren
suffix:semicolon
id|dump_regs
c_func
(paren
id|isp
comma
id|__FUNCTION__
)paren
suffix:semicolon
multiline_comment|/* If this has a Mini-AB connector, this mode is highly&n;&t; * nonstandard ... but can be handy for testing, so long&n;&t; * as you don&squot;t plug a Mini-A cable into the jack.&n;&t; */
r_if
c_cond
(paren
id|isp1301_get_u8
c_func
(paren
id|isp
comma
id|ISP1301_INTERRUPT_SOURCE
)paren
op_amp
id|INTR_VBUS_VLD
)paren
id|b_peripheral
c_func
(paren
id|isp
)paren
suffix:semicolon
r_return
l_int|0
suffix:semicolon
macro_line|#else
id|dev_dbg
c_func
(paren
op_amp
id|isp-&gt;client.dev
comma
l_string|&quot;peripheral sessions not allowed&bslash;n&quot;
)paren
suffix:semicolon
r_return
op_minus
id|EINVAL
suffix:semicolon
macro_line|#endif
)brace
multiline_comment|/*-------------------------------------------------------------------------*/
r_static
r_int
DECL|function|isp1301_set_power
id|isp1301_set_power
c_func
(paren
r_struct
id|otg_transceiver
op_star
id|dev
comma
r_int
id|mA
)paren
(brace
r_if
c_cond
(paren
op_logical_neg
id|the_transceiver
)paren
r_return
op_minus
id|ENODEV
suffix:semicolon
r_if
c_cond
(paren
id|dev-&gt;state
op_eq
id|OTG_STATE_B_PERIPHERAL
)paren
id|enable_vbus_draw
c_func
(paren
id|the_transceiver
comma
id|mA
)paren
suffix:semicolon
r_return
l_int|0
suffix:semicolon
)brace
r_static
r_int
DECL|function|isp1301_start_srp
id|isp1301_start_srp
c_func
(paren
r_struct
id|otg_transceiver
op_star
id|dev
)paren
(brace
r_struct
id|isp1301
op_star
id|isp
op_assign
id|container_of
c_func
(paren
id|dev
comma
r_struct
id|isp1301
comma
id|otg
)paren
suffix:semicolon
id|u32
id|otg_ctrl
suffix:semicolon
r_if
c_cond
(paren
op_logical_neg
id|dev
op_logical_or
id|isp
op_ne
id|the_transceiver
op_logical_or
id|isp-&gt;otg.state
op_ne
id|OTG_STATE_B_IDLE
)paren
r_return
op_minus
id|ENODEV
suffix:semicolon
id|otg_ctrl
op_assign
id|OTG_CTRL_REG
suffix:semicolon
r_if
c_cond
(paren
op_logical_neg
(paren
id|otg_ctrl
op_amp
id|OTG_BSESSEND
)paren
)paren
r_return
op_minus
id|EINVAL
suffix:semicolon
id|otg_ctrl
op_or_assign
id|OTG_B_BUSREQ
suffix:semicolon
id|otg_ctrl
op_and_assign
op_complement
id|OTG_A_BUSREQ
op_amp
id|OTG_CTRL_MASK
suffix:semicolon
id|OTG_CTRL_REG
op_assign
id|otg_ctrl
suffix:semicolon
id|isp-&gt;otg.state
op_assign
id|OTG_STATE_B_SRP_INIT
suffix:semicolon
id|pr_debug
c_func
(paren
l_string|&quot;otg: SRP, %s ... %06x&bslash;n&quot;
comma
id|state_name
c_func
(paren
id|isp
)paren
comma
id|OTG_CTRL_REG
)paren
suffix:semicolon
macro_line|#ifdef&t;CONFIG_USB_OTG
id|check_state
c_func
(paren
id|isp
comma
id|__FUNCTION__
)paren
suffix:semicolon
macro_line|#endif
r_return
l_int|0
suffix:semicolon
)brace
r_static
r_int
DECL|function|isp1301_start_hnp
id|isp1301_start_hnp
c_func
(paren
r_struct
id|otg_transceiver
op_star
id|dev
)paren
(brace
macro_line|#ifdef&t;CONFIG_USB_OTG
r_struct
id|isp1301
op_star
id|isp
op_assign
id|container_of
c_func
(paren
id|dev
comma
r_struct
id|isp1301
comma
id|otg
)paren
suffix:semicolon
r_if
c_cond
(paren
op_logical_neg
id|dev
op_logical_or
id|isp
op_ne
id|the_transceiver
)paren
r_return
op_minus
id|ENODEV
suffix:semicolon
r_if
c_cond
(paren
id|isp-&gt;otg.default_a
op_logical_and
(paren
id|isp-&gt;otg.host
op_eq
l_int|NULL
op_logical_or
op_logical_neg
id|isp-&gt;otg.host-&gt;b_hnp_enable
)paren
)paren
r_return
op_minus
id|ENOTCONN
suffix:semicolon
r_if
c_cond
(paren
op_logical_neg
id|isp-&gt;otg.default_a
op_logical_and
(paren
id|isp-&gt;otg.gadget
op_eq
l_int|NULL
op_logical_or
op_logical_neg
id|isp-&gt;otg.gadget-&gt;b_hnp_enable
)paren
)paren
r_return
op_minus
id|ENOTCONN
suffix:semicolon
multiline_comment|/* We want hardware to manage most HNP protocol timings.&n;&t; * So do this part as early as possible...&n;&t; */
r_switch
c_cond
(paren
id|isp-&gt;otg.state
)paren
(brace
r_case
id|OTG_STATE_B_HOST
suffix:colon
id|isp-&gt;otg.state
op_assign
id|OTG_STATE_B_PERIPHERAL
suffix:semicolon
multiline_comment|/* caller will suspend next */
r_break
suffix:semicolon
r_case
id|OTG_STATE_A_HOST
suffix:colon
macro_line|#if 0
multiline_comment|/* autoconnect mode avoids irq latency bugs */
id|isp1301_set_bits
c_func
(paren
id|isp
comma
id|ISP1301_MODE_CONTROL_1
comma
id|MC1_BDIS_ACON_EN
)paren
suffix:semicolon
macro_line|#endif
multiline_comment|/* caller must suspend then clear A_BUSREQ */
id|usb_gadget_vbus_connect
c_func
(paren
id|isp-&gt;otg.gadget
)paren
suffix:semicolon
id|OTG_CTRL_REG
op_or_assign
id|OTG_A_SETB_HNPEN
suffix:semicolon
r_break
suffix:semicolon
r_case
id|OTG_STATE_A_PERIPHERAL
suffix:colon
multiline_comment|/* initiated by B-Host suspend */
r_break
suffix:semicolon
r_default
suffix:colon
r_return
op_minus
id|EILSEQ
suffix:semicolon
)brace
id|pr_debug
c_func
(paren
l_string|&quot;otg: HNP %s, %06x ...&bslash;n&quot;
comma
id|state_name
c_func
(paren
id|isp
)paren
comma
id|OTG_CTRL_REG
)paren
suffix:semicolon
id|check_state
c_func
(paren
id|isp
comma
id|__FUNCTION__
)paren
suffix:semicolon
r_return
l_int|0
suffix:semicolon
macro_line|#else
multiline_comment|/* srp-only */
r_return
op_minus
id|EINVAL
suffix:semicolon
macro_line|#endif
)brace
multiline_comment|/*-------------------------------------------------------------------------*/
multiline_comment|/* no error returns, they&squot;d just make bus scanning stop */
DECL|function|isp1301_probe
r_static
r_int
id|isp1301_probe
c_func
(paren
r_struct
id|i2c_adapter
op_star
id|bus
comma
r_int
id|address
comma
r_int
id|kind
)paren
(brace
r_int
id|status
suffix:semicolon
r_struct
id|isp1301
op_star
id|isp
suffix:semicolon
r_struct
id|i2c_client
op_star
id|i2c
suffix:semicolon
r_if
c_cond
(paren
id|the_transceiver
)paren
r_return
l_int|0
suffix:semicolon
id|isp
op_assign
id|kcalloc
c_func
(paren
l_int|1
comma
r_sizeof
op_star
id|isp
comma
id|GFP_KERNEL
)paren
suffix:semicolon
r_if
c_cond
(paren
op_logical_neg
id|isp
)paren
r_return
l_int|0
suffix:semicolon
id|INIT_WORK
c_func
(paren
op_amp
id|isp-&gt;work
comma
id|isp1301_work
comma
id|isp
)paren
suffix:semicolon
id|init_timer
c_func
(paren
op_amp
id|isp-&gt;timer
)paren
suffix:semicolon
id|isp-&gt;timer.function
op_assign
id|isp1301_timer
suffix:semicolon
id|isp-&gt;timer.data
op_assign
(paren
r_int
r_int
)paren
id|isp
suffix:semicolon
id|isp-&gt;irq
op_assign
op_minus
l_int|1
suffix:semicolon
id|isp-&gt;client.addr
op_assign
id|address
suffix:semicolon
id|i2c_set_clientdata
c_func
(paren
op_amp
id|isp-&gt;client
comma
id|isp
)paren
suffix:semicolon
id|isp-&gt;client.adapter
op_assign
id|bus
suffix:semicolon
id|isp-&gt;client.driver
op_assign
op_amp
id|isp1301_driver
suffix:semicolon
id|strlcpy
c_func
(paren
id|isp-&gt;client.name
comma
id|DRIVER_NAME
comma
id|I2C_NAME_SIZE
)paren
suffix:semicolon
id|i2c
op_assign
op_amp
id|isp-&gt;client
suffix:semicolon
multiline_comment|/* if this is a true probe, verify the chip ... */
r_if
c_cond
(paren
id|kind
OL
l_int|0
)paren
(brace
id|status
op_assign
id|isp1301_get_u16
c_func
(paren
id|isp
comma
id|ISP1301_VENDOR_ID
)paren
suffix:semicolon
r_if
c_cond
(paren
id|status
op_ne
id|I2C_VENDOR_ID_PHILIPS
)paren
(brace
id|dev_dbg
c_func
(paren
op_amp
id|bus-&gt;dev
comma
l_string|&quot;addr %d not philips id: %d&bslash;n&quot;
comma
id|address
comma
id|status
)paren
suffix:semicolon
r_goto
id|fail1
suffix:semicolon
)brace
id|status
op_assign
id|isp1301_get_u16
c_func
(paren
id|isp
comma
id|ISP1301_PRODUCT_ID
)paren
suffix:semicolon
r_if
c_cond
(paren
id|status
op_ne
id|I2C_PRODUCT_ID_PHILIPS_1301
)paren
(brace
id|dev_dbg
c_func
(paren
op_amp
id|bus-&gt;dev
comma
l_string|&quot;%d not isp1301, %d&bslash;n&quot;
comma
id|address
comma
id|status
)paren
suffix:semicolon
r_goto
id|fail1
suffix:semicolon
)brace
)brace
id|status
op_assign
id|i2c_attach_client
c_func
(paren
id|i2c
)paren
suffix:semicolon
r_if
c_cond
(paren
id|status
OL
l_int|0
)paren
(brace
id|dev_dbg
c_func
(paren
op_amp
id|bus-&gt;dev
comma
l_string|&quot;can&squot;t attach %s to device %d, err %d&bslash;n&quot;
comma
id|DRIVER_NAME
comma
id|address
comma
id|status
)paren
suffix:semicolon
id|fail1
suffix:colon
id|kfree
c_func
(paren
id|isp
)paren
suffix:semicolon
r_return
l_int|0
suffix:semicolon
)brace
id|isp-&gt;i2c_release
op_assign
id|i2c-&gt;dev.release
suffix:semicolon
id|i2c-&gt;dev.release
op_assign
id|isp1301_release
suffix:semicolon
multiline_comment|/* initial development used chiprev 2.00 */
id|status
op_assign
id|i2c_smbus_read_word_data
c_func
(paren
id|i2c
comma
id|ISP1301_BCD_DEVICE
)paren
suffix:semicolon
id|dev_info
c_func
(paren
op_amp
id|i2c-&gt;dev
comma
l_string|&quot;chiprev %x.%02x, driver &quot;
id|DRIVER_VERSION
l_string|&quot;&bslash;n&quot;
comma
id|status
op_rshift
l_int|8
comma
id|status
op_amp
l_int|0xff
)paren
suffix:semicolon
multiline_comment|/* make like power-on reset */
id|isp1301_clear_bits
c_func
(paren
id|isp
comma
id|ISP1301_MODE_CONTROL_1
comma
id|MC1_MASK
)paren
suffix:semicolon
id|isp1301_set_bits
c_func
(paren
id|isp
comma
id|ISP1301_MODE_CONTROL_2
comma
id|MC2_BI_DI
)paren
suffix:semicolon
id|isp1301_clear_bits
c_func
(paren
id|isp
comma
id|ISP1301_MODE_CONTROL_2
comma
op_complement
id|MC2_BI_DI
)paren
suffix:semicolon
id|isp1301_set_bits
c_func
(paren
id|isp
comma
id|ISP1301_OTG_CONTROL_1
comma
id|OTG1_DM_PULLDOWN
op_or
id|OTG1_DP_PULLDOWN
)paren
suffix:semicolon
id|isp1301_clear_bits
c_func
(paren
id|isp
comma
id|ISP1301_OTG_CONTROL_1
comma
op_complement
(paren
id|OTG1_DM_PULLDOWN
op_or
id|OTG1_DP_PULLDOWN
)paren
)paren
suffix:semicolon
id|isp1301_clear_bits
c_func
(paren
id|isp
comma
id|ISP1301_INTERRUPT_LATCH
comma
op_complement
l_int|0
)paren
suffix:semicolon
id|isp1301_clear_bits
c_func
(paren
id|isp
comma
id|ISP1301_INTERRUPT_FALLING
comma
op_complement
l_int|0
)paren
suffix:semicolon
id|isp1301_clear_bits
c_func
(paren
id|isp
comma
id|ISP1301_INTERRUPT_RISING
comma
op_complement
l_int|0
)paren
suffix:semicolon
macro_line|#ifdef&t;CONFIG_USB_OTG
id|status
op_assign
id|otg_bind
c_func
(paren
id|isp
)paren
suffix:semicolon
r_if
c_cond
(paren
id|status
OL
l_int|0
)paren
(brace
id|dev_dbg
c_func
(paren
op_amp
id|i2c-&gt;dev
comma
l_string|&quot;can&squot;t bind OTG&bslash;n&quot;
)paren
suffix:semicolon
r_goto
id|fail2
suffix:semicolon
)brace
macro_line|#endif
r_if
c_cond
(paren
id|machine_is_omap_h2
c_func
(paren
)paren
)paren
(brace
multiline_comment|/* full speed signaling by default */
id|isp1301_set_bits
c_func
(paren
id|isp
comma
id|ISP1301_MODE_CONTROL_1
comma
id|MC1_SPEED_REG
)paren
suffix:semicolon
id|isp1301_set_bits
c_func
(paren
id|isp
comma
id|ISP1301_MODE_CONTROL_2
comma
id|MC2_SPD_SUSP_CTRL
)paren
suffix:semicolon
multiline_comment|/* IRQ wired at M14 */
id|omap_cfg_reg
c_func
(paren
id|M14_1510_GPIO2
)paren
suffix:semicolon
id|isp-&gt;irq
op_assign
id|OMAP_GPIO_IRQ
c_func
(paren
l_int|2
)paren
suffix:semicolon
id|omap_request_gpio
c_func
(paren
l_int|2
)paren
suffix:semicolon
id|omap_set_gpio_direction
c_func
(paren
l_int|2
comma
l_int|1
)paren
suffix:semicolon
id|omap_set_gpio_edge_ctrl
c_func
(paren
l_int|2
comma
id|OMAP_GPIO_FALLING_EDGE
)paren
suffix:semicolon
)brace
id|status
op_assign
id|request_irq
c_func
(paren
id|isp-&gt;irq
comma
id|isp1301_irq
comma
id|SA_SAMPLE_RANDOM
comma
id|DRIVER_NAME
comma
id|isp
)paren
suffix:semicolon
r_if
c_cond
(paren
id|status
OL
l_int|0
)paren
(brace
id|dev_dbg
c_func
(paren
op_amp
id|i2c-&gt;dev
comma
l_string|&quot;can&squot;t get IRQ %d, err %d&bslash;n&quot;
comma
id|isp-&gt;irq
comma
id|status
)paren
suffix:semicolon
macro_line|#ifdef&t;CONFIG_USB_OTG
id|fail2
suffix:colon
macro_line|#endif
id|i2c_detach_client
c_func
(paren
id|i2c
)paren
suffix:semicolon
r_goto
id|fail1
suffix:semicolon
)brace
id|isp-&gt;otg.dev
op_assign
op_amp
id|isp-&gt;client.dev
suffix:semicolon
id|isp-&gt;otg.label
op_assign
id|DRIVER_NAME
suffix:semicolon
id|isp-&gt;otg.set_host
op_assign
id|isp1301_set_host
comma
id|isp-&gt;otg.set_peripheral
op_assign
id|isp1301_set_peripheral
comma
id|isp-&gt;otg.set_power
op_assign
id|isp1301_set_power
comma
id|isp-&gt;otg.start_srp
op_assign
id|isp1301_start_srp
comma
id|isp-&gt;otg.start_hnp
op_assign
id|isp1301_start_hnp
comma
id|enable_vbus_draw
c_func
(paren
id|isp
comma
l_int|0
)paren
suffix:semicolon
id|power_down
c_func
(paren
id|isp
)paren
suffix:semicolon
id|the_transceiver
op_assign
id|isp
suffix:semicolon
macro_line|#ifdef&t;CONFIG_USB_OTG
id|update_otg1
c_func
(paren
id|isp
comma
id|isp1301_get_u8
c_func
(paren
id|isp
comma
id|ISP1301_INTERRUPT_SOURCE
)paren
)paren
suffix:semicolon
id|update_otg2
c_func
(paren
id|isp
comma
id|isp1301_get_u8
c_func
(paren
id|isp
comma
id|ISP1301_OTG_STATUS
)paren
)paren
suffix:semicolon
macro_line|#endif
id|dump_regs
c_func
(paren
id|isp
comma
id|__FUNCTION__
)paren
suffix:semicolon
macro_line|#ifdef&t;VERBOSE
id|mod_timer
c_func
(paren
op_amp
id|isp-&gt;timer
comma
id|jiffies
op_plus
id|TIMER_JIFFIES
)paren
suffix:semicolon
id|dev_dbg
c_func
(paren
op_amp
id|i2c-&gt;dev
comma
l_string|&quot;scheduled timer, %d min&bslash;n&quot;
comma
id|TIMER_MINUTES
)paren
suffix:semicolon
macro_line|#endif
id|status
op_assign
id|otg_set_transceiver
c_func
(paren
op_amp
id|isp-&gt;otg
)paren
suffix:semicolon
r_if
c_cond
(paren
id|status
OL
l_int|0
)paren
id|dev_err
c_func
(paren
op_amp
id|i2c-&gt;dev
comma
l_string|&quot;can&squot;t register transceiver, %d&bslash;n&quot;
comma
id|status
)paren
suffix:semicolon
r_return
l_int|0
suffix:semicolon
)brace
DECL|function|isp1301_scan_bus
r_static
r_int
id|isp1301_scan_bus
c_func
(paren
r_struct
id|i2c_adapter
op_star
id|bus
)paren
(brace
r_if
c_cond
(paren
op_logical_neg
id|i2c_check_functionality
c_func
(paren
id|bus
comma
id|I2C_FUNC_SMBUS_BYTE_DATA
op_or
id|I2C_FUNC_SMBUS_READ_WORD_DATA
)paren
)paren
r_return
op_minus
id|EINVAL
suffix:semicolon
r_return
id|i2c_probe
c_func
(paren
id|bus
comma
op_amp
id|addr_data
comma
id|isp1301_probe
)paren
suffix:semicolon
)brace
DECL|variable|isp1301_driver
r_static
r_struct
id|i2c_driver
id|isp1301_driver
op_assign
(brace
dot
id|owner
op_assign
id|THIS_MODULE
comma
dot
id|name
op_assign
l_string|&quot;isp1301_omap&quot;
comma
dot
id|id
op_assign
l_int|1301
comma
multiline_comment|/* FIXME &quot;official&quot;, i2c-ids.h */
dot
r_class
op_assign
id|I2C_CLASS_HWMON
comma
dot
id|flags
op_assign
id|I2C_DF_NOTIFY
comma
dot
id|attach_adapter
op_assign
id|isp1301_scan_bus
comma
dot
id|detach_client
op_assign
id|isp1301_detach_client
comma
)brace
suffix:semicolon
multiline_comment|/*-------------------------------------------------------------------------*/
DECL|function|isp_init
r_static
r_int
id|__init
id|isp_init
c_func
(paren
r_void
)paren
(brace
r_return
id|i2c_add_driver
c_func
(paren
op_amp
id|isp1301_driver
)paren
suffix:semicolon
)brace
DECL|variable|isp_init
id|module_init
c_func
(paren
id|isp_init
)paren
suffix:semicolon
DECL|function|isp_exit
r_static
r_void
id|__exit
id|isp_exit
c_func
(paren
r_void
)paren
(brace
r_if
c_cond
(paren
id|the_transceiver
)paren
id|otg_set_transceiver
c_func
(paren
l_int|0
)paren
suffix:semicolon
id|i2c_del_driver
c_func
(paren
op_amp
id|isp1301_driver
)paren
suffix:semicolon
)brace
DECL|variable|isp_exit
id|module_exit
c_func
(paren
id|isp_exit
)paren
suffix:semicolon
eof
